- passes/memory/memory.cc
- passes/memory/memory_share.cc
- passes/opt/Makefile.inc
- passes/opt/opt_mem_feedback.cc
memory_share is actually three passes in a trenchcoat.  Split off the
one that has the least in common with the other two as a separate pass.
> memory_share: Split off feedback path finding as a separate pass.

- kernel/mem.cc
- kernel/mem.h
- passes/memory/memory_map.cc
- passes/memory/memory_nordff.cc
This is not used yet, but will be needed when read port reset/initial
value support lands.
> extract_rdff: Add initvals parameter.

- kernel/mem.cc
- kernel/mem.h
This is going to be used to store arbitrary priority masks in the
future.  Right now, it is not supported by our cell library, so the
priority_mask is computed from port order on helper construction,
and discarded when emitted.  However, this allows us to already convert
helper-using passes to the new model.
> kernel/mem: Add priority_mask to model.

- kernel/mem.cc
- kernel/mem.h
- passes/opt/opt_mem.cc
Like wide port support, this is still completely unusable, and support
in various passes will be gradually added later.  It also has no support
at all in the cell library, so attempting to create a read port with
a reset or initial value will cause an assert failure for now.
> kernel/mem: Add model support for read port init value and resets.

- frontends/verilog/verilog_lexer.l
- frontends/verilog/verilog_parser.y
- tests/simple/asgn_binop.sv
- Add support for: *=, /=, %=, <<=, >>=, <<<=, >>>=
- Unify existing support for: +=, -=, &=, |=, ^=
Fixes #1440
> sv: support remaining assignment operators

- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- tests/simple/case_expr_const.v
- tests/simple/case_expr_non_const.v
- The case expression and case item expressions are extended to the maximum width among them, and are only interpreted as signed if all of them are signed
- Add overall width and sign detection for AST_CASE
- Add sign argument to genWidthRTLIL helper
- Coverage for both const and non-const case statements
From Section 12.5 of IEEE 1800-2017:
> In a _case_expression_ comparison, the comparison only succeeds when each bit matches exactly with respect to the values `0`, `1`, `x`, and `z`. As a consequence, care is needed in specifying the expressions in the case statement. The bit length of all the expressions needs to be equal, so that exact bitwise matching can be performed. Therefore, the length of all the _case_item_expressions_, as well as the _case_expression_, shall be made equal to …
> verilog: fix case expression sign and width handling

- kernel/mem.cc
- passes/memory/memory_nordff.cc
When converting a sync transparent read port with const address to async
read port, nothing at all needs to be done other than clk_enable change,
and thus we have no FF cell to return.  Handle this case correctly in
the helper and in its users.
> mem/extract_rdff: Fix "no FF made" edge case.

- backends/btor/btor.cc
- backends/firrtl/firrtl.cc
- backends/smt2/smt2.cc
- kernel/mem.cc
- passes/memory/memory_bram.cc
This essentially adds wide port support for free in passes that don't
have a usefully better way of handling wide ports than just breaking
them up to narrow ports, avoiding "please run memory_narrow" annoyance.
> Make a few passes auto-call Mem::narrow instead of rejecting wide ports.

- kernel/mem.cc
Transparency is meaningless for asynchronous ports, so we assume
transparent == false to simplify the code in this case.  Likewise,
enable is meaningless, and we assume it is const-1.  However,
turns out that nMigen emits the former, and Verilog frontend emits
the latter, so squash these issues when ingesting a $memrd cell.
Fixes #2811.
> kernel/mem: Recognize some deprecated memory port configs.

- passes/cmds/autoname.cc
I'm not making any algorithmic changes, just trying to fix some low hanging fruit. I'm sure there is still a lot of room for improvement. On @anuejn's test case in #2816, these changes reduced the `autoname` runtime from ~85s to ~20s.
> autoname: simple perf optimizations

- frontends/ast/simplify.cc
- tests/simple/mem2reg_bounds_tern.v
- tests/verilog/mem_bounds.sv
- tests/verilog/mem_bounds.ys
This brings the mem2reg behavior in line with the nomem2reg behavior.
Fixes #1649
> mem2reg: tolerate out of bounds constant accesses

- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- tests/simple/module_scope_case.v
The recent fix for case expression width detection causes the width of
the expressions to be queried before they are simplified. Because the
logic supporting module scope identifiers only existed in simplify,
looking them up would fail during width detection. This moves the logic
to a common helper used in both simplify() and detectSignWidthWorker().
> verilog: check for module scope identifiers during width detection

- passes/opt/opt_expr.cc
Turns out the code for div by a power of 2 is already almost capable of
optimizing this to a shift-by-0 or and-with-0, which will be further
folded into nothingness; let's beef it up to handle div by 1 as well.
Fixes #2820.
> opt_expr: Optimize div/mod by const 1.

- kernel/rtlil.cc
- kernel/rtlil.h
- passes/opt/opt_expr.cc
The previous code, in addition to being needlessly limitted to 32 bits
in the first place, also had UB for the 31th bit (doing 1 << 31).
> opt_expr: Fix mul/div/mod by POT patterns to support >= 32 bits.

- kernel/rtlil.cc
No change in behaviour, but use range-based for loops instead of
iterators.
(Note: This patch is part of the larger queue at #2752. The idea is to split things out to avoid having a giant PR to review all at once)
> Simplify some RTLIL destructors

- passes/hierarchy/hierarchy.cc
There should be no functional change, but this splits up the control
flow across functions, using class fields to hold the state that's
being tracked. The result should be a bit easier to read.
This is part of work to add bind support, but I'm doing some
refactoring in the hierarchy pass to make the code a bit easier to
work with. The idea is that (eventually) the IFExpander object will
hold all the logic for expanding interfaces, and then other code can
do bind insertion.
(Note: This patch is part of the larger queue at #2752. The idea is to split things out to avoid having a giant PR to review all at once)
> Move interface expansion in hierarchy.cc into a helper class

- kernel/yosys.cc
This is equivalent to https://github.com/YosysHQ/nextpnr/commit/b1cbae1293fecf3ba14a7ce073d26dcfb07177f0 from way-back-when.
Python sets up its own SIGINT handler which stops Ctrl+C from working in pyosys builds, this clears that after Python has been initialised.
> pyosys: Clear SIGINT handler after Python loads

- kernel/yosys.cc
WASI doesn't have signals, or Python for that matter.
> Fix WASI build after commit 1d88bea1

- backends/cxxrtl/cxxrtl_backend.cc
This *only* does conversion, but doesn't add any new functionality —
support for memory read port init/reset is still upcoming.
> cxxrtl: Convert to Mem helpers.

- backends/smt2/smtio.py
The boolector team appears to be developing a new solver, [bitwuzla](https://bitwuzla.github.io/). I have a case where it is 3X faster than boolector, though another where it's 2X slower, so it is perhaps not always quicker. It seems to be where most of their development effort is going and was the tool they entered in the 2021 SMT competition, so I would expect it might continue to improve.
The interface unsurprisingly seems very similar to boolector, so I've added it to the same code path.
Both solvers support a timeout with the ``--time`` or ``-t`` options, so I've added support for that as well.
> Add support for the Bitwuzla solver and the timeout option

- backends/cxxrtl/cxxrtl_backend.cc
- kernel/mem.cc
- kernel/mem.h
While this helper is already useful to squash sequential initializations
into one in cxxrtl, its main purpose is to squash overlapping masked memory
initializations (when they land) and avoid having to deal with them in
cxxrtl runtime.
> kernel/mem: Add a coalesce_inits helper.

- passes/proc/proc_init.cc
Spotted during compilation:
passes/proc/proc_init.cc: In function ‘void {anonymous}::proc_init(Yosys::RTLIL::Module*, Yosys::SigMap&, Yosys::RTLIL::Process*)’:
passes/proc/proc_init.cc:31:7: warning: variable ‘found_init’ set but not used [-Wunused-but-set-variable]
> Delete unused found_init variable

- passes/hierarchy/hierarchy.cc
- tests/svinterfaces/load_and_derive.sv
- tests/svinterfaces/load_and_derive.ys
- tests/svinterfaces/ondemand.sv
- tests/svinterfaces/run-test.sh
- tests/svinterfaces/run_simple.sh
*(Text edited after a force-push)*
This PR has two commits. The first is a small clean-up in `hierarchy.cc`. The second adds a test to check that this functionality interacts properly with interface expansion. The message for the first commit is:
> I think the code is now a bit easier to follow (and has lost some
> levels of indentation!).
> 
> The only non-trivial change is that I removed the check for
> `cell->type[0] != '$'` when deciding whether to complain if we couldn't
> find a module. This will always be true because of the early exit
> earlier in the function.
This is part of the commit queue in #2752, but has been split out to make reviewing easier.
> Extract missing module support in hierarchy.cc to a helper function

- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- tests/verilog/struct_access.sv
- tests/verilog/struct_access.ys
- preserve signedness of struct members
- fix initial width detection of struct members (e.g., in case expressions)
Fixes #2843
> sv: fix two struct access bugs

- backends/cxxrtl/cxxrtl_backend.cc
> cxxrtl: mark dead local wires as unused even with inlining disabled

- backends/cxxrtl/cxxrtl_backend.cc
Public wires may alias buffered internal wires, so keep `BUFFERED` wires in debug information even if they are private. Debug items are only created for public wires, so this does not otherwise affect how debug information is emitted.
Fixes #2540.
Fixes #2841.
Supersedes #2541.
> cxxrtl: don't mark buffered internal wires as UNUSED for debug

- backends/cxxrtl/cxxrtl_backend.cc
Ports can be connected to constants, too. (Usually resets.)
Fixes #2521.
> cxxrtl: don't expect user cell inputs to be wires

- backends/cxxrtl/cxxrtl_backend.cc
This greatly improves debug information coverage.
Fixes #2500.
> cxxrtl: emit debug items for unused public wires

- backends/cxxrtl/cxxrtl_backend.cc
The hierarchy pass does a lot more than just finding the top module, mainly resolving implicit (positional, wildcard) module connections.
Fixes #2589.
> cxxrtl: run hierarchy pass regardless of (*top*) attribute presence

- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/verilog/verilog_lexer.l
- frontends/verilog/verilog_parser.y
- tests/bind/.gitignore
- tests/bind/basic.sv
- tests/bind/basic.ys
- tests/bind/cell_list.sv
- tests/bind/cell_list.ys
- tests/bind/hier.sv
- tests/bind/hier.ys
- tests/bind/inst_list.sv
- tests/bind/inst_list.ys
- tests/bind/param.sv
- tests/bind/param.ys
- tests/bind/run-test.sh
- tests/bind/toplevel.sv
- tests/bind/toplevel.ys
This doesn't do anything useful yet: the patch just adds support for
the syntax to the lexer and parser and adds some tests to check the
syntax parses properly. This generates AST nodes, but doesn't yet
generate RTLIL.
Since our existing `hierarchical_identifier` parser doesn't allow bit
selects (so you can't do something like `foo[1].bar[2].baz`), I've also
not added support for a trailing bit select (the `constant_bit_select`
non-terminal in `bind_target_instance` in the spec). If we turn out to
need this in future, we'll want to augment `hierarchical_identifier` and
its other users too.
Note that you can't easily use the BNF from the spec:
bind_directive ::=
"bind" bind_target_scope [ : bind_target_instance_list]
bind_instantiation ;
| "bind" bind_target_instance bind_instantiation ; …
> Add support for parsing the SystemVerilog 'bind' construct

- backends/cxxrtl/cxxrtl_backend.cc
> cxxrtl: treat internal wires used only for debug as constants

- backends/cxxrtl/cxxrtl_vcd.h
The following VCD file crashes GTKWave's VCD loader:
$var wire 1 ! x:1 $end
$enddefinitions $end
In practice, a colon can be a part of a variable name that is
translated from a Verilog function, something like:
update$func$.../hdl/hazard3_csr.v:350$2534.$result
> cxxrtl: escape colon in variable names in VCD writer

- backends/cxxrtl/cxxrtl_backend.cc
This issue was introduced in commit 4aa65f40 while fixing #2739.
Fixes #2882.
> cxxrtl: treat assignable internal wires used only for debug as locals

- backends/cxxrtl/cxxrtl_backend.cc
> cxxrtl: treat wires with multiple defs as not inlinable

- passes/hierarchy/hierarchy.cc
No functional change, but pulls more logic out of the expand_module
function.
This is part of the commit queue in #2752, but has been split out to make reviewing easier.
> Extract connection checking logic from expand_module in hierarchy.cc

- passes/opt/opt_expr.cc
- tests/opt/opt_expr_constconn.v
- tests/opt/opt_expr_constconn.ys
This adds one simple piece of functionality to opt_expr: when a cell
port is connected to a fully-constant signal (as determined by sigmap),
the port is reconnected directly to the constant value.  This is just
enough optimization to fix the "non-constant $meminit input" problem
without requiring a full opt_clean or a separate pass.
> opt_expr: Propagate constants to port connections.

- frontends/verilog/preproc.cc
- frontends/verilog/preproc.h
- tests/verilog/macro_arg_tromp.sv
- tests/verilog/macro_arg_tromp.ys
> verilog: save and restore overwritten macro arguments

- techlibs/xilinx/xc7_brams_map.v
UG473 from Xilinx states that 15 bit should always be set if RAMB isn't in cascade mode.
Signed-off-by: Maciej Dudek <mdudek@antmicro.com>
> Fixes xc7 BRAM36s

- passes/memory/memory_bram.cc
> memory_bram: Move init data swizzling before other swizzling.

- passes/memory/memory_share.cc
> memory_share: Don't skip ports with EN wired to input for SAT sharing.

- frontends/verilog/verilog_lexer.l
These are, by the standard, just aliases for wire/wand/wor.
Fixes #2918.
> verilog: Support tri/triand/trior wire types.

- Makefile
- kernel/modtools.h
- kernel/qcsat.cc
- kernel/qcsat.h
- passes/memory/memory_share.cc
- passes/opt/opt_dff.cc
- passes/opt/share.cc
This also aligns the functionality:
- in all cases, the onehot attribute is used to create appropriate
constraints (previously, opt_dff didn't do it at all, and share
created one-hot constraints based on $pmux presence alone, which
is unsound)
- in all cases, shift and mul/div/pow cells are now skipped when
importing the SAT problem (previously only memory_share did this)
— this avoids creating clauses for hard cells that are unlikely
to help with proving the UNSATness needed for optimization
> Refactor common parts of SAT-using optimizations into a helper.

- frontends/verilog/verilog_parser.y
An extra comma is already allowed in module port lists and task/function argument lists, so I thought, why not in enum.
> Allow optional comma after last entry in enum

- backends/cxxrtl/cxxrtl_backend.cc
- backends/verilog/verilog_backend.cc
- kernel/mem.cc
- kernel/mem.h
- passes/memory/memory_bram.cc
- passes/memory/memory_dff.cc
- passes/memory/memory_share.cc
- passes/opt/opt_mem_feedback.cc
This should be in mergeable state, but I'd like to delay the merge until it has been properly validated by the following follow-up PRs:
- #2807, rebased on top of this and with transparency mask support in new cells
- future PR that will add transparency logic recognition to `memory_dff`
> kernel/mem: Introduce transparency masks.

- tests/arch/ecp5/memories.ys
- tests/arch/ice40/memories.ys
These parts keep rereading a Verilog module, then using chparam
to test it with various parameter combinations.  Since the default
parameters are on the large side, this spends a lot of time
needlessly elaborating the default parametrization that will then
be discarded.  Fix it with -deref and manual hierarchy call.
Shaves 30s off the test time on my machine.
> test/arch/{ecp5,ice40}/memories.ys: Use read_verilog -defer.

- passes/memory/memory_share.cc
This fixes wide port recognition in some cases.
> memory_share: Pass addresses through sigmap_xmux everywhere.

- frontends/verilog/verilog_parser.y
- tests/svtypes/typedef_initial_and_assign.sv
- tests/svtypes/typedef_initial_and_assign.ys
This is on top of #2847 to exclude invalid syntax and support declaring nets and variables with user-defined types.
> Support wire and var with typedef

- kernel/log.cc
- passes/cmds/logger.cc
This allows us to have multiple "expect this warning" calls in a single
long script, covering only as many passes as necessary.
> logger: Add -check-expected subcommand.

- passes/memory/memory.cc
- passes/memory/memory_share.cc
- tests/memories/run-test.sh
- tests/memories/wide_read_async.v
- tests/memories/wide_read_mixed.v
- tests/memories/wide_read_sync.v
- tests/memories/wide_read_trans.v
- tests/memories/wide_thru_priority.v
- tests/memories/wide_write.v
- tests/opt/memory_dff_trans.ys
- tests/opt/opt_mem_priority.ys
This unlocks wide port recognition by default.
Submitting as draft, as it's still missing tests.
> memory_share: Add -nosat and -nowiden options.

- Makefile
- frontends/ast/Makefile.inc
- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/ast_binding.cc
- frontends/ast/ast_binding.h
- frontends/ast/genrtlil.cc
- kernel/binding.cc
- kernel/binding.h
- kernel/rtlil.cc
- kernel/rtlil.h
This code now takes the AST nodes of type AST_BIND and generates a
representation in the RTLIL for them.
This is a little tricky, because a binding of the form:
bind baz foo_t foo_i (.arg (1 + bar));
means "make an instance of `foo_t` called `foo_i`, instantiate it inside
`baz` and connect the port `arg` to the result of the expression `1+bar`".
Of course, `1+bar` needs a cell for the addition. Where should that cell
live?
With this patch, the `Binding` structure that represents the construct
is itself an `AST::AstModule` module. This lets us put the adder cell
inside it. We'll pull the contents out and plonk them into 'baz' when
we actually do the binding operation as part of the hierarchy pass.
Of course, we don't want `RTLIL::Binding` to contain an
`AST::AstModule` (since kernel code …
> Generate an RTLIL representation of bind constructs

- passes/proc/proc_prune.cc
- tests/proc/bug2962.ys
> proc_prune: Make assign removal and promotion per-bit, remember promoted bits.

- kernel/mem.cc
> kernel/mem: Remove old parameter when upgrading $mem to $mem_v2.

- techlibs/ice40/cells_sim.v
> ice40: Fix typo in SB_CARRY specify for LP/UltraPlus

- techlibs/gowin/cells_map.v
- techlibs/gowin/cells_sim.v
- techlibs/gowin/synth_gowin.cc
- techlibs/nexus/cells_map.v
- tests/arch/gowin/tribuf.ys
Now that we're adding support in Apicula for inout and tristate buffers we're finding that they are actually active-low, causing inverted behavior.
This PR matches the behavior of Nexus explained in #2916 by using an intermediate cell.
It also moves the iopadmap earlier into the process, so that there is more room to optimize away the inverter.
> Gowin: deal with active-low tristate

- passes/opt/opt_clean.cc
- tests/techmap/iopadmap.ys
Previously, opt_clean would reconnect all ports (including FF Q ports)
to a "canonical" SigBit chosen by complex rules, but would leave the
init attribute on the old wire.  This change applies the same
canonicalization rules to the init attributes, ensuring that init moves
to wherever the Q port moved.
Part of another jab at #2920.
> opt_clean: Make the init attribute follow the FF's Q.

- passes/opt/opt_merge.cc
Mutating the SigMap by adding a new connection will throw off FfInitVals
index.  Work around this by removing the relevant init values from index
whenever we connect nets, then re-add the new init value.
Should fix #2920.
> opt_merge: Remove and reinsert init when connecting nets.

- techlibs/ecp5/brams.txt
- techlibs/ecp5/lutrams.txt
The current link points to a tutorial that does not (no longer?) describe these attributes. The new link points to "Lattice Synthesis Engine for Diamond User Guide". I hope this is the correct document, please check again before merging.
Thank you.
> [ECP5] fix wrong link for syn_* attributes description

- frontends/verilog/verilog_parser.y
- tests/verilog/genfor_decl_no_init.ys
- tests/verilog/genfor_decl_no_sv.ys
- tests/verilog/genvar_loop_decl_1.sv
- tests/verilog/genvar_loop_decl_1.ys
- tests/verilog/genvar_loop_decl_2.sv
- tests/verilog/genvar_loop_decl_2.ys
- tests/verilog/genvar_loop_decl_3.sv
- tests/verilog/genvar_loop_decl_3.ys
This is accomplished by generating a unique name for the genvar, renaming references to the genvar only in the loop's initialization, guard, and incrementation, and finally adding a localparam inside the loop body with the original name so that the genvar can be shadowed as expected.
> sv: support declaration in generate for initialization

- passes/techmap/abc9_ops.cc
- techlibs/ecp5/synth_ecp5.cc
- tests/arch/ecp5/bug2731.ys
Fixes #2731.
If more than one cell exists which instantiates an `(* abc9_box *)` that contains a non-zero initial value, then the first cell will have its type/parameters flattened, but not any following cells.
> abc9: replace cell type/parameters if derived type already processed

- passes/techmap/abc9_ops.cc
- tests/techmap/bug2759.ys
Rather than using the identifier from the first matching cell in the user design.
Fixes #2759.
> abc9: holes module to instantiate cells with NEW_ID

- passes/techmap/abc9.cc
- passes/techmap/abc9_ops.cc
- tests/techmap/bug2972.ys
Clean up some state at the end of `abc9` so that it can be re-entrant.
Fixes #2972.
> abc9: make re-entrant

- backends/protobuf/Makefile.inc
`backends/protobuf/protobuf.cc` depends on the source and header files generated by `protoc`, but this dependency wasn't explicitly declared. This PR adds a rule to the Makefile to fix intermittent build failures when the protobuf header/source file isn't (due to sheer luck) built before `protobuf.cc`.
> Fix protobuf backend build dependencies - intermittent build issue due to missing rule

- frontends/ast/simplify.cc
- frontends/verilog/verilog_parser.y
- tests/verilog/prefix.sv
- tests/verilog/prefix.ys
- Root AST_PREFIX nodes are now subject to genblk expansion to allow them to refer to a locally-visible generate block
- Part selects on AST_PREFIX member leafs can now refer to generate block items (previously would not resolve and raise an error)
- Add source location information to AST_PREFIX nodes
Fixes #2905
> verilog: fix multiple AST_PREFIX scope resolution issues

- CHANGELOG
- frontends/verilog/verilog_parser.y
- tests/verilog/net_types.sv
- tests/verilog/net_types.ys
This enables the usage of declarations of wand or wor with a base type of logic, integer, or a typename. Note that declarations of nets with 2-state base types is still permitted, in violation of the spec.
> sv: support wand and wor of data types

- frontends/rtlil/rtlil_parser.y
- frontends/verilog/verilog_parser.y
Yosys works with bison 3.0 (or newer), but not bison 2.7 (the previous release). Ideally, we would require "3" rather than "3.0" to give a better error message, but bison 2.3, which still ships with macOS, does not support major-only version requirements. With this change, building with an outdated bison yields: `frontends/rtlil/rtlil_parser.y:25.10-14: require bison 3.0, but have 2.3`.
> Specify minimum bison version 3.0+

- backends/verilog/verilog_backend.cc
- kernel/ff.h
- kernel/ffmerge.cc
- kernel/mem.cc
- kernel/satgen.cc
- passes/memory/memory_dff.cc
- passes/opt/opt_dff.cc
- passes/sat/async2sync.cc
- passes/sat/clk2fflogic.cc
- passes/techmap/dffunmap.cc
- passes/techmap/zinit.cc
- *_en is split into *_ce (clock enable) and *_aload (async load aka
latch gate enable), so both can be present at once
- has_d is removed
- has_gclk is added (to have a clear marker for $ff)
- d_is_const and val_d leftovers are removed
- async2sync, clk2fflogic, opt_dff are updated to operate correctly on
FFs with async load
> kernel/ff: Refactor FfData to enable FFs with async load.

- backends/verilog/verilog_backend.cc
Verilator can not handle verilog input where modules do have large number of ports defined.
Splitting it multiple lines for easier parsing. Should help other software consuming verilog as well.
> Split module ports, 20 per line

- frontends/verific/verific.cc
This add support for bufif0, bufif1, notif0 and notif1 when used in Verific.
Difference between these two on Verific side is only in case:
```
input     output
PRIM_TRI        Z         Z 
PRIM_BUFIF1     Z         X 
```
> Support PRIM_BUFIF1 primitive, fixes #2981

- passes/opt/opt_lut_ins.cc
- techlibs/gowin/synth_gowin.cc
Now that Apicula support wide luts, enable them in yosys.
Also fix `opt_lut_ins` to never remove a LUT in the "gowin" target, because it leaves incomplete wideluts.
Supersedes #3037
> gowin: widelut support

- techlibs/gowin/synth_gowin.cc
As of [0.0.1a12](https://github.com/YosysHQ/apicula/releases/tag/0.0.1a12) Apicula supports ALU, so this no longer needs to be disabled in the nextpnr flow.
> Remove noalu from synth_gowin json output as Apicula now supports it

- manual/command-reference-manual.tex
Building `yosys` as a package for Fedora, I get the following `pdflatex` / `inputenc` error while building the manual:
```
! Package inputenc Error: Keyboard character used is undefined
(inputenc)                in inputencoding `latin1'.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
...                                              
l.3159 ...y can never collide with each other — 
ie. there can never be
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on manual.log.
make: *** [Makefile:897: manual] Error 1
```
With this PR applied, the manual PDF once again builds correctly.
> manual: fix pdflatex inputenc undefined char error

- techlibs/gowin/synth_gowin.cc
`splitnets` will not split ports by default, but `iopadmap` creates a new internal net which could be a wider bus. By moving the command down, any generated nets are also split.
This does not completely solve #2434 but it should resolve some cases where it happens.
> synth_gowin: move splitnets to after iopadmap

- frontends/ast/genrtlil.cc
Discovered while working on https://github.com/YosysHQ/yosys/pull/3050
When packages are processed, they don't have current_ast_mod set and when some error occurs while processing package, it results in segmentation fault.
This PR adds check if current_ast_mod is set and if so, it displays whole module AST, if not it only displays AST of current node.
> genrtlil: Fix displaying debug info in packages

- frontends/verific/verific.cc
This was introduced time ago in https://github.com/YosysHQ/yosys/commit/71072d1945b76107a4adc84f6666d100beca6ced#diff-a7714cc0445546659a3412ba5023bc0031110ccda62581ef0622319dfa51d42f where there was actually failure. Meanwhile Verific changed, and widths are properly calculated in all cases, but due to this line we have allocated more memory then needed by design in usual cases.
This also fixes  https://github.com/YosysHQ/yosys/issues/3054
> No need to allocate more memory than used

- passes/cmds/show.cc
> show: Fix wire bit indexing.

- frontends/ast/simplify.cc
- tests/various/param_struct.ys
This PR fixes the case when parameter is used with a wiretype of a struct.
Currently, all of the wiretype children are copied to the parameter children (this includes e.g. ``AST_STRUCT_ITEM``). This makes ``param_has_no_default`` (https://github.com/YosysHQ/yosys/blob/master/frontends/ast/ast.cc#L981) check fail as it assumes that simplified parameter can only have at most 2 children.
``AST_STRUCT_ITEM`` is unused as children to AST_PARAMETER, so I changed it to only copy AST_RANGE from wiretype node.
> Fix parameters using struct as a wiretype

- techlibs/intel_alm/common/alm_sim.v
- techlibs/intel_alm/common/dff_sim.v
- techlibs/intel_alm/common/dsp_sim.v
- techlibs/intel_alm/common/mem_sim.v
- techlibs/intel_alm/common/quartus_rename.v
- techlibs/intel_alm/synth_intel_alm.cc
The non-GZ Arria V parts are essentially just larger Cyclone Vs.
This PR simply adds Arria V timings and extends the `-family` option to accept "arriav".
cc @mwkmwkmwk
> intel_alm: preliminary Arria V support

- manual/command-reference-manual.tex
- passes/opt/opt_mem_priority.cc
This is a fixed version of #3072.
> opt_mem_priority: Fix non-ascii char in help message.

- frontends/verific/verific.cc
When interface is used there is a PortBus but direction for it is none. Patch set direction to one of first bit if defined.
[test_case.zip](https://github.com/YosysHQ/yosys/files/7675476/test_case.zip)
> If direction NONE use that from first bit

- frontends/verific/verific.cc
Test case:
```SystemVerilog
typedef enum logic {d0 = 1'b0, d1 = 1'b1, dx = 1'bx, dz = 1'bz} data_t;
typedef enum logic [3:0] {c0 = 4'b zzz1, c1 = 4'b zz1z, cx = 4'b z1zz, cz = 4'b 1zzz} ctrl_t;
module enum_xz(input logic clk, input ctrl_t ctrl, input data_t data, input data_t [0:3] cmp, output logic [1:0] out);
always_comb begin
casez (ctrl)
c0: out = {data === d0, data === cmp[0]};
c1: out = {data === d1, data === cmp[1]};
cx: out = {data === dx, data === cmp[2]};
cz: out = {data === dz, data === cmp[3]};
default: out = 2'b 00;
endcase
end
endmodule
```
> Fix verific import of enum values with x and/or z

- backends/verilog/verilog_backend.cc
Before this commit, zero width sigspecs were dumped as "" (empty
string). Unfortunately, 1364-2005 5.2.3.3 indicates that an empty
string is equivalent to "\0", and is 8 bits wide, so that's wrong.
After this commit, a replication operation with a count of zero is
used instead, which is explicitly permitted per 1364-2005 5.1.14,
and is defined to have size zero. (Its operand has to have a non-zero
size for it to be legal, though.)
PR #1203 has addressed this issue before, but in an incomplete way.
> write_verilog: dump zero width sigspecs correctly

- backends/rtlil/rtlil_backend.cc
Without this, empty connections will be always skipped by `dump`, since
they contain no selected wires.  This makes debugging rather confusing.
> rtlil: Dump empty connections when whole module is selected.

- kernel/mem.cc
> Fix null pointer dereference after failing to extract DFF from memory

- frontends/verilog/preproc.cc
- tests/verilog/doubleslash.ys
The preprocessor currently destroys double slash containing escaped
identifiers (for example \a//b ). This is due to next_token trying to
convert single line comments (//) into /* */ comments. This then leads
to an unintuitive error message like this:
ERROR: syntax error, unexpected '*'
This patch fixes the error by recognizing escaped identifiers and
returning them as single token. It also adds a testcase.
> preprocessor: do not destroy double slash escaped identifiers

- backends/cxxrtl/cxxrtl_backend.cc
Fixes #3112.
Co-authored-by: Irides <irides@irides.network>
> cxxrtl: demote wires not inlinable only in debug_eval to locals

- CHANGELOG
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- tests/simple/case_expr_extend.sv
- tests/simple/case_expr_query.sv
I also removed the unnecessary shadowing of `width_hint` and `sign_hint` in the corresponding case in `simplify()`.
This fixes the issue raised in #3082, while also handling the (now covered) edge case that requires the existing ordering of `detectSignWidth` and `simplify`.
> fix width detection of array querying function in case and case item expressions

- techlibs/intel_alm/common/bram_m10k.txt
This BRAM mode uses both address ports of the M10K memory block, making it logically single-port.
Since memory_bram can't presently map to single-port memories, remove it.
> intel_alm: disable 256x40 M10K mode

- backends/cxxrtl/cxxrtl_backend.cc
Such wires can be generated by Amaranth.
> cxxrtl: don't reset elided wires with \init attribute

- CHANGELOG
- frontends/ast/genrtlil.cc
- tests/simple/lesser_size_cast.sv
This fixes the `c2` case in #3090. Fixes for `c3` will come separately after further investigation.
> sv: fix size cast clipping expression width

- tests/verilog/.gitignore
- tests/verilog/doubleslash.ys
This test was recently introduced in #2982. My original motivation was to prevent running the `verilog` suite from making the working directory dirty. Rather than avoid creating the file, I decided to extend the test to make use of it.
- add generated doubleslash.v to .gitignore
- ensure backend verilog can be read again
> fixup verilog doubleslash test

- tests/simple/case_expr_extend.sv
- tests/simple/case_expr_query.sv
The Docker image uses an older version of iverilog (10.2). I confirmed the build works with these changes, and that the tests are still providing the intended coverage. @Trolldemorted, can you double check that this fixes your build? 
Fixes #3132.
> fix iverilog compatibility for new case expr tests

- manual/CHAPTER_TextRtlil.tex
In RTLIL cell statements; the type becomes before the name.
e.g. `cell $sub $5`
> manual: Fix cell-stmt order

- passes/opt/opt_dff.cc
Newer GCCs emit the following warning for opt_dff:
passes/opt/opt_dff.cc:560:17: warning: operation on ‘ff.Yosys::FfData::has_clk’ may be undefined [-Wsequence-point]
560 |      ff.has_clk = ff.has_ce = ff.has_clk = false;
|      ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Which is correct: the order of whether the read or write of has_clk occurs first is undefined since there is no sequence point between them.
This is almost certainly just a typo/copy paste error and objectively wrong, so just fix it.
> opt_dff: fix sequence point copy paste bug

- kernel/log.cc
- tests/various/logger_fail.sh
- Prevent unmatched expected error patterns from self-matching
- Prevent infinite recursion on unmatched expected warnings
- Always print the error message for unmatched error patterns
- Add test coverage for all unmatched message types
- Add test coverage for excess matched logs and warnings
> logger: fix unmatched expected warnings and errors

- CHANGELOG
- frontends/ast/genrtlil.cc
- tests/verilog/size_cast.sv
- tests/verilog/size_cast.ys
This fixes the `c3` case in #3090. Given #3135 has been merged, this closes #3090.
> sv: fix size cast internal expression extension

- CHANGELOG
- frontends/ast/simplify.cc
- tests/verilog/always_comb_latch_1.ys
- tests/verilog/always_comb_latch_2.ys
- tests/verilog/always_comb_latch_3.ys
- tests/verilog/always_comb_latch_4.ys
- tests/verilog/always_comb_nolatch_1.ys
- tests/verilog/always_comb_nolatch_2.ys
- tests/verilog/always_comb_nolatch_3.ys
- tests/verilog/always_comb_nolatch_4.ys
If a local variable is always assigned before it is used, then adding nosync prevents latches from being needlessly generated.
This supplants #3059.
@tgorochowik @kamilrakoczy
> sv: auto add nosync to certain always_comb local vars

- techlibs/anlogic/.gitignore
- techlibs/anlogic/Makefile.inc
- techlibs/anlogic/brams.txt
- techlibs/anlogic/brams_init.py
- techlibs/anlogic/brams_map.v
- techlibs/anlogic/synth_anlogic.cc
- tests/arch/anlogic/blockram.ys
- tests/arch/anlogic/lutram.ys
Anlogic FPGAs all have two kinds of BRAMs, one is 9bit*1K when being
true dual port (or 18bit*512 when simple dual port), the other is
16bit*2K.
Supports mapping of these two kinds of BRAMs. 9Kbit BRAM in SDP mode and
32Kbit BRAM with 8bit width are not support yet.
-------------------------------------
BTW after applying this patch Yosys can do better than Anlogic TD synthesizer now, because the vendor one just infer anything as bram9k, and then complain about the lack of bram9k (even when bram32k is still totally not used yet...)
> anlogic: support BRAM mapping

- backends/verilog/verilog_backend.cc
> verilog backend: Emit a `wire` for ports as well.

- techlibs/quicklogic/synth_quicklogic.cc
This PR helps add some missing fields in the reference manual.
Edit:
This PR helps fix the help message of `synth_quicklogic` command.
Before:
```
yosys> help synth_quicklogic
synth_quicklogic [options]
This command runs synthesis for QuickLogic FPGAs
...
verilog:
```
After:
```
yosys> help synth_quicklogic
synth_quicklogic [options]
This command runs synthesis for QuickLogic FPGAs
...
verilog:
write_verilog -noattr -nohex <file-name>
```
> Fix the help message of synth_quicklogic command.

- frontends/ast/ast.cc
Without this change, Apple clang 13.0.0 produces the warning below.
```
frontends/ast/ast.cc:348:23: warning: format specifies type 'int' but the argument has type 'std::__bit_const_reference<std::vector<bool>>' [-Wformat]
fprintf(f, " %d", v);
~~   ^
```
> fix dumpAst() compilation warning

- backends/smt2/smtbmc.py
Add a bit of flexibilty re trace length when processing aiger witnesses in smtbmc.py
Signed-off-by: Claire Xenia Wolf <claire@clairexen.net>
> Add a bit of flexibilty re AIG witness trace length to smtbmc.py

- Makefile
- backends/json/json.cc
- frontends/json/jsonparse.cc
- tests/various/.gitignore
- tests/various/json_escape_chars.ys
https://www.json.org/json-en.html
It is mandatory to escape the characters `\`, `"`, and any control character (<0x20) in JSON. This uses the two-character escapes `\\ \" \r \t \n \f \b` preferentially, and `\uXXXX` escapes for others in `write_json`.
It's optionally allowed to escape any character. This accepts any of the above in `read_json`, but *does not* implement parsing of code points >0x7F (despite this being mandatory according to the standard).
> fix handling of escaped chars in json backend and frontend (mostly)

- frontends/verific/verific.cc
Attribute value starts/ends with quotes if it is string attribute coming from Verific
> Remove quotes if any from attribute

- backends/smt2/smt2.cc
- backends/smt2/smtio.py
Part of https://github.com/YosysHQ/sby/pull/133: print the exact cell name of the assert for lookup/use in sby
Q: should this even be an extra argument or should we always just print the cell name too?
> add argument for printing cell names in yosys-smtbmc

- backends/json/json.cc
This field was added in https://github.com/YosysHQ/yosys/pull/2006 but the help message was not updated at that time
> json: Add help message for `signed` field

- .github/workflows/test-linux.yml
This PR aims to remove excess build variants from the CI. Please feel free to share any comments or concerns!
**Update:** see https://github.com/YosysHQ/yosys/pull/3222#issuecomment-1065015254
Below are the 18 current Linux matrix runs, with the 10 runs this PR removes struck.
* ubuntu-20.04, focal, clang-12, c++11
* ~~ubuntu-20.04, focal, clang-12, c++14~~
* ~~ubuntu-20.04, focal, clang-12, c++17~~
* ubuntu-20.04, focal, clang-12, c++20
* ubuntu-20.04, focal, clang-11, c++11
* ~~ubuntu-20.04, focal, clang-11, c++14~~
* ~~ubuntu-20.04, focal, clang-11, c++17~~
* ~~ubuntu-20.04, focal, clang-11, c++20~~
* ubuntu-20.04, focal, gcc-11, c++11
* ~~ubuntu-20.04, focal, gcc-11, c++14~~
* ~~ubuntu-20.04, focal, gcc-11, c++17~~
* ubuntu-20.04, focal, gcc-11, c++20
* ubuntu-20.04, focal, gcc-10, …
> Prune Linux CI builds

- kernel/rtlil.cc
This results in a slight ~0.22% total speedup synthesizing vexriscv
> Add some more reserve calls to RTLIL::Const

- passes/techmap/abc9.cc
This adds an additional ABC9 script which uses `&mfs` calls where [the original `&flow3` script does](https://github.com/berkeley-abc/abc/blob/796c29039a4983e92bf12051d73326758127162e/src/aig/gia/giaScript.c#L765-L772).
Experimentally I've found this to be a bit better in some cases when playing about with different values of `abc9.W`. Otherwise, no functional change.
> abc9: add flow3mfs script

- backends/smt2/smtbmc.py
This adds the `--keep-going` option to smtbmc which continues the BMC run even after an assertion failed. Further assertion failures are reported. If necessary, multiple counterexample traces are written.
> smtbmc `--keep-going`

- backends/smt2/smtio.py
Currently the unroll code uses `deepcopy` to make a snapshot of the unrolling state whenever the solver state is pushed. It also uses `deepcopy` on declarations/definitions before substituting parameters. Since no element of the dicts/sets that make up the unrolling state is ever mutated, a shallow `copy` is sufficient. When substituting parameters, the code also recursively builds a new expression, so there too a shallow copy is sufficient.
These `deepcopy` calls have become a bottleneck for my currently WIP changes to check one individual assertion at a time, which can result in many more solver state pushs/pops.
Locally tested with the sby tests.
> smtbmc: Avoid unnecessary deep copies during unrolling

- backends/smt2/smtbmc.py
this was broken by the `--keep-going` changes
> smtbmc: fix bmc with no assertions

- frontends/verific/verific.cc
- frontends/verific/verific.h
In current implementation std::set is used and that one is ordered, but it is ordered per pointer which is not consistent. 
Changed data structure to use std::map which will be ordered by imported module name.
Also found error that check in line 2213 did not have any sense, and verific -import was not properly assigning top attribute, due to missing check (added in line 3209)
> Import Verific netlist in consistent order

- passes/sat/clk2fflogic.cc
With current code next example fails since counter starts at wrong value.
Bug is noticed due to fact that all FFs are aldffs when imported trough Verific.
```
[options]
mode bmc
multiclock on
depth 2
[engines]
smtbmc boolector
[script]
read -formal aldff.v
prep -top aldff
[file aldff.v]
module aldff(
input clk
);
parameter WIDTH=10;
reg [3:0] f_count;
initial f_count = 1;
always @(posedge clk)
if (f_count == WIDTH-1)
f_count <= 0;
else
f_count <= f_count + 1'b1;
always @(*)
assert(f_count < WIDTH);
endmodule
```
> Set init values for wrapped  async control signals

- passes/opt/opt.cc
- passes/opt/opt_merge.cc
- tests/opt/opt_merge_init.ys
The `-keepdc` option prevents merging flipflops with dont-care bits in their initial value, as, in general, this is not a valid transform for formal verification.
The keepdc option of `opt` is passed along to `opt_merge` now.
See https://github.com/YosysHQ/sby/pull/155 for an example of how the current `opt_merge` behavior as invoked from `opt -keepdc` is not valid in this setting.
I don't know whether `opt -keepdc` is used outside of formal verification. If this breaks any other uses I can split off this behavior into another option and change the yosys scripts generated by sby.
> opt_merge: Add `-keepdc` option required for formal verification

- Makefile
- passes/sat/Makefile.inc
Currently several files are compiled always despite a dependency on inclusion of libraries that are conditionally compiled in. This fixes the issue by expressing the dependency in the build system properly.
> Do not enable features that require the support of compression compiled in

- kernel/fstdata.cc
- passes/sat/sim.cc
- handle multiclock for btor2 witness files
- properly set all signals coming from FST input in simulation model (this covers flip flops and $anyconst)
- handle $anyseq cells in simulation
- only if last sample of input FST file contains clock edge, ignore it, since solvers produce edge without updating rest of values
- fix aiger witness file to set latches to zero always independent if they are inverse latches
> Simulation improvements

- libs/fst/config.h
After this fix, `abc` compilation failed, which was fixed upstream in https://github.com/berkeley-abc/abc/pull/147. I have applied that change locally and used `ABCREV=default` to buid). Do you prefer to merge upstream changes into https://github.com/YosysHQ/abc, or should I make a PR with that change for your fork?
> Fix build on FreeBSD, which has no alloca.h

- backends/smt2/smt2.cc
Currently, for smt2, write ports are encoded by unconditionally applying the `store` operation to the array containing the previous state's memory content. When the write mask is all zeros, this results in a store operation that leaves the array unchanged, but solvers might take a long time to discover this useful fact. This PR changes the encoding to explicitly select the previous state's array as new memory content when the write mask is all zero (matching the encoding used for btor output). This encoding change results in much faster solving times for the benchmarks I tested it on. For example when using riscv-formal's reg_check for the picorv32 core I get the following results:
* `smtbmc boolector` (before): 18:04.20 total
* `smtbmc boolector` (this PR): 2:49.22 total
This closes most …
> smt2: Make write port array stores conditional on nonzero write mask

- passes/memory/memory_share.cc
In memory_share pass, the call to `extra_args` specifies `1` as `argidx` which makes memory_share fail when any of the options is specified:
```
yosys> memory_share -nowiden
2. Executing MEMORY_SHARE pass (consolidating $memrd/$memwr cells).
Syntax error in command `memory_share -nowiden':
memory_share [-nosat] [-nowiden] [selection]
This pass merges share-able memory ports into single memory ports.
The following methods are used to consolidate the number of memory ports:
- When multiple write ports access the same address then this is converted
to a single write port with a more complex data and/or enable logic path.
- When multiple read or write ports access adjacent aligned addresses, they are
merged to a single wide read or write port.  This transformation can be
disabled with the …
```
> memory_share: fix wrong argidx in extra_args

- backends/btor/btor.cc
- kernel/fstdata.cc
- kernel/fstdata.h
- passes/sat/sim.cc
Included changes are here to support two different ways of representing memory locations in VCD/FST file, one is memory_cell<hex_address> and other memory_cell[decimal_addres], in both cases we create special memory structure with mappings of specific addresses to data inputs in FST (so mem cells can use that directly) and also add mapping to memory_cell[decimal_addres] as wire, since memory pass can convert mem cells to registers.
Also including change in btor writer to put aliases for main clock signal in info file, that then generates proper VCD output created by btorsim.
> sim pass: support for memories

- frontends/verific/verific.cc
- frontends/verific/verific.h
- frontends/verific/verificsva.cc
- tests/sva/nested_clk_else.sv
For SVAs that have an explicit clock and are contained in a procedure
which conditionally executes the assertion, verific expresses this using
a mux with one input connected to constant 1 and the other output
connected to an SVA_AT. The existing code only handled the case where
the first input is connected to 1. This patch also handles the other
case.
> verific: Fix conditions of SVAs with explicit clocks within procedures

- frontends/verific/verific.cc
- tests/sva/sva_value_change_changed_wide.sv
- tests/sva/sva_value_change_sim.sv
I missed this in the previous PR #3305, this uses the same new logic now also for wide signals.
> verific: Use new value change logic also for $stable of wide signals.

- kernel/yosys.cc
Without this patch, Yosys doesn't call Tcl_Init(), which means that a handful of Tcl commands don't work - for example, attempting to use "clock format" results in the following error:
ERROR: TCL interpreter returned an error: invalid command name "::tcl::clock::format"
Tcl_Init() calls the init.tcl script, part of the Tcl standard library code, which fills in some implemented-in-tcl commands in the ::tcl::clock namespace, namely clock format, clock add and clock scan.
Adding this call fixes the problem.
> Now calls Tcl_Init after creating the interp, fixes clock format.

- passes/cmds/select.cc
Both of these options consider a selection containing only empty modules
as non-empty. This wasn't mentioned in the documentation nor did the
error message when using `select -assert-none` list those empty modules,
which produced a very confusing error message complaining about a
non-empty selection followed by an empty listing of the selection.
This fixes the documentation and changes the `-assert-none` and
`-assert-any` assertion error messages to also output fully selected
modules (this includes selected empty modules).
It doesn't change the messages for `-assert-count` etc. as they don't
count modules.
> select: Fix -assert-none and -assert-any error output and docs

- CHANGELOG
- frontends/ast/simplify.cc
- tests/verilog/unreachable_case_sign.ys
This fixes an issue where simplifying case statements by removing unreachable cases can result in the wrong signedness being used for comparison with the remaining cases.
> verilog: fix signedness when removing unreachable cases

- backends/smt2/smt2.cc
Fixes: #3330
Also adds a simple test that `$divfloor` and `$modfloor` actually work correctly, though it does require yices to run...
> add $divfloor support to write_smt2

- CHANGELOG
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- tests/verilog/past_signedness.ys
This fixes https://github.com/YosysHQ/sby/issues/132 and fixes https://github.com/YosysHQ/sby/issues/117
> verilog: fix $past's signedness

- Makefile
The WebAssembly build (`make config-emcc`) generates tons of unnecessary warnings. This PR fixes these warnings by splitting the compiler and linker arguments in the Makefile.
Warnings that are resolved:
```
emcc: warning: linker flag ignored during compilation: '--memory-init-file' [-Wunused-command-line-argument]
emcc: warning: linker flag ignored during compilation: '--embed-file' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during compilation: 'NO_EXIT_RUNTIME' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during compilation: 'EXPORTED_FUNCTIONS' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during compilation: 'TOTAL_MEMORY' [-Wunused-command-line-argument]
emcc: warning: linker setting ignored during …
```
> Fix emcc warnings for WebAssembly build

- kernel/fstdata.cc
- kernel/yosys.cc
- kernel/yosys.h
- passes/sat/qbfsat.cc
- passes/techmap/abc.cc
- passes/techmap/abc9.cc
POSIX defines $TMPDIR as containing the pathname of the directory where
programs can create temporary files. On most systems, this variable points to
"/tmp". However, on some systems it can point to a different location.
Without respecting this variable, yosys fails to run on such systems.
Signed-off-by: Mohamed A. Bamakhrama <mohamed@alumni.tum.de>
> Observe $TMPDIR variable when creating tmp files

- Makefile
The `EMCC_LDFLAGS` in the `Makefile` are overwritten in the second line due to a typo. This typo breaks the emcc build during WebAssembly runtime, because the `share` folder is not embedded.
> Fix typo in emcc flags (typo introduced by #3053)

- passes/cmds/sta.cc
I got a bit tired of being spammed with warnings in complex designs.
> sta: warn on unrecognised cells only once

- backends/smt2/smtio.py
This fixes #3356 and also fixes trace generation when using cvc4/5 in smtbmc's `--unroll` mode by reissuing `(check-sat)` whenever further unrolling is needed during trace generation.
> smtbmc: recognize cvc5 and fix unrolling for cvc4/cvc5

- passes/fsm/fsmdata.h
The local variable is used just to iterate through the values, so
a const reference is all we need.
> Avoid unnecessary copy of a potential large constant value.

- kernel/rtlil.cc
- kernel/rtlil.h
No need for a manual implementation.
While at it: have the constructor that takes a string take a
const string reference instead to avoid a copy.
> Use compiler-generated default  copy constructor for RTLIL::Const::Const

- passes/cmds/select.cc
- passes/cmds/stat.cc
E.g. so the value can be accessed for decision making in script passes.
> Make 'stat' and 'select -count' save counts to scratchpad

- backends/smt2/smtio.py
Without this, trace generation fails when combining --unroll with --noincr
> smtbmc: noincr: keep solver running for post check-sat unrolling

- backends/btor/btor.cc
- backends/smt2/smt2.cc
This avoids provability regressions now that we infer more ROMs.
This fixes #3378
> smt2, btor: Use memory_map -rom-only to make ROMs usable for k-induction

- backends/btor/btor.cc
This PR adds support for the `$pos` cell type to the btor backend.
This is my first PR to yosys and I would appreciate any comments on style and any possible misunderstandings wrt. how the `$pos` cell is supposed to be interpreted. Thanks!
> btor: add support for $pos cell

- frontends/blif/blifparse.cc
- tests/blif/bug3374.ys
Add a check when parsing BLIF that model name is not nullptr.
Fixes #3374
> Add check for BLIF with no model name

- passes/sat/async2sync.cc
The formal backends do not support multiple clocks. This includes
constant clocks. Constant clocks do appear in what isn't a proper
multiclock design, for example when mapping not fully initialized ROMs.
As converting FFs with constant clocks to FFs using the global is doable
even in a single clock flow, make async2sync do this.
> async2sync: turn FFs with const clks into gclk FFs with feedback

- kernel/yosys.cc
This pull request is to address YosysHQ/yosys#2980.
The documentation, as originally written, does not make it clear that yosys commands, when used within a tcl script, do not return any value to the tcl script.
This pull request notes this and offers a workaround via tee as noted in the issue.
> Update tcl doc, yosys does not return data to tcl

- Makefile
- libs/fst/config.h
These three commits are all it takes to compile the yosys part!
```
$ gmake ENABLE_TCL=0 ENABLE_READLINE=0
[Makefile.conf] CONFIG := clang
[  0%] Building kernel/version_52c275a8c.cc
[  0%] Building kernel/version_52c275a8c.o
[100%] Building yosys
/usr/local/bin/ld: libs/fst/fstapi.o: in function `fstWriterEmitHdrBytes(fstWriterContext*)':
/home/josuah/Code/yosys/libs/fst/fstapi.cc:893: warning: strcpy() is almost always misused, please use strlcpy()
/usr/local/bin/ld: libs/fst/fstapi.o: in function `fstWriterClose':
/home/josuah/Code/yosys/libs/fst/fstapi.cc:1994: warning: sprintf() is often misused, please use snprintf()
[100%] Building yosys-config
[100%] Building abc/abc-5f40c47
Pulling ABC from https://github.com/YosysHQ/abc:
+ test -d abc
+ git clone https://github.com/YosysHQ/abc …
```
> Better compatibility for OpenBSD

- backends/jny/jny.cc
- misc/jny.schema.json
This PR addes the `jny.schema.json` to formally define the output files from the `write_jny` pass, as well as defining the new element for the output `invocation` which is the exact invocation line used to invoke the backend that produced the file
> jny: Added JNY schema and additional information to JNY output file

- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- frontends/verific/verific.cc
- kernel/rtlil.h
- passes/sat/qbfsat.cc
- passes/techmap/abc.cc
- passes/techmap/abc9_exe.cc
- tests/arch/ice40/.gitignore
- tests/gen-tests-makefile.sh
- tests/tools/autotest.sh
Added encode_filename helper to convert file path to RTLIL compatible string, and used it in verilog and verific frontends. Fixes https://github.com/YosysHQ/yosys/issues/3438
> File path encoding improvements

- frontends/verilog/preproc.cc
According to specs text macros are not affected by `resetall but they are with `undefineall (which is SystemVerilog only)
This fixes https://github.com/YosysHQ/yosys/issues/3410
> resetall does not affect text defines, but undefineall does

- passes/cmds/rename.cc
- tests/various/rename_scramble_name.ys
This is useful for changing the order that ABC{,9} visits nodes, which changes the end netlist.
> rename: add -scramble-name option to randomly rename selections

- passes/cmds/stat.cc
This is useful for `mddbench`, since it makes extracting Yosys statistics easier than e.g. an `awk` script.
Fixes #3371.
> stat: add option for machine-readable json output

- backends/aiger/aiger.cc
- tests/various/aiger_dff.ys
This broke while switching sby's formal flows to always use $_FF_'s.
> write_aiger: Fix non-$_FF_ FFs

- kernel/driver.cc
This adds the `-B <filename.json>` command line option to dump the execution time information to json file (same information as provided by -d option, but machine-readable for use in benchmarking).
> dump runtime information for passes to json

- passes/cmds/show.cc
This PR adds file re-writing to the `show -lib` command to allow for `+/` paths. This closes #409
> yosys: passes: cmds: show: added filename re-writing to `show -lib`

- passes/techmap/abc.cc
After speaking with the author of ABC he let me know that ifraig is a very old command, and that &get; &fraig -x; &put is over 100x faster than ifraig with improved PPA results.
After making the change I confirmed that this is in fact a major speed up. On our internal designs in O(millions) of standard cells we saw multi hour reductions in runtime.
Also included is an improvement to the dress command. Using AIG based transformations removes the spec it SATs against. Providing the input blif will make sure that no matter what commands are run, the dress command can still do its job. I noticed a regression against some LUT mapping jobs that prompted me to fix this.
> Improves ABC command runtime by 10-100x

- passes/techmap/abc.cc
- passes/techmap/abc9.cc
#3333 changed the base directory for the abc tmpdir to use `$TMPDIR`, but didn't change the path rewriting logic for the `-nocleanup` option which assumed that the base directory is `/tmp/`.
This fixes that logic so that the `-nocleanup` option works even on systems (like macOS) where `$TMPDIR` is not `/tmp/`.
> Fix tmpdir naming when passing -nocleanup option to abc(9) on mac

- passes/cmds/stat.cc
Currently, the JSON report does not include any of the technology-specific numbers.
- refactor resource utilization estimation/calculations for Xilinx and CMOS
- add tech tech-specific utilizations to json
The generated output (used for example with "tee" to redirect to a file), is not a valid JSON, as it includes a log header text ("x. Printing statistics.")/
- don't print log_header if the "-json" flag is provided.
> stat: fix and improve JSON report

- passes/techmap/flowmap.cc
In 2fcc1ee72e, the following is apparantly added in order to mark any number of undefined LUT inputs:
lut_a.append(RTLIL::Const(State::Sx, minlut - input_nodes.size()));
However this can only be done if the number of input nodes is less than minlut.
This fixes #3317
> Fix crash in flowmap

- misc/yosys-config.in
On Posix systems, the path /bin/bash is not guaranteed to exist and it is more portable to use /usr/bin/env instead.
Fixing this for yosys-config with is the most important for a functioning installation.
> Fix hard-coded path to /bin/bash -> /usr/bin/env bash

- CHANGELOG
- kernel/log.cc
A debug feature to always get core-dumps on yosys errors without having to re-run yosys under a debugger.
> Add YOSYS_ABORT_ON_LOG_ERROR environment variable for debugging.

- frontends/verific/verific.cc
As discussed on Friday: Add an implicit `-L work` at the beginning of the Verific -L option list, unless `-L work` is already present at any (other) position in the list. (That exception enables the user to specify a library with module implementations that should replace the implementations that come with the design, by specifying that library first, followed by `-L work`.)
> Fix handling of verific -L options, add implicit "-L work"

- passes/equiv/equiv_make.cc
- passes/equiv/equiv_opt.cc
- passes/sat/clk2fflogic.cc
- tests/arch/ice40/bug1597.ys
- tests/arch/ice40/ice40_opt.ys
- tests/arch/intel_alm/counter.ys
- tests/arch/xilinx/abc9_dff.ys
- tests/arch/xilinx/opt_lut_ins.ys
- tests/arch/xilinx/xilinx_dffopt.ys
- tests/opt/opt_dff_en.ys
- tests/opt/opt_dff_mux.ys
- tests/opt/opt_dff_qd.ys
- tests/opt/opt_dff_sr.ys
- tests/opt/opt_expr_xor.ys
- tests/techmap/adff2dff.ys
- tests/techmap/dff2ff.ys
- tests/techmap/dfflegalize_adlatch.ys
- tests/techmap/dfflegalize_adlatch_init.ys
- tests/techmap/dfflegalize_aldff.ys
- tests/techmap/dfflegalize_aldff_init.ys
- tests/techmap/dfflegalize_dffsr_init.ys
- tests/techmap/dfflegalize_dlatchsr_init.ys
- tests/techmap/dfflegalize_sr_init.ys
- tests/techmap/dfflibmap.ys
- tests/techmap/dffunmap.ys
- tests/techmap/pmux2mux.ys
- tests/techmap/shiftx2mux.ys
- tests/techmap/zinit.ys
Fix and re-enable essentially all equiv_opt based tests. This is based on #2740 but instead of changing the negative hold time behavior of clk2fflogic it fixes the underlying issue in the logic used to emulate negative hold time using $ff cells.
Apart from fixing the previously disabled tests in the test suite, this also fixes the following issues:
* #639 remains fixed, even after now having reverted the incorrect previous fix for this
* fixes #2728
* fixes #3169 
* fixes #3428
> equiv_opt and clk2fflogic fixes

- .github/ISSUE_TEMPLATE/bug_report.yml
This PR adds an OS selection drop down for our issue templates to better help identify on which OS or which set of OS families the issues occur on.
> Add OS selector for Issue templates

- backends/smt2/smt2.cc
- backends/smt2/smtbmc.py
- backends/smt2/smtio.py
- tests/various/smtlib2_module-expected.smt2
The witness metadata was missing fine grained FFs completely and for coarse grained FFs where the output connection has multiple chunks it lacked the offset of the chunk within the SMT expression. This fixes both, the later by adding an "smtoffset" field to the metadata.
> smt2/smtbmc: Fix FF witness data for fine grained or multi chunk FFs

- backends/smt2/smtio.py
The "uninitialized" value is a _list_ of chunks that are part of the initial state for the witness trace.
> smtbmc: Fix witness handling for k-induction failures

- backends/smt2/smtbmc.py
I have added an optional flag to smtbmc that causes failed temporal induction counterexample traces to be checked for duplicate states and reported to the user, since loops in the counterexample mean that increasing the induction depth won't help prove a design's safety properties. Designs containing memory are skipped for now. I'm open to suggestions of any kind
> Temporal induction counterexample loop detection

- libs/fst/fstapi.cc
The *BSD stdio library seems to buffer data from the FST file leading to the seek position of the underlying file description being ahead of the stdio maintained seek position (that's what buffering is for after all). 
fstapi.cc uses gzdopen(dup(fileno())) to open and so zlib is given the underlying seek position instead of the seek position that the stdio using application is expecting with the result that gzread() starts reading from EOF instead of byte 17.
This PR moves the underlying seek position so that gzread() will read from the location that the application expects. This doesn't appear to affect stdio (which is still sharing that underlying seek position) because in one of the cases, the original FILE is promptly closed and in the other case the FST library seeks the original …
> Failure to read FST files on *BSD systems

- backends/smt2/smtbmc.py
This is not valid when the prefix of a trace already violates assertions. This can happen when the trace generating solver doesn't look for a minimal length counterexample.
> smtbmc: Do not assume skipped assertions when loading a witness trace

- techlibs/common/Makefile.inc
- techlibs/common/smtmap.v
Some builtin cells have an undefined (x) output even when all inputs are defined. This is not natively supported by the formal backends which will produce a fully defined value instead. This can lead to issues when combining different backends in a formal flow. To work around these, this adds a file containing verilog implementation of cells matching the fully defined behavior implemented by the smt2 backend.
> Add smtmap.v describing the smt2 backend's behavior for undef bits

- techlibs/common/simlib.v
The use of a procedural continuous assignment introduced in #3526 was unintended and is completely unnecessary for the actual change of that PR.
> simlib: Simplify recently changed $mux model

- Makefile
- libs/dlfcn-win32/dlfcn.cc
- libs/dlfcn-win32/dlfcn.h
- adds dlfcn library to enable compatibility of win32 code with posix
- for DLL to be able to access main executable, we need to export all symbols and make them visible to plugin
> Plugin support for mingw windows builds

- passes/sat/sat.cc
Otherwise the final values will not show up in gtkwave waveforms when looking at the generated traces.
Signed-off-by: Claire Xenia Wolf <claire@clairexen.net>
> Add extra time at the end of a sat VCD trace

- CHANGELOG
- frontends/ast/simplify.cc
- tests/simple/module_scope_func.v
I noticed this issue while investigating https://github.com/zachjs/sv2v/issues/223 / https://github.com/YosysHQ/yosys/issues/3520. This change is primarily intended to enable the standard-permitted use of module-scoped identifiers to refer to tasks and non-constant functions. As a side-effect, this also adds support for the non-standard use of module-scoped identifiers referring to constant functions, a feature that is supported in some other tools, including Iverilog.
> verilog: Support module-scoped task/function calls

- frontends/verilog/verilog_parser.y
IEEE Std 1800™-2017 7.4.2 specifies that [size] is the same as [0:size-1].
> Correct interpretation of SystemVerilog C-style array dimensions

- frontends/ast/ast.h
- frontends/ast/simplify.cc
- tests/svtypes/struct_array.sv
This also corrects the implementation of C type arrays within structs.
Fixes #3550
> Support for arrays with swapped ranges within structs

- frontends/ast/simplify.cc
- tests/various/cellarray_array_connections.ys
Otherwise the AST_CELL simplification uses the wrong celltype before the AST_CELLARRAY simplification has a chance to unroll it and change it to the $array... celltype.
> simplify: Do not recursively simplify AST_CELL within AST_CELLARRAY

- kernel/modtools.h
These variants of the functions don't have anything to specialize.
> remove template declaration that stops function from being used

- techlibs/gowin/cells_sim.v
This primitive is used in the GW1NS-4, GW1NS-4C, GW1NSR-4, GW1NSR-4C and GW1NSER-4C chips.
Signed-off-by: YRabbit <rabbit@yrabbit.cyou>
> gowin: add a new type of PLL - PLLVR

- passes/cmds/show.cc
This isn't actually representative of any problem nor actionable in any way - afaics it was just left in debugging rather than intended to warn of anything.
> show: Remove left-in debug log_warning

- passes/fsm/fsm_detect.cc
- passes/techmap/bmuxmap.cc
- tests/techmap/bmuxmap_pmux.ys
Verific likes to do optimizations when inferring FSMs, using the state value directly as select signal rather than the comparison to constants that `fsm_detect` expects the frontend to produce.
This adds a `-pmux` option to `bmuxmap` that transforms the `$bmux` into a `$pmux` with the one-hot selection signal connected to an `$eq` for each possible value of the original `S` signal. (The default case is `X`.)
This doesn't seem to fix the whole problem though, as now all the example FSMs I was testing on are rejected for being self-resetting.
Edit: Now I have added an option to `fsm_detect` to mark also self-resetting circuits for potential recoding. This may not preserve the self-resetting property of the FSM, which is why this is a rejection criteria, but it doesn't stop `fsm_extract` …
> add pmux option to bmuxmap for better fsm detection with verific

- backends/smt2/smt2.cc
The output width for the boolean value should not influence the operation width. The previous incorrect width extension would still produce correct results, but could produce invalid smt2 output for reduction operators when the output width was larger than the width of the vector to which the reduction was applied.
This fixes #3654
> smt2: Fix operation width computation for boolean producing cells

- backends/firrtl/firrtl.cc
This should fix #3648 where when calling `emit_elaborated_extmodules` it checks to see if a module is a black-box, however there was no validation that the cell type was actually known, and it just always assumed that we would get a valid instance, causing a segfault.
> backends/firrtl: Ensure `modInstance` is valid

- tests/xprop/run-test.sh
Needed in case make isn't compatible with GNU make.
> tests: in xprop tests, use MAKE variable if set

- techlibs/gatemate/cells_bb.v
- techlibs/gatemate/cells_sim.v
With these commits, some minor adjustments are made to the cells:
- 81b18307073f57bf3c049fa3259fbd705422911f fixes incompatibilities with reserved VHDL keywords (`IN`and `ON`) in LVDS buffers/ports
- 59c543bf584401be095ff0508054a4106acd3d48 adds parameters for the clock doubling feature and lock behavior of `CC_PLL` as described in [UG1001](https://www.colognechip.com/docs/ug1001-gatemate1-primitives-library-latest.pdf) from page 107
- 2432c01044fd19ed2aea059c741473755c97bc5a introduces the `CC_USR_RSTN` primitive as described in [UG1001](https://www.colognechip.com/docs/ug1001-gatemate1-primitives-library-latest.pdf) from page 105
> gatemate: cell library update

- passes/equiv/equiv_make.cc
- tests/various/equiv_make_make_assert.ys
This adds an -assert flag to equiv_make. When used, the pass generates $eqx and $assert cells to encode equivalence instead of $equiv, which means the equivalence check can be done with SymbiYosys. As these assertions are at the word level, they typically solve faster with SymbiYosys than using equiv_induct in yosys, at the cost of less helpful error messages.
I'm not certain on the name of the option as -assert is used in some other commands to mean that the command should produce an error if it fails which is different to its meaning here
You can also do something similar to this by using `equiv_make` followed by `equiv_miter -assert`, however the assertions resulting from this are all one bit wide (as they are derived from equiv cells which are always only 1 bit). In my experiments …
> equiv_make: Add -assert option

- passes/cmds/chformal.cc
- tests/various/chformal_coverenable.ys
- tests/various/chformal_coverprecond.ys
This inserts $cover cells to cover the enable signal (precondition/antecedent) for the selected formal cells. This allows you to check that your properties are not vacuous.
This will not cover preconditions that you write as part of the statement (e.g. this will cover `a` for `if (a) assert(b)`, but not for `assert(!a || b)`). ~~This should also work with preconditions arising from SVA in the verific front end (if the preconditions are converted to the enable signal as I believe they are?) but I do not have a copy to check~~ (it does not as sequential properties are more complex).
> chformal: Add -coverenable option

- frontends/ast/simplify.cc
- tests/svtypes/struct_array.sv
This brings the metadata for packed arrays in packed structs in line with the metadata for unpacked arrays, and correctly handles the case when the least of lsb and msb in an address range is non-zero.
> Handle range offsets in packed arrays within packed structs

- tests/verilog/typedef_const_shadow.sv
- tests/verilog/typedef_const_shadow.ys
This possible edge case came up while reviewing #3555. It is currently handled correctly, but there is no clear test coverage.
@daglem, FYI.
> Add test for typenames using constants shadowed later on

- frontends/ast/simplify.cc
- tests/svtypes/struct_sizebits.sv
For now, $bits, $left, $right, $low, $high, and $size are supported.
Fixes #3604
> Support for data and array queries on struct/union item expressions

- techlibs/fabulous/prims.v
This lets us do timing analysis on these in nextpnr (which always requires a clock port for clocked timing relationships).
> fabulous: Add CLK to BRAM interface primitives

- techlibs/xilinx/cells_sim.v
The DSP48E1 implementation checked the wrong attribute (i.e. CREG) to initialize the D input register. 
Fixes #3680
> Check DREG attribute

- passes/techmap/muxcover.cc
- tests/various/muxcover.ys
This turned out to be a surprisingly simple fix: if a decode mux would map to a buffer, don't set it up as a mux.
I'm expecting some tests will need to be modified as this changes how mux trees get mapped in designs, but hopefully nothing too severe.
Fixes #3591.
> muxcover: do not add decode muxes with x inputs

- techlibs/gatemate/cells_sim.v
- techlibs/gatemate/reg_map.v
- techlibs/gatemate/synth_gatemate.cc
We managed to implement register initialization through specific configuration of CPEs in the P&R bitstream. This commit enables both 0 and 1 initialization with `dfflegalize`.
> gatemate: Enable register initialization

- backends/smt2/smtbmc.py
In YoWASP CI scripts I run the binaries with `--help` to check that at least they can import everything they need and don't fail with a syntax error. Right now this doesn't work with `yosys-smtbmc`: https://github.com/YoWASP/yosys/blob/21140e14ab3eca5c539da7a66019a48cbbee137d/.github/workflows/package.yml#L45
> yosys-smtbmc: support -h/--help (and exit with code 0)

- techlibs/ice40/cells_sim.v
I tried to simulate an ice40 synthesized Verilog design with path delays in iverilog. After finding the correct flags, iverilog threw some error when reading `ice40/cells_sim.v`.
I did some digging on how path delays are defined in Verilog and came to the following conclusion.
Parallel connections do not allow matching different bit widths. A full connection has to be used instead.
This PR allows iverilog to parse the simulation library with hardware path delays enabled.
`The operator *> establishes a full connection between source and destination. The operator => establishes a parallel connection between source and destination.`
Full connection:
` In a full connection, every bit in the source shall connect to every bit in the destination. The module path source need not have the same …
> ice40: Fix path delay definitions

- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- tests/gen-tests-makefile.sh
- tests/svtypes/struct_array.sv
- tests/svtypes/struct_dynamic_range.sv
- tests/svtypes/struct_dynamic_range.ys
Currently, only constant indices are checked.
> Out of bounds checking for struct/union members

- frontends/verific/verific.cc
- tests/verific/enum_values.sv
- tests/verific/enum_values.ys
This uses the same constant parsing for enum_values and for attributes and extends it to handle signed values as those are used for enums that implicitly use the int type.
> verific: Fix enum_values support and signed attribute values

- techlibs/machxo2/Makefile.inc
- techlibs/machxo2/cells_map.v
- techlibs/machxo2/cells_sim.v
- techlibs/machxo2/synth_machxo2.cc
- tests/arch/machxo2/add_sub.ys
- tests/arch/machxo2/dffs.ys
- tests/arch/machxo2/fsm.ys
- tests/arch/machxo2/logic.ys
- tests/arch/machxo2/mux.ys
- tests/arch/machxo2/shifter.ys
- tests/arch/machxo2/tribuf.ys
Note this is minimal effort unification, enough to provide proper handling and simulation of these primitives, in future, they can fully share simulation models for these.
https://github.com/YosysHQ/yosys/pull/3705 is needed since cells_io.vh from ECP5 is being used.
> MachXO2 unification of TRELLIS primitives with ECP5

- frontends/verilog/verilog_lexer.l
- frontends/verilog/verilog_parser.y
- tests/verilog/void_func.ys
The difference between void functions and tasks is that always_comb's implicit sensitivity list behaves as if functions were inlined, but ignores signals read only in tasks. This only matters for event based simulation, and for synthesis we can treat a void function like a task.
> verilog: Support void functions

- kernel/yw.cc
The return value of the min(...) call is never used. Looks like some leftover from some previous implementation.
> Remove a statement without effect.

- frontends/ast/ast.cc
- tests/verilog/unbased_unsized_shift.sv
- tests/verilog/unbased_unsized_shift.ys
When the verilog frontend perfomed constant evaluation of unbased unsized constants in a context-determined expression it did not properly extend them by repeating the bit value. This only affected constant evaluation and not constants that made it through unchanged to RTLIL. The latter case was already covered by tests and working before.
This fixes the const-eval issue by checking the `is_unsized` flag in bitsAsConst and extending the value accordingly.
The newly added test also tests the already working non-const-eval case to highlight that both cases should behave the same.
> verilog: Fix const eval of unbased unsized constants

- frontends/ast/simplify.cc
- frontends/verilog/verilog_parser.y
- tests/svtypes/.gitignore
- tests/svtypes/struct_dynamic_range.sv
- tests/svtypes/struct_dynamic_range.ys
(* nowrshmsk *) on a struct / union variable now affects bit slice assignments to members of the struct / union.
> Handling of attributes for struct / union variables

- passes/cmds/rename.cc
This was renaming cells while iterating over them which would always cause an assertion failure. Apparently having to rename cells to make all witness signals public is rarely required, so this slipped through.
> rename: Fix renaming cells in -witness mode

- frontends/verific/verific.cc
- frontends/verific/verificsva.cc
This handles conditions on clocked concurrent assertions in unclocked procedural contexts.
> verific: Handle conditions when using sva_at_only in VerificClocking

- passes/sat/sim.cc
Writeback of simulation state into initial state was only working for `run()` and `run_cosim_fst()`.
This change moves the writeback into the `write_output_files()` function so that all simulation modes work with the writeback option.
> Fix sim writeback check for yw_cosim

- passes/cmds/plugin.cc
This PR updates the `plugin -i` command to better deal with some edge cases and inconsistencies with how it behaved.
The first update is that it now ensures that the plugin does not end with `.so` before trying to append it. Previously when running `plugin -i nya.so` it would try to look for `nya.so.so` in the `YOSYS_SHARE/plugins` directory, that has been fixed.
The second update is that it now checks for the `.py` extension even without Python support being enabled, and produces an error message accordingly.
The final update is that the filename path is now also run through `rewrite_path`, as is done with a large portion of the other file inputs in Yosys.
This PR does not address #2545 nor #3151 yet, I wanted to get some basic restructuring done first to make implementation a little …
> Updated the `plugin` command to better handle paths

- techlibs/gowin/arith_map.v
- tests/arch/gowin/compare.v
- tests/arch/gowin/compare.ys
The `X` output in the gowin `$alu` mapping didn't take the `BI` input into account, which caused `$eq`, `$ne`, `$le` and `$ge` comparisons to be broken: https://github.com/YosysHQ/apicula/issues/140.
> gowin: Fix X output of $alu techmap

- passes/techmap/libparse.cc
- tests/liberty/issue3498_bad.lib
[YOSYS] Issue #3498 - Fix Synopsys style unquoted Liberty style function body parsing with unittest
> [YOSYS] Issue #3498 - Fix Synopsys style unquoted Liberty style

- tests/verilog/block_labels.ys
genvar declaration cannot take an initial value when declared as a module_or_generate_item_declaration. Correct this test so that it doesn't fail unexpectedly if Yosys aligns with the standard.
> Standard compliance for tests/verilog/block_labels.ys

- backends/aiger/aiger.cc
This change fixes an issue where the input port ordering isn't maintained when writing an AIGER file if an output is directly connected to an input.
For example, if the inputs are `[a, b, c]` and `b` is connected to an output, then `b` gets moved to the end, and the inputs in the AIG are incorrectly ordered `[a, c, b]`.
Verilog file `/tmp/circuit.v`:
```verilog
module circuit(a, b, c, out);
input a;
input b;
input c;
wire a;
wire b;
wire c;
output [2:0] out;
wire [2:0] out;
assign out[0] = b;
assign out[1] = a & c;
endmodule
```
Command: `yosys -p "read_verilog -sv /tmp/circuit.v; aigmap; write_aiger -ascii -symbols /tmp/circuit.aig"`
The AIGER file shows the following snippet in the symbol table, showing that the inputs are being ordered `[a, c, b]`:
```
i0 a
i1 c
i2 b
```
The AIGER file …
> Add outputs before inputs to the sigmap in the AIGER backend.

- backends/smt2/smt2.cc
- passes/sat/sim.cc
Wires weren't being assigned an smtoffset value so when generating a yosys witness trace it would also use an offset of 0.
Not sure if this has any other effects, but it fixes the bug I was having.
@jix could you take a look at this?
> Assign wires an smtoffset

- techlibs/intel_alm/common/alm_sim.v
- tests/arch/intel_alm/counter.ys
The issue of whitebox carry chains having multiple fanout seems to have been fixed by berkeley-abc/abc#139, so we can safely revert 34a08750fa1a490be09411b07f64f4236eff234e to re-enable whitebox optimisation of carry chains.
> intel_alm: re-enable carry chains for ABC9

- passes/techmap/abc9_ops.cc
- tests/arch/xilinx/dsp_abc9.ys
As demonstrated in the included test:
```
module top(input signed [29:0] A, input signed [17:0] B, output signed [47:0] P);
wire [47:0] casc;
DSP48E1 #(.AREG(1)) u1(.A(A), .B(B), .PCOUT(casc));
DSP48E1 #(.AREG(1)) u2(.A(A), .B(B), .PCIN(casc), .P(P));
endmodule
```
`abc9_ops -prep_hier` would encounter `u2` first and create an "unmap" module that is used later to transform `u2` (and `u1`) from its derived (mapped) cell back into the parameterised cell. The problem is that the unmap module is not general: since `u2` does not have a `PCOUT` port, the unmap will not have one either. As a result, `u1` gets its `PCOUT` connection dropped.
Fix that here.
> abc9_ops -prep_hier to unmap entire module

- techlibs/intel_alm/common/bram_m10k.txt
- techlibs/intel_alm/common/bram_m10k_map.v
This is effectively a revert of #3124, which was a misunderstanding of how the M10K works - I had assumed that one port is a 20-bit write and one port is a 20-bit read, but in fact both ports have a 20-bit data input and a 20-bit data output, so this can function as a 8x40-bit SDP.
I've plumbed support into nextpnr as YosysHQ/nextpnr#1169, so let's enable it in Yosys as well.
> intel_alm: re-enable 8x40-bit M10K support

- backends/aiger/aiger.cc
- backends/btor/btor.cc
- backends/smt2/smt2.cc
- passes/cmds/rename.cc
- passes/opt/opt_clean.cc
- passes/sat/clk2fflogic.cc
- passes/sat/sim.cc
See e36c71b5b743e578f3a965cda9926a426cd5c295 for a detailed description.
> Use clk2fflogic attr on cells to track original FF names in witnesses and fix a sim initialization bug.

- passes/cmds/show.cc
This updates the show command to use similar logic for the `-color <color> <selection>` and `-colorattr <attr>` options. Both will now color the cells, wires, and connection arrows for the designated elements.
Also adds a `-viewer none` option to disable opening the viewer (this is already possible indirectly because specifying `-format <foo>` disables the viewer).
Also fixes a bug where the `:e` and `:w` compass port options would be added twice on some nodes (graphviz doesn't mind the redundancy so this didn't change anything functionally).
> show -colorattr: extend colors to arrows when wires have attribute

- misc/py_wrap_generator.py
Makes the below show up in the binding.
.def<const char * (IdString::*)(void)>("c_str", &IdString::c_str)
.def<boost::python::list (SigSpec::*)(void)>("chunks", &SigSpec::chunks)
.def<boost::python::list (SigSpec::*)(void)>("bits", &SigSpec::bits)
.def<SigBit (SigSpec::*)(int, const SigBit* )>("at", &SigSpec::at)
.def<SigSpec (Cell::*)(const IdString* )>("getPort", &Cell::getPort)
.def<boost::python::dict (Cell::*)(void)>("connections", &Cell::connections)
.def<Const (Cell::*)(const IdString* )>("getParam", &Cell::getParam)
.def<boost::python::list (Module::*)(void)>("connections", &Module::connections)
def<const char * (*)(const SigSpec* )>("log_signal", YOSYS_PYTHON::log_signal);
def<const char * (*)(const SigSpec* , bool)>("log_signal", YOSYS_PYTHON::log_signal);
def<const char * …
> Fix the python generator for a bunch of const cases 

- docs/source/CHAPTER_CellLib.rst
Minor: "input" for `\RD_DATA` where "output" was wanted.
> docs: RD_DATA is an output, not input

- passes/cmds/show.cc
This is mainly a problem for VHDL parameters assigned `(others=>0)`.
Reduced example to reproduce: `yosys -p show top.il`
```top.il
attribute \top 1
module \top
wire width 9 input 0 \a
wire width 9 input 1 \b
wire width 18 output 2 \c
cell \demo<=>cell \orig
parameter \A_WIDTH 9
parameter \B_WIDTH 9
parameter \Y_WIDTH 18
connect \A \a
connect \B \b
connect \Y \c
end
end
```
Added a fix to truncate module names that are too long. (To 256 characters by default, get up to the max of 16k allowed by the dot format with `-long`.)
> show: escape angle brackets

- passes/proc/proc_prune.cc
An `std::vector<T>::reverse_iterator` stores the `std::vector<T>::iterator` which points to the (forwards-ordered) *following* item.  Thus while `vec.rbegin()` dereferences to the final item of `vec`, the iterator it wraps (`vec.rbegin().base()`) is equal to `vec.end()`.
In the remove case here, we advance `it` (backwards), erasing the item we just advanced past by grabbing its (pre-increment) base forward-iterator and subtracting 1.
The iterator maths here is obviously all OK, but the forward-iterator that `it` wraps post-increment actually points to the item we just removed.  That iterator was invalidated by the `erase()` call.
That this works anyway is (AFAICT) some combination of luck and/or promises that aren't part of the C++ spec, but MSVC's debug iterator support picks this up. …
> proc_prune: avoid using invalidated iterator

- frontends/verific/verific.cc
@mmicko is there any way to also import source location for `$meminit` cells? (That one seems more complex and is probably less important, but would be nice to have.)
> verific: import src attribute on $memrd/$memwr cells

- passes/cmds/check.cc
- tests/various/constant_drive_conflict.ys
Apparently we didn't check for conflicts with constant driver at all.
This adds checks for 0,1 and x drivers conflicting with other drivers. It doesn't check for z drivers as the already existing checks also didn't count inout ports as drivers. I'm not certain whether there are any cases where we do want to allow conflicts with x drivers, though. (@clairexen any idea?)
> check: Also check for conflicts with constant drivers

- backends/smt2/smtbmc.py
As cover mode by default stops looking for further traces when an assertion fails, it should respect --keep-going.
> smtbmc: Make cover mode respect --keep-going

- backends/cxxrtl/cxxrtl.h
- backends/cxxrtl/cxxrtl_backend.cc
Does what it says on the tin.
I'm not sure if just subtracting one in the negative-result non-zero-remainder case is the "most correct" way of representing this operation, but it produces the result!
> cxxrtl: add `$divfloor`.

- passes/opt/opt_share.cc
- tests/opt/bug3848.ys
Distinguish between the A, B input ports of `$_ANDNOT_`, `$_ORNOT_` gates when considering those for sharing. Unlike the input ports of the other supported single-bit gates, those are not interchangeable.
Fixes #3848.
> opt_share: Fix input confusion with ANDNOT, ORNOT gates

- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- kernel/log.cc
- kernel/log.h
This is supposed to untangle the simplify code a bit by removing three of its arguments (in_lvalue/in_param/at_zero), and making few other changes.
I expect the at_zero removal to be less objectionable than the in_param/in_lvalue removal, since the latter (with the way it's being replaced) requires the code to be sprinkled with calls to `fixup_hierarchy_flags` and `set_attribute` (new methods). That may not be as bad if we (1) don't require the in_param/in_lvalue values of the old code to be perfectly reproduced (which the change here does reproduce, at least as exercised by `make test`); (2) move to a coding style in the simplify code that doesn't rely on explicitly modifying the children list of an existing node as much. See the commits and let me know what you think.
This should be …
> Touch on ast/simplify

- passes/techmap/abc.cc
- passes/techmap/abc9_exe.cc
This is mostly important for YoWASP builds, since those do not have a way to build with external ABC (I prototyped it but for some reason ABC always segfaults when built as an independent Wasm binary...)
> abc, abc9_exe: respect `-q` when built with linked ABC

- passes/techmap/abc.cc
- passes/techmap/abc9_exe.cc
It turns out that https://github.com/YosysHQ/yosys/pull/3859 didn't actually build on WASI (or musl). My bad for not testing it more thoroughly; I forgot that `stdout`/`stderr` can be `const`.
C does not guarantee that stdout/stderr can be reassigned. Most platforms do make them assignable, however musl and WASI that is based on musl do not. WASI does not have `dup2()`; instead it has its own non-portable version of it that can only assign to previously allocated fds.
Update the stream redirection code so that it does the right thing on WASI and other platforms.
> abc, abc9_exe: fix build on WASI (and others with `const* stdout`).

- kernel/rtlil.cc
- kernel/rtlil.h
This PR solves an issue in program teardown which we hit on GCC 12 (Debian 12) and which was first reported in #3525.
The original issue is that accessing a member of an already destructed class is undefined behaviour, so the `destruct_guard.ok` accesses get ejected by the compiler as "always true" as is a valid optimisation per the language lifetime model. The patch is technically invoking UB too (because calling any functions on the destroyed IdString instance is UB), but results in correct behaviour for now rather than yosys segfaulting as it exits.
Fixes #3525
> Fix: RTLIL teardown segfault

- tests/techmap/aigmap.ys
For the test to pass this depends on PRs #3838 (for `$_NMUX_`) and #3840 (for `$lt` and friends).
From the commit:
> Extend the aigmap.ys test with SAT-based comparison of the original cells and their AIG implementations.
>
> This tests both the usual cells and the single-bit Yosys gates.
As I have found out after having written this, the lowercase cells can also be tested with `test_cell -aigmap`, though that does not seem to check that the cells are actually mapped onto an and-inverter network (and not kept as they are).
> tests: Extend aigmap.ys with SAT comparison

- passes/opt/opt_expr.cc
- tests/opt/bug3867.ys
If the `$ge` cell we are replacing has wide output port, the upper bits on the port should be driven to zero. That's not what a `$not` cell with a single-bit input does. Instead opt for a `$logic_not` cell, which does zero-pad its output.
Fixes #3867.
> opt_expr: Fix 'signed X>=0' replacement for wide output ports

- passes/opt/wreduce.cc
Group the reconnections, so that instead of producing
connect $auto$wreduce.cc:455:run$24 [0] 1'0
connect $auto$wreduce.cc:455:run$23 [31] 1'0
connect $auto$wreduce.cc:455:run$23 [30] 1'0
... (40 more lines)
we produce
connect $auto$wreduce.cc:461:run$23 [31:11] 21'000000000000000000000
connect $auto$wreduce.cc:461:run$24 [31:10] 22'0000000000000000000000
.
> wreduce: Group reconnections

- passes/proc/proc_clean.cc
- tests/proc/clean_undef_case.ys
This is a bug report with a suggested fix.
Consider the following RTLIL:
```rtlil
module \m
wire width 1 \w
process $p
switch 2'10
case 2'-1
assign \w 1'0
case 2'1-
assign \w 1'1
end
end
end
```
Invoking `proc` on this will first run `proc_clean`. `proc_clean` does not know how to handle `Sa`, and for fully-const switch operands (`2'10` here) that don't `==` fully-const case operands (`2'-1` and `2'1-` here), the case operand will be removed:
https://github.com/YosysHQ/yosys/blob/2829cd9caa5729b3b7e2393d3428e265cd038ea6/passes/proc/proc_clean.cc#L44-L51
`SigSpec::operator ==` doesn't do "don't care" matching, so none are considered equal. Accordingly, post-`proc_clean` we get:
```rtlil
autoidx 1
module \m
wire \w
process $p
switch 2'10
end
end
end
```
The only passes invoked by `proc` …
> proc_clean doesn't handle State::Sa, will remove switches that use them

- backends/smt2/witness.py
- backends/smt2/ywio.py
Intended for use with SCY to combine sequential cover traces.
Arbitrary number of inputs, will load all and attempt to join them.  Each trace will be replayed one after the other, in the same order as the files are provided.
Mismatch in init_only fields seems to work fine, with values in subsequent traces being assigned in the initial only if they weren't previously defined.
Uncertain if a mismatch in non init_only fields will cause problems.
Fixes WitnessSig.__eq__().
Adds helper functions to WitnessValues and ReadWitness classes.
> yosys-witness concat yw trace files

- libs/fst/fstapi.cc
Likely related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=323#c225
Thanks to @jix for digging this up
> Fix i386 FP excess-precision issue in fstapi (Fixes: #3898)

- libs/fst/fstapi.cc
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1025307
> Fix fstGetUint32 crash on mips64el due to misaligned access

- passes/techmap/abc.cc
A suggestion inspired by #3893
> abc: Warn about replacing undef bits

- frontends/ast/genrtlil.cc
Apply the local substitutions stemming from process context when parsing out format arguments to `$display` or other statements.
This is to fix #3917.
> ast: Substitute rvalues when parsing out print arguments

- passes/techmap/abc.cc
ABC's read_lib command has a dont_use
cell list that is configurable by the user.
This PR exposes that option to Yosys.
See
https://github.com/berkeley-abc/abc/blob/5405d4787a86615de76afccf1356676fb5c56c1c/src/map/scl/scl.c#L285 for documentation on this option.
> abc: Exposes dont_use flag in ABC

- kernel/mem.cc
Fix mistaking the read-port and write-port indices for each other when we are adding the partial transparency emulation to be able to merge two write ports.
> mem: Fix index confusion in write port merging

- kernel/fmt.cc
> fmt: Fix C++ string assertion when buf is empty

- frontends/verific/verific.cc
This makes src attribute completely same as in Yosys verilog frontend and gives full information about source position.
Location for Yosys verilog frontent is created here :
https://github.com/YosysHQ/yosys/blob/master/frontends/ast/ast.cc#L985
> Set src attribute for verific with full info

- CHANGELOG
- README.md
- frontends/verilog/verilog_parser.y
- tests/verilog/asgn_expr.sv
- tests/verilog/asgn_expr.ys
- tests/verilog/asgn_expr_not_proc_1.ys
- tests/verilog/asgn_expr_not_proc_2.ys
- tests/verilog/asgn_expr_not_proc_3.ys
- tests/verilog/asgn_expr_not_proc_4.ys
- tests/verilog/asgn_expr_not_proc_5.ys
- tests/verilog/asgn_expr_not_sv_1.ys
- tests/verilog/asgn_expr_not_sv_2.ys
- tests/verilog/asgn_expr_not_sv_3.ys
- tests/verilog/asgn_expr_not_sv_4.ys
- tests/verilog/task_attr.ys
- Add support for assignments within expressions, e.g., `x[y++] = z;` or `x = (y *= 2) - 1;`. The logic is handled entirely within the parser by injecting statements into the current procedural block.
- Add support for pre-increment/decrement statements, which are behaviorally equivalent to post-increment/decrement statements.
- Fix non-standard attribute position used for post-increment/decrement statements.
I am not particularly attached to this implementation. I had initially anticipated adding a new AST node type and elaborating them in `simplify.cc`, but sticking the statements into the current procedure ended up working quite naturally.
Closes #3870.
> sv: support assignments within expressions

- tests/verific/memory_semantics.ys
This test requires both #3927, #3928 to pass. It has the kind of per-byte mixed transparency scenario by which we found #3928. Suggestions are welcome.
Cc @nakengelhardt
> verific: Add test of accurate semantics in memory inference

- passes/cmds/autoname.cc
This is accomplished by only constucting IdString objects from plain strings that have a higher score.
Before:
After:
> Speed up the autoname pass by 3x. 

- passes/cmds/show.cc
The "BUF" display is confusing as it is easy to misinterpret as a `$_BUF_` cell.
> show: use dot for wire aliases instead of BUF

- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
Split off from PR #3722, ~~but it's still on top of the other PR's commits to save on rebase work. So, only the last three commits, starting with "[ast/simplify: Make tweaks in advance of big in_lvalue/in_param change](https://github.com/YosysHQ/yosys/commit/31b7b2e41c53ab59266e69f613f3b948565299dc)" should be the subject of this PR.~~
As is, the change might be objectionable since it requires the code to be sprinkled with calls to fixup_hierarchy_flags and set_attribute (new methods). That may not be as bad if we (1) don't require the in_param/in_lvalue values of the old code to be perfectly reproduced (which the change here does reproduce, at least as exercised by make test); (2) move to a coding style in the simplify code that doesn't rely on explicitly modifying the children list of …
> ast/simplify: Remove in_lvalue/in_param simplify() parameters

- frontends/ast/simplify.cc
Compiling on GCC hid this bug as it optimized the nullptr call away as undefined behavior, but running the SBY tests with a clang build hits this error.
> simplify: Avoid calling fixup_hierarchy_flags on nullptr

- kernel/rtlil.cc
- kernel/rtlil.h
- passes/techmap/booth.cc
- tests/techmap/booth.ys
Following up to #3924, this PR will to some degree clean up the code of the Booth pass.
> `booth` cleanup

- kernel/rtlil.cc
This replaces part of https://github.com/YosysHQ/yosys/pull/3940. The main source of the speedup is from implementing the extraction of the data from all but the last n % 8 bits as a fixed trip-count loop, which the compiler can unroll. 
Benchmark measurements for a synthesis run of a representative circuit:
Before:
After:
> Speed up RTLIL::Const::decode_string by 1.7x.

- passes/sat/sim.cc
This adds the -noinitstate option which is required to simulate counterexamples to induction with yw-cosim. Also add handling for $initstate cells for non-co-simulation.
> sim: Add -noinitstate option and handle non-cosim initstate

- passes/techmap/simplemap.cc
- passes/techmap/techmap.cc
This is accomplished by directly inserting the cell source attribute in the new object's 'attributes' map instead of creating a new attribute pool and then copying that. Based on a suggestion by Martin Poviser in a comment on https://github.com/YosysHQ/yosys/pull/3959
Topdown view before:
Topdown view after:
> Speed up simplemap_mux by 9.6x.

- kernel/yosys.cc
- kernel/yosys.h
The speedup is accomplished by avoiding a heap allocation in the common case where the final string length is less than 128.  Another smaller improvement is from inlining stringf/vstringf.
Benchmark timings from synthesis of a representative circuit:
Bottom-Up view before:
Bottom-Up view After:
> Speed up stringf/vstringf by 1.8x

- techlibs/gowin/cells_sim.v
A certain past wolfenby wrote a bunch of sequential paths in `specify` blocks to describe asynchronous sets/resets within `abc9_box` cells, which require combinational paths. This horrifically broke ABC9 flows, and I apologise.
While I was here, I took the liberty of turning some fully-synchronous cells into `abc9_flop` rather than `abc9_box`, which will likely help sequential synthesis (if somebody asks me nicely to implement that).
cc @pepijndevos @yrabbit
> gowin: fix abc9 attributes and specify blocks

- passes/techmap/booth.cc
- tests/techmap/booth.ys
In commit fedd12261 ("booth: Move away from explicit `Wire` pointers") a bug was introduced when checking for vacant slots in arrays holding some intermediate results. Non-wire SigBit values were taken to imply a vacant slot, but actually a constant one can make its way into those results, if the multiplier cell configuration is just right. Fix the vacancy check to address the bug.
> booth: Fix vacancy check when summing down result

- frontends/ast/simplify.cc
> ast/simplify: Remove unused in_param code

- backends/verilog/verilog_backend.cc
The Verilog grammar does not allow an empty case.  Most synthesis tools are quite permissive about this, but Quartus is not.  This causes problems for amaranth with Quartus (see amaranth-lang/amaranth#931).
> write_verilog: avoid emitting empty cases.

- kernel/celltypes.h
- kernel/hashlib.h
- kernel/rtlil.h
- passes/opt/opt_merge.cc
- passes/sat/recover_names.cc
The main speedup comes from switching away from using SHA1 hash to using `std::hash<std::string>` for fingerprinting cells. There is no need to use an expensive cryptographic hash for fingerprinting in this context.
Flamegraph of benchmark timings from synthesis of a representative circuit:
Before:
After:
> Speed up OptMergePass by 1.75x.

- passes/pmgen/Makefile.inc
- passes/pmgen/README.md
- passes/pmgen/peepopt.cc
- passes/pmgen/peepopt_shiftmul.pmg
- passes/pmgen/peepopt_shiftmul_left.pmg
- passes/pmgen/peepopt_shiftmul_right.pmg
This extends the shiftmul matcher in two useful ways:
* It deals with cases where the shift amount is zero-padded from below because `opt_expr` ran before and applied `opt.opt_expr.mul_low_zeros`.
* It can deal with left shifts implementing a demuxer (through the addition of a mirrored matcher).
Related to #3833.
> Extend the `peepopt` shiftmul matcher

- passes/cmds/scc.cc
I was getting diverging SCC reports for the exact same input depending on whether I ran on ppc64 or ppc64le.
With this change the result should be the same regardless of the operating environment.
> scc: Use hashlib instead of STL for deterministic behaviour

- tests/arch/quicklogic/dffs.ys
Fix name confusion which was making the test look into the vendor's cell blackbox rather than into the synthesis results.
> quicklogic: Fix pp3 `dffs` test

- backends/cxxrtl/cxxrtl.h
- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/cxxrtl_capi.cc
- backends/cxxrtl/cxxrtl_capi.h
Among other things this allows retrieving source locations for wires in the simulation, e.g.:
```c
void print_location_cb(void *, const char *name, struct cxxrtl_object *object, size_t parts) {
printf("%s:\n", name);
cxxrtl_attr_set attrs = object->attrs;
if (cxxrtl_attr_type(attrs, "src") == CXXRTL_ATTR_STRING) {
const char *src = cxxrtl_attr_get_string(attrs, "src");
while (src) {
char buf[256] = {0};
const char *next = strchr(src, '|');
if (!next) {
printf("\t%s\n", src);
src = NULL;
} else {
strncpy(buf, src, next - src);
printf("\t%s\n", buf);
src = next + 1;
}
}
} else {
printf("(missing!)\n");
}
}
int main() {
cxxrtl_handle top = cxxrtl_create_at(cxxrtl_design_create(), "toplevel");
cxxrtl_reset(top);
printf("Source location information for this simulation:\n");
cxxrtl_enum(top, …
```
> cxxrtl: export wire attributes through the C API

- techlibs/ecp5/synth_ecp5.cc
- techlibs/ice40/synth_ice40.cc
- tests/arch/ecp5/add_sub.ys
- tests/arch/ecp5/counter.ys
- tests/arch/ice40/add_sub.ys
- tests/arch/ice40/mux.ys
It's been [four years](https://github.com/YosysHQ/yosys/pull/1544) since ABC9 was last proposed to be used by default. The arguments made back then still apply: results are superior compared to the default ABC flow, and we seem to have gotten most of the bugs fixed or worked around.
So, I'm once again asking for ~~your financial support~~ ABC9 to be made the default on iCE40 and ECP5. I think using these two architectures as a baseline for wide adoption should quickly expose any other bugs in ABC9 that can then be fixed, given how popular they are over the others.
> ice40, ecp5: enable ABC9 by default

- passes/pmgen/Makefile.inc
- passes/pmgen/peepopt.cc
- passes/pmgen/peepopt_shiftadd.pmg
- tests/simple/partsel.v
This has been lightly discussed in #3873.
Together with #3873 and #3880 it should fix #3833.
Another approach to fix #3833 using attributes is shown in #3875 and #3877.
This transformation has been tested a bit but not completely and never on larger modules. Additionally the benefits to Quality-of-Results are as of now non-obvious and lack empirical evidence (though since #3880 does show benefits and this should allow more of these transformations, QoR should improve).
ToDo:
> peepopt: Add `shiftadd` pattern

- CHANGELOG
- kernel/driver.cc
Pass all argument after the tcl script name to tcl execution in argv, argument number in argc and tcl script name in argv0 like in tclsh or wish :
https://wiki.tcl-lang.org/page/argv
> cli(tcl): add ability to pass argument to tcl script from cli

- techlibs/lattice/synth_lattice.cc
These two changes can shed more than 15 % of `TRELLIS_COMB` usage on a representative design with a picorv32 core and some user peripherals. See the commits for details.
> MachXO3 QoR improvements

- techlibs/ecp5/synth_ecp5.cc
- techlibs/gowin/synth_gowin.cc
- techlibs/ice40/synth_ice40.cc
- tests/arch/ecp5/add_sub.ys
- tests/arch/ecp5/counter.ys
- tests/arch/gowin/counter.ys
- tests/arch/gowin/init.ys
- tests/arch/gowin/mux.ys
- tests/arch/ice40/add_sub.ys
- tests/arch/ice40/mux.ys
#4019 again, but the Gowin team also wanted ABC9 enabled for their flow.
> ice40, ecp5, gowin: enable ABC9 by default

- Makefile
I'm doing this in YoWASP already, but this change should make compilation easier for anyone else attempting.
> Update WASI compilation flags to include required libraries

- techlibs/gowin/synth_gowin.cc
I forgot to change the flag name when copy-pasting the argument option, which leads to the unintended effect that specifying `-abc9` turns *off* ABC9 instead of having no effect. Oops.
> gowin: fix typo

- techlibs/ice40/synth_ice40.cc
I really should have read over my ABC9 patch with a fresh set of eyes, huh.
> ice40: fix -noabc9

- frontends/verific/verific.cc
`port->GetNet()` can return nullptr on blackbox modules
> verific: don't try to import attributes from nullptr

- kernel/fmt.cc
> fmt: Handle free-standing time arguments

- kernel/rtlil.h
- passes/techmap/booth.cc
- techlibs/lattice/synth_lattice.cc
~~Implement Wallace tree summation as an option in `booth`. This significantly improves the propagation delay of the multiplier, at least for some dimensions of inputs and outputs. So far the Wallace tree option is only supported with the signed multiplier architecture, and is implemented in the most crude way possible. There's likely space for improvement.~~ Redo the selection of architectures: Have one classic Booth architecture for both signed and unsigned multiplication. Move what was formerly the signed architecture under a new `-lowpower` option. Also improve the balance of the Wallace tree generated.
With these changes, the Booth multiplier no longer has worse timing on MachXO3 than the baseline multiplier emitted by `maccmap`. Since Booth can use a lot less area, opt for it as the …
> Change `booth` architecture for improved delay, similar signed/unsigned results

- .gitignore
These files are generated in `-gsplit-dwarf` builds, which provide faster linking.
> Add *.dwo files to .gitignore

- .github/workflows/wasi.yml
- techlibs/quicklogic/Makefile.inc
Added script from https://github.com/YosysHQ/yosys/pull/4045, was not able to reproduce a bug but it more looks like order of execution issue in passes/pmgen directory. Let see if this CI is happy.
> Add WASI CI build

- passes/pmgen/peepopt_shiftmul_right.pmg
- tests/various/peepopt.ys
The previous version could easily generate a large amount of padding when the constant factor was significantly larger than the width of the shift data input. This could lead to huge amounts of logic being generated before then being optimized away at a huge performance and memory cost.
Additionally and more critically, when the input width was not a multiple of the constant factor, the input data was padded with 'x bits to such a multiple before interspersing the 'x padding needed to align the selectable windows to power-of-two offsets.
Such a final padding would not be correct for shifts besides $shiftx, and the previous version did attempt to remove that final padding at the end so that the native zero/sign/x-extension behavior of the shift cell would be used, but since the last …
> peepopt: Fix padding for the peepopt_shiftmul_right pattern

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
> cxxrtl: Remove redundant divmod

- examples/python-api/pass.py
When a plugin is being loaded from Python source, the binding will be available under
import libyosys
That is unfortunately different from how a self-standing Python program would import the Yosys interface, which is
from pyosys import libyosys
Until that is made consistent, at least fix the example to have it working as is.
> python: Fix import in plugin example

- frontends/ast/ast.cc
Explicit conversion of AST_TO_SIGNED, AST_TO_UNSIGNED, and AST_CAST_SIZE makes it possible to reason about simplified array expressions.
> Uncloak array expressions generated by read_verilog -dump_vlog2

- frontends/ast/genrtlil.cc
The $shift and $shiftx cells perform a left logical shift if the second operand is negative. This change passes the sign of the second operand of AST_SHIFT and AST_SHIFTX into $shift and $shiftx cells, respectively.
> Respect the sign of the right operand of AST_SHIFT and AST_SHIFTX

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
I tried to fix `ctlz` and give it the usual semantics, then adjusted the `divisor_shift` calculation in `udivmod` appropriately.
> cxxrtl: Fix `ctlz`, `udivmod`

- backends/cxxrtl/cxxrtl_backend.cc
This pull request addresses an issue where an incorrect include file name is generated for the `.cc` file when using the `-header` flag and the filename includes folders.
For example:
```verilog
// top.v
module top ();
endmodule
```
```bash
$ mkdir -p build && yosys -p "read_verilog top.v; write_cxxrtl -header build/top.cc"
```
The following files are created: `build/top.h` and `build/top.cc`. The `top.cc` has the following include directive to include the `top.h`:
```c++
#include "build/top.h"
```
It should instead be:
```c++
#include "top.h"
```
> cxxrtl: Use the base name of the interface file for the include directive

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- tests/cxxrtl/test_value.cc
> cxxrtl: Mask `bmux` result appropriately

- passes/equiv/equiv_simple.cc
Fix how `equiv_simple` walks over signals back in time and extend the flip-flop support to all kinds of purely synchronous flip-flops.
> Fixes to `equiv_simple`

- techlibs/gowin/synth_gowin.cc
This should work now thanks to @yrabbit  https://github.com/YosysHQ/apicula/pull/202
> Enable bram for Gowin

- techlibs/lattice/brams_8kc.txt
- techlibs/lattice/brams_map_8kc.v
This appears to be the right wiring of `DP8KC` per the MachXO3 simulation model I have at hand.
Some points:
* I don't know if this applies to all `DP8KC`primitives across the Lattice families.
* Reading into the simulation model, it seems one cannot map a memory with write port of width 18 and read port of width 2 onto `DP8KC`. This is because `DIB1`, which would be used for the 10th data bit input, gets ignored. If this is true, or even if it's just a bug of the simulation model, we may want to disable this configuration in libmap inference of `$__PDPW8KC_`. **UPDATE:** done in the second commit
> lattice: Fix mapping onto DP8KC for data width 1 or 2

- backends/cxxrtl/runtime/cxxrtl/cxxrtl_time.h
While the VCD format separates the timescale and the timestep (likely to allow representing the timestep with a small integer type), time in CXXRTL is represented using a uniform 96-bit number, which allows for a ±100 year range at femtosecond resolution.
The implementation uses `value<96>`, which provides fast arithmetic and comparison operations, as well as conversion to/from a more common representation of integer seconds plus femtoseconds.
This isn't yet used anywhere, but will be used in the upcoming record/replay debugging feature.
> cxxrtl: add a representation of simulation timestamps

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
The commit observer is a structure containing a callback that is invoked whenever the `commit()` method changes a wire or a memory. This allows code external to the compiled netlist to react to changes in the design state in a very efficient way. One example of how this feature can be used is an efficient implementation of record/replay.
Note that the VCD writer does not benefit from this feature because it must be able to react to changes in any debug items and not just those that contain design state.
<hr>
There is a performance penalty associating with translating wire/memory identity (`base` argument) to some sort of persistent identifier in an upper layer using this feature. The penalty, specific to this translation, can be as high as 25% compared to an uninstrumented design. At a …
> cxxrtl: add a way to observe state changes during the commit step

- techlibs/quicklogic/ql_bram_merge.cc
- techlibs/quicklogic/ql_dsp_io_regs.cc
- techlibs/quicklogic/ql_dsp_simd.cc
Windows build is crashing on start, since registering of passes crashed. IdString can not be used as variable default values since order of initialization is not guaranteed, and MinGW compiler always doing it in different order than Clang.
Using `static` is not strictly necessary but makes sure to do this only once per run.
Have tried to make this with less changes as possible, but guess `m_` prefix for variables should be removed since they are local.
FYI doing init as part of constructor initialization does not help, since that is actually same moment of execution as previous code.
> Fix Windows build by forcing initialization order, fixes #4068

- backends/verilog/verilog_backend.cc
A minor thing I stumbled on while reviewing #4090
This change only matters for processes that weren't processed by `proc_rmdead` for which follow-up cases after a default case are treated differently in Verilog and RTLIL semantics.
> write_verilog: Handle edge case with non-pruned processes

- backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
This PR adds a reader/writer implementation for a file format optimized for fast, single-pass storage and retrieval of design state changes, as well as a recorder/replayer that integrate with the eval and commit simulation steps to create replay logs and reproduce them later.
This feature makes it possible to run a simulation once, recording the stimulus as well as changes to the registers, and navigate to a past time point in the simulation later without rerunning it. Both the changes in inputs (stimulus) and changes in state are saved so that navigation does not require calling `eval()` or `commit()`; only a series of memory copy operations.
On a representative example of a SoC netlist, saving the replay log while simulating it takes 150% of the time it would take to simulate the same …
> cxxrtl: implement a generic record/replay interface

- backends/verilog/verilog_backend.cc
This results in a very significant improvement in readability when emitting Verilog from Amaranth code, and a slight improvement when emitting Verilog from Yosys-parsed Verilog code. Not sure about Verific.
> write_verilog: emit `casez` as `if/elif/else` whenever possible

- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/simplify.cc
- tests/various/dynamic_part_select.ys
- tests/various/dynamic_part_select/forloop_select_nowrshmsk.v
- tests/verilog/dynamic_range_lhs.sh
- tests/verilog/dynamic_range_lhs.v
Generation of minimal AST_CASE for variable slices on the form dst[i*stride +: width] = src.
Corrections of corner cases, now correctly tested by tests/verilog/dynamic_range_lhs.v
> Optimization of nowrshmsk

- frontends/ast/simplify.cc
- tests/simple/sign_part_assign.v
Simplify and correct AST for array slice assignment
Corrects sign extension of the right hand side, and hopefully
makes the code simpler to understand.
Fixes #4064
> Simplify and correct array slice assignment

- backends/cxxrtl/cxxrtl_backend.cc
- backends/verilog/verilog_backend.cc
- docs/source/CHAPTER_CellLib.rst
- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- frontends/verilog/verilog_frontend.cc
- passes/sat/sim.cc
This cherry picks the completed parts from #3963, cherry picks commits by @whitequark correcting the Verilog backend output of the `$print` cell and implementing initial `$print` cells in CXXRTL, and adds the `-nodisplay` option to `read_verilog` to optionally suppress elaboration output from `$display` et al.
Fixes https://github.com/chipsalliance/sv-tests/issues/5082
> Pass `$display` et al. in `initial` blocks on to `sim`

- passes/sat/sim.cc
Restores `sim` output from `initial $display`, which was inadvertedly removed in #4129.
> Restore sim output from initial $display

- frontends/ast/simplify.cc
- passes/memory/memory_libmap.cc
- passes/sat/recover_names.cc
Just what compiler found. Uses proper types like %zu for size_t and %PRIx64 for uint64_t in hexadecimal.
> Fix printf formats

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
- kernel/fmt.cc
- kernel/fmt.h
- tests/fmt/always_full_tb.cc
See individual commits for detailed explanation and rationale. Although there are a few changes that are strictly speaking breaking, I don't think any are controversial. I tried to keep backwards compatibility where it made sense, e.g. `-print-output` is preserved.
> CXXRTL: Allow capturing `$print` cell output

- techlibs/gowin/brams_map.v
The primitives used have been corrected and changes have been made to the set of signals. It has been empirically established that it is necessary to set the OCEx signal to 1 when using READ_MODE=0.
Addresses issue https://github.com/YosysHQ/yosys/issues/4098
Thanks Saviour Owolabi for the help.
> gowin: fix the BRAM mapping.

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- tests/fmt/always_full_tb.cc
This is mostly useful for collecting coverage for the future `$check` cell, where, depending on the flavor, formatting a message may not be wanted even for a failed assertion.
> cxxrtl: always lazily format print messages

- passes/cmds/stat.cc
> Fix typo in stat help

- backends/verilog/verilog_backend.cc
- tests/verilog/roundtrip_proc.ys
It is embarrassing to have written it, but also, three independent reviewers missed it too :D
See https://github.com/amaranth-lang/amaranth/issues/1049.
Issue introduced in #4090
> write_verilog: don't emit code with dangling else related to wrong condition

- backends/cxxrtl/cxxrtl_backend.cc
> cxxrtl: fix typo in codegen for async set/clear

- techlibs/gowin/brams.txt
- techlibs/gowin/brams_map.v
When inferring we allow writing to all bytes for now.
In the Gowin documentation for BSRAM 2019, the byte_enable port and its operation and use in generating IP with pictures were described in detail, two years later in the same document the byte_enable port was listed as supported only for the NS-2 family, and finally in the 2023 edition, all references to both the NS-2 family and the byte_enable port were removed.
I don’t know, maybe it turned out that they forgot the transistor there and it works unstable or something else, but at the moment I’m thinking of using only fixed values when inferring. You can use anything manually - after all, these are just lsb addresses.
> gowin: Change BYTE ENABLE handling.

- .github/workflows/codeql.yml
- .github/workflows/emcc.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-macos.yml
- .github/workflows/version.yml
- .github/workflows/vs.yml
- .github/workflows/wasi.yml
Node.js 16 actions are deprecated.  For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> Update workflows to Node.js 20

- kernel/rtlil.cc
- kernel/rtlil.h
- tests/various/bug4082.ys
Ought to fix #4082
The issue here is we replace removed wires in assignments with x-bits on both the LHS and RHS of the assignment. This triggers an assertion later on because we cannot assign to a constant.
> rtlil: Fix handling of connections on wire deletion

- backends/aiger/aiger.cc
Without this it will overflow the stack when loops are present.
> write_aiger: Detect and error out on combinational loops

- techlibs/gowin/brams_map.v
This primitive does not have a separate WRE port, so we regulate writing using Clock Enable.
> gowin: Fix SDP write enable port.

- backends/verilog/verilog_backend.cc
These were previously not being converted correctly leading to yosys internal cells being written to my netlist.
> write_verilog: Making sure BUF cells are converted to expressions.

- passes/pmgen/peepopt_shiftadd.pmg
Fixes #4160 
If the offset is larger than the signal itself, meaning the signal is completely shifted out,
it tried to extract a negative amount of bits from the old signal.
This RTL pattern is suspicious since it is a complicated way of arriving at a constant value, so we warn the user.
> peepopt: handle offset too large in `shiftadd`

- frontends/verific/verific.cc
This change adds `-no-split-complex-ports` option to `verific -import` making complex ports remaining packed as single port.
It makes changes from https://github.com/YosysHQ/yosys/pull/1654 optional when using `verific -import`.
> verific: add option to skip simplifying complex ports

- passes/opt/opt_clean.cc
(This is a by-product of investigating the hang from #4118.)
See the commits.
> opt_clean: Add commentary, remove dead code

- frontends/blif/blifparse.cc
> Issue a warning instead of a syntax error for blif delay constraints

- frontends/verific/verific.cc
- frontends/verific/verific.h
The following SV module at HEAD imported with verific,
```systemverilog
module my_module(
input logic [4:0] a,
input logic clk,
input logic enable,
output logic [4:0] z
);
reg [4:0] pipeline_register;
always @(posedge clk) begin
pipeline_register <= enable ? a : pipeline_register;
end
assign z = pipeline_register;
endmodule : my_module
```
results in the following output verilog
```systemverilog
/* Generated by 0.36 */
(* top =  1  *)
(* hdlname = "my_module" *)
(* src = "/tmp/temp_directory_zTwd0l/my_input.v:2.12-2.21" *)
module my_module(clk, enable, a, z);
wire [4:0] _0_;
(* src = "/tmp/temp_directory_zTwd0l/my_input.v:3.25-3.26" *)
input [4:0] a;
wire [4:0] a;
(* src = "/tmp/temp_directory_zTwd0l/my_input.v:4.19-4.22" *)
input clk;
wire clk;
(* src = …
```
> verific: Fixes incorrect aldff inference in verific importer

- passes/hierarchy/hierarchy.cc
- tests/verilog/param_no_default.ys
This fixes hierarchy when used with cell libraries that were loaded with -defer and also makes more of the hierarchy visible to the auto-top heuristic.
> hierarchy: Without a known top module, derive all deferred modules

- kernel/driver.cc
- kernel/yosys.cc
- kernel/yosys.h
Closes https://github.com/YosysHQ/yosys/issues/2060
> Follow the XDG Base Directory Specification

- frontends/verilog/verilog_parser.y
Consider this SystemVerilog file:
module top(...);
input clk;
input [7:0] data;
input ack;
always @(posedge clk)
if (ack) begin
assert(data != 8'h0a);
end
endmodule
Before this commit, the span for the assert was:
if (ack) begin>
assert(data != 8'h0a)<;
After this commit, the span for the assert is:
if (ack) begin
>assert(data != 8'h0a)<;
This helps editor integrations that only look at the beginning of the span.
> read_verilog: don't include empty `opt_sva_label` in span

- kernel/hashlib.h
We use `uint32_t` `uint64_t` etc. so add an explicit include.
> hashlib: Add missing `stdint.h` include

- README.md
- frontends/ast/ast.cc
- frontends/ast/ast.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- frontends/verilog/verilog_parser.y
- tests/sat/sizebits.sv
- tests/simple/arrays03.sv
- tests/simple/memory.v
- tests/svtypes/multirange_array.sv
- tests/svtypes/struct_array.sv
- tests/svtypes/struct_sizebits.sv
* Generalization of dimensions metadata (also simplifies $size et al.)
* Parsing and elaboration of multidimensional packed arrays
* Implementation of $increment, $dimensions and $unpacked_dimensions
* Resolve multiple dimensions defined in stages with typedef
Fixes #667
Fixes #3776
> Add support for packed multidimensional arrays

- Makefile
- backends/aiger/aiger.cc
- backends/blif/blif.cc
- backends/edif/edif.cc
- backends/firrtl/firrtl.cc
- backends/json/json.cc
- backends/smv/smv.cc
- backends/spice/spice.cc
- backends/verilog/verilog_backend.cc
- examples/cxx-api/scopeinfo_example.cc
- kernel/celltypes.h
- kernel/rtlil.cc
- kernel/satgen.cc
- kernel/scopeinfo.cc
- kernel/scopeinfo.h
- passes/opt/opt_clean.cc
- passes/opt/opt_merge.cc
- passes/techmap/flatten.cc
- techlibs/common/simlib.v
- tests/various/scopeinfo.ys
This PR adds `$scopeinfo` cells to preserve information about the hierarchy during flattening, in particular attributes including `src`.
This is still missing a kernel header containing utilities for easily querying `$scopeinfo` data.
> $scopeinfo support

- kernel/driver.cc
In #3973 we switched to using an internal `getopt` implementation unconditionally, but there turns out to be an issue with missing option arguments which lead to crashes. Address that.
Now we handle it gracefully:
```
$ ./yosys -p
./yosys: option '-p' expects an argument
Run './yosys -h' for help.
```
> driver: Fix crashes on missing cli arguments

- backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi.h
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
Because all objects in C++ must have non-zero size, a `value<0>` has a size of 4 despite consisting of a `uint32_t chunks[0]`. The debug item assertions were not written expecting that and prevent any debug items for such values from compiling.
The C API does not define exactly what happens for a zero-width debug item, but it seems OK to say that they should refer to some unique pointer that cannot be, in actuality, read or written. This allows some techniques or optimizations that use `curr` pointers as keys and assume they correspond 1-to-1 to simulation objects.
> cxxrtl: fix debug information for zero-width items

- passes/sat/clk2fflogic.cc
- tests/various/clk2fflogic_effects.sh
- tests/various/clk2fflogic_effects.sv
Fixes a bug in the handling of the recently introduced $check cells. Both $check and $print cells in clk2fflogic are handled by the same code and the existing tests for that were only using $print cells. This missed a bug where the additional A signal of $check cells that is not present on $print cells was dropped due to a typo, rendering $check cells non-functional.
Also updates the tests to explicitly cover both cell types such that they would have detected the now fixed bug.
> clk2fflogic: Fix handling of $check cells

- Makefile
A yosys build with verific support can act as a non-verific yosys with `YOSYS_NOVERIFIC=1` in the enviornment, which is useful for quickly testing code that works with either frontend without rebuilding yosys.
Before this change, this did not work with `make test` as it would only consider the build time configuration to decide whether to run tests that depend on verific support, immediately failing on those tests when the enviornment contains `YOSYS_NOVERIFIC=1`.
This adds logic to the makefile that checks this enviornment variable and also exports YOSYS_NOVERIFIC=1 to the enviornment when that is present as a make variable to support `make test YOSYS_NOVERIFIC=1` invocations.
> tests: Support running `make test` with YOSYS_NOVERIFIC=1

- tests/gen-tests-makefile.sh
Variable `yosys_args`  is used in other places in script and due to this ys tests in generated `run-test.mk` had yosys parameters repeated multiple times, each one  in list one time more.
This makes variable name unique
> do not override existing shell variable

- passes/cmds/stat.cc
Checks to see if a cell is of type ff in the liberty, and keeps track of an additional area value.
```
Chip area for module '\addr': 92.280720
Sequential area for module '\addr': 38.814720
```
> stat: Add sequential area output to stat -liberty

- passes/cmds/connect.cc
Instead of silently ignoring what would ordinarily be the selection arguments to a pass, interpret those and mark the support in the help message.
For context, later on in the help message, it says
```
The connect command operates in one module only. Either only one module must
be selected or an active module must be set using the 'cd' command.
```
> connect: Do interpret selection arguments

- .github/workflows/test-linux.yml
- .github/workflows/test-macos.yml
- tests/xprop/test.py
Ought to fix the CI failures which prompted iverilog pinning in #4148 / ddfd867.
> Address race in `xprop` tests

- passes/proc/proc_rom.cc
- tests/proc/proc_rom.ys
See the test case.  PROC_ROM will consider this for evaluation, even though -- without any actions -- lhs is empty (but still "uniform"). A zero-width memory is constructed, which later fails check with:
```
ERROR: Assert `width != 0' failed in kernel/mem.cc:518.
```
Ensure we don't proceed if there's nothing to encode.
---
Alternatively, do we want to reject this switch as meaningless? This came up in an Amaranth (`188eb8d4`) project; I've yet to investigate deeply why it's produced this, but either way Yosys probably doesn't want to give the assert it currently does here.
> proc_rom: don't assert on big actionless switch.

- frontends/ast/ast.cc
- frontends/ast/simplify.cc
The leading slash is not a part of the attribute as it only concerns public values.
No idea why this fails tests. @povik, do you know?
> read_verilog: correctly format `hdlname` attribute value

- passes/techmap/dfflibmap.cc
- tests/techmap/dfflibmap.ys
This is an alternative to setting the `dont_use` property in lib. This brings `dfflibmap` in parity with the abc pass for `-dont_use`.
This feature is extremely useful in the case where Liberty files are not easily modifiable, such as when they are stored on a read-only network drive.
This is my first PR here, so I am very open to feedback!
> dfflibmap: Add a -dont_use flag to ignore cells

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
This fixes a regression introduced when commit observers were added.
> cxxrtl: make blackbox `commit()` possible to override

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi.cc
- backends/cxxrtl/runtime/cxxrtl/capi/cxxrtl_capi.h
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
This commit adds a `debug_scopes` container, which can collect metadata about scopes in a design. Currently the only scope is that of a module. A module scope can be represented either by a module and cell pair, or a `$scopeinfo` cell in a flattened netlist. The metadata produced by the C++ API is identical between these two cases, so flattening remains transparent to a netlist with CXXRTL.
The existing `debug_items` method is deprecated. This isn't strictly necessary, but the user experience is better if the path is provided as e.g. `"top "` (as some VCD viewers make it awkward to select topmost anonymous scope), and the upgrade flow encourages that, which should reduce frustration later.
While the new `debug_items` method could still be broken in the future as the C++ API permits, this …
> cxxrtl: expose scope information in the C++ API

- Makefile
- libs/ezsat/Makefile
- libs/subcircuit/Makefile
- misc/yosys-config.in
- passes/techmap/Makefile.inc
- tests/unit/Makefile
This would solve the CXX and LD points of https://github.com/YosysHQ/yosys/issues/2011.
LD is also changed to g++ when appropriate.
All pipelines pass in my fork (https://github.com/RCoeurjoly/yosys/actions).
> ´Use g++ and clang++ instead of gcc and clang as C++ compilers

- Makefile
`--memory-init-file` is no longer supported as of emscripten version 3.1.55 (released 03/01/24).  It was previously taking a value of `0`, so I don't think it was actually doing anything for us and can be safely removed?
> Fix emcc build

- kernel/yosys.cc
Tweak the FreeBSD version of proc_self_dirname() to work on NetBSD use it.
Resolves issue #4253.
> Add NetBSD support

- passes/equiv/equiv_simple.cc
This fixes an issue introduced in commit 26644ea due to which flip-flops are inadvertently ignored when building up driver map. The mentioned commit wasn't without functional change after all.
Thanks to @ArkadyKlimov who pointed this out.
> equiv_simple: Take FFs into account for driver map

- .github/workflows/test-macos.yml
Adds `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1` to prevent brew trying to upgrade dependents, which is both a waste of time, and raises an error trying to symlink `bin/2to3`.
> ci: Fix mac builds

- passes/techmap/techmap.cc
- techlibs/common/synth.cc
> synth: Introduce `-extra-map` for amending techmap

- backends/smt2/smtbmc.py
- backends/smt2/smtbmc_incremental.py
- backends/smt2/smtio.py
The --track-assumes option makes smtbmc keep track of which assumptions were used by the solver when reaching an unsat case and to output that set of assumptions. This is particularly useful to debug PREUNSAT failures.
The --minimize-assumes option can be used in addition to --track-assumes which will cause smtbmc to spend additional solving effort to produce a minimal set of assumptions that are sufficient to cause the unsat result.
> smtbmc: Add --track-assumes and --minimize-assumes options

- kernel/celledges.cc
- kernel/utils.h
- passes/cmds/check.cc
- tests/opt/opt_dff_qd.ys
- tests/various/check.ys
- tests/various/check_2.ys
- tests/various/check_3.ys
- tests/various/check_4.ys
Partially obsoletes #4178.
Sample:
```
module top(y);
output wire [7:0] y;
wire f = ~y[0];
assign y = &{f, 2'h0, {4{f}}, 1'h0};
endmodule
```
outputs
```
3. Executing CHECK pass (checking for obvious problems).
Checking module top...
Warning: found logic loop in module top:
cell $not$loop_test.v:3$1 ($not) source: loop_test.v:3.11-3.16
A[0] --> Y[0]
wire \f source: loop_test.v:3.7-3.8
cell $reduce_and$loop_test.v:4$2 ($reduce_and) source: loop_test.v:4.13-4.37
A[1] --> Y[0]
A[2] --> Y[0]
A[3] --> Y[0]
...
wire \y [0] source: loop_test.v:2.20-2.21
Found and reported 1 problems.
```
> Use cell edges data in `check`, improve messages

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- tests/cxxrtl/test_value_fuzz.cc
`x = x.neg();` results in the subsequent `x.is_neg()` to always be false.
Ditto for the `dividend.is_neg() != divisor.is_neg()` test.
Fix this.
> cxxrtl: Fix sdivmod

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- kernel/fmt.cc
- kernel/fmt.h
This is a work-in-progress PR at the moment.
> Add several new formatting features used by Amaranth to translate Python format strings

- backends/verilog/verilog_backend.cc
Processes without sync rules correspond to simple decision trees that directly correspond to `always @*` or `always_comb` blocks in Verilog, and do not need a warning.
This removes the need to suppress warnings during the RTLIL-to-Verilog conversion performed by Amaranth.
> write_verilog: only warn on processes with sync rules

- backends/verilog/verilog_backend.cc
- tests/simple/.gitignore
- tests/verilog/.gitignore
- tests/verilog/assign_to_reg.ys
> write_verilog: don't `assign` to a `reg`

- passes/cmds/stat.cc
This adds information about the number of ports and port bits on a module to the `stat` command.
> add port statistics to stat command

- docs/source/yosys_internals/formats/cell_library.rst
- techlibs/common/simlib.v
I did my best to frontload the description with a bit that's free of CONFIG technicalities. This PR unfortunately duplicates information between cell library docs and simlib.v, where the first paragraph is pulled as the output of `help $macc`
> docs: Document $macc

- techlibs/efinix/cells_sim.v
- tests/arch/run-test.sh
- tests/memlib/memlib_9b1B.v
- tests/memlib/memlib_wren.v
- tests/memories/issue00335.v
After last change iverilog is more strict to "use before declaration" of parameters.
To use localparam in module declaration required use of SystemVerilog syntax, only affecting Efinix.
> Tests update for latest more strict iverilog

- passes/opt/opt_demorgan.cc
By setting argidx correctly this PR prevents the warning opt_demorgan would unconditionally throw: `Warning: Selection "opt_demorgan" did not match any module.`
> opt_demorgan: fix extra args warning

- CODEOWNERS
- tests/arch/quicklogic/.gitignore
Add owner of CODEOWNERS file
Add owner of workflows in CODEOWNERS
Fixes QuickLogic tests .gitignore file
> Add workflows and CODEOWNERS and fixed gitignore

- passes/opt/opt_clean.cc
This is on top of #4123, only the final commit is the subject of this PR. This should be merged some time later after the base PR is merged.
> opt_clean: Remove dead assertion 

- Makefile
- docs/.gitignore
- docs/Makefile
- docs/source/appendix/auxprogs.rst
- docs/source/cmd_ref.rst
- docs/source/code_examples/extensions/Makefile
> Strip compilation date from doc outputs

- passes/sat/formalff.cc
The `has_srst` case was checking `sig_ce` instead of `sig_srst` due to a copy and paste error.
This would crash when `has_ce` was false and could incorrectly determine that an initial value is unused when `has_ce` and `has_srst` are both set.
> formalff -setundef: Fix handling for has_srst FFs

- frontends/verific/verific.cc
Each module is represented by Netlist object in Verific. It's owner is Cell and it's owner is Library object, that matches "work" specified when reading Verilog or VHDL sources.
There is always such object so no need for NULL checks.
> verific: expose library name as module attribute

- .github/workflows/test-verific.yml
- Moved CI environment from Jenkins to private GitHub actions.
- Contains documentation update on "main"
- Runs sby tests on "main"
- Runs Verific related and simple sby test on any branch/PR
> Add new verific testing environment CI

- passes/techmap/abc.cc
Changes:
- adds the `-m` flag to the ABC script when multiple liberty files are specified to indicate to ABC that is should merge the libraries, this solves the issue of only the last liberty file specified getting used for synthesis.
Requirements:
- needs the abc fork to be synced with the main abc to get the new flag.
> add support for using ABCs library merging when providing multiple liberty files

- kernel/rtlil.cc
Previously `extract` on a `SigSpec` would always unpack it. Since a significant amount of `SigSpec`s have one or few chunks, it's worth having a dedicated implementation.
This is especially true, since the RTLIL frontend calls into this for every `wire [lhs:rhs]` slice, making this `extract` take up 40% when profiling `read_rtlil` with one of the largest coarse grained RTLIL designs I had on hand.
With this change the `read_rtlil` profile looks like I would expect it to look like, but I noticed that a lot of the other core RTLIL methods also are a bit too eager with unpacking or implementing `SigChunk`/`Const` overloads that just convert to a single chunk `SigSpec` and forward to the implementation for that, when a direct implementation would avoid temporary std::vector allocations. While …
> rtlil: Add packed `extract` implementation for `SigSpec`

- passes/hierarchy/hierarchy.cc
- tests/various/hierarchy_generate.ys
This change in refactoring commit e38f40af5b7 (passes/hierarchy/hierarchy.cc:51) actually changed the behavior:
```
-		if (cell->type.substr(0, 1) == "$" && cell->type.substr(0, 3) != "$__")
+		if (cell->type.begins_with("$__"))
```
As far as I can tell, the intended behavior for `hierarchy -generate` is to only create the requested module if:
- the module is instantiated in the design
- the module is not defined in the design
- the module name is not an internal cell type (heuristically)?
The heuristic in the last point being, if the cell name starts with `$` it's ignored, unless it starts with `$__` (which is the recommended prefix for intermediate cell types in techmap rules, for which it might be desirable to generate a blackbox definition, e.g. to be able to correctly `show` or …
> fix hierarchy -generate mode handling of cells

- tests/techmap/techmap_chtype.ys
Is this behavior expected? A foo of width 4 gets techmapped to something named LCU_10. I expected the WIDTH parameter to be inferred. Are port sizes allowed to be mismatched when techmapping?
> techmap: add dynamic cell type test

- passes/techmap/Makefile.inc
- passes/techmap/cellmatch.cc
- tests/techmap/cellmatch.ys
```
cellmatch -lib <design> [module selection]
This pass identifies functionally equivalent counterparts between each of the
selected modules and a module from the secondary design <design>. For every such
correspondence found, a techmap rule is generated for mapping instances of the
former to instances of the latter. This techmap rule is saved in yet another
design called '$cellmatch', which is created if non-existent.
This pass restricts itself to combinational modules. Modules are functionally
equivalent as long as their truth tables are identical upto a permutation of
inputs and outputs. The supported number of inputs is limited to 6.
```
> cellmatch: New pass for picking out standard cells automatically

- backends/smt2/smtbmc.py
- backends/smt2/smtbmc_incremental.py
- backends/smt2/smtio.py
This extends the experimental incremental JSON API to allow arbitrary smtlib subexpressions, defining smtlib constants and to allow access of signals by their .yw path.
It also fixes a bug during .yw writing where values would be re-emitted in later cycles if they have no newer defined value and a potential crash when using --track-assumes.
> smtbmc: Improvements for --incremental and .yw fixes

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
- backends/cxxrtl/runtime/cxxrtl/cxxrtl_replay.h
The large amount of stack space used by this function is problematic especially on macOS, where the default stack size is 512 KiB.
> cxxrtl: reduce stack space used by the `debug_info()` function

- .github/workflows/codeql.yml
- .github/workflows/emcc.yml
- .github/workflows/test-docs.yml
- .github/workflows/test-linux.yml
- .github/workflows/test-macos.yml
- .github/workflows/test-verific.yml
- .github/workflows/version.yml
- .github/workflows/vs.yml
- .github/workflows/wasi.yml
- .gitignore
- .gitmodules
- Makefile
Add YosysHQ/abc as a submodule located in abc. Apart from cloning with submodules, no other modifications are made to github actions.
This would enable building yosys with abc fetched as tar.gz, as pointed out by @mmicko in  https://github.com/YosysHQ/yosys/pull/4238#issuecomment-1966067326
Before starting the compilation of abc, we check four cases:
1. abc directory does not exist. The compilation is stopped with the following error.
> Error: The 'abc' directory does not exist.
> Initialize the submodule: Run 'git submodule update --init' to set up 'abc' as a submodule.
2. abc is a clone of abc (abc/.gitcommit content is Format). The compilation is stopped with the following error.
> Error: 'abc' is not configured as a git submodule.
> To resolve this:
> 1. Back up your changes: Save any …
> Add YosysHQ/abc as a submodule located in abc.

- frontends/verific/verific.cc
Test Case
```
module packed_dimensions_range_ordering (
input  wire [0:4-1] in,
output wire [4-1:0] out
);
assign out = in;
endmodule : packed_dimensions_range_ordering
module instanciates_packed_dimensions_range_ordering (
input  wire [4-1:0] in,
output wire [4-1:0] out
);
packed_dimensions_range_ordering U0 (
.in (in),
.out(out)
);
endmodule : instanciates_packed_dimensions_range_ordering
```
```
// with verific, does not pass formal
module instanciates_packed_dimensions_range_ordering(in, out);
input [3:0] in;
wire [3:0] in;
output [3:0] out;
wire [3:0] out;
assign out = { in[0], in[1], in[2], in[3] };
endmodule
// with surelog, passes formal
module instanciates_packed_dimensions_range_ordering(in, out);
input [3:0] in;
wire [3:0] in;
output [3:0] out;
wire [3:0] out;
assign out = in; …
```
> frontend: Fixes verific import around range order

- docs/source/_static/yosyshq.css
- docs/source/appendix/primer.rst
- docs/source/getting_started/example_synth.rst
- docs/source/getting_started/scripting_intro.rst
- docs/source/introduction.rst
- docs/source/using_yosys/more_scripting/interactive_investigation.rst
- docs/source/using_yosys/more_scripting/selections.rst
- docs/source/using_yosys/synthesis/cell_libs.rst
- docs/source/using_yosys/synthesis/extract.rst
- docs/source/using_yosys/synthesis/memory.rst
- docs/source/using_yosys/synthesis/opt.rst
- docs/source/using_yosys/synthesis/proc.rst
- docs/source/yosys_internals/extending_yosys/extensions.rst
- docs/source/yosys_internals/flow/control_and_data.rst
- docs/source/yosys_internals/flow/overview.rst
- docs/source/yosys_internals/flow/verilog_frontend.rst
- docs/source/yosys_internals/formats/rtlil_rep.rst
- docs/source/yosys_internals/techmap.rst
#4385
New `invert-helper` css class uses svg color filter matrix from @jix (via https://github.com/YosysHQ/yosys/issues/4385#issuecomment-2102187927) to invert brightness for images when using dark theme.
Make docs locally, check images in both light and dark mode, using both the forced light/dark mode selector and the auto mode with browser/OS selected light/dark mode.
> Dark theme images for docs

- .github/workflows/test-build.yml
https://github.com/YosysHQ/yosys/actions/runs/9038879272 skipped test-docs because `pre_job` ignores changes to docs, but it should not.
Add a different skip check for the docs that doesn't ignore the docs directory.
> test-docs should not ignore docs changes

- passes/cmds/logcmd.cc
For usage in Tcl scripting, when one essentially writes a pass in Tcl by combining existing passes.
> Extend `log` command with `-push`, `-pop`, `-header` options

- Makefile
Since https://github.com/YosysHQ/yosys/pull/4334, when building docs with `ABCEXTERNAL` set, the rule for yosys-abc docs usage would attempt to build in-tree ABC.
This fix this regression by only including yosys-abc in `DOCS_USAGE_STDERR` when `ABCEXTERNAL` is not set.
> Only build yosys-abc usage docs when ABCEXTERNAL is not set

- backends/cxxrtl/cxxrtl_backend.cc
As explained in #4405, having outputs or inputs aliased causes a loss of information in `debug_info`.
To prevent this behavior, we stop assigning debug information at the beginning of the `debug_alias` option corresponding logic if the wire is an input and/or an output.
One implementation choice here was to choose, for an input that is tied to a constant, whether we should generate:
```
items->add(path, "a0", "src\000sand_ti.v:1.18-1.20\000", p_a0, 0, debug_item::INPUT|debug_item::DRIVEN_COMB);
```
or
```
static const value<1> const_p_a0 = value<1>{0u};
items->add(path, "a0", "src\000sand_ti.v:1.18-1.20\000", const_p_a0);
```
This patch is an implementation for the first one, because we can still query the constant later in the first whereas we would loose the `INPUT` and `DRIVEN_COMB` …
> cxxrtl: Prevent wires with input or output ports from being aliased

- docs/source/yosys_internals/formats/cell_library.rst
`$demux` isn't documented so we should have a TODO for it
> docs: add todo for $demux

- backends/smt2/smtbmc.py
These came up when using the experimental incremental interface and are also in code that was recently refactored to support that interface.
This fixes observed crashes when using the incremental interface. In both cases a special case was missed and the specific changes handle the missed special case. 
* Making `smt_concat` accept anything iterable in addition to tuples and lists, as it is sometimes called with generators.
* Avoiding calling `smt_extract_mask` with a completely empty mask and expecting a useful result, as it returns None in that case.
The `check-sby` CI checks should be sufficient to ensure this doesn't regress …
> smtbmc: Fix two .yw handling related crashes

- frontends/verific/verific.cc
Running AddressSanitizer on yosys when using verific uncovered a memory leak in a `file_names` Array, as the char* copy created by `strdup()` is not freed.
Manually iterate over the array and free the memory, similar to other instances in the `verific.cc` file.
> Fix memory leak in verific file parsing.

- backends/cxxrtl/cxxrtl_backend.cc
- tests/cxxrtl/run-test.sh
- tests/cxxrtl/test_unconnected_output.v
Unconnected sync outputs cause `dump_cell_sync` to emit an invalid assignment in the instantiating module, namely `value<0>() = …;`.
Ensure the LHS is not empty before emitting.
> cxxrtl: don't emit invalid code on unconnected outputs.

- frontends/ast/ast.h
The `ast.h` header has a stale comment saying it's a generic API. In practice this is used by the Verilog frontend internally and is maintained as a part of that frontend. Update the comment accordingly.
> Update stale top comment in `ast.h`

- tests/cxxrtl/test_value_fuzz.cc
Correct C++ code
A few instances of incorrect (and non-portable) use of format specifiers have been fixed.
Compilation with `-Werror=format` of the changed file should now succeed.
> cxxxrtl: fix use of format specifiers in test

- docs/source/getting_started/scripting_intro.rst
Some script parsing features are currently undocumented.
Document `!` and `:`.
Add warning that semicolons need spaces.
> Document script parsing

- .github/workflows/test-compile.yml
- Makefile
- README.md
- docs/source/getting_started/installation.rst
- docs/source/yosys_internals/index.rst
- guidelines/CodingStyle
- kernel/yosys_common.h
- misc/create_vcxsrc.sh
Team decided it is time to update minimal requirement for C++ compiler to be at least C++17 compliant.
Change in header file (that is used everywhere) makes sure that requirement is enforced.
Also updated workflow to run now tests with new minimal requirements.
> Make C++17 compiler required

- kernel/rtlil.cc
This fixes the helper creating invalid RTLIL when called with `is_signed` set to true.
See here from the commit message:
> Only the `B` input (the shift amount) can be marked as signed on a `$shiftx` cell. Adapt the helper accordingly and prevent it from creating invalid RTLIL when called with `is_signed` set. Previously it would mark both `A` and `B` as signed.
There's no way to test this without writing external code, I think.
> rtlil: Fix `addShiftx` for signed shifts

- passes/pmgen/peepopt.cc
- passes/pmgen/peepopt_shiftadd.pmg
Related to #4445 and #4448.  
The padding created in shiftadd increases the input to the shift operations. During `techmap` the shift operation will be implemented as a logarithmic shifter with all `$_MUX_` cells, even if it muxes between two identical inputs (constants). This is then later optimized away. For large constant shifts a lot of padding is added, significantly inflating the number of temporary `$_MUX_` cells, thus increasing the runtime and memory usage.
I think this would also solve #4445 but you may still want to add #4448 since it deals with a internal representation limit and theoretically you could still run into it with only this PR (though you would now need a signal that is millions of bits wide).
Here some numbers (script and module below):
```
shift by  5k bits -> …
```
> peepopt: limit padding from shiftadd

- misc/create_vcxsrc.sh
There were issues with unavailability of these download locations in past.
By using GitHub pre-release location as part of this repo, we got these files hosted on higher availability servers.
CI process will already utilize this script and it is enough to confirm changes working
> Use alternate location for VS build required files

- passes/opt/opt_expr.cc
See the commits. This avoids having to populate `dict<RTLIL::Cell*, std::set<RTLIL::SigBit>> cell_to_inbit;`, and it saves repeated conversions of type IDs to strings (36 times per cell for one iteration of the loop in `opt_expr`). Allocating a string for the IDs was significant enough to stand out when watching where `opt_expr` spends its time.
> Improve `opt_expr` performance

- .gitcommit
- Makefile
See https://github.com/YosysHQ/abc/pull/35
abc submodule is bumped. abc .gitcommit checks for `Format:%h` are replaced with checks for either  `Format:%h` or  `Format:%H`. Yosys .gitcommit is changed also to ` Format:%H`. The yosys .gitcommit check for `Format:%h` is replaced with a check for a substring check for `Format:`
Modify .gitcommit files at will to simulate tarballs instead of git checkouts and observe build success and errors to match intended behavior
> Reproducible git hash

- techlibs/gowin/cells_sim.v
- techlibs/gowin/cells_xtra.v
Not so much adding the primitive itself, but only its DCS_MODE parameter, without which an error occurs.
> Gowin. Add the DCS primitive

- Makefile
`bitpattern.h` is useful to plugins which process HDLs.
> Makefile: do install `bitpattern.h`

- frontends/ast/ast.cc
- frontends/ast/ast.h
Some external projects, like synlig, depend on `ast.h` which is valid but isn't generally necessary or advisable. The Verific frontend doesn't use it. This PR removes the suggestion that external yosys frontends other than the open source Verilog frontend can use this ast functionality
> ast: don't suggest use in external projects

- passes/proc/proc_rom.cc
Make the ROMs generated from a case statement be attributable to their source location.
> proc_rom: Set `src` on the emitted memory

- kernel/yosys.cc
*.vhdl files, and not only *.vhd files, seem to be valid VHDL extensions.
For example, GitHub assigns VHDL to both .vhd and .vhdl, when searching for VHDL files in GHDL:
https://github.com/search?q=repo%3Aghdl%2Fghdl++language%3AVHDL&type=code
Tested locally the following:
```
cp tests/sva/basic04.vhd tests/sva/basic04.vhdl
./yosys tests/sva/basic04.vhdl
```
We get:
> -- Parsing `tests/sva/basic04.vhdl' using frontend ` -vhdl' --
Checking that we did not brake *.vhd
`./yosys tests/sva/basic04.vhd`
We also get:
> -- Parsing `tests/sva/basic04.vhd' using frontend ` -vhdl' --
> Guess VHDL frontend for both *.vhd and *vhdl files

- kernel/hashlib.h
- kernel/sigtools.h
This PR adds developer comments to sigmap and mfp
> sigmap: comments

- frontends/verific/verific.cc
Makes sure extensions are initialized properly on when self-registration of pass is done
> Initialize extensions when Verific pass is registered

- Makefile
- kernel/cost.cc
- kernel/cost.h
- passes/cmds/stat.cc
- passes/hierarchy/Makefile.inc
- passes/hierarchy/keep_hierarchy.cc
- passes/tests/test_cell.cc
Modules being flattened improves QoR in practice. It also makes the yosys runtime take much longer.
This PR creates cost.cc with linear cost models for almost all internal cell types to estimate the size of a module after techmapping. To get most of these numbers, I used a modified version of the `test_cell` command, see [emil/gather-cell-size](https://github.com/widlarizer/yosys/tree/emil/gather-cell-size).
This PR also adds the `keep_hierarchy` pass which marks all selected modules with that attribute and has an optional `-max_cost` integer argument which sets a maximum estimated cost threshold.
```
6. Executing keep_hierarchy pass.
Marking top.cpu (module too big: 8880 > 100).
Marking top.cpu.alu (module too big: 2068 > 100).
Marking top.cpu.brancher (module too big: 515 > 100). …
```
> cost: add keep_hierarchy pass with min_cost argument

- frontends/verific/verific.cc
VHDL is case insensitive and even if name match import was not properly done.
By renaming provided VHDL unit name to original VHDL unit name we make sure that Verific generated Netlist object will be matched by name.
> VHDL is case insensitive, make sure netlist name is proper

- .github/workflows/test-build.yml
- .github/workflows/test-verific.yml
- Makefile
- README.md
On mac, there's problems with lld presence, compatibility, and detection with brew vs nixos. Disable lld and LTO by default and inform users in the README about the benefit of enabling both.
> Makefile: no LTO and lld by default

- .github/workflows/test-compile.yml
[test-compile (ubuntu-22.04, clang-11)](https://github.com/YosysHQ/yosys/actions/runs/10374983466/job/28755517074?pr=4537#logs) is broken as of 14/08/2024 since clang-11 and clang-12 were dropped from ubuntu-22.04.
Replace with ubuntu-20.04, which also has earlier versions of clang so we can test clang-10 instead.
> Replace test-compile (ubuntu-22.04, clang-11)

- Makefile
abc builds unconditional because `check-git-abc` is a phony prerequisite and therefore always runs, and since it always runs it will always trigger abc to rebuild.
Convert `check-git-abc` to an order-only prerequisite.  It still runs as before, but no longer triggers yosys-abc to rebuild when it does.
> Stop unconditionally building abc

- .github/workflows/test-verific.yml
- .readthedocs.yaml
- Makefile
- docs/source/conf.py
- docs/source/requirements.txt
[Yosys ReadtheDocs](https://yosyshq.readthedocs.io/projects/yosys/en/latest/) is currently built from a separate repo, [yosys-cmd-ref](https://github.com/YosysHQ-Docs/yosys-cmd-ref).  This would occasionally lead to problems with people looking at the wrong repository for the documentation source, since yosys-cmd-ref is automatically updated from this repo with the verific runner.  This was being done since a portion of the documentation requires yosys to be compiled in order to generate, which would take too long for the ReadtheDocs builder and would generate without verific compatibility which also changes the generated documentation.
Because the verific runner would only update documentation from the main branch, the current setup also …
> Local readthedocs

- techlibs/gowin/cells_sim.v
Without OSER4_MEM, IDES4_MEM and DQS the synthesis of my Rocket Chip design for my Sipeed Tang FPGA fails.
Two memory cell defines were missing for running through a Litex design
This PR fixes the open issue in https://github.com/YosysHQ/yosys/issues/4453
> Add DQS and related primitives to Gowin tech files

- passes/pmgen/peepopt_shiftadd.pmg
- tests/opt/bug4413.ys
This solves issue #4413. `shiftadd` did not consider underflows for unsigned shift-amounts.  
Specifically the issue arises if peepopt receives an expression like 
```verilog
wire [6:0] shift;
wire [7:0] data, shift2;
assign shift2 = shift - 1'b1;
assign out = data >> shift2;
```
Here an _intended_ underflow occurs if `shift<1`. (by _intended_ I mean it is what the current network implies, no matter what the designer might have wanted).  
This adds a filter for the case described and adds the bug to the tests.
> peepopt: avoid shift-amount underflow

- .github/workflows/extra-builds.yml
This is achieved by having a matrix build, where we build with nix under both ubuntu-latest and macos-latest.
We could also test that yosys builds locally with nix on macOS. Unfortunately I don't have the machine required to do that, so any help is 
Tested the action on my fork and it works (https://github.com/RCoeurjoly/yosys/actions/runs/10169394792).
> Run nix build also on macos. Build with more logs

- techlibs/common/simlib.v
Hello, 
As discussed in #121, Not all cell types have an help message yet. This PR adds around 23 new help messages.
These cells are:-  `$shr`, `$shl`,  `$sshr`, `$sshl`, `$lt`, `$le`, `$eq`, `$ne`, `$eqx`, `$nex`, `$gt`, `$ge`, `$add`, `$sub`, `$mul`, `$pow`, `$logic_*`, `$concat`, `$mux`, `$demux`, `$tribuf`.
I have updated `techlibs/common/simlibs.v` to write the messages . 
I have tested these changes locally by running it on a Docker container. Here are screenshots of some of the new messages:-
Here's the [Dockerfile](https://gist.github.com/NachtSpyder04/0dd5ce7ab6e486d3d3728a7210acc24b) that I have used. You can also test the same by building it.
Let me know if there are any changes required.
Thank You
> [Docs]:Add new cell type help messages 

- .github/workflows/test-verific.yml
PRs from forks don't have access to secrets and will error when trying to trigger ReadtheDocs, e.g. https://github.com/YosysHQ/yosys/actions/runs/10456408410/job/28954216463?pr=4550
Add back the "if ref == main" check from previous docs building.
The "Trigger RTDs build" step of this pr's action should be skipped.
> docs: Only trigger RTDs on main

- .github/workflows/test-verific.yml
- backends/rtlil/rtlil_backend.cc
- frontends/rtlil/rtlil_lexer.l
- frontends/rtlil/rtlil_parser.y
- tests/various/rtlil_signed_attribute.ys
Fix https://github.com/YosysHQ/yosys/issues/4539
Updated rtlil_lexer.l to recognize constants with an optional s for signedness.
Modified rtlil_parser.y to set RTLIL::CONST_FLAG_SIGNED when appropriate.
Adjusted rtlil_backend.cc to correctly export signed constants.
Added a test (rtlil_signed_attribute.ys) for round-trip verification of signed constants.
I have included a test doing round trip test. I assume the rest of tests could catch relevant bugs.
> Ensure signed constants are correctly parsed and exported in RTLIL. Add a test to check parsing and exporting

- kernel/fmt.cc
- kernel/satgen.cc
- libs/fst/fstapi.cc
- libs/minisat/00_PATCH_warnings.patch
- libs/minisat/00_UPDATE.sh
- libs/minisat/System.cc
- libs/minisat/Vec.h
- passes/techmap/abc.cc
The test-compile.yml action ends up with a lot of warnings, e.g. [latest main run](https://github.com/YosysHQ/yosys/actions/runs/10406437503) has 47 warnings.  Many of these warnings are simple things like uninitialized/unused variables and deprecated system functions.
Assign default values to variables, add `ifdef` guards to debug variables, replace sprintf with snprintf, and replace `realloc` in the minisat library with `reallocarray` when using GCC.
This should be passing all tests (and with fewer warnings), but there might be some weird edge case compilations that I'm not aware of
> Resolve (some) compiler warnings

- passes/proc/proc_dff.cc
- tests/proc/proc_dff.ys
This fixes #4560, where previously the order that sync rules were processed in depended on the order they were pulled out of a std::map. This PR changes this to process them in the order they are found in, respecting the priorities among the async signals.
This is an alternative to #4568 that should fix the issues highlighted there (I've tested the example I left in the replies there and it seems to give the correct result now).
It still makes the optimizations made before, such as merging together control signals if all sync rules cause the DFF to take the same value.
> proc_dff: respect sync rule priorities when generating complex dffsrs

- .github/workflows/prepare-docs.yml
- .github/workflows/test-verific.yml
- .readthedocs.yaml
- Makefile
- README.md
- docs/Makefile
- docs/source/_images/Makefile
- docs/source/code_examples/opt/Makefile
- docs/source/conf.py
- docs/source/using_yosys/more_scripting/index.rst
- docs/source/using_yosys/more_scripting/troubleshooting.rst
- docs/source/using_yosys/synthesis/cell_libs.rst
- docs/source/yosys_internals/extending_yosys/build_verific.rst
- The current setup for rtds_action doesn't work locally.
- There are also cases where ReadtheDocs will build before the docs artifact is ready and upload an incomplete version of the documentation.
- Gate rtds_action behind checks for both `READTHEDOCS` and `GITHUB_TOKEN` environment variables.  This also has some changes to (better) support building on mac and other small formatting fixes.
- Update `.readthedocs.yaml` to fail if sphinx raises any warnings, notably because it's missing files.  This also involves fixing the couple of warnings that were still popping up.  I also ended up splitting the `prepare-docs` job from the `test-verific` in order to better control when the job would run.  There is an …
> Better docs builds

- passes/cmds/Makefile.inc
- passes/cmds/internal_stats.cc
To find out static memory usage right after RTLIL generation and at other points in the flow, currently the best practice is to dump and reload and inspect peak memory usage. This PR adds the experimental `devstat` command that prints in a JSON format the current memory usage. It is intended to be expanded further for information about the efficiency of RTLIL object representation and anything else that's relevant to yosys developers but not users.
On linux, yosys inspects its `/proc/self/status` file. This may not be present on some Linux distributions, but it should be handled gracefully should that file not exist.
On macOS, I use [task_info](https://developer.apple.com/documentation/kernel/1537934-task_info)
> internal_stats: init, report current memory consumption on linux and mac

- kernel/ff.h
Active-high as a concept doesn't clearly map to a the polarity of a clock signal, this PR makes it explicit
> ff: improve comments

- backends/aiger/xaiger.cc
A clean-up
Avoid any `bswap` helpers or the detection of host endianness when there's a portable way to write out a number in big endian: e.g. for 32-bit `x` you can do an equivalent of `put(x >> 24); put(x >> 16); put(x >> 8); put(x);`
> write_xaiger: Get by without endianness helpers

- .github/workflows/test-verific.yml
- Makefile
Save time running these tests on public CI
Added ENABLE_FUNCTIONAL_TESTS option disabled by default
> Run functional tests on private runner only

- passes/cmds/stat.cc
Currently, the area variables in the stat struct are not initialized. This caused the area stats occasionally being an erroneous value.
I got the following output when synthesizing a two-bit flip-flop using SKY130 PDK,
```
Chip area for module '\main': 40.038400
of which used for sequential elements: -nan (-nan%)
```
> Initialize area stats in stat pass

- frontends/verific/verific.cc
- kernel/rtlil.cc
- kernel/rtlil.h
- passes/cmds/printattrs.cc
- tests/verific/bounds.vhd
- tests/verific/bounds.ys
Having bound properties for wires would help detect underflow and overflow in cases where the user is more restrictive than the RTLIL representation.
For example, the following VHDL
`signal a : INTEGER range 0 to 6;
`
is represented in RTLIL as:
`wire width 3 input 1 \a
`because to represent decimal 6 you need at least 3 bits.
However, decimal 7 can also be represented, which would be an overflow as per the user specified range, and that user constraint would get lost without this attribute.
This patch helps ensure that those user constraints are maintained and accessible in the RTLIL representation.
With the Verific API, we get the bounds information and create attributes (named `bottom_bound` and `top_bound`).
Those attributes are of the same bit width as the wire they belong to.
If at …
> verific: Add bottom and top bound properties to wire

- passes/techmap/Makefile.inc
- passes/techmap/clockgate.cc
- tests/techmap/clockgate.ys
According to several users, large power savings in ASICs can be achieved by centralizing clock gating per clock domain rather than routing CLK and EN into many FFs.
The new `clock_gate` command allows the user to specify a rising edge clock gating cell ("ICG") with `-pos` and a falling one with `-neg`. Within each selected module, flip flops driven with the same clock and enable signals of the same polarities are grouped. If this group has more flops than the threshold set by `-min_net_size N`, they are converted via `kernel/ff.h` to versions withouth clock enable, and corrsepondingly, clock gating cells are emitted to create one GCLK net per flop group. 
Since clock gates often have DFT ports, those are …
> clockgate: centralize clock enables out of FFs

- frontends/ast/ast.cc
- frontends/ast/simplify.cc
- frontends/verilog/verilog_parser.y
- tests/verilog/size_cast.sv
Added support for casting to type; e.g. 
assign a = int'(some_var);
assign b = my_type_def'(some_var);
> Added cast to type support

- .github/workflows/test-build.yml
To be able to load VCD files with `sim`, the executable `vcd2fst` has to be available in PATH.
While FST files can also be used for simulation, VCD files are human readable, which can be useful for issues like https://github.com/YosysHQ/yosys/pull/4620.
Instead of installing `gtkwave` from `apt`, which would bring too many dependencies into scope, we just compile all the helpers from `gtkwave` in a repo maintained by @mmicko.
Credit goes to @mmicko.
> Add "Get vcd2fst" step to test-yosys job

- .github/workflows/prepare-docs.yml
- Makefile
- docs/source/_images/Makefile
This should resolve issue #4631 when building the doc images in parallel.
I have removed the `tidy` target and I just delete log and aux file after building each pdf.
> docs: avoid concurrency issues when generating images in parallel

- kernel/driver.cc
This adds a Python equivalent to the `-c` option, where scripts importing `libyosys` can be used. 
Most of the requisite work for this was already done to enable Python passes a couple years back, so this is a relatively small changeset, and would add another option for supporting libyosys-based scripts (that does not involve PYTHONPATH shenanigans.)
Adding a new opt, `-y` (`-p` and `-P` were already taken,) and running `PyRun_SimpleFile` on `scriptfile`. Similar to `-c` for Tcl, any unprocessed arguments are passed to the script in the form of `sys.argv`.
```sh
./yosys -y <(echo "
import libyosys as ys
d = ys.Design() …
```
> -y flag for libyosys Python scripts

- techlibs/common/techmap.v
- techlibs/quicklogic/synth_quicklogic.cc
- tests/arch/quicklogic/qlf_k6n10f/div.ys
The default mapping rules for division-like operations (div/divfloor/ mod/modfloor) invoke subtractions which can get mapped to carry chains in FPGA flows. Optimizations across carry chains are weak, so in practice this ends up too costly compared to implementing the division purely in soft logic.
For this reason arrange for `techmap.v` ignoring division operations under `-D NODIV`, and use this mode in `synth_quicklogic` to avoid carry chains for divisions.
> quicklogic: Avoid carry chains in division mapping

- frontends/liberty/liberty.cc
- tests/liberty/.gitignore
- tests/liberty/run-test.sh
- tests/liberty/unit_delay.ys
Avoiding timing path segmentation on explicitly instantiated or pre-mapped standard cells. When the SC mapper is configured for the unit delay model, with this new option we can supply complementary arcs for those cells which are viewed as boxes
Under each cell and pin, we look at `timing()` sections with `timing_type` set to `combinational`, and for each arc found, we emit a `$specify2` cell with fixed delay of 1000 which matches the unit delay inside ABC.
> read_liberty: Optionally import unit delay arcs

- kernel/log.cc
- tests/various/logger_cmd_error.sh
Some errors can get hidden by `-v N`, see The-OpenROAD-Project/OpenROAD-flow-scripts#2375
This makes the user almost always worse off. The only exception I can think of is someone scripting around Yosys commands, checking for their exit status, and handling failures gracefully (for the few failure modes where that can be done). I've never seen such a Yosys script.
Add extra handling to arrange for `log_cmd_error` never being silenced by the command line `-v N` option. Similar path for `log_error` exists already.
With test.tcl:
```
yosys -import
hierarchy -top nonexistent
```
Before
```
$ ./yosys -v 3 test.tcl
1. Executing HIERARCHY …
```
> log: Never silence `log_cmd_error`

- passes/techmap/bufnorm.cc
An unimplemented mode for bufnorm is advertised since it's intended to turn off a feature that doesn't exist exist. This PR avoids the unused variable warning by commenting out the arg parsing and corresponding log string section. This pass is marked experimental and therefore free to change interface without breakage concerns
> bufnorm: avoid warning. NFC

- backends/smt2/smtbmc.py
This escapes segments of cell paths that contain `.` with verilog style `\na.me `, as well as making the printing format more consistent in the case of cover properties to allow easier parsing on the SBY side. As this changes the smtbmc text output that SBY parses it has a corresponding SBY change to be merged at the same time.
> smtbmc: escape path identifiers

- .github/actions/setup-build-env/action.yml
CI broken after LLVM bew package update.
LLVM package does not include lld anymore but it is separate package so it needs to be installed explicitly.
> Fix CI by adding lld as brew package

- .github/actions/setup-build-env/action.yml
brew formulas are better updated otherwise it depend of runner if new packages (like in case  of lld) or new versions would be detected.
> CI: force brew formula update

- tests/cxxrtl/test_value.cc
Through fast and loose regex action in #4516 I broke the stream operator for `cxxrtl::value` but the tests didn't discover this. This PR addresses that
> cxxrtl: test stream operator

- .github/workflows/wheels.yml
- Makefile
- kernel/yosys.cc
- misc/__init__.py
- setup.py
- tests/arch/ecp5/add_sub.py
Due to an oversight on my part, #4534 does not copy either `yosys-abc` or the `share` directory. While Yosys technically still runs, it is unusable for anything non-trivial.
* `misc/__init__.py`:
* checks if there's a `yosys-abc` in the same directory - if yes, sets the variable `sys._pyosys_abc`
* checks if there's a `share` in the same directory - if yes, sets the variable `sys._pyosys_share_dirname`
* `yosys.cc::init_share_dirname`: check for `sys._pyosys_share_dirname` at the highest priority if Python is enabled
* `yosys.cc::init_abc_executable_name`: check for `sys._pyosys_abc`, use it at at the highest priority if Python is enabled
* `Makefile`: add new target, `share`, to only create the extra …
> wheels: fix missing yosys-abc/share directory

- passes/techmap/cellmatch.cc
Under an undocumented `-lut_attrs` option the `cellmatch` command can annotate output ports with a `lut` attribute describing the port's function. Previously these attributes were 32-bit, which meant the value for 6-input cells was cropped, and one needed knowledge of the number of inputs to interpret the value. Make the change to size the `lut` attribute to two to the power of number of inputs.
> cellmatch: Size the `lut` attribute

- .gitmodules
- kernel/driver.cc
Implements #4580.
In this PR I'm adding the [cxxopts](https://github.com/jarro2783/cxxopts) header-only library as a submodule. This allows me to introduce long option aliases such as `--quiet` for `-q`. Since `-B` was undocummented and is assumed not broadly used, I'm replacing it with `--perffile`. Behaviour of `--` is retained as implemented in #3973. The behavior of `yosys -help` being special cased not to be equivalent to `yosys -h -e -l -p` is also retained. Help string indentation isn't retained since we're letting cxxopts generate it. Argument names like `logfile` are converted for consistency into `<logfile>` which is then used as is broadly the POSIX/GNU convention. Long options don't have to match the first letter of the short option if it's more logical that way, for example, …
> driver: replace getopt with cxxopts, replace -B, clean up help

- backends/cxxrtl/runtime/cxxrtl/cxxrtl_vcd.h
The vcd writer incorrectly treated two scope vectors as the same, whenever they have the same length of entries and the last item matches. This is however not always true, for example consider a current_scope of ["top", "something0", "other_i"] and a scope of ["top", "something1", "other_i"] as one might obtain from the following verilog file:
```verilog
module other2();
wire w_inner;
endmodule
module other();
other2 other_i();
endmodule
module top();
other something0();
other something1();
endmodule
```
The old code emitted a vcd of 
```
$scope module top $end
$scope module something0 $end
$scope module other_i $end
$var wire 1 ! w_inner $end
$var wire 1 " w_inner $end
$upscope $end
$upscope $end
$upscope $end
$enddefinitions $end
#0
0!
0"
```
not changing the scope correctly for the two …
> cxxrtl: fix vcd writer scope handling

- backends/cxxrtl/runtime/cxxrtl/cxxrtl_vcd.h
Before this commit, `vcd_writer.sample()` emits vector values for 0-bit variables.
For example, the following RTLIL:
```
module \top
wire width 0 \foo
end
```
would result in the following VCD:
```
$timescale 1 us $end
$var wire 0 ! foo $end
$enddefinitions $end
#0
b !
```
However, according to IEEE 1364-2001, the syntax for vector values is:
After this commit, `foo` is no longer sampled in the VCD:
```
$timescale 1 us $end
$var wire 0 ! foo $end
$enddefinitions $end
#0
```
> cxxrtl: fix handling of 0-bit variables in `vcd_writer.sample()`.

- kernel/rtlil.cc
- kernel/rtlil.h
If one has a Sigspec that is fully constant it is currently non-trivial to get its value.  
The main blocking point here is that the SigSpec may be wider than 32bit (an integer).  
However, this doesn't mean the value stored in it is necessarily this large/small.
Eg something like `33'd4` or `33'd-2` cannot be easily converted to an int.
This adds a `compress(is_signed)` function.  
It tries to minimize the number of bits used for the representation of the number. 
It does so by removing the leading bits while taking signedness into consideration.
With this function, the above can be successfully converted to an integer by first calling compress.
Edit:
Here is a possible application.
https://github.com/povik/yosys-slang/blob/28cea56840a6bc8a4b6398d36609500d5960ad79/src/builder.cc#L134 …
> rtlil: add Const::compress helper function

- frontends/verific/verific.cc
If we have assert that is inside VHLD process, it fails since condition signal is coming from uninitialized FF. 
Please note that this primitive is VHDL only so it will not affect SVA code path.
Also there is left-over from past and there was never an "assume" attribute to convert this to assume.
```
assert (conv_integer(addr) >= sram'low and conv_integer(addr) <= sram'high) report "out of bounds for read" severity error;
rdata <= sram(conv_integer(addr));
process(clk)
begin
if clk'event and clk = '1' then
if wen = '1' then
assert (conv_integer(addr) >= sram'low and conv_integer(addr) <= sram'high) report "out of bounds for write" severity error;
sram(conv_integer(addr)) <= wdata;
end if;
end if;
end process;
```
_Explain how this is …
> Set VHDL assert condition initial state if fed by FF

- frontends/verilog/verilog_parser.y
`yynerrs` is an automatically emitted variable we have no use for. Ignoring warnings isn't in good taste and leads to overlooking more meaningful ones.
```
frontends/verilog/verilog_parser.tab.cc:3743:9: warning: variable 'frontend_verilog_yynerrs' set but not used [-Wunused-but-set-variable]
int yynerrs = 0;
^
frontends/verilog/verilog_parser.tab.cc:74:25: note: expanded from macro 'yynerrs'
#define yynerrs         frontend_verilog_yynerrs
^
```
In this PR I cast the variable to void at a reasonably top level rule in the parser. You can check the effect by observing there's no yynerrs warning when building this PR, but there is when building its parent commit
> verilog_parser: silence yynerrs warning

- .github/workflows/test-build.yml
- Makefile
- docs/Makefile
- docs/source/index.rst
- docs/source/using_yosys/synthesis/synth.rst
- kernel/register.cc
Fixes missing links in body and `??` in tag/command index.
Update synth.rst to match.
> Docs: Use formatted cmd ref in pdf

- .github/actions/setup-build-env/action.yml
macOS brew upgrade reports that it can not update links to python (3.12->3.13) but that it also returns error code even if it is not a critical issue. It is something that commonly occurred in the past on github runners, and got fixed when they updated the base image to be based on the same python major version.
It affects only macos-13 but we just ignore error code now that is coming from brew.
> CI: make CI continue even if brew objects

- kernel/rtlil.h
- misc/py_wrap_generator.py
Fixes #4670 by probably implementing nested class declaration. I don't really know what the wrapper generator does and I don't want to find out more than I already did. Also the DIY C++ parser doesn't like trailing commas in enum declarations so I removed it from `RTLIL::ConstFlags`.
> py_wrap: implement nested class definitions

- .github/workflows/source-vendor.yml
- .gitmodules
- README.md
We like submodules for SBOM reasons and prefer them over in-repo vendored libraries. However this creates a burden on users with needs for gitless workflows who have to take our (yosys) source tarball, drop in our other (yosys-abc) source tarball, manually check submodules versions at the git tag, download those, and only then build yosys. An alternate solution is to add Makefile targets like curl-abc #4472 but that needs per-submodule work. This PR adds a workflow which on main commits creates a source tarball artifact including submodule sources
> actions: vendor sources with submodules for releases

- kernel/driver.cc
Fixes #4669. To test the python side this needs the changes from #4671 but even with that I get a segfault with `valgrind ./yosys -y foo` starting with this:
```
Invalid read of size 8
at 0x4D033A3: PyList_New.constprop.0 (in /nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/libpython3.11.so.1.0)
by 0x4CEB408: PyImport_Import (in /nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/libpython3.11.so.1.0)
by 0x4CEB6DF: PyImport_ImportModule (in /nix/store/sxr2igfkwhxbagri49b8krmcqz168sim-python3-3.11.8/lib/libpython3.11.so.1.0)
by 0xDA234D: Yosys::init_share_dirname() (kernel/yosys.cc:1017)
by 0xDA0DCF: Yosys::yosys_setup() (kernel/yosys.cc:550)
by 0xCC1FCC: main (kernel/driver.cc:497)
Address 0x10 is not stack'd, malloc'd or (recently) free'd
```
@donn any ideas?
> driver: fix special args passing to tcl and python

- misc/yosys-config.in
The '==' operator is non-standard and does not work with all versions of test(1) or sh(1).
The fix is simple: use the standard '=' operator instead.
Ensure yosys builds.
Resolves issue #4665.
> misc/yosys-config.in: don't use the non-portable '==' operator with test(1)

- passes/techmap/cellmatch.cc
- tests/select/mod-attribute.ys
- tests/techmap/cellmatch.ys
I found this (previously undocumented) command mode useful for identifying the nand2 gate in a library to do some rough instance count to/from area conversions.
> Document `cellmatch -derive_luts` option

- frontends/ast/ast.cc
* Fixes #4696 
Special cases zero width strings as `"\0"` as required by IEEE 1364-2005 5.2.3.3
> The null string ( "") shall be considered equivalent to the ASCII NUL ("\0"), which has a value zero (0),
which is different from a string "0".
> frontends/ast.cc: special-case zero width strings as "\0"

- kernel/fstdata.cc
- tests/sim/assume_x_first_step.ys
- tests/sim/simple_assign.v
- tests/sim/simple_assign.vcd
Handle cases where signal data is missing in FST files during simulation. Previously, when a signal ID was not found in past_data, it would cause an error. This patch ensures that missing signal data is assumed to be undefined ('x'), which aligns with the behaviour of `gtkwave`. Below is a screenshot of how `gtkwave` interprets `tests/sim/simple_assign.vcd`.
Instead of logging an error when the signal ID is not found, the `valueOf` now returns a string filled with 'x' characters, where the length of the string corresponds to the signal’s width.
I considered adding a warning like:
`log_warning("Signal id %d not found, assuming x\n", …
> Assume x values for missing signal data in FST

- passes/techmap/bufnorm.cc
- tests/techmap/bufnorm.ys
Fixes an issue where constant driving bits in connections would be replaced with `Sx` by bufnorm
> bufnorm: preserve constant bits driving wires

- Makefile
- libs/fst/00_PATCH_win_io.patch
- libs/fst/00_PATCH_win_zlib.patch
- libs/fst/00_UPDATE.sh
- libs/fst/fastlz.cc
- libs/fst/fst_win_unistd.h
- libs/fst/fstapi.cc
- libs/fst/fstapi.h
- libs/fst/lz4.cc
- libs/fst/lz4.h
https://github.com/YosysHQ/yosys/pull/4541#issuecomment-2293151370
i.e. why don't we track upstream fstapi
Add and run shell script (based on minisat lib) to clone and copy relevant files.
Need to check if there are any changes lost that we need to patch back in.
> libs/fst: Update from upstream

- libs/subcircuit/subcircuit.cc
Little cleanup as we're currently [using `free()`](https://github.com/YosysHQ/yosys/blob/2de9f0036833f782318a475d20dd982193bf2501/libs/subcircuit/subcircuit.cc#L51)  without declaration.
> Include cstdlib for free()

- Makefile
Prior to this change, some symbols would be missing from the yosys executable if built on macOS with LTO. This would break plugins on dlopen. By adding `-rdynamic` to the linker flags, we can export all symbols even if they're unused due to LTO-enabled inlining or otherwise. You can check the exported symbols by building yosys with LTO on macOS and running `objdump --macho --exports-trie yosys`.
> Makefile: add -rdynamic on macOS to fix plugins with LTO

- README.md
The current instructions suggest that ENABLE_LTO should be used, but the example usage doesn't work on MacOS. This PR adds an explicit provision for that
> readme: tell macOS users to use brew clang with LTO

- passes/pmgen/Makefile.inc
- passes/pmgen/peepopt.cc
- passes/pmgen/peepopt_formal_clockgateff.pmg
- passes/sat/clk2fflogic.cc
- tests/various/peepopt_formal.ys
Common clock gating patterns use a latch, which after `clk2fflogic` leaves a combinational path between the enable input and clock output. This can cause comb loops even though there is no true path due to an AND gate gating the output when the latch is transparent. This can be optimized into an equivalent circuit using a flip-flop that no longer has this comb path.
This optimization is suitable for formal to prevent false comb loops, but should not be used for synthesis where the latch is an intentional choice.
```verilog
// Latch style:
always @* if (!clk_i) latched_en = en;
assign gated_clk_o = latched_en & clk_i;
// Flip-flop style:
always @(posedge clk) flopped_en = en;
assign gated_clk_o = flopped_en & clk_i;
```
_Explain how this …
> peepopt: Add formal opt to rewrite latches to ffs in clock gates

- backends/btor/btor.cc
If all addresses of an array have the same initial value, they can be initialized in one go in btor with the constraint that the initial value must be fully const and thus can't have undef bits in. This constraint was not being checked before.
> write_btor: only initialize array with const value when it is fully def

- backends/smt2/smt2.cc
Fixes #3769.
The issue occured when exporting a bit that is driven through some connections by the output of a cell, but is known to be a constant. This happens with e.g. the following
```verilog
module top(input wire a, output wire b);
wire [1:0] inner = |a;
assign b = inner[1];
endmodule
```
where `b` is always `0`, but is driven by the `$reduce_or` cell.
The previous code would export the `$reduce_or` just for `inner[0]`. When exporting `b`, the `sigmap` would be unable to map `b` through to the constant value driving it, so would create a fresh `declare-fun` for it.
With this change, when exporting `b` we first ensure that if there is a cell driving `b` it has been mapped and apply the `sigmap`. This allows the subsequent code to see that `b` is constant, and thus emit `true`/`false` …
> write_smt2: Check for constant bool after fully resolving signal

- misc/py_wrap_generator.py
This adds support for `cells()`, `modules()` and `wires()` that all return ObjRanges, converting them into lists for python.
The C++ diff is slightly messy as this causes a load of generated variable indices to be shifted, but ignoring those changes you get the following
```diff
2572a2573,2578
> 		// WRAPPED from "RTLIL::ObjRange<RTLIL::Wire*> wires() { return RTLIL::ObjRange<RTLIL::Wire*>(&wires_, &refcount_wires_); }" in kernel/rtlil
> 		boost::python::list wires();
>
> 		// WRAPPED from "RTLIL::ObjRange<RTLIL::Cell*> cells() { return RTLIL::ObjRange<RTLIL::Cell*>(&cells_, &refcount_cells_); }" in kernel/rtlil
> 		boost::python::list cells();
>
4082a4089,4091
> 		// WRAPPED from "RTLIL::ObjRange<RTLIL::Module*> modules();" in kernel/rtlil
> 		boost::python::list modules();
> …
```
> pyosys: support ObjRange

- kernel/timinginfo.h
- passes/cmds/Makefile.inc
- passes/cmds/portarcs.cc
To preserve boundaries of arithmetic operators we need to synthesize them separately and box them for synthesis of the surrounding logic. We need to characterize the propagation delay of this box so the technology mapper is aware of it, this characterization step is where this new command comes in.
Help sample:
```
portarcs [options] [selection]
This command characterizes the combinational content of selected modules and
derives timing arcs going from module inputs to module outputs representing the
propagation delay of the module.
-draw
plot the computed delay table to the terminal
-icells
assign unit delay to gates from the internal Yosys cell library
-write
write the computed arcs back into the module as $specify2 instances
```
> portarcs: New command to derive propagation arcs

- passes/techmap/dfflibmap.cc
- passes/techmap/libparse.cc
- passes/techmap/libparse.h
`dfflibmap` can't map flops with enables, so yosys has to use muxes. By using flops that have enables, we can save area and possibly delay.
The `next_state` attribute of the `ff` block needs to be evaluated to see if it's an enable expression. This means a bunch of infrastructure related to parsing liberty expressions.
Run `dfflibmap -liberty foo.lib` on various liberty files you can find, and see if they a) parse without crashing and b) successfully detect the enable flops in the file.
_Still to do:_
- ~~a bunch of `log_warning`s are commented out because they are extremely noisy.~~ 
- ~~sky130 has some scan chain flops with the …
> dfflibmap: enable inference

- techlibs/gatemate/synth_gatemate.cc
This PR addresses an issue where multiplexers may remain unmapped, leading to their representation as simple assignments in the final netlist instead of as technology primitives.
By running `simplemap` after `muxcover`, we ensure proper mapping of multiplexers into technology primitives.
> synth_gatemate: Ensure proper mapping of multiplexers

- backends/verilog/verilog_backend.cc
`write_verilog` is incredibly slow for modules with lots of ports. We have some modules with thousands of ports and `write_verilog` can take hours to run. Related to issue #3845 perhaps.
This is because port dumping is `O(N^2)` runtime, where `N` is the number of ports in the design. This poor runtime behavior arises due to the nested `for` loop (see lines 2337-2349); each loop can iterate up to the number of ports in the design.
We reduce the runtime to `O(N)` by pre-building a `port_id` to `wire` vector, then using a single `for` loop.
Passes all tests.
> `write_verilog`: Fix `O(N^2)` port dumping to `O(N)`

- Makefile
There are three issues with `editline` in the Makefile:
1. It includes `libbsd` and `ncurses` libraries, which are no longer needed
2. It needs `ENABLE_READLINE := 1` in the Makefile to do anything
3. It does not properly set `ABC_USE_NO_READLINE=1`, so `readline` still gets used for `abc`
Fully decouple `editline` from `readline` in the Makefile and reduce `LIBS` flags down to just `-ledit`
Test on a machine/container/VM with `editline` installed but no `readline`. Run `make ENABLE_READLINE=0 ENABLE_EDITLINE=1` before and after the change
> Fix `editline` Makefile

- kernel/rtlil.cc
- tests/memories/nordports.ys
There's a mismatch between what `kernel/mem.cc` emits for memories with no read ports and what the internal RTLIL check expects.
The point of dispute it whether some of the parameters relating to read ports have a zero-width value in this case. The `mem.cc` code says no, the internal checker says yes.
Surveying the other `$mem_v2` parameters, and internal cell parameters in general, I am inclined to side with the `mem.cc` code.
This breaks RTLIL compatibility but for an obscure edge case.
> rtlil: Adjust internal check for `$mem_v2` cells

- README.md
- docs/source/code_examples/fifo/fifo.v
- docs/source/getting_started/example_synth.rst
- docs/source/introduction.rst
Users are often confused and/or surprised when the `read_verilog` frontend runs into syntactical edge cases that it doesn't handle well.
Mention Verilator (and `verilator --lint-only`) in a few places and reiterate that `read_verilog` does not lint, and you should lint your code before trying to use it.
Preview available on [readthedocs](https://yosyshq.readthedocs.io/projects/yosys/en/docs-preview-lintonly/introduction.html#things-you-can-t-do).  Note that preview builds show todos, which are normally hidden.
> Emphasise that read_verilog doesn't lint

- backends/json/json.cc
there is already codes of select_module, but the write_json cmd don't receive the option.
now we can use the cmd like this:
```
select -module top;
write_json -selected xxx.json
```
> add select option for write_json

- passes/proc/proc_dff.cc
- tests/proc/bug4712.ys
Fixes #4712 which is a bug introduced in #4569, where multiple rules in processes were not being considered if an asynchronous one was encountered as the code erroneously returned from the function instead of continuing the processing loop.
> proc_dff: fix early return bug

- passes/opt/opt_reduce.cc
- tests/opt/opt_reduce_andor.ys
When all inputs to a `$reduce_or` (resp. `$reduce_and`) are `0` (resp `1`), `opt_reduce` would remove them all leaving a zero width input to the cell. This can sometimes be poorly handled by other passes as in #4610, so this PR checks for that case and drives the cell by a constant.
I haven't chosen to fully replace the cell as the logic in that function would turn e.g. `|{a, 1'b1, 1'b0}` into `|{1'b1}` rather than `1'b1`, so this is in keeping for the `1'b0` case. `opt_expr` easily eliminates this cell due to the constant input.
> opt_reduce: keep at least one input to $reduce_or/and cells

- passes/opt/opt_demorgan.cc
- tests/opt/bug4610.ys
> opt_demorgan: skip zero width cells

- misc/py_wrap_generator.py
This allows `log_error`, `log_file_error` and `log_cmd_error` which are all marked `[[noreturn]]` to be wrapped.
The corresponding diff to the generated c++ is
```diff
12653a12654,12671
> 	// WRAPPED from "[[noreturn]] void log_error(const char_p format, ...) YS_ATTRIBUTE(format(printf, 1, 2));" in kernel/log
> 	void log_error(const char * format)
> 	{
> 		::YOSYS_NAMESPACE::log_error("%s", format);
> 	}
> 
> 	// WRAPPED from "[[noreturn]] void log_file_error(const string &filename, int lineno, const char_p format, ...) YS_ATTRIBUTE(format(printf, 3, 4));" in kernel/log
> 	void log_file_error(const string filename, int lineno, const char * format)
> 	{
> 		::YOSYS_NAMESPACE::log_file_error(filename, lineno, "%s", format);
> 	}
> 
> 	// WRAPPED from "[[noreturn]] void log_cmd_error(const …
```
> pyosys generator: ignore attributes

- passes/pmgen/peepopt_shiftadd.pmg
This addresses issue #4445. There are two issues from that, one being that casting a constant of arbitrary size to an `int` can overflow, and the other being that the `shiftadd` peephole optimization creates logic that can be very large for large shift constants.
This is a simple fix to both that just disables the optimization for constants over a certain bitwidth. I have arbitrarily chosen 24 bits here but am happy to change that or discuss a more fine-grained solution than just disabling the optimization. I suspect most user code will not have offsets outside of this range.
> peepopt shiftadd: Only match for sufficiently small constant widths

- tests/opt/bug4610.ys
#4612 was written before read_ilang was deprecated but merged after so caused test failures. This switches read_ilang to read_rtlil in its testcase.
> tests: replace read_ilang with read_rtlil

- passes/techmap/clockgate.cc
- tests/techmap/clockgate.lib
- tests/techmap/clockgate.ys
Integrated clock gating cells (ICGs) are ASIC cells designed as part of PDKs and they are described in Liberty files. To avoid requiring per-PDK hacks to PDK-agnostic scripts, instead of requiring in the invocation a specification of a concrete ICG cell name and its interface, this PR allows the user to use `-liberty <filename>` argument for the `clockgate` command and automatically selects the most suitable ICGs described in `<filename>`. A suitable cell is one with matching clock polarity, a reasonable interface based on the [Liberty Reference Manual](https://people.eecs.berkeley.edu/~alanmi/publications/other/liberty07_03.pdf) (refer to pin attributes `clock_gate_...` and cell attribute `clock_gating_integrated_cell`). Most suitable cells are those with the fewest scan/test inputs to …
> clockgate: add -liberty

- misc/py_wrap_generator.py
This catches exceptions from internal passes, printing them in a readable manner where the user would otherwise see an unspecified boost exception.
e.g. consider the following pass in `pass.py`:
```python
import libyosys as ys
class MyPass(ys.Pass):
def __init__(self):
super().__init__("my_pass", "")
def py_help(self):
raise Exception("broken")
p = MyPass()
```
Previously, when invoked with `yosys -m pass.py -p "help my_pass"`, yosys would error with
```
-- Running command `help my_pass' --
terminate called after throwing an instance of 'boost::python::error_already_set'
```
but with this change it instead shows
```
-- Running command `help my_pass' --
Traceback (most recent call last):
File "<...>/pass.py", line 8, in py_help
raise Exception("broken")
Exception: broken
ERROR: Python …
```
> pyosys: catch boost::python::error_already_set

- frontends/verific/verific.cc
Recognizing DFF excusively used by assert is not that easy since it can be optimized in various ways by Verific itself.
Initial value of DFF is set in our own Verific patch.
> verific : VHDL assert DFF initial value set on Verific library patch

- frontends/verific/verific.cc
- tests/verific/blackbox.ys
Due to a change to Verific, "veri_create_empty_box" parameter needs to be set to get blackboxes import correctly after static and full elaboration.
Added test case to make sure blackboxes are imported.
> verific: fix blackbox regression and add test case

- .github/workflows/test-compile.yml
The 'newest' compilers are actually not all that new, they're just the default for the image.
Explicitly use clang-18 and gcc-13 as the 'newest' versions.
> test-compile: Use newer clang and gcc versions

- docs/source/appendix/rtlil_text.rst
- frontends/rtlil/rtlil_frontend.cc
- frontends/rtlil/rtlil_frontend.h
- frontends/rtlil/rtlil_parser.y
Previously `read_rtlil` would allow `assign` and `switch` rules to be freely mixed in RTLIL case rules, but internally yosys stores the two in two separate vectors and treats assigns as if they came before switches. This change modifies the parser to ~~reject~~ (edit: changed to emit a warning instead) RTLIL that doesn't obey this and updates the docs. `write_rtlil` will only write RTLIL obeying this property.
~~The `case_body` rule is split into two parts, firstly assignments and then switches.~~ edit: A warning is run in the assign rule if the current level already has switches assigned.
The `read_rtlil` commands in the test suite …
> read_rtlil: Warn on assigns after switches in case rules

- passes/hierarchy/hierarchy.cc
As suggested in https://github.com/YosysHQ/yosys/issues/3717#issuecomment-2460672212, make it more obvious to the user if the top module was selected due to an attribute overriding the heuristic.
Print a log message. If multiple modules are marked `(* top *)`, the message gets repeated multiple times, matching how the code works (the last attribute encountered while iterating over `design->modules()` overrides any previously seen attributes).
> Print a note about finding attribute (* top *) in hierarchy

- kernel/drivertools.h
Initialize "unsigned int inner" in hash() functions
Includes a log_assert() that might help catch corrupted data structures or future incomplete modification of DriveType definition
See Issue #4713, Reduce compiler warnings when building yosys
> kernel/drivertools.h: avoid maybe-uninitialized compile warnings

- kernel/rtlil.h
`ID::blackbox` and `ID::whitebox` attributes never appear to be set on anything except modules, and the `get_blackbox_attribute()` method appears to only be called on a `Module`.
Mark `AttrObject::get_blackbox_attribute()` deprecated and add `Module::get_blackbox_attribute()` to replace it.
> Move get_blackbox_attribute method to Module instead of AttrObject

- docs/source/conf.py
#4725 
Call e.g. `YOSYS_DOCS_RELEASE= make docs` from the top directory and check there are no todos in the output.
> Improvements for downstream-distro maintainability.

- techlibs/common/choices/han-carlson.v
This was left out by copy pasting mistake. Removes the necessity for `-autoproc` and makes it consistent with Kogge-Stone
> techlibs: add _TECHMAP_DO_ to Han-Carlson adder

- passes/techmap/dfflibmap.cc
In #4698 @povik mentioned that the new - but otherwise harmless - warnings can be quite noisy on some PDKs, and since ASIC flows are sensitive to warning count, this can cause breakage.
The new warnings are demoted to `log_debug`.
> dfflibmap: demote some warnings to debug

- README.md
- passes/hierarchy/keep_hierarchy.cc
- tests/various/keep_hierarchy.ys
This makes two changes to `keep_hierarchy -min_cost` to make it better suited to the task of partially preserving hierarchy for macro placement:
* Don't count cost from submodules marked with `keep_hierarchy` towards the upper module's cost.
* Accept a `gate_cost_equivalent` attribute as a way of specifying cost on blackboxes.
> Adjust `keep_hierarchy` behavior

- tests/arch/common/blockrom.v
Prior to this PR, `integer j` had two drivers: a constant, and the result of the xorshift chain. This can be verified by replacing the contents of `tests/arch/ice40/memories.ys` with the following pass sequence. The driver conflict created a loop which later somehow would get resolved, but it killed `opt_expr` topological ordering and inflated `make test` runtime. This PR reduces the duration of `make test -j24` on my machine by a factor of >2.5.
```
design -reset; read_verilog -defer ../common/blockrom.v
chparam -set ADDRESS_WIDTH 2 -set DATA_WIDTH 2 sync_rom
hierarchy -top sync_rom
proc -noopt
check
```
> tests: fix blockrom.v driver conflict

- passes/techmap/techmap.cc
Preserving operator boundaries requires leaving some cells unmapped at first. That can be accomplished by commenting out the relevant section of the mapping rule file, but an explicit argument to `techmap` is a more elegant solution.
> techmap: Add `-dont_map` for selective disabling of rules

- passes/techmap/clockgate.cc
- passes/techmap/dfflibmap.cc
- passes/techmap/libparse.cc
- passes/techmap/libparse.h
- tests/techmap/clockgate.ys
- tests/techmap/clockgate_neg.lib
- tests/techmap/clockgate_pos.lib
- tests/techmap/dfflibmap.ys
- tests/techmap/dfflibmap_dffn.lib
- tests/techmap/dfflibmap_dffsr.lib
`dfflibmap` and `clockgate` are the only passes which accept a `-liberty` flag but only once. This requires workarounds for PDKs like asap7 which come in multiple files sharing the same "header" (that is, anything but cells) and having distinct sets of cells. The other commands accepting any number of `-liberty` arguments are the abc commands and `stat`. `read_liberty` is a frontend and therefore fixed to one file per invocation.
In this PR, I'm extending libparse with `LibertyMergedCells` which steals `LibertyAst*` out of `LibertyParser`s before the AST is destroyed when `~LibertyAst` is executed. I'm extending tests for both affected commands to cover this functionality. There's a nice extra benefit of deduplicating some sanity checks from passes into `LibertyMergedCells`.
> Allow multiple -liberty args in dfflibmap and clockgate

- kernel/macc.h
- passes/techmap/booth.cc
- tests/techmap/booth.ys
As it stands `booth` ignores `$macc` cells, which means one cannot sequence `booth` after `alumacc`. Make the change to `booth` to handle at least the basic `$macc` cells which represent a simple product. The more advanced case in which `$macc` is a combined multiply-accumulate operation is left for later to be dealt with
> booth: Map simple `$macc` instances too

- passes/cmds/Makefile.inc
- passes/cmds/wrapcell.cc
- tests/various/wrapcell.ys
Preserving arithmetic operator boundaries upto a backend tool requires putting them into a module of their own. This module must not be parametric, and should be given a human-readable name (so not the `$paramod$...` naming used by Yosys internally).
Combinations of `techmap -extern`, `box_derive`, `chtype` can be used for this but the sequencing grows awkward and requires custom techmap files.
A new command let's you wrap selected internal cells into individual modules, with the name generated from a template by filling in parameter values.
E.g.
```
wrapcell -name MUL_{A_WIDTH}_{B_WIDTH}_{Y_WIDTH} t:$mul  # ignores signedness
```
> wrapcell: Add new command

- kernel/driver.cc
[autoidx](https://yosyshq.readthedocs.io/projects/yosys/en/latest/appendix/rtlil_text.html#autoindex-statements) is an arbitrarily incrementing integer used to create unique names. We're suspicious it's another source of unimportant changes that introduce false regressions and should be randomized in testing quality of synthesis results. I'm adding an `--autoidx=<n>` option in the developer section of the help string to set its initial value to `<n>` on yosys startup.
> driver: add --autoidx

- backends/aiger2/aiger.cc
- backends/edif/edif.cc
- frontends/aiger2/xaiger.cc
- frontends/ast/ast.cc
- frontends/ast/genrtlil.cc
- frontends/ast/simplify.cc
- kernel/calc.cc
- kernel/rtlil.cc
- kernel/rtlil.h
- passes/fsm/fsm_map.cc
- techlibs/quicklogic/ql_dsp_simd.cc
There are a number of easy to fix warnings:
1.  `comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]` 
1. `Const::size()` returns int, so change iterators that use it to `auto` instead of `size_t`. For cases where size is being explicitly cast to `int`, use the wrapper that we already have instead: `Yosys::GetSize()`.
Check what/if any warnings still show up at the bottom of the "Files changed" tab and in the "Compiler testing" section of the checks
> Reduce number of warnings

- kernel/mem.cc
- libs/fst/00_PATCH_win_io.patch
- libs/fst/fstapi.cc
Cygwin builds currently fail with two errors, one due to an overzealous compatibility check in libs/fst; the other in kernel/mem.cc due to redefining `addr_t` which is a system type.
Drop `__CYGWIN__` from the mmap compatibility check in libs/fst.
Remove the `addr_t` redefinition, instead using `MemContents::addr_t` where needed.
> Fix Cygwin compatibility

- kernel/scopeinfo.h
Allow `Cursor` to be stored in a `dict`.
> add hash method to scopeindex cursor

- passes/cmds/Makefile.inc
- passes/cmds/setenv.cc
- tests/verific/setenv.flist
- tests/verific/setenv.ys
File lists (a verific feature) will often make use of environment variables in file paths, e.g. [this example from the CV32E40P core](https://github.com/openhwgroup/cv32e40p/blob/master/cv32e40p_manifest.flist). This provides a way to set these variables from within a yosys script.
Add a `setenv` command that simply passes its arguments to the `setenv()` POSIX function.
There's a testcase included that can be used with verific.
In the absence of verific, it's possible to use this to set any other environment variable that yosys checks (although there aren't too many - you can change HOME or PATH and see what mayhem you can cause...) …
> add setenv pass

- tests/techmap/dfflibmap-sim.v
- tests/techmap/dfflibmap.lib
- tests/techmap/dfflibmap.ys
Expands test for basic #4698 coverage
> dfflibmap: cover enable inference with test

- frontends/liberty/liberty.cc
Make two changes which make it easier to use boxes loaded in by `read_liberty` for abc9 boxes: Attach the `simple_comb_cell` attribute on box definitions which are purely combinational and have simple input/output pins. Also redo the `-unit_delay` mode to: avoid reading the `timing_type` attribute (which is optional) and avoid needing to deal with arcs from an output pin to an output pin.
> read_liberty: Revisit for abc9 whiteboxes

- backends/aiger2/aiger.cc
- frontends/aiger2/xaiger.cc
- passes/techmap/abc9_ops.cc
- passes/techmap/abc_new.cc
To preserve boundaries of arithmetic operators, we want to isolate them into a new module which will become part of the design hierarchy. Ordinarily this would mean segmenting the timing paths for the technology mapper within ABC, but with new changes to `abc_new` we support having those be abc9 boxes with their propagation arcs described to the mapper.
Internally this calls the new `portarcs` command (PR #4736) once the module to be boxed has been technology-mapped.
In addition this PR allows applying different ABC scripts per module.
> Support `abc9_box` on ordinary modules in abc_new

- passes/techmap/abc9_ops.cc
`abc9_ops -prep_box` manipulates the relevant attributes (`abc9_box` and `abc9_box_id`) in a way which prohibits repeated invocation of the command unless the design is reloaded. Adjust it.
Repeated invocation is required for the feature #4737. The `abc9` script which only calls the command once should be unaffected.
> Adjust `abc9_ops -prep_box` to allow repeated invocation

- backends/verilog/verilog_backend.cc
In the expr mode use `assign Y = A;` to export a `$buf` cell instead of falling back to an explicit instantiation of an internal cell type (which is a bug in the expr mode)
> write_verilog: Use assign for `$buf`

- passes/cmds/wrapcell.cc
- tests/various/wrapcell.ys
Provide the option for `wrapcell` to generate wrapper modules with unused ports removed. In the motivating use case for this command which is preserving arithmetic operator boundaries this helps with QoR.
> wrapcell: Optionally track unused outputs

- frontends/verific/verific.cc
- frontends/verific/verific.h
- tests/verific/bounds.sv
- tests/verific/bounds.vhd
- tests/verific/bounds.ys
Fixes two issues:
1. Erroneous `top_bound`/`bottom_bound` attributes appear on SystemVerilog wires
2. `top_bound`/`bottom_bound` attributes are the wrong size on VHDL null ranges, and the value of the bounds may be truncated. It's not possible to tell the size of the wire from the `type_range` object in these cases.
1. Only run on nets coming from VHDL
2. Pass in an optional width hint that `import_attributes` can use to determine the size of the bounds.
Expanded tests for many port types are included.
> Verific frontend: fix `top_bound`/`bottom_bound` attributes

- Makefile
This is removing MXE and Cygwin (Windows builds) and AFL ( gcc wrapper for American Fuzzy Lop ), users for last two should use standard gcc target instead.
> Unsupported targets removal

- Makefile
- tests/arch/anlogic/run-test.sh
- tests/arch/ecp5/run-test.sh
- tests/arch/efinix/run-test.sh
- tests/arch/gatemate/run-test.sh
- tests/arch/gowin/run-test.sh
- tests/arch/ice40/run-test.sh
- tests/arch/intel_alm/run-test.sh
- tests/arch/machxo2/run-test.sh
- tests/arch/microchip/run-test.sh
- tests/arch/nanoxplore/run-test.sh
- tests/arch/nexus/run-test.sh
- tests/arch/quicklogic/pp3/run-test.sh
- tests/arch/quicklogic/qlf_k6n10f/run-test.sh
- tests/arch/xilinx/run-test.sh
- tests/gen-tests-makefile.sh
- tests/opt/run-test.sh
- tests/sat/run-test.sh
- tests/sim/run-test.sh
- tests/svtypes/run-test.sh
- tests/techmap/run-test.sh
- tests/various/run-test.sh
- tests/verific/run-test.sh
- tests/verilog/run-test.sh
This PR uses some simple GNU Make trickery to actually run tests in parallel with the correct number of jobs. On my 24-thread zen 4 machine this results in another 2.9x speedup. To test, grep for `""...passed tests in"` and compare with the list of test directories prior to this PR. Feel free to watch CPU usage and counts of yosys and other processes spawned by `make test` (ld.lld, vvp etc)
> test: every test everywhere all at once

- kernel/yw.h
`IdPath` is an `std::vector<IdString>` with extra methods and should be hashed as `std::vector<IdString>`. That was the intention behind this implementation but it ended up creating unintential recursion
> yw: fix unintensional recursion in hash_into

- kernel/yosys_common.h
See [here](https://stackoverflow.com/a/37195204/8048373)
> yosys_common: fix gcc warning in #error directive

- passes/opt/wreduce.cc
- tests/various/wreduce2.ys
See the attached test case. It can happen the RTL designer has written an explicit sign extension combined with an unsigned operation. Previously this would make `wreduce` unable to reduce the size of operands.
We detect conditions under which the signedness of the operands is arbitrary (because the input operands are fully sized wrt to the output and the operation is one of addition, subtraction, multiplication). Under these conditions estimate the size of the reduced operator if we make the operands signed or unsigned, and then flip the signedness accordingly before the usual operand reduction of `wreduce` takes place.
> wreduce: Optimize signedness when possible

- docs/source/index.rst
It's been almost a year since the restructure, so it's not recent anymore and doesn't need to link back to the old version.
Remove the note (and associated links).
[Preview build](https://yosyshq.readthedocs.io/projects/yosys/en/docs-preview-norestructure/) (note the TODOs don't appear in release builds).
> Docs: Remove restructure note

- Makefile
- kernel/consteval.h
- kernel/macc.h
- kernel/satgen.cc
- passes/opt/share.cc
- passes/techmap/alumacc.cc
- passes/techmap/maccmap.cc
- passes/tests/test_cell.cc
- tests/alumacc/macc_b_port_compat.ys
- tests/alumacc/run-test.sh
The B port is for single-bit summands. These can just as well be represented as an additional summand on the A port (which supports summands of arbitrary width). An upcoming `$macc_v2` cell won't be special-casing single-bit summands in any way.
In preparation, make the following changes:
* remove the `bit_ports` field from the `Macc` helper (instead add any single-bit summands to `ports` next to other summands)
* leave `B` empty on cells emitted from `Macc::to_cell`
An included test makes sure we interpret the B port on existing RTLIL exports.
> macc: Stop using the B port

- backends/json/json.cc
- tests/various/json_scopeinfo.ys
Linty want to use the JSON output to build interactive netlist visualization, including of flattened designs. The information carried by `$scopeinfo` cells is valuable for that purpose.
Add an argument to override the logic that currently skips `$scopeinfo`.
Testcase included
> write_json: add option to include $scopeinfo cells

- passes/hierarchy/keep_hierarchy.cc
Removes two warnings from the compile, at least on amd64 arch
> keep_hierarchy.cc: use strictly correct syntax for printf of uint64_t values

- passes/techmap/flatten.cc
Enables elaborated instance name parity with the default behavior of a commercial synthesis tool.
New option in `flatten` for a custom block separator string.
flatten -separator /
> Add option for a custom flatten block separator char

- libs/json11/json11.cpp
Explicitly include <cstdint> in libs/json11/json11.cpp, to avoid:
"error: ‘uint8_t’ does not name a type"
compile errors when building against TCL 9.0
(https://bugzilla.redhat.com/show_bug.cgi?id=2337817)
> Fix undefined type error

- frontends/verific/verific.cc
- kernel/scopeinfo.h
- passes/fsm/fsm_extract.cc
Supersedes #4842: There are currently too many cases that don't respect this invariant, so defer the enforcement for now.
For the next release, just fix the cases already identified. In the case of an object with a private name and an `hdlname` attribute, allow `parse_hdlname()`/`parse_scopename()` to act as if it was a corresponding scopename attribute (ignoring the final entry). The behaviour should be unchanged for other cases.
> handle some cases of hdlname attribute on private objects

- .github/actions/setup-build-env/action.yml
- .github/workflows/test-compile.yml
ubuntu-latest is now 24.04 instead of 22.04 and broke some things:
- test-compile for {os: ubuntu-latest, compiler: clang-14} failing cpp setup
- test-build for {os: ubuntu-latest} missing bzlib.h
Change clang-14 to clang-10 as oldest supported under ubuntu-latest (somehow clang-10 is now working under latest but clang-11 through clang-16 are not).
Also update newest clang to -19.
apt-get libbz2-dev.
> Update workflow(s) for ubuntu-latest == ubuntu-24.04

- docs/source/conf.py
For some reason the automatic detection for read the docs github repository information is missing.
We can manually assign the values needed to get the links to work.
The [preview build](https://yosyshq.readthedocs.io/projects/yosys/en/docs-preview-git_links/) for this pr should have working view source and edit source buttons at the top of each page, as well as footer icons linking to the readthedocs project and the git repository.
> Fix links for view/edit source

- passes/techmap/flatten.cc
- techlibs/common/synth.cc
Closes https://github.com/YosysHQ/yosys/issues/4843
Since https://github.com/YosysHQ/yosys/pull/4839 added this flag to flatten, this change allows for the user to specify this for the synth command.
```
scratchpad -set flatten.separator "/"
synth -flatten
write_verilog test.v
```
> add support for passing flatten -separator to flatten in synth

- docs/source/yosys_internals/hashing.rst
- kernel/hashlib.h
- kernel/rtlil.h
When writing #4524 I made it so that a type can have an implementation for how to hash a single instance (`hash_top_ops`) distinct from one for how to hash an instance in the context of an on-going context (`hash_ops`). This PR implements @povik's idea to merge them together so that plugin code can still explicitly pass `hash_ptr_ops` into associative data structures like `dict`.
> hashlib: merge hash_ops with hash_top_ops for plugin compat

- backends/verilog/verilog_backend.cc
Right now `assert`/`assume`/`cover` cell labels get parsed as the cell name of the `$check` cell, but the verilog backend does not use that information again. 
This now emits public names again as labels in the verilog backend.
Running the following script:
```
read -sv -formal <<EOF
module test();
always test : assert(1);
endmodule
EOF
prep -top test
write_verilog
```
used to result in 
```sv
(* keep =  1  *)
(* hdlname = "test" *)
(* top =  1  *)
(* src = "<<EOF:1.1-3.10" *)
module test();
(* src = "<<EOF:2.9-2.25" *)
wire test_EN;
always @*
if (1'h1) begin
assert (1'h1);
end
assign test_EN = 1'h1;
endmodule
```
and with this change results in 
```sv
(* keep =  1  *)
(* hdlname = "test" *)
(* top =  1  *)
(* src = "<<EOF:1.1-3.10" *)
module test();
(* src = "<<EOF:2.9-2.25" *)
wire …
```
> write_verilog: emit $check cell names as labels

- passes/opt/wreduce.cc
In #4524 I found the `IdString::in(pool<IdString>)` to be redundant and being annoying about the ordering of definitions or something and deprecated it. This PR replaces the pattern creating a warning, which was generated due to parallel work on the aforementioned PR and #4819 with the usage `pool<IdString>::count(IdString)` as suggested in the comment above the deprecated method definitions
> wreduce: fix warning for deprecated IdString::in(pool<IdString>)

- frontends/ast/simplify.cc
- kernel/celledges.cc
#4845 (and https://github.com/YosysHQ/yosys/issues/4844#issuecomment-2589140999) reveal undefined behaviors in the Yosys code.  This PR aims to resolve them.
`b_width_capped` already exists for preventing arithmetic overflow, limiting the value of `b_width` to 30.  This just changes the left shifts to also use it. The caveat of incorrect results for extremely large values of `a_width` still applies, as does the improbability of that actually happening. This fixes #4844 (or at least, the floating point exception; the circuit still isn't valid but I think that's fine).
In the `nowrshmsk` handling, `log2(0)` returns -inf, which gives undefined behaviour when casting to an int.  So catch the case when the …
> Fixing undefined behaviours

- .github/workflows/test-build.yml
- libs/fst/00_PATCH_strict_alignment.patch
- libs/fst/00_UPDATE.sh
- libs/fst/fastlz.cc
Yosys includes some amount of buggy code that invokes undefined behavior, e.g. https://github.com/YosysHQ/yosys/issues/4844. This should be fixed and stay fixed.
By running the Undefined Behavior Sanitizer on each commit/PR. UBSan does not have false positives and has a slim impact on performance, so this is done unconditionally.
Add `SANITIZER = undefined` to your `Makefile.conf`, then run `make clean && make && UBSAN_OPTIONS=halt_on_error=1 make test`.
> CI: Sanitize for undefined behavior

- passes/techmap/alumacc.cc
`$lt` and related are sometimes inhibited from unifying with `$sub` as when `B < A`, then the `$sub` cell is unable to swap inputs, but `$lt` does. This resolves this problem by instead considering `sig_alu` as an unordered pair mapping.
Addendum:
`$add` and `$sub` might still be unable to unify with `share -aggressive` but changing the behavior [1] causes [2] to fail, so I'm keeping it to `cmp` only.
[1] https://github.com/YosysHQ/yosys/commit/ded586c0485484996ea85f3eb596321582631345#diff-f5a16f8ab735a667cabcdd605b428eeaa92f223f044ef01a91d52141d404633bL334-L336
[2] https://github.com/YosysHQ/yosys/blob/ded586c/tests/opt/opt_expr.ys#L27
> alumacc: alternative cmp unification implementation

- passes/techmap/extract_fa.cc
- tests/various/bug3879.ys
The `extract_fa` pass seems to have issues when an odd number of inputs are inverted, this is previously reported in https://github.com/YosysHQ/yosys/issues/3879 and https://github.com/YosysHQ/yosys/issues/4573.
_I think_ @eddiehung solved this in the `xor2`/`xnor2` case in https://github.com/YosysHQ/yosys/pull/1297, but the `xor3`/`xnor3` case lacks the equivalent logic. 
Similarly to how it is handled in the `xor2`/`xnor2` case, we invert the `xor3`/`xnor3` output if the `majority3` has an odd number of inverted inputs.
I have tried to make this break using @jix's test case from https://github.com/YosysHQ/yosys/pull/3882.
~I don't have much confidence in my understanding of this code, and I hope that some discussion here will help clarify some things for me.~ …
> extract_fa: Fix `xor3`/`xnor3` inversion bug

- passes/techmap/libparse.h
When the clocked_on expression contains an expression like: `D&!SE+SE&SI` the lexer segfaults when processing the SI pin because `find_first_of` returns `std::string::npos` causing the calls to `strsub` to throw an exception.
Check the return value and use the size of the string if those characters are not found.
I have a liberty file which was modified from one of the yosys testcases I can add, but I might need to guidance on how to integrate that as a test.
See attached (added the sdff cell for testing): [normal_scan_ff.zip](https://github.com/user-attachments/files/18594737/normal_scan_ff.zip)
> liberty expression lexer check if characters are found and use size if not for `pin()`

- Makefile
Every time when I run `make config-gcc` or `make clean` it would give an error of `docs/images` directory could not be found.
Remove Makefile call to `docs/images clean` from top level makefile, the new `docs/sources/_images` clean target would be called by `docs` Makefile clean target
> Remove obsolete Makefile docs/images clean call

- passes/memory/memory_libmap.cc
As reported in #4883, indices to the pass are reused after the module is modified, leading to dangling cell pointers in ModWalker etc. This has been the case since the inception of the pass but has only recently been discovered when 901935fbcec42cbf79594efd9cc2877810395715 exposed the issue as a segfault when a `PortBit` is hashed. This issue is easily detected with valgrind but since there's limited use of valgrind in testing (`vgtest` Makefile target only runs simple tests due to the runtime, for example) we've missed it. Whether this has lead to incorrect mapping results is uncertain.
This PR fixes the issue by rebuilding MapWorker but only when a memory actually gets emitted modifying the design. This rebuilds all the indices used in the and resolves anything detectable by valgrind at …
> memory_libmap: update indices on design modification

- Makefile
If a test directory already contains a `run-test.mk` file it won't regenerate if anything in the directory changes, meaning any files will be skipped and any removed tests will raise an error because of the missing file.
`MK_TEST_DIRS` provides a list of directories that generate `run-test.mk` files, so we can use that list in the `clean` target to delete them; thus allowing future runs of `make test` to correctly regenerate the needed file.
```bash
make tests/techmap/run-test.mk
rm tests/techmap/abc9.ys
clean
make makefile-tests/tests/techmap
```
Without this change, the second call to make will raise an error due to the missing …
> Makefile: Add run-test.mk to clean

- Makefile
This PR resolves the issue below seen on my macOS Apple Silicon with a vanilla Yosys clone:
```
akashlevy@Akashs-MacBook-Pro yosys % make -j8 ENABLE_PYOSYS=1
$BREW_PREFIX is [/opt/homebrew/opt]
Makefile:343: *** BOOST_PYTHON_LIB could not be detected. Please define manually.  Stop.
```
There are two issues:
1. The `boost` include path is incorrect (`$(BREW_PREFIX)/boost/include/boost` instead of `$(BREW_PREFIX)/boost/include`). This means that the canonical form of Boost includes such as `#include <boost/...>` will not work
2. `boost-python3` library needs to be linked to detect `boost-python3` properly
You can work around these issues by manually setting the `BOOST_PYTHON_LIB`, but this PR makes it so that is not needed.
_Explain how …
> Fix macOS boost-python issues

- Makefile
`git submodule status` can be prefixed with `[ -+U]`, of which we expect the space, and assume anything else is a `-`.  But seeing an error message that tells you abc is not initialized when it *is* initialized but pointing at a different commit is confusing.
Also closes #4888.
Handle the `[+U]` cases and give an actually related error message instead of the generic one.
> Cover all cases of submodule status in check-git-abc

- libs/fst/00_PATCH_wx_len_overread.patch
- libs/fst/00_UPDATE.sh
- libs/fst/fstapi.cc
Fix the compiler warnings
‘ssize_t write(int, const void*, size_t)’ reading between 65536 and 4294967295 bytes from a region of size 16 [-Wstringop-overread]
Two of the three warnings were already fixed upstream, so we pull the fix and then patch the third.
> libs/fst: Fix stringop_overread warning under GCC

- kernel/yosys.cc
`TMPDIR=/foo ./yosys -p "read_verilog tests/sat/alu.v; proc; abc"` 
before:
```
3. Executing ABC pass (technology mapping using ABC).
ERROR: Assert `res != NULL' failed in kernel/yosys.cc:417.
```
now:
```
3. Executing ABC pass (technology mapping using ABC).
ERROR: mkdtemp failed for '/foo/yosys-abc-e7oKww': No such file or directory [Error 2]
```
> improve mkdtemp error message

- passes/cmds/splitcells.cc
Currently, `aldff`s do not get split by splitcells; this PR fixes this.
Add `aldff` to the list of reg/latch cell types to be split.
> `aldff`s do not get split by `splitcells` pass

- techlibs/quicklogic/Makefile.inc
- techlibs/quicklogic/ql_ioff.cc
- techlibs/quicklogic/synth_quicklogic.cc
- tests/arch/quicklogic/qlf_k6n10f/counter.ys
- tests/arch/quicklogic/qlf_k6n10f/dffs.ys
- tests/arch/quicklogic/qlf_k6n10f/ioff.ys
There are registered I/Os available in the qlf_k6n10f architecture, using them saves fabric FFs. 
If a `dffsre` or `sdffsre` cell in the top module fulfils the following criteria:
- the set, reset, and enable ports are unused
- the D port is connected to an input signal or the Q port is connected to an output signal
- the signal in question has no other users
then its type is changed to `dff`.
Testcase included.
> add IOFF inference for qlf_k6n10f

- frontends/liberty/liberty.cc
Fixes #4885. Currently, all Liberty-described clear and preset latches were modeled with a disconnected data input, since the enable logic is clobbering the data signal. This PR fixes this.
Reproducer, from IHP 130:
```
library (sg13g2_stdcell_fast_1p32V_m40C_latch_repro) {
comment : "IHP Microelectronics GmbH, 2024, modified";
date : "$Date: Thu Mar 14 15:30:46 2024 $";
revision : "$Revision: 0.1.0 $";
cell (sg13g2_dllrq_1) {
area : 29.0304;
pin (Q) {
direction : "output";
function : "IQ";
}
pin (D) {
direction : "input";
}
pin (GATE_N) {
clock : true;
direction : "input";
}
pin (RESET_B) {
direction : "input";
}
latch (IQ,IQN) {
clear : "RESET_B'";
data_in : "D";
enable : "GATE_N'";
}
}
}
```
`yosys -p "read_liberty latch.lib; opt; show` reproduces the image
`yosys -p "read_liberty …
> liberty: fix clear and preset latches

- techlibs/intel/common/brams_map_m9k.v
- techlibs/intel/max10/cells_sim.v
- techlibs/intel/max10/dsp_map.v
- techlibs/intel/synth_intel.cc
Fixed altsyncram data/address width parameters
Added DSP (mult) support
Updated synth_intel script (~20% higher performance)
> MAX10 updates

- passes/opt/share.cc
Previously, `share` assumed there is no combinational loop composed of `$mux` cells when collecting terminal bits. This PR uses the already implemented `visited_cells` to avoid running forever in the case of a `$mux` cell loop. Fixes #4260
> share: fix infinite loop in find_terminal_bits on $mux loop

- passes/opt/opt_clean.cc
- passes/techmap/simplemap.cc
- techlibs/common/techmap.v
- tests/techmap/buf.ys
The `write_xaiger2` command transiently enters the buffered-normalized mode. This can introduce `$buf` cells into the design. These cells are missing handling by the `opt_clean` and `techmap` passes, and as such they just fall through to the end of a flow.
So far the bufnormed mode usage has been isolated to the insides of a single pass, once we will want to extend this to let designs in bufnormed mode cross from one pass to another, we will need to revisit the `opt_clean`/`techmap` behavior. At that point we will need to revisit all other cases where these passes introduce connections anyway.
There's a minimal `buf.ys` test of the new behavior
> opt_clean, simplemap: Add `$buf` handling

- techlibs/gowin/cells_sim.v
`nextpnr` currently wires an ALU in `MULT` mode in a different fashion than expected. Instead of `I2` to `GND`, it is connected to `VCC`. This has been mentioned in https://github.com/YosysHQ/nextpnr/pull/1407. While fixing this in `nextpnr` would work, leaving it as-is is arguably a better option, since it can perform the same operations plus being able to take a second operand. This would have a profound impact if choosing to synthesize multiplication using this mode.
So, instead of fixing the wiring in `nextpnr`, this PR seeks to update the expected behavior of the cell to reflect the current wiring.
`yosys` doesn't use this mode yet, and therefore no tests or workflows should be impacted.
> Update ALU MULT mode in gowin to match nextpnr

- backends/aiger/xaiger.cc
This is an attempt to fix stack overflow in [#4689](https://github.com/YosysHQ/yosys/issues/4689) issue.
This is achieved by finding cycles in XAIG. The code was taken from [aiger.cc](https://github.com/YosysHQ/yosys/commit/ac6fcb2547085d041a432a3182a3bfb2c3d2e6ea).
This fix currently passes all yosys test, so I would suggest to test it with large combinational circuits.
> write_xaiger: Detect and error on combinatorial loops

- backends/cxxrtl/cxxrtl_backend.cc
- kernel/fmt.cc
`"\x0a"` is a perfectly valid escape sequence, but unfortunately `"\x0ac"` is equivalent to `"\xac"`, and not `"\x0a" "c"` as we might expect --- *any* number of hexadecimal characters after the `\x` is accepted. This can be hit pretty easily if a newline is present in a format string.
`"\x{...}"` syntax is only available as of C++23, so use octal format instead; a maximum of 3 digits following the backslash is accepted.
The alternative would be to render every escape like `" "\x0a" "`, but it seems more effort that way.
cc @whitequark.
> cxxrtl: use octal encoding of non-printables.

- passes/cmds/splitcells.cc
- tests/various/bug4909.ys
#4909 
Before this change the offset was calculated from iterator variable and wasnt checked against GetSize(old_sig) bounds, which caused assertion error. This pr uses offset as an iteration variable which is bound checked in for loop.
> splitcells: Fix the assertion bug caused by out-of-bound offset

- .gitignore
- frontends/verific/verific.cc
- frontends/verilog/verilog_frontend.cc
Most large Verilog/SystemVerilog IP use a file list/command '.f' file to hold list of Verilog file need to be compiled, this change make yosys able to directly parse file list.
Implement a `read_verilog_file_list` command, that read in file list, and calls `read_verilog` on each Verilog file in the file list. Currently the command only handles file path in file list file, in a future PR I will implement support for `+define+` and `+incdir+` in file list file.
> Verilog file list suport

- passes/opt/share.cc
The `share` pass uses SAT to find cells with same observability with regards to inputs of cells other than `$mux`. First, it expresses the observability conditions as basically a logical function over the S inputs of `$mux` cells in `find_cell_activation_patterns` by traversing contiguous `$mux` regions. This function is stored per cell as a sum of products in `activation_patterns_cache[cell]`. In some unfortunately shaped designs, the count of these products increases exponentially with the length of a chain of divering-converging muxes. This PR adds a user-configurable limit to how many "patterns" can be stored per cell. When this limit is exceeded, the cell is assumed to be always "active" in the sense that some of its input bits are always observable by outputs or cells other than …
> share: add -pattern-limit to limit analysis effort

- docs/source/conf.py
Scott found we need this latex magic to get reproducible PDFs out of sphinx in our Debian packaging.
I haven't checked personally and this hasn't gone through repro testing in our infrastructure yet, but it seems correct enough given prior battles I did with latex. :-)  
--Daniel
> docs: Add latex magic to make PDFs reproducible again

- Makefile
Make will happily consider a target available if it's zero sized.
It's necessary to apply the `|| rm $@` pattern when writing output files with shell redirections to avoid problems with rebuilds here.
--Daniel
> mk: Avoid broken rebuild if program --help fails

- passes/opt/opt_merge.cc
- tests/opt/opt_merge_basic.ys
This is a direct remake of #4175 sans the 64-bit hash value. I'm making use of the interface in #4524 and requiring that PR (and containing its commits at the moment). Instead of xorshifts, values are sorted, though a final xorshift is included as a part of the fudge (`--hash-seed=N`) mechanism.
Additionally, I discovered opt_merge behaves incorrectly in the case of hash collisions. This suggests that this PR might in rare cases bring improvements in quality of results for flows that use opt_merge, since prior to it, hash collisions would inhibit merging. I modified the `sharemap` from a `dict<hash_t, Cell*>` to an equivalent `std::unordered_multimap` so that multiple cells can be associated with the same hash. This can't be a separate change since this bug actually broke the build just …
> opt_merge: hashing performance and correctness

- docs/source/conf.py
- docs/source/getting_started/installation.rst
- docs/source/yosys_internals/extending_yosys/test_suites.rst
- libs/fst/00_PATCH_i386_endian.patch
- libs/fst/00_UPDATE.sh
- libs/fst/fstapi.cc
- Close #3898 (again).
- Local html builds included `READTHEDOCS` et al, making a weird and unformatted version selector element in the sidebar.
- Close #4777.
- Reapply #3904, now with patch file.
- Gate `READTHEDOCS` on environment variable.
- Drop svg badges.
> A few fixes, mostly local docs builds

- Makefile
- docs/source/_images/Makefile
Using rsync for such a simple job seems excessive. We're using this patch in Debian to avoid the build-dependency on `rsync`.
I'd actually just recommend switching to `cp -ru` (-u is "update") completely but I'm not sure what the rsync call is trying to accomplish exactly.
From `man cp`:
-u, --update
copy only when the SOURCE file is  newer  than  the  destination
file or when the destination file is missing
--Daniel
> mk: Fall back to cp if rsync is not available

- techlibs/common/simlib.v
- tests/cxxrtl/test_value_fuzz.cc
While working to get the Debian package up to date I noticed that some tests failed on 32-bit archs.
The first one was fixed by #3904 this should mop up the other two.
The simple/string_format test was causing iverilog to try to allocate huge amounts of memory.
This can be fixed by making sure that the arguments to $print were signed when needed.
A similar fix was done to $mem back in 2015, 95944eb
The cxxrtl tests were also failing but this time the problem was in the test code's reference implementation.
A 64-bit int is being passed to __builtin_clzl which is fine when longs are 64-bit but fails when they are 32-bit.
I chose to check the size of long and use __builtin_clzll is required rather than any of the newer standardised alternatives (stdc_leading_zeros) so as not to change the …
> Make 32-bit tests pass

- passes/cmds/setundef.cc
- tests/various/setundef.sv
- tests/various/setundef.ys
This PR fixes setting bits of parameters in `setundef` pass.
Currently we are looping through module parameters using `for (auto bit : parameter.second)`.
It is equivalent to:
```
for( auto _bit = parameter.second.begin(); _bit != parameter.second.end(); _bit++) {
auto bit = *_bit;
...
}
```
where `auto` is resolved to [`RTLIL::Const`](https://github.com/YosysHQ/yosys/blob/915df16c84f4595b6ad5f198de0f7aaf43896723/kernel/rtlil.h#L1677C2-L1677C49). 
Iterator that we are using is defined in [`Const` class](https://github.com/YosysHQ/yosys/blob/915df16c84f4595b6ad5f198de0f7aaf43896723/kernel/rtlil.h#L713) which iterates through [`State` enum](https://github.com/YosysHQ/yosys/blob/6d4f056a353faeaa69dc23bb30c1ea05 …
> Fix setting bits of parameters in setundef pass

- tests/gen-tests-makefile.sh
CI checks for `*.err` files for reporting failures, but only tests that use `autotest.sh` get a `*.err` file, and not tests that use `gen-tests-makefile.sh`.
Modify `gen-tests-makefile.sh` so that instead of logging to `*.log`, we log to `*.err`, and then `mv` the `*.err` to `*.log`.  Because it is `&& mv` it only gets renamed on a success, leaving behind the `*.err` file on a failure so that it can be reported as expected.
If CI for this PR passes then the change doesn't break anything.  To check for correct behaviour, checkout locally and change a test that uses `gen-tests-makefile.sh`, such as `tests/arch/gatemate/memory.ys` to …
> More *.err files in test failures

- Makefile
- misc/yosys-config.in
To be consistent we should return exit code 1 only if no parameters are provided to yosys-config, asking for actual help will return exit code 0
> yosys-config: Propagate exit code for help command

- kernel/yosys_common.h
- passes/techmap/libparse.cc
- passes/techmap/libparse.h
This PR makes liberty parsing roughly twice as fast by
1. using a custom ifstream wrapper that implements buffering and the used methods in a way that is much more amenable to compiler optimizations than ifstream, and
2. extending the ifstream wrapper with arbitrary lookahead to avoid growing std::string instances byte by byte.
Here 1. is the biggest improvement, reducing runtime by around 40% and 2. adds saves another 10%.
> Improve lexer performance for read_liberty

- passes/opt/opt_expr.cc
- tests/opt/opt_pow.ys
#4896 
This PR handles pow of 2 cells in two ways, if A port of pow cell is 2 than cell is replaced with shl, if A port is other power of 2 value cell is replaced with mul and shl sequence. This optimization accept only unsigned signals at port B.
The default verilog frontend can handle simple pow to shl optimization so basic first case is tested with rtlil
```
read_rtlil << EOF
autoidx 3
attribute \cells_not_processed 1
attribute \src "<stdin>:1.1-3.10"
module \top
attribute \src "<stdin>:2.17-2.20"
wire width 32 $add$<stdin>:2$1_Y
attribute \src "<stdin>:2.12-2.21"
wire width 32 signed $pow$<stdin>:2$2_Y
attribute \src …
```
> opt_expr: optimize pow of 2 cells

- passes/opt/opt_expr.cc
- tests/opt/opt_expr_mux_undef.ys
#4590
If all the (non-select) inputs of a `$_MUX{4,8,16}_` are undefined, replace it, just like we do for `$mux` and `$_MUX_`. Add `tests/opt/opt_expr_mux_undef.ys` to verify this.
This doesn't do any const folding on the wide muxes, or shrinking to less wide muxes.  It only handles the case where all inputs are 'x and the mux can be completely removed.
The following script (from https://github.com/YosysHQ/yosys/issues/4590#issuecomment-2766390391) fails without this patch, and passes with it.
```
read_verilog << EOT
module top (
input  clk,
output [7:0] rddata
);
reg [31:0] index;
always @(posedge clk)
index <= index + 1;
initial …
```
> opt_expr: Fix #4590

- techlibs/xilinx/cells_map.v
Fixes https://github.com/YosysHQ/yosys/issues/4590 where a bit-banged mux has all inputs at `x`.
This case can happen when the selection input signal is originally larger than the data source.
Mapping of underlying smaller muxes end up having to handle upper mux with all inputs at `x` which was not handled.
The root cause was identified by @KrystalDelusion.
To fix the crash, handling of the case where all inputs are `x` is explicitly handled, in that case the output is simply assigned to `x`.
Tested on the reproducer poster on https://github.com/YosysHQ/yosys/issues/4590
> Fix mux mapping for xilinx techno when all inputs are x

- Makefile
- passes/techmap/libparse.cc
- passes/techmap/libparse.h
- tests/liberty/XNOR2X1.lib.filtered.ok
- tests/liberty/XNOR2X1.lib.verilogsim.ok
- tests/liberty/idranges.lib
- tests/liberty/idranges.lib.filtered.ok
- tests/liberty/normal.lib.filtered.ok
- tests/liberty/normal.lib.verilogsim.ok
- tests/liberty/run-test.sh
- tests/liberty/semicolextra.lib.filtered.ok
- tests/liberty/semicolextra.lib.verilogsim.ok
- tests/liberty/semicolmissing.lib.filtered.ok
- tests/liberty/semicolmissing.lib.verilogsim.ok
Some pins may be in a list, and we need to refer to one specifically.
We reuse the range parsing code from a different part of the parser.
Try parsing a liberty file like:
```
pin("foo") {
bar : baz[0] ;
}
```
> Support array ranges for identifiers in the Liberty parser.

- kernel/rtlil.cc
- passes/hierarchy/hierarchy.cc
- passes/sat/cutpoint.cc
- tests/various/.gitignore
- tests/various/cutpoint_blackbox.ys
Supersedes #4812.
Calling `cutpoint -blackbox [options]` will replace the contents of all (black)boxes in the design with a formal cut point (`$anyseq` cell by default).
This is preferable to #4812, which instead calls `cutpoint` on instances of (black)box modules.
Since the module now has contents, it is also no longer a (black)box so we can remove those attributes.
> Add -blackbox option to cutpoint pass

- kernel/consteval.h
- kernel/cost.cc
- kernel/macc.h
- kernel/satgen.cc
- passes/opt/share.cc
- passes/techmap/alumacc.cc
- passes/techmap/booth.cc
- passes/techmap/maccmap.cc
- passes/tests/test_cell.cc
Fill in blind spots of the keep_hierarchy command.
Add `$mem`, `$macc` estimation consistent with existing `$mul`, `$dff` formulas.
This script can exercise the new support:
```
design -reset
read_verilog <<EOF
module top(input clk, input [10:0] a, input [2:0] w, output [2:0] y);
reg [3:0] m[60:0];
always @(posedge clk) begin
y <= m[a];
m[a] <= w;
end
endmodule
EOF
prep
keep_hierarchy -min_cost 20
design -reset
read_verilog <<EOF
module top(input [2:0] a, input [2:0] b, output [2:0] y);
assign y = a * b;
endmodule
EOF
design -save r
keep_hierarchy -min_cost 20
design -load r
alumacc
opt_clean
keep_hierarchy -min_cost 20
```
> cost: Add `$mem_v2`, `$macc_v2` estimates

- misc/py_wrap_generator.py
It seems that `pyosys` breaks with latest changes adding `NamedObject` class. Attempting to get the name of a module in `pyosys` no longer works.
Register `NamedObject` in `py_wrap_generator.py`
Load a simple design in `pyosys` and try to get the name of the top module before and after the change.
> Add `NamedObject` to `py_wrap_generator.py`

- backends/cxxrtl/cxxrtl_backend.cc
- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
Fixes #5029 
By adding the cell to the cxxrtl backend.
Follow the steps in #5029 to create the error.
For a trivial example, create:
```
module bwmux_test(
input [8-1:0] A, B,
input [8-1:0] S,
output [8-1:0] Y
);
\$bwmux #(.WIDTH(8)) mux (.A(A), .B(B), .S(S), .Y(Y));
endmodule
```
and build the .cpp with 
```
yosys -p "read_verilog -icells test_bwmux.v; select =*; proc; clean; write_cxxrtl cxxrtl-test-bwmux.cc"
```
compiling it with the header afterwards.
Implementation is originally by @povik from https://github.com/YosysHQ/yosys/issues/5029#issuecomment-2809093496.
Supersedes #5030
> cxxrtl: Add internal cell "bwmux"

- passes/opt/share.cc
- tests/sat/share.v
- tests/sat/share.ys
In case the two sets of activation patterns are mutually exclusive without considering the logic feeding into the activation signals, an activation condition can only be relevant if present in both sets with opposite polarity.
This detects pattern-only mutual exclusion by running an additional SAT query before importing the input cone logic. If that is already UNSAT, we remove all non-relevant condition and re-simplify the remaining patterns.
In cases of pattern-only mutual exclusion, this will often produce much smaller selection logic and avoid the more costly SAT query that includes the input cones.
This effectively provides a limited version of the interpolant idea explained in #4921, but in a way that can be easily retrofitted to the current implementation of share, as this keeps the …
> share: Restrict activation patterns to potentially relevant signals

- passes/techmap/libparse.cc
- passes/techmap/libparse.h
- tests/liberty/non-ascii.lib
- tests/liberty/non-ascii.lib.filtered.ok
- tests/liberty/non-ascii.lib.verilogsim.ok
This fixes #5027 and adds checks to the parser to produce errors for liberty files that are completely empty or have unclosed curly braces.
> liberty: More robust parsing

- passes/cmds/stat.cc
- tests/various/stat.ys
In Stat there is a separate calculation for the sequential area of a circuit. 
This output of stat has been incorrect if the design isn't flattened. 
We would like to be able to calculate accurate sequential area for non flattened designs. 
add the sequential area to the macro that implements the add and multiply operations. 
Check a report of a flattened and unflattened design. 
Before it had different sequential areas. Now the sequential area will be the same.
> stat: fix sequential area not being included in addition/multiplication

- kernel/satgen.cc
Fix the x-prop behavior of `$macc_v2` in satgen. The satgen extension from #4818 missed to account for `$macc_v2` having an extra `C` port.
Testing coupled to #5024
> satgen: Fix $macc_v2 x-prop

- passes/techmap/flatten.cc
Some (third-party) analysis passes work only on flattened modules, but still want to report back results for each module in the hierarchy.
Add an option to not delete the submodules when running flatten. (The functionality is already there, just needs a flag.)
Load a hierarchical design (with a top module), run `flatten -nocleanup`, observe the number of modules being more than 1, but no module instantiating another module.
> add flatten -nocleanup option

- tests/liberty/run-test.sh
`set -e` is the correct solution but `&&` prevents it from working. Doing `|| exit 1` on a for loop only checks the last iteration of the for loop, or something of that sort. `pipefail` added out of superstition
> liberty: fix tests

- Makefile
- passes/techmap/dfflibmap.cc
- tests/liberty/dff.lib
- tests/liberty/dff.lib.filtered.ok
- tests/liberty/dff.lib.verilogsim.ok
- tests/liberty/dff.log.ok
- tests/liberty/run-test.sh
This supports PDKs that may enclose the `ff` `next_state` function in parentheses.
example:
```
ff (IQ,IQN) {
clocked_on : "!clk";
next_state : "(d)";
}
```
> Detect FF functions that use parentheses.

- techlibs/ecp5/cells_sim.v
Possibly an incorrect use of non-blocking assignment in a non-clocked always process.
see #5026 for discussion
Changing to blocking assignments.
Simulate and compare behavior.
> Changing non clocked alway assignment to blocking.

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
This PR fixes https://github.com/YosysHQ/yosys/issues/5048, which causes an assertion failure during division when the actual value of the divisor exceeds its bit-width range.
The issue is resolved by modifying the `divmod_uu()` function to truncate the divisor to its declared bit-width before zero-extending it to the unified width, ensuring that the value passed to `udivmod()` remains within valid bounds:
```cpp
value<Bits> divisor = b.template trunc<BitsB>().template zext<Bits>();
```
> fix udivmod crashes when operand value exceeds logical width

- techlibs/gatemate/brams.txt
Removing "wrtrans" setting makes designs to work on actual hardware. Without this change LiteX cores are not working correctly and return bad chars over serial port.
Pinging @pu-cc
> gatemate: WRITE_THROUGH mode change

- frontends/ast/simplify.cc
This fixes `tests/various/struct_access.ys` when run with `SANITIZER=address` as described in #5020. All AstNodes must be part of some AstModule and dangling ones are leaks that cause yosys to exit with an error if instrumented with some sanitizers. Unimportant problems like this make sanitizers unusable which is a sever quality issue. This PR deletes an attribute AstNode if it were to become no longer referred to by anything in the AST
> simplify: fix struct wiretype attr memory leak

- techlibs/ice40/ice40_dsp.pmg
- tests/arch/ice40/ice40_dsp_const.ys
ice40_dsp seems to incorrectly handle unsigned consts. The issue seems to be with unextend function. By searching previous issues I could find this one #2648.
Now unextend is called only on non constant inputs.
```
read_verilog << EOT
module top(input wire [14:0] a, output wire [31:0] b);
assign b = a*$unsigned(5'b01111);
endmodule
EOT
prep
ice40_dsp
write_rtlil
```
```
read_verilog << EOT
module top(input wire signed [14:0] a, output wire signed [31:0] b);
assign b = a*$signed(5'b01111);
endmodule
EOT
prep
ice40_dsp
write_rtlil
```
Gives two different connect \B values in \SB_MAC16 cell on pre-PR code, and the same value on post-PR …
> ice40_dsp: fix const handling

- backends/cxxrtl/cxxrtl_backend.cc
The `$paramod\...\...` name for a module doesn't match the source code and isn't useful to the end user given that it's usually containing just a hash.
Module's `hdlname` attribute is used if present.
> cxxrtl: strip `$paramod` from module name in scope info

- kernel/driver.cc
The count of -X arguments used is meaningful as it's used as the super sketchy backtrace depth on debug builds. This fixes args like `-XXX...` while `-X -X` were probably fine before as well
> driver: fix -XX xtrace backtrace level

- passes/sat/formalff.cc
- tests/various/formalff_declockgate.ys
Most FV backends can't deal with clock-gating, this adds a new `-declockgate` option to `formalff` that turns clock gating into clock enables.
It scans the clock inputs of FF cells to check for standard clock gating logic and extracts the clock and gate signal to use from those.
Includes a new testcase covering the added functionality.
> formalff: Add -declockgate option

- kernel/celledges.cc
- passes/opt/opt_expr.cc
- tests/opt/opt_expr_shift.ys
This fixes #5065. When optimizing a shift with constant shift amount, an optimization is used to limit the shift amount to the width of the input, but this limiting was done before potentially increasing the input's size by sign-extending it. This allowed the sign extended parts of the signal to be shifted into the output bits incorrectly. This PR defers the optimization until after the sign extension has happened to handle this and adds tests.
Could someone make sure that this doesn't break anything for `$shift`/`$shiftx` before merging please, I wasn't sure where they come from/what the difference is to the other shift cells.
> opt_expr: fix sign extension for shifts

- kernel/gzip.cc
- kernel/register.cc
- passes/cmds/stat.cc
- passes/techmap/clockgate.cc
- passes/techmap/dfflibmap.cc
Fixes #5013
By refactoring any error handling away from the passes, we now report `ERROR: Can't open input file '$FILENAME' for reading: No such file or directory` every time we fail to open a file with `uncompress`. This includes cases when the file isn't actually compressed. This changes some error outputs (`Can't open liberty file` -> `Can't open input file`) but I doubt anybody minds since you see the filename right after anyway
> gzip: refactor file open failure errors

- passes/cmds/tee.cc
Currently, `tee -o "test file"` creates a file literally named `"test file"`. This essentially makes it impossible to indicate files/paths that include whitespace without adding the literal quotes.
Uses `void rewrite_filename(std::string &filename)` to rewrite the path. As a nice side effect, ~/tilde paths are now expanded as well.
Just try `tee -o "test file"` before and after.
> Allow whitespace in `tee` command paths

- Makefile
As in #4968, `check-git-abc` is misleading if Yosys itself isn't a git repository. 
So check `git status` before suggesting `git` based solutions, providing alternative suggestions for using ABCEXTERNAL (which bypasses `check-git-abc`), or downloading release tar (noting that the 'Source code' archives won't work, which is probably how they ended up in this situtation).
Applying patch to release yosys.tar.gz and running `make check-git-abc` should be be unaffected (i.e. should still succeed).
Applying patch to release source code archive and running `make check-git-abc` (or removing contents of abc folder from yosys.tar.gz) should …
> Makefile: Test yosys git status in check-git-abc

- backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
This PR fixes the issue described in https://github.com/YosysHQ/yosys/issues/5074. Now, for expressions like `assign t = a op b`, when the width of the expression is larger than the width of `a` and `a` is signed, `a` will first be sign-extended before performing the shift operation. 
The fix is implemented by applying the above logic in the `shr_su` function：
```cpp
template<size_t BitsY, size_t BitsA, size_t BitsB>
CXXRTL_ALWAYS_INLINE
value<BitsY> shr_su(const value<BitsA> &a, const value<BitsB> &b) {
if (BitsY > BitsA) {
value<BitsY> extended_a = a.template scast<BitsY>();
return extended_a.shr(b);
}
return a.shr(b).template scast<BitsY>();
}
```
After the fix, the CXXRTL produces results consistent with other simulators for the test case related to …
> fix missing sign extension before shift operation for signed values

- frontends/verilog/verilog_parser.y
- tests/verilog/param_default.ys
Fix #5069, problem appears to be that the `TOK_ID` is created (and allocated space in memory) but never cleaned up, leading to ASAN detected memory leak.
Delete the `TOK_ID` (`$2`), similarly to other cases such as:
```
non_opt_delay:
'#' TOK_ID { delete $2; } |
```
Test file included as `tests/verilog/param_default.ys`.  Running tests in directory *without* fix fails ASAN on this file and `tests/verilog/typedef_{across_files, const_shadow, legacy_conflict}.ys`.
> verilog_parser.y: Delete unused TOK_ID

- kernel/log.h
Change the implementation of log_debug in kernel/log.h from a macro function to a normal function.
Because when integrating Yosys in other applications, if you do not use the code like `using namespace Yosys;`, `log` will not be found correctly, which leads to the mandatory use of `using namespace` and potential namespace pollution problems.
It is just variable length parameter forwarding.
Just run the regression tests.
> Change the implementation of log_debug in kernel/log.h

- kernel/gzip.cc
- kernel/io.cc
- kernel/io.h
- kernel/yosys.cc
- kernel/yosys_common.h
Fixes #5103. Additionally, makes the concepts of "file" and "directory" distinct in check functions in `kernel/io.cc`
> gzip: reject uncompressing directory

- frontends/ast/simplify.cc
From #5020, LeakSanitizer: detected memory leaks in `Yosys::AST::AstNode::clone() const frontends/ast/ast.cc:256:18`.  Identified as being due to the redefinition of the wiretype attribute on the new AstNode when resolving recursive typedef.
Minimal reproducer:
```
read_verilog -sv <<EOF
typedef logic T;
typedef T [3:0] S;
module top;
S s;
endmodule
EOF
```
Delete the wiretype attribute if it already exists, as is done just above.
Alternatively, the `set_attribute()` method should just do this automatically?  There are enough calls to it that are immediately preceded by either this exact check, the inverse (only adding the attribute if it isn't already), or deleting all children and making the check …
> simplify.cc: Fix mem leak

- Makefile
Using `:=` while providing an override in Makefile.conf does not correctly apply the override in other simply expanded variables (using `:=`).  Instead, setting an explicit `PYTHON_EXECUTABLE := python3.15` while leaving `PYTHON_CONFIG` implicitly defined results in it being set to `python3-config` instead of the expected `python3.15-config`.
Using `?=` instead uses the explicit assignment in simply expanded variables as expected.
Add the following target to the Makefile:
```makefile
echo-python-vars:
@echo "$(PYTHON_EXECUTABLE)"
@echo "$(PYTHON_CONFIG)"
```
And an explicit `PYTHON_EXECUTABLE := <path/to/python>` to `Makefile.conf`. …
> Makefile: Conditional assignment of python exe

- passes/sat/cutpoint.cc
- tests/various/cutpoint_whole.ys
#4854 inadvertently removed the optimization for when a whole module was selected.
Adds whole module optimization back, as well as a test script for it.
Run following script:
```
read_verilog << EOT
(* blackbox *)
module bb (input a, b, output o);
endmodule
module sub_mod(input a, b, output o);
bb bb2 (.a (a), .b (b), .o (o));
endmodule
EOT
hierarchy -top sub_mod
cutpoint sub_mod
```
With latest Yosys (before this change):
```
3. Executing CUTPOINT pass.
Removing cell sub_mod.bb2, making all cell outputs cutpoints.
Making wire sub_mod.$auto$rtlil.cc:3769:Anyseq$2 a cutpoint.
Making output wire sub_mod.o a cutpoint.
Making wire …
```
> cutpoint: Re-add whole module optimization

- kernel/register.h
- passes/cmds/design.cc
Fix #5088.
When building `WITH_PYTHON`, where a global list of modules is maintained, deleting a module also erases the entry in said global list.  This can lead to memory corruption if the global list is destructed before the module.
Using `on_shutdown()` instead means the module destructor is explicitly called before the global list can be destructed, preventing the issue.
Also add a comment to `Pass::~Pass()` to suggest the same for future passes that might try to use that (and see this commit/PR in the blame if they need a reason why).  
> design.cc: Use on_shutdown method

- kernel/io.cc
I bisected a [bug](https://github.com/YosysHQ/nextpnr/pull/1479#issuecomment-2878583483) back to commit b05c0c70af50, where `yosys` just plain fails to initialize and thinks its `share/` directory doesn't exist (when it almost certainly does exist):
```
$ python3 -m amaranth_boards.orangecrab_r0_2
ERROR: init_share_dirname: unable to determine share/ directory!
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "C:/msys64/home/William/Projects/FPGA/amaranth/amaranth-boards/amaranth_boards/orangecrab_r0_2.py", line 140, in <module>
OrangeCrabR0_2Platform().build(Blinky(), do_program=True)
File …
```
> Strip trailing slashes when checking for directories on Windows.

- passes/techmap/libcache.cc
- passes/techmap/libparse.cc
- passes/techmap/libparse.h
- tests/liberty/libcache.ys
Using #4986 broke `stat -json -liberty`. This PR silences the log prints unless a verbose mode is enabled. Fixes #5104
> libcache: add -quiet and -verbose

- Makefile
It was always difficult to debug the logic in yosys when using it as a dynamic library, and it was further discovered that this was because STRIP was always used to remove symbol information in yosys when installing yosys, regardless of how ENABLE_DEBUG was set. I don't know if this is by design or just an unexpected behavior.
The STRIP variable is cleared when ENABLE_DEBUG is set to 1, and validity checks are performed everywhere the STRIP variable is used.
Build with ENABLE_DEBUG=1 and inspect with a debug symbol viewing tool.
> Disable STRIP operations when appropriate.

- frontends/ast/simplify.cc
- frontends/verilog/verilog_parser.y
- tests/svtypes/typedef_struct_global.ys
When the `typedef struct` is inside the module, it is before the AST node that uses that type and so the custom type is fully resolved.
When the `typedef struct` is inside a package, the package is resolved before the module, so it is again fully resolved.
In the case from #4653, the `typedef struct` is in the global space, and ends up appended to the module so isn't fully resolved until _after_ the nodes that reference it are resolved, so indexing into it ends up with a range of `[-1:0]`, causing it to throw an assertion error.
By marking `struct`s with `is_custom_type`, the code will fully resolve the `typedef struct` before any nodes that reference it, thereby avoiding the assertion error and fixing …
> SystemVerilog: Fix typedef struct in global space

- kernel/log.h
This reverts commit 15cfce061a118111 from #5078. The concern is that we're using log_debug in hot loops of important passes like opt_expr and the change I'm reverting forces the arguments to `log` to be evaluated even when the log will not be executed
> Revert log_debug back to macro from function

- passes/proc/proc_arst.cc
- passes/proc/proc_clean.cc
- passes/proc/proc_dff.cc
- passes/proc/proc_dlatch.cc
- passes/proc/proc_init.cc
- passes/proc/proc_memwr.cc
- passes/proc/proc_mux.cc
- passes/proc/proc_prune.cc
- passes/proc/proc_rmdead.cc
- passes/proc/proc_rom.cc
- passes/techmap/abc9_ops.cc
With the recent change to selections (#4768), a number of passes now give a warning when they ignore boxed modules, instead of doing so silently.  #5142 reveals that many of the `proc_*` passes ignore boxes, raising warnings when `abc9_ops` calls `proc` on the derived modules.  It seems like the major `proc_*` passes handled boxes but some of the newer optimizations used `selected_modules`, potentially without realizing that it was silently ignoring boxes.
All of the `proc_*` passes have now been updated to be consistent, universally accepting all selected modules, including boxes.
```c++
for (auto mod : design->all_selected_modules()) {
// ...
for (auto proc : mod->selected_processes()) {
// ...
}
// ...
} …
```
> Fix `proc` handling of whiteboxes

- frontends/verific/verific.cc
- kernel/rtlil.cc
- passes/hierarchy/hierarchy.cc
A grab bag of warnings that have been annoying me:
1) Since #4854, `hierarchy` warns on every parametrizable blackbox coming from verific. Having a blackbox in a design is normal, I'm not sure what I'm supposed to do with this warning.
2) #4324
3) The compiler warning in `rtlil.cc:2412` where a deprecated function is called to sanity-check that the deprecated infrastructure isn't used any more.
This probably should have been 3 separate PRs but I'm lazy.
1) Change `log_warning` to `log_debug` (someone can figure out later if there's something more to do here, but in the meantime let's stop annoying/scaring users).
2) Same approach as for increasing the severity of `VERI-1063` (cf #3568)
3) `#pragma GCC …
> Suppress several spurious warnings

- docs/source/cell/word_mux.rst
- docs/source/yosys_internals/verilog.rst
- frontends/verilog/verilog_parser.y
- tests/proc/case_attr.ys
- tests/verilog/unique_priority_case.ys
- tests/verilog/unique_priority_if.ys
To improve compatibility with SystemVerilog 1800-2012 (by handling `unique if` and similar constructions according to the spec), and to continue the changes started in PR #5141.
`unique if` (etc.) are treated by the parser as follows:
1. Apply the relevant `full_case` and/or `parallel_case` attribute(s) to the generated `AST_CASE` node(s), so that the existing AST frontend and subsequent passes will generate RTLIL with appropriate behaviour.
(This is handled in the grammar's `if_attr` non-terminal.)
2. Rearrange the `AST_CASE` structure when necessary.  For `priority if` (i.e., `full_case`), this requires only ensuring that directly nested `else if` branches also inherit the `full_case` attribute.  For …
> verilog: implement SystemVerilog unique/unique0/priority if semantics.

- frontends/verilog/verilog_lexer.l
Use a greedy regular expression to match input inside a string literal, so that flex can accumulate a longer match instead of invoking a rule for each individual character.
Before this change, matching long string literals was slow (see issue #5706).
A small regexp is added to match the body of string literals while in the `<STRING>` state; this allows the DFA to do the work of analysing the string so it doesn't have to suspend processing between characters.
From the `flex` manual:
> Another area where the user can increase a scanner's performance (and one that's easier to implement) arises from the fact that the longer the tokens matched, the faster the scanner will run.  This is because with long tokens …
> verilog: improve string literal matching speed (fixes #5076)

- kernel/driver.cc
cxxopts has this 'cool feature' where you can use a comma separator between multiple arguments for the same option (see also https://github.com/jarro2783/cxxopts/issues/228), even if the comma is inside a quoted string.  This is problematic for some commands like `eval` which can use a comma.
Take this very simple example `test.v`:
```verilog
module top(input a, b, output o);
assign o = a ^ b;
endmodule
```
Say you want to to call `yosys test.v -p prep -p 'eval -table a,b'`.  The arguments passed to main are
```
yosys
test.v
-p
prep
-p
eval -table a,b
```
The resulting `result["p"]` is
```
prep
eval -table a
b
```
Which breaks the `eval` call, and then fails on the unrecognised `b` ccommand.
By setting the …
> driver.cc: Don't split options on commas

- frontends/verilog/verilog_lexer.l
- tests/verilog/bug5160.v
Fix the bug reported in #5160, where a closing quote on a string literal failed to terminate the string when preceded by an escaped backslash.
_Originally posted by @mmicko in https://github.com/YosysHQ/yosys/issues/5160#issuecomment-2983643084_
Properly escape the backslash in the regular expression in `verilog_lexer.l`.
See the included regression test `tests/verilog/bug5160.v`, or @mmicko's test case in the original report.
With this fix applied, both cases work properly.  Before the fix, parsing would fail with a spurious syntax error.
> verilog: fix string literal regular expression

- passes/opt/opt_dff.cc
- tests/opt/bug5164.ys
Fixes #5164.
Instead of removing and emiting changed cells as they are found no longer needed, cache them and remove/emit afterwards to prevent invalidating the Cell*s in ModWalker.
Added a testcase from #5164 that fails with an ASAN build before this change.
> opt_dff: don't remove cells until all have been visited to prevent UAF

- frontends/verilog/verilog_parser.y
Fix buggy memory allocation introduced in #5152:
1) clean up `ast_stack` to reflect AST node rearrangement when necessary, to avoid dangling pointer;
2) call `free_attr()` on unused attribute list when no new syntax node is created, to avoid leaking it.
To fix the allocation bug discussed in #5152 and #5189.
This also assists #5180, which was blocked by this bug.
Commit 370d5871f4bd04d6ccd57457827dc1dfcaf74d1e handles an `else if` branch within a `unique if` by replacing the current `AST_COND`/`AST_DEFAULT`/`AST_BLOCK` "else" construction with a new `AST_COND`/(expr)/`AST_BLOCK` within the original `AST_CASE`.  However, it mistakenly left a dangling reference to the original (now orphaned) structure …
> verilog: fix parser "if" memory errors.

- kernel/yosys.cc
When using yosys as a dynamic library, the yosys environment is sometimes opened and closed multiple times for different purposes, and the already_setup flag is not maintained correctly.
Simply maintain the already_setup and already_shutdown flags.
Only one regression test needs to be executed. I don't know if there is any place that takes advantage of the side effects of the previous commit changes (although that feature doesn't make common sense).
> Allows calling yosys_shutdown and then yosys_setup to restart.

- .github/workflows/test-build.yml
- tests/verific/run-test.sh
We have UBSAN running on CI, but sometimes ASAN issues slip through as well (e.g. #5020, #5163).
Define the sanitizer as part of the test strategy matrix in the `test-build.yml` family of CI jobs.
There are still memory leaks being picked up in the Verific tests, but I added a (hopefully temporary) patch to `tests/verific/run-test.sh` to disable `halt_on_error` for the tests in that directory.  The sanitizer builds are running on the open source runner, so they shouldn't actually hit the Verific tests _anyway_, but better safe than sorry.
CI should pass, having run the test suite with ASAN.
> Add ASAN to CI

- techlibs/gowin/cells_xtra.py
- techlibs/gowin/cells_xtra_gw5a.v
If let's say the enumeration of inputs took several lines, then all after the first one were ignored. Since the first line ended with a comma, an error was generated when trying to use the resulting file.
> Gowin. BUGFIX. Fix multi-line descriptions.

- backends/verilog/verilog_backend.cc
- backends/verilog/verilog_backend.h
- passes/cmds/rename.cc
- tests/various/rename_unescape.ys
ASIC flows with some commercial tools rely on the transformation of escaped Verilog identifiers into simple identifiers by replacing some characters with underscores. Most notably, `a[0]` gets renamed to `a_0_`. This PR implements a new mode for `rename` that implements this and ensures no selected public name has to be escaped by `write_verilog`. Conflicts in renaming are resolved by appending numbering suffixes.
The current implementation approach relies on the verilog backend exposing its escaping logic in a new header, `verilog_backend.h`. In addition to seeing the test passes, reviewers may add `write_verilog` to its end and observe the end result is such that no wire names are escaped by the Verilog backend
> rename: add -unescape

- kernel/rtlil.cc
Fixes #5175 
Zero width constants are special cased and treated as the constant value zero.
The testcase from #5175
> kernel: treat zero width constant as zero

- Makefile
This is useful to be able to build a plugin like yosys-slang without having to build the entirety of Yosys, which can save a lot of time.
Although I don't expect Yosys itself to support it any time soon, for YoWASP I'd like to embed yosys-slang directly in the main Yosys binary, which also needs this feature to avoid loops in the dependency graph.
A new make target `install-dev` is introduced which only installs `yosys-config` and `share` (which are sufficient to build any C++ extension, I believe).
> Allow installing headers and `yosys-config` without the rest

- backends/firrtl/firrtl.cc
Fixes #5231 
The cache of names that have been used when exporting the current design is global and was not being cleared on each invocation (namecache was cleared, used_names was not), so now we clear it each time. Ideally this probably wants the code being restructured to not depend on global variables, but I am not familiar with the name aliasing rules in firrtl and don't want to get stuck refactoring a pass its not clear if anyone uses, so this fix should work for now.
> write_firrtl: clear used names cache each invocation

- docs/source/code_examples/macro_commands/opt.ys
- docs/source/using_yosys/synthesis/opt.rst
- passes/opt/Makefile.inc
- passes/opt/opt.cc
- passes/opt/opt_hier.cc
- techlibs/common/synth.cc
- tests/opt/opt_hier.tcl
- tests/opt/opt_hier_simple1.v
- tests/opt/opt_hier_simple2.v
- tests/opt/opt_hier_test1.v
- tests/opt/run-test.sh
Improve QoR in synthesis with preserved module boundaries.
Add `opt_hier` which propagates tied-together signals, tied-off signals, and unused signals both into and out of modules. The pass supports non-uniquified hierarchies in which case it propagates what's common to all instances.
See the attached test which verifies functional equivalence on few simple test sources.
> Start `opt_hier` to enable hierarchical optimization

- frontends/ast/simplify.cc
- tests/verilog/bug4785.ys
Close #4785.
We have an input error about cell arrays of primitives not being supported, but the `AST_PRIMITIVE` is simplified before it can be checked, leading to an assertion error instead.
Don't simplify `AST_PRIMITIVE` in `AST_CELLARRAY`, similar to #3467.
Run `yosys tests/verilog/bug4785.ys` with/without this patch.
> simplify: Skip AST_PRIMITIVE in AST_CELLARRAY

- backends/verilog/verilog_backend.cc
- kernel/io.cc
- kernel/io.h
- kernel/yosys_common.h
Format string checking happens at compile time if `-std=c++20` (or greater) is enabled. Otherwise the checking happens at run time --- invalid format strings will result in a call to `abort()`.
Compile-time format string checking requires the format string to be a compile-time constant, so fix a few places where that isn't true.
See #5210. By replacing `stringf()` and then `log()` and related varargs functions with variadic template implementations, and adding direct support for C++ types such as `std::string`, we will be able to clean up some pretty ugly code and avoid some space leaks.
> Introduce variadic template implementation of `stringf` that supports `std::string` parameters

- kernel/rtlil.cc
- kernel/rtlil.h
`dict` is pretty slow when you don't ever need to iterate the container and the hash function for `char*` in `dict` hashes for every single byte in the string, likely doing significantly more work than `std::hash`.
A private flatten benchmark shows that this change provides a 2-4x improvement in `IdString`s constructor:
> Use unordered_map instead of dict for IdString's char* to index storage.

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Since the Slack has been deprecated, I thought it might be a good idea to direct users to the Discourse in the readme. I couldn't find any other direct links to it on the Yosys website or elsewhere. This is similar for the blog too.
Happy to adjust wording if needed.
My editor has removed some trailing whitespace later in the file, that is the reason for those diffs.
_(this is the same as #5261, but my fork was severely outdated, so I've redone the PR to clean things up)_
> docs: mention Yosys Discourse group and blog

- frontends/verific/verificsva.cc
The code added in f019e44e7 contains a tab-completion typo, meaning it only added support for the overlapped followed-by operator, not the non-overlapped one.
Obvious typo fix
@mmicko is currently working on a feature that will make use of the operator and exercise this functionality.
> verificsva: Fix typo in the cover only followed-by operator support

- kernel/io.cc
- kernel/io.h
- tests/unit/kernel/ioTest.cc
Fix regression in #5260 so that the width of format conversion specs is treated accurately.
Just remove the code I added to widen the format conversion specs. For some reason I thought handling the widths accurately was going to be more work, but it's actually less work --- I don't know what I was thinking!
I added some sorely-needed unit tests for `stringf()`.
> Making `stringf()` use the format conversion specs as-is without widening them

- misc/py_wrap_generator.py
This fixes a bug where when converting a tuple from python to c++, `get_cpp_obj()` was called (returning a pointer) without dereferencing the pointer to get the underlying object.
> pyosys: dereference cpp objects when constructing a tuple

- kernel/register.h
- misc/py_wrap_generator.py
pyosys broke with 6fdefee35ba7b1a63ab3f83e891f6f317ccd0fc3 as the generator couldn't interpret `source_location` arguments. This is for two reasons, the first that it doesn't recognise the type, but even if it did it would require a user to pass a `source_location` argument in from python as default arguments aren't supported in the wrapper.
This is fixed by special casing `source_location` when it is a trailing, defaulted argument for functions/classes, leaving it to take its default value. I also fix some trailing whitespace issues in the first two commits.
Before `6fdefee35` this generated:
```c++
// WRAPPED from "Pass(std::string name, std::string short_help = "** document me **");" in kernel/register …
```
> pyosys: support trailing defaulted source_location arguments

- kernel/hashlib.h
Casting away const is dirty and it's pretty easy to avoid in this case.
It's also probably a tiny bit faster to avoid rehashes if we're only doing lookups.
Just refactor the code a little.
> Make `dict` and `pool` const lookup methods never rehash the hashtable

- kernel/log.cc
- kernel/log.h
- passes/cmds/logger.cc
- tests/verilog/constparser_f.ys
- tests/verilog/constparser_f_file.sv
- tests/verilog/constparser_f_file.ys
- tests/verilog/constparser_g.ys
For #5135 I need to be able to check the correctness of filenames and line numbers in diagnostics. In this PR I add new types for `logger -expect` that also match not just on the content of the diagnostic but also on the prefix. I use this in new tests that cover some const2ast code. The intention is to resolve #5181 with this infrastructure soon
> logger: add -expect types prefix-log, prefix-warning, prefix-error

- kernel/satgen.h
- passes/equiv/equiv_induct.cc
- passes/equiv/equiv_simple.cc
- tests/various/equiv_assume.ys
Fix #5196.
Based on `-set-assumes` option from `sat` pass (also because that is an option rather than default behavior).
I initially wasn't convinced that the `$assume` cells would work with FFs because of the `seed_a` `next_seed_a` stuff going on, but I think actually the implementation I did of *not* checking through the FFs and instead only testing the inputs of the `$assume` is fine.  It probably could use some tidy up though since it is a bit of a mess just because of how it does the same thing for both the A and B input cones.
> Assumptions for equiv_*

- .github/workflows/extra-builds.yml
Current version of nix is missing support for macos-15 (sequoia).  macos-latest is currently transitioning to macos-15.  nix builds on macos are failing.
Bump the nix version so that it has sequoia support.
CI should pass: https://github.com/YosysHQ/yosys/actions/runs/16842411384/job/47716064329?pr=5276
> Bump nix on CI

- frontends/verilog/verilog_error.cc
- frontends/verilog/verilog_error.h
- frontends/verilog/verilog_parser.y
In #5135 I accidentally promoted some parser warnings to errors so I'm fixing the ones I can see
> verilog: demote some parser errors to warnings again

- kernel/ffinit.h
- kernel/ffmerge.h
- kernel/hashlib.h
- kernel/sigtools.h
- passes/techmap/abc.cc
We have some large modules where a single ABC pass runs ABC thousands of times. The pass is very slow because in a couple of places it scans the entire module each time it runs ABC. Without too much work we can avoid this and get significant speedups. For example on one of our real-world examples this PR speeds up the ABC pass by 6x.
One problem is rebuilding `assign_map` from scratch for every ABC call. Instead we can build it once and maintain it incrementally as the module is modified.
Another problem is scanning all module wires and cells to call `mark_port()`. This is a bit trickier; we need to introduce a reverse map from canonical `SigBit`s to the module wires and cells associated with each bit, and …
> In the ABC pass, avoid scanning the entire module for each ABC run

- passes/cmds/rename.cc
- tests/various/rename_unescape.ys
The following test fails with an assertion error:
```
read_verilog << EOT
module top(output \$e );
submod \a$ (\$e );
endmodule
module submod(output \a[0] );
assign \a[0] = 0;
endmodule
EOT
rename -unescape
check
```
If a port is renamed, we need to call `module->fixup_ports()`.
`tests/various/rename_unescape.ys` has been updated with the above testcase.
> rename.cc: Fixup ports after -unescape

- frontends/verilog/verilog_location.h
This header file is missing when running with inclusion checking.
Adding the correct include for sstream.
> verilog: Fix missing sstream include

- passes/opt/opt_merge.cc
`OptMergePass` hashes cells into equivalence classes by hashing sorted cell inputs, which in some cases requires allocating memory. We can do this more efficiently and more simply using `commutative_hash`.
Now that we have a good `commutative_hash` implementation we can use it here to simplify and speed up the code. This change reduces the cost of `OptMergePass` from 150s to 130s for one of our large circuits.
> Use commutative hashing in `OptMergePass` instead of allocating containers and sorting them to get canonical hashes

- Makefile
I am using the Yosys API in my project through `libyosys.so`. However, the current Makefile always hardcodes `soname` to `$PREFIX/lib/yosys/libyosys.so`. Unless the `libyosys.so` is exactly in that location, the runtime linking will fail even if the `LD_LIBRARY_PATH` contains the shared lib.
This PR removes the hardcoded prefix.
> Makefile: fix hardcoded -soname for libyosys.so

- techlibs/lattice/cells_bb_ecp5.v
- techlibs/lattice/cells_xtra.py
Fixes #3952 , missing parameters on ECP5 EBR blackboxes.
prjtrellis documentation shows that EBR clock inputs have optional inverters. The bram techmap outputs those parameters, and nextpnr consumes them. But for whatever reason, Diamond doesn't include those parameters in its blackbox models. This makes synth_lattice fail when targeting ECP5 with a design that maps block RAMs.
This change fixes up the ECP5 bram blackbox models at generation time, by adding in the missing parameters.
1. Grab this `synth.v` https://gist.github.com/danderson/3e80ce79da41673de1ee0dff22e0e596 . The Verilog is a bit verbose, but it's just a basic 1kiB block RAM with registered output.
2. With yosys@main: `yosys -p 'read_verilog -sv -defer synth.v; hierarchy -top mkTop; synth_lattice -family ecp5'`
Observe …
> techlibs/lattice: add missing clock muxes to ECP5 block ram blackboxes

- techlibs/quicklogic/synth_quicklogic.cc
Not flattening gives faster execution time and lower memory usage in exchange for worse QoR. Probably more useful for debugging/exploring synthesis results than for actual use with an FPGA (not sure if the VPR P&R flow even accepts hierarchical netlists at all).
Same way as for the other `synth_*` passes (except `synth_xilinx` which doesn't flatten by default).
> synth_quicklogic: add -noflatten option

- backends/btor/btor.cc
This is treated the same as `$pos`, passing through transparently
> write_btor: support $buf

- passes/memory/memlib.cc
The code in memory_libmap expects `clk_en` to be initialized for all `PortVariant`s but the parsing in memlib.cc didn't initialize it for variants of kind `PortKind::Ar` (async read ports).
While this fixes the immediate CI failure (which is non-deterministic since it depends on an uninitialized value), it would be best to refactor the code so it becomes obvious if something isn't initialized.
> memory_libmap: Fix use of uninitialized value for async read ports

- frontends/verilog/verilog_lexer.l
- frontends/verilog/verilog_parser.y
- tests/verilog/specify-ifnone.ys
Rebased #5121 with an added minimal test and the `-Wcex` bison flag removed
> Add state_dependent_path_declaration so that `ifnone` can be parsed (rebased)

- tests/cxxrtl/run-test.sh
- tests/fmt/run-test.sh
- tests/tools/autotest.sh
This removes the need for a similar patch in nixpkgs and kind of just makes sense
> tests: replace CC and gcc with CXX and g++

- kernel/rtlil.cc
- tests/sat/fminit_noexpand.ys
- tests/sat/fminit_seq_width.ys
#5234 
Add code in `SigSpec::parse_rhs` to adjust the width of RHS.
Try different combinations of width and signedness of the arguments of `-seq`
> fix(parse): #5234 adjust width of rhs according to lhs

- kernel/log.cc
- kernel/log.h
- passes/techmap/abc.cc
See #5215
Easy. We only have to fix one caller in-tree so this probably has very low impact on out-of-tree plugins.
> Remove `string_buf` by making `log_signal()` and `log_const()` return `std::string`

- Makefile
- backends/aiger2/aiger.cc
- backends/verilog/verilog_backend.cc
- frontends/ast/simplify.cc
- frontends/verilog/verilog_lexer.l
- kernel/celltypes.h
- kernel/rtlil.cc
- kernel/rtlil.h
- kernel/rtlil_bufnorm.cc
- passes/opt/opt_clean.cc
- passes/techmap/abc9_ops.cc
- passes/techmap/abc_new.cc
- passes/techmap/simplemap.cc
- techlibs/common/simlib.v
- techlibs/common/techmap.v
- tests/various/aiger2.ys
The previously merged support for buffer normalized RTLIL (bufnorm) was incomplete, in both design and implementation, in that it would only handle a subset of RTLIL. In particular it would break in unpredictable ways for unsupported input. This PR extends buffer normalization to cover a much larger RTLIL subset that should cover all RTLIL supported by any commonly used flow.
This PR extends the concept of buffer normalized RTLIL to
* Support inout ports, by always treating them as output ports as far as buffer normalization is concerned.
* Support undirected connections, represented using a new `$connect` cell that has two ports (modeled as input ports within RTLIL, but better thought of as inout ports).
* …
> Extended buffer normalization

- kernel/log.h
Using this requires C-style varargs, which are deprecated in favour of C++ variadic template formatting. There are no in-tree users. Out-of-tree users should migrate to using `log_formatted_file_error()` or `log_file_error()`.
> Deprecate `logv_file_error()`

- passes/techmap/abc.cc
Currently in some configurations the ABC_DONE token is missed and ABC just hangs.
Moving the emission of the `ABC_DONE` token into the sourced script makes things simpler because we don't have to worry about ABC echoing the command before it runs, and the end of the ABC `source` command flushes stdout in a way that ensures our token appears.
> Make ABC_DONE tracking more robust

- kernel/rtlil.cc
> Fix off-by-one error in bounds check in `RTLIL::SigChunk::operator[]`

- kernel/log.cc
- kernel/yosys_common.h
- passes/techmap/abc9_ops.cc
- passes/techmap/simplemap.cc
This collects various logging fixes I made while debugging something unrelated.
This is removing some temporary debug log output that shouldn't have been merged, fixes a long standing bug where we don't flush stdout before we log fatal errors to stderr (which didn't occur with `-l` log targets or line-buffered stdout) and makes sure that YOSYS_ABORT macro outputs a helpful message.
Straightforward changes, YOSYS_ABORT now forwards to a new `log_yosys_abort_message` which has to be declared in an unusual place since the new template based printf-style formatting which everything depends on uses YOSYS_ABORT to bail out on format string vs argument mismatches when compiling with C++17 . 
_If applicable, please suggest to reviewers how they can test the …
> Various logging fixes and cleanup

- kernel/rtlil.h
- passes/opt/opt_merge.cc
Some trivial refactorings makes the code more readable (and in the `SigSpec` swapping case, slightly more efficient).
> Some small readability improvements to `OptMergeWorker`

- kernel/rtlil.h
`pyosys` build is failing since https://github.com/YosysHQ/yosys/commit/1c73011e7e8236c88157d37bd22a456b47c459d1 (blame: @rocallahan)
`pyosys` cannot parse headers with omitted function args. This fix populates the (unused) function args to support `pyosys`.
(Ideally, `pyosys` would support omitted function args, but this fix is easier than rearchitecting that...)
Run: `make ENABLE_PYOSYS=1`. Will fail to build before this change, will build after.
> BUGFIX: pyosys cannot parse header with omitted function args

- passes/opt/opt_hier.cc
- tests/opt/bug5398.ys
Fix a conflict between the following two:
* propagation of tied-together inputs in
* propagation of unused inputs out
Tie-together optimization is made ignore unused inputs.
See included test case which is reduced from #5398
> opt_hier: Fix two optimizations conflicting

- kernel/rtlil.h
I actually saw this take 0.6% of the time in an `opt_clean` pass (under Module::check()). Trivial issue, but the fix is also trivial and simple.
> Optimize `IdString::empty()`

- techlibs/common/simlib.v
Fixes https://github.com/YosysHQ/yosys/issues/5367
I added in the `` `ifndef SIMLIB_NOCONNECT ``, as was mentioned in https://github.com/YosysHQ/yosys/issues/5367.
Now Verilator can correctly read the file with:
```bash
verilator -DSIMLIB_NOCONNECT -Wno-fatal --lint-only techlibs/common/simlib.v
```
Possibly the next step would be to create a test that verifies this never happens again. Maybe there could be a new file `".github/workflows/test-techlibs.yml"`, that runs Icarus and Verilator on each of the techlib cells_sim.v files.
> Added ifndef SIMLIB_NOCONNECT

- passes/cmds/portarcs.cc
- passes/techmap/abc9_ops.cc
- passes/techmap/abc_new.cc
We were performing the helper passes `abc9_ops -replace_zbufs` and `abc9_ops -restore_zbufs` for every module, but those passes act on the full design (and can't be applied entirely selectively due to entering and leaving bufnorm).
This lead to an explosive creation of a lot of redundant bufnorm helper cells that would have been cleaned up by `clean` but that never ran. 
Instead we now run each helper pass once, one before and one after iterating over the selected modules. This limits the number of bufnorm helper cells.
Since this just reduces memory usage, we can't easily test for it as part of our testsuite, but #5404 contains a reproducer (but I'd recommend running it with something like `systemd-run …
> abc_new: Avoid bufnorm helper cell churn
