YosysHQ/yosys

Makefile, frontends/ilang/Makefile.inc, frontends/verilog/Makefile.inc
Correctly finds and uses Homebrew's installation of libreadline/libffi/bison.
=> Fixes building on a Mac using Homebrew as package manager

Makefile
These Makefile targets simply echo the corresponding Makefile variable,
simplifying package build scripts.
Signed-off-by: Martin Schmölzer <mschmoelzer@gmail.com>
=> Add "echo-yosys-ver" and "echo-git-rev" Makefile targets.

backends/verilog/verilog_backend.cc, tests/bram/run-single.sh
Hi Clifford,
This should *finally* complete the $mem cell portion of the verilog backend. This was a pain in the butt, but mostly because of the simulation differences in tests/bram.
I've tried to use your advice given on my reddit question (at least the way I understood it) and had to change the command sequence in tests/bram/run_single.sh
The flow of test/bram is now:
1. attempt to map to brams (as it was before)
2. any memories that were not matched to a bram fall through and the output verilog is written to file (using the new $mem code)
3. read the verilog back into yosys, combine into $mem cells, write the verilog back to file, but this time don't use the new $mem cell code; this allows the $mem cells to be defined by simlib.v and should also test the generated code
Using this flow …
=> Bug fix in $mem verilog backend + changed tests/bram flow of make test.

frontends/verilog/verilog_frontend.cc
This change allows misspelled signal names to be caught as errors without having to put "`default_nettype none" in every single Verilog source file.  Instead the flag -noautowire can be supplied to the read_verilog command by the build system, to get the sane behaviour which is default in e.g. iverilog...
=> Add -noautowire option to verilog frontend

techlibs/ice40/cells_sim.v
This change adds SB_WARMBOOT to the known blackboxes on iCE40.
It goes well with cseed/arachne-pnr#7.  :-)
=> Added iCE40 WARMBOOT cell

.travis.yml
This patch enables automatic testing on if you enable the yosys repository on travis-ci.org.  The current version tests clean.
=> Added .travis.yml.

frontends/verilog/const2ast.cc
This checks that literals only contain digits valid in the specified base.
Additionally it warns on literals with a value that requires more bits to encode than specified.
=> Check number literals

Makefile
Every time I create a package of a new version I have to spend quite some time merging in some patches. These fixes will make the packaging much more straight forward.
Thanks
=> Correcting wrong usage of DESTDIR and use LDFLAGS etc from the environment

passes/techmap/dffinit.cc
The code was already trying to add the required number of bits, but
fell one short of the mark.
The vector needs to hold at least i+1 elements for bits[i] to be valid.
=> Fix a segfault in dffinit when the value has too few bits

Makefile, manual/clean.sh
Hi, was just building yosys on Mac (El Capitan, with Homebrew) and ran into some new problems. With this patch, it's building successfully again.
=> Trivial changes to fix Mac OS build

kernel/rtlil.cc, kernel/rtlil.h
As described in #114, remove2() as used by Yosys::AST_INTERNAL::ProcessGenerator::removeSignalFromCaseTree() was doing a lot of memory allocations and causing a performance bottleneck.  These changes mostly remove unnecessary copies.  With these changes, read_verilog of the test module from #114 with COUNT=1600 improves from 160s to 4s.
=> RTLIL::SigSpec::remove2() speedups

frontends/ast/genrtlil.cc, kernel/rtlil.cc
More changes to avoid unnecessary copies and memory allocations.  I've been using the following module and synthesizing to Xilinx as the test case:
module test(
input wire clock
);
parameter ITERATIONS = 1600;
reg buffer[0:ITERATIONS-1];
always @(posedge clock) begin : GENERATE
integer ii;
for (ii = 0; ii < ITERATIONS; ii = ii + 1) begin
buffer[ii] <= 1'b0;
end
end
endmodule
Building at commit 5462399c880c4736d0382bf5ba294e97637b393d, read_verilog+synth_xilinx took 79s as reported by yosys.  With these changes, it now takes 22s.
=> More RTLIL performance improvements

Makefile, passes/techmap/abc.cc
$ make ABCEXTERNAL=my-abc && make ABCEXTERNAL=my-abc install
configures yosys to use an external ABC executable instead of
building and installing the in-tree ABC copy (yosys-abc).
=> Support calling out to an external ABC.

passes/tests/test_autotb.cc, tests/tools/autotest.sh
Testbench writes output dumps instead of redirected STD to file.
No need to grep #OUT#
DUT ERROR prints don't pollute output dump.
I have tested this fix with vsim and iverilog.
**xsim needs to be fixed.** I don't have ability test how to pass defines to xsim.
=> Fix for issue #164

passes/hierarchy/hierarchy.cc
The `hierarchy_worker` function in `passes/hierarchy/hierarchy.cc` fills a `std::set` with pointers to modules to expand.  Because it does not specify a comparison function, pointer comparison will be used, leading to undeterministic ordering in the set.  Unfortunately, expanding the modules in different orders lead to differences in the BLIF output that affects the placing and routing of arachne-pnr.  Thus, it is possible for the same design to fail to route on one system and route OK on a different system even though the versions and options of yosys and arachne-pnr are identical.
Long story short, I think that `IdString::compare_ptr_by_name` should be used here to ensure deterministic output.
=> Made the expansion order of hierarchy deterministic

frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y, kernel/rtlil.cc, kernel/rtlil.h
Hi Clifford,
I've put together some code which enables having packages in separate files with localparams. This is a pretty common thing to do in SystemVerilog. The behaviour seems to be correct after the changes. I don't expect that you accept the pull request right away, but I'm looking for feedback.
At first I made a global vector with all packages, but this did not fit well with the "Design" concept, so therefore I had to add a package-vector as a member of the Design struct. This requires including "ast.h" in rtlil.h
It is not very efficient to always copy all members of every package to every module, but to change this, I wanted to (in simplify) check if the identifier-name contains "::", and in that case include all members of the corresponding packages in current_scope. This would …
=> Added support for SystemVerilog packages with localparam definitions

frontends/verilog/verilog_parser.y
Hi Clifford,
A lot of SV code uses the following syntax in the module port definition list:
input logic signal1,
etc.
I removed the check that makes read_verilog fail when it encounters this for SV. Do you think this has any negative implications? I have not completely been able to grasp how you treat wire and reg differently in yosys, and what implications this will have for "logic".
Cheers,
Ruben
=> Allow defining input ports as "input logic" in SystemVerilog

backends/json/json.cc
This allows gp4par to automatically discover the top module as marked by Yosys, instead of requiring the user to provide it explicitly.
=> write_json: also write module attributes

Makefile, kernel/yosys.cc
Both aranche-pnr and Icestorm allow one to link against libraries and install into the MSYS2 hierarchy without modification by just running the `gcc` config. For various reasons, this does not work with yosys. Because I would prefer to keep programs compiled with gcc under a single hierarchy, like a Unix installation, and because I may need to make further changes to yosys (openfpga work), I added a target that allows MSYS compilation.
As of this commit, this now means it is possible to successfully build a native yosys on Windows. There is currently a minor issue when building any target:
```
couldn't read file "/proc/17844/fd/63": no such file or directory
couldn't read file "/proc/17764/fd/63": no such file or directory
```
While MSYS2 does come with a `/proc` file system, it doesn't …
=> Add MSYS2-compatible build.

Makefile
These two commits add some flexibility to the build process without compromising the default operation.
Adding a variable for the URL of the ABC Mercurial repository allows a user to override the default location in the case where the user is privately mirroring the ABC repository.
The second commit allows yosys to be a submodule. Currently, if yosys is a submodule, the YOSYS_VER variable is not properly set. More specifically, the number of commits since the last tag is left off due to the "test" command returning false.
=> Add some useful flexibility to build process

Makefile
In this way Debian scripts can define it as berkeley-abc from the shell.
=> Allow to overwrite ABCEXTERNAL from the environment.

backends/firrtl/firrtl.cc
Forgot to assign to wmask. With this change and ucb-bar/firrtl#379 and ucb-bar/firrtl#380, test.v is proven equivalent to test_out.v.
=> Bugfix: include assign to write-mask

Makefile
On some Linux systems, -lcurses is required in addition to -lreadline. LINK_CURSES adds this (optionally) both to yosys and abc. This is a problem that has been recognized by ABC as well on their [bitbucket page](https://bitbucket.org/alanmi/abc).
I'm not sure if this is the best way to go about adding it, but I think it's a good start.
=> Added optional flag for linking curses with readline.

passes/hierarchy/hierarchy.cc
While reading through the hierarchy pass in the course of writing a Yosys plugin, I discovered this tiny bit of dead code. (It could technically be even shorter perhaps, but probably not without sacrificing readability.)
Passed `make test` on amd64/Linux.
=> Delete some dead code in the Hierarchy pass

Makefile, README.md
I use MacPorts on my machine which gives me a lot of "command not found: brew" warnings during compilation.
This is because `brew` is called everytime for generating the compiler flags.
`brew`should be called only once. And only of available..
=> Use Homebrew only if installed

Makefile
Running make uninstall used to fail to remove binaries:
```shell
rm -vf /usr/local/binyosys /usr/local/binyosys-config #...etc
```
Fix Makefile so that it runs a command like this:
```shell
rm -vf /usr/local/bin/yosys /usr/local/bin/yosys-config #...etc
```
=> Add missing slashes in paths for make uninstall

examples/intel/DE2i-150/quartus_compile/de2i.qpf, examples/intel/DE2i-150/quartus_compile/de2i.qsf, examples/intel/DE2i-150/quartus_compile/runme_quartus, examples/intel/DE2i-150/run_cycloneiv, examples/intel/DE2i-150/sevenseg.v, examples/intel/DE2i-150/top.v, examples/intel/MAX10/run_max10, examples/intel/MAX10/runme_postsynth, examples/intel/MAX10/sevenseg.v, examples/intel/MAX10/top.v, examples/intel/asicworld_lfsr/README, examples/intel/asicworld_lfsr/lfsr_updown.v, examples/intel/asicworld_lfsr/lfsr_updown_tb.v, examples/intel/asicworld_lfsr/run_cycloneiv, examples/intel/asicworld_lfsr/run_max10, examples/intel/asicworld_lfsr/runme_postsynth, examples/intel/asicworld_lfsr/runme_presynth, techlibs/altera_intel/Makefile.inc, techlibs/altera_intel/cycloneiv/cells_comb_cycloneiv.v, techlibs/altera_intel/cycloneiv/cells_map_cycloneiv.v, techlibs/altera_intel/lpm_functions.v, techlibs/altera_intel/max10/cells_arith_max10.v, techlibs/altera_intel/max10/cells_comb_max10.v, techlibs/altera_intel/max10/cells_map_max10.v, techlibs/altera_intel/synth_intel.cc
Dear Clifford,
I have:
- Removed the Quartus project copyright.
- Cleaned the iverilog outputs.
- Keeping Yosys version (0.7).
- Doing a clean pull request.
I suggest the following text in CHANGELOG, but is up to you if you want to modify for something else:
- Added Contributor dh73, Code of Conduct.
- Added initial version of metacommand "synth_intel".
- Improved write_verilog command to produce VQM netlist for Quartus Prime.
- Added support for MAX10 FPGA family synthesis.
- Added support for Cyclone IV family synthesis.
- Added example of implementation for DE2i-150 board.
- Added example of implementation for MAX10 development kit.
- Added LFSR example from Asic World. 
Looking forward to see if this request satisfies the criteria now.
=> Add initial support for both MAX10 and Cyclone IV (E|GX) FPGAs

passes/opt/opt_merge.cc
This is the same you did for $tribuf but applied to $_TBUF_ (I'm using iCE40HX4K FPGAs)
=> Excluded $_TBUF_ from opt_merge pass

Makefile
To remove the files generated during the test. So we can go back to a fresh state.
=> Added the test outputs to the clean target

Makefile, kernel/hashlib.h
* Allow using libtermcap rather than ncurses
* Fix build failures without `-fpermissive` on Win64
=> Miscellaneous build tweaks

passes/opt/Makefile.inc, passes/opt/opt_rmports.cc, passes/opt/rmports.cc
This is a special-use optimization pass (should NOT be called by default when the "opt" command is run) that deletes all top-level ports in the design that have no cells connected to them.
=> Added opt_rmports pass

kernel/rtlil.cc, kernel/rtlil.h, passes/techmap/alumacc.cc, passes/techmap/dfflibmap.cc, passes/techmap/techmap.cc
These are some minor edits to help retain source line tracking information on cells through some of the synthesis passes, i.e. propagate "src" attributes from original cells to the derived cells they are being replaced with.
=> Add support for source line tracking through synthesis phase

passes/opt/Makefile.inc, passes/opt/opt_demorgan.cc
This pass replaces "reduce_and" or "reduce_or" cells in which >50% of the inputs are driven by NOT gates with their DeMorgan equivalents, to reduce area consumed by inverters.
=> Added "opt_demorgan" pass (fixes #408)

passes/techmap/extract_reduce.cc
This is easily triggered when un-techmapping if the technology-specific
cell library isn't loaded. Outputs of technology-specific cells will be
seen as inputs, and nets using those outputs will be seen as undriven.
Just ignore these cells because they can't be part of a reduce chain
anyways.
=> extract_reduce: Fix segfault on "undriven" inputs

passes/techmap/extract_reduce.cc
Added an optional, non-default argument that makes "extract_reduce" infer a reduction operation even if intermediate gates in the reduction chain drive other logic. This can lead to needless replication of logic and an increase in design area, but is a useful intermediate in coarse-grained synthesis and reverse engineering flows.
=> Added support for off-chain loads in extract_reduce

frontends/ast/simplify.cc, tests/simple/functions01.sv
Reminder:
These are SystemVerilog extensions:
$size() yields the width of its argument (See IEEE-1800-2012 section 20.7)
$bits() yields the total number of bits of its argument (See IEEE-1800-2012 section 20.6.2)
For 1D bit vectors, these functions are the same.
For memories, $size() will yield the memory width while $bits() will yield the total number of bits taken to store this array.
I also added a small testcase to check the new functions, with assertions:
```
read_verilog -sv tests/simple/functions01.sv
sat -prove-asserts
```
The feature could use some further testing, using more complex expressions as arguments.
The 6 individual commits are just part of my working history. You can squash them to one commit.
I intend to keep adding SystemVerilog design features. I'm already working …
=> Add $bits() and $size()

frontends/ast/ast.cc, frontends/ast/ast.h
This is really a minor PR.
While working on a different change I wanted to create a const AstNode to be sure I'm not modifying it, only to discover I can't dump it.
After changing dumpAst() and dumpVlog() to const, I tagged a few other functions which are also clearly const.
This also passed 'make test'
=> Turned a few member functions into const, esp. dumpAst(), dumpVlog().

passes/opt/opt_reduce.cc
Test unit.
```
module test(input [3:0] a, input [3:0] b, output w);
assign w = |{a[3], a[1], a[2], a[0], b[3], b[1], b[2], b[0]};
endmodule
```
Now: New input vector for $reduce_or cell $reduce_or$mini_redu.v:2$1: { \a [0] \a [1] \a [2] \a [3] \b [0] \b [1] \b [2] \b [3] }
Fixed to: New input vector for $reduce_or cell $reduce_or$mini_redu.v:2$1: { \b \a }
=> Fix input vector for reduce cells.

techlibs/ice40/cells_sim.v
This adds `SB_MAC16`, `SB_SPRAM256KA`, `SB_HFOSC`, `SB_LFOSC` and `SB_RGBA_DRV` to the ice40 `cells_sim.v`.
It does not yet contain simulation models or any support for inference for any of these new primitives.
=> Add UltraPlus specific cells to ice40 techlib

techlibs/ice40/cells_sim.v
This adds support for all of the iCE40 UltraPlus cells not added in the previous pull request, including the I2C and SPI hard IP. It also adds SB_IO_OD and SB_IO_I3C and simulation models for these (which in both cases were trivial changes to the existing SB_IO model).
=> Add remaining UltraPlus cells to ice40 techlib

techlibs/ice40/cells_sim.v
This PR fixes two mistakes that were preventing Icarus from being able to parse the `SB_IO_OD` module:
* Removes the trailing comma at the end of the port list. Although Yosys supports this syntax, Icarus doesn't seem to and it's inconsistent with all the other modules in `ice40/cells_sim.sv`.
* Fixes port names inside the body of the module - the port names are declared without underscores (and although this is inconsistent with the similar `SB_IO` module, it is correct according to the technology library PDF and existing code on the Internet) but the body attempted to refer to the ports with underscores in the names.
=> Fix SB_IO_OD module

kernel/celltypes.h, kernel/cost.h
I'm building Yosys using Bazel, and I noticed that you're using <> includes for some non-system headers. Changing this makes it easier to build since Bazel can be picky about how files get included.
=> Use quote includes for yosys.h

passes/techmap/libparse.cc
Patch to fix expressions used in value for properties in the liberty file. I will need to push similar patch to abc for full support.
=> Value of properties can be expression.

Makefile
This PR fixes [link issues](https://bitbucket.org/alanmi/abc/issues/77/link-error-when-building-on-msys2-mingw) I had with `abc` after a long period of not updating `yosys`. Just tested on current `HEAD` on `master`, I've had this fix since November, but I forgot to make a PR up to this point (sorry!) :).
=> Improve msys2 flags for building abc.

kernel/yosys.cc
Create TCL alias for rename command.  Using renames.  Following the same convention as proc -> procs.
=> Rename rename to renames

techlibs/coolrunner2/Makefile.inc, techlibs/coolrunner2/coolrunner2_sop.cc, techlibs/coolrunner2/synth_coolrunner2.cc, techlibs/coolrunner2/tff_extract.v
Rather than "properly" teaching  yosys and/or ABC to understand how to generate "XOR of SOP with a p-term" we use the hack from #398 to get simple counters "working for now." This time the hack is confined to the `techlibs/coolrunner2` directory. We may or may not want to still consider what to do with the general case (#378).
Before adding this hack, counters tended to generate a ridiculous number of product terms that would quickly overfill the CPLD. Now it only generates ~1 product term per bit.
=> coolrunner2: Improve optimization for TFF/counters

techlibs/achronix/Makefile.inc, techlibs/achronix/speedster22i/cells_map.v, techlibs/achronix/speedster22i/cells_sim.v, techlibs/achronix/synth_achronix.cc, techlibs/intel/cyclone10/cells_map.v, techlibs/intel/cycloneiv/cells_map.v, techlibs/intel/cycloneive/arith_map.v, techlibs/intel/cycloneive/cells_map.v, techlibs/intel/cyclonev/cells_map.v, techlibs/intel/max10/cells_map.v, techlibs/intel/synth_intel.cc
As per the recent changes in **__synth_intel.cc__** regarding the power up initialization of DFFEAS primitive, the missing parameter in the techlibs was making Quartus mapper fails. The generated netlist was incorrect.
I did corrected all the dffeas primitives in all the Intel families, but __tested only on Cyclone V__ since is the only hardware I have from such FPGA vendor. But also tried to compile the same working design after and before the changes and all of them are passing fine Quartus map.
* Achronix Speedster organization. Should work fine now.
* VPR implementation on Intel devices. For experiments and hopefully someone else could use it as well.
* Fixed Cyclone V lut functions map. The Yosys netlist can generate a working SOF file fur such device now.
This is the first commit …
=> Fixed broken Quartus backend on dffeas init value, and other updates.

frontends/verific/verific.cc
This is a follow up to https://github.com/YosysHQ/yosys/issues/516. By setting these runtime flags, users will get the expected results from the Verific frontend regardless of the flag values at compile time.
* veri_extract_multiport_rams enables RamNets so that the memories are preserved when importing to Yosys.
* veri_extract_dualport_rams needs to be disabled, because the two flags should not be used together.
* db_infer_wide_operators looks for wide operators instead of "bitblasting".
As far as I know, it makes sense to always use multiport rams. For everything I do, it also makes sense to set db_infer_wide_operators. It does disable some optimizations, but those simplifications could always be done in Yosys. Furthermore, based on the log file you provided in …
=> Set RAM runtime flags for Verific frontend

Makefile, README.md, tests/tools/autotest.sh
Changes (only for FreeBSD):
- ABC revision changed to revision from Feb 05 which supports FreeBSD
- removed <code>-ldl</code> - FreeBSD's <code>dlopen()</code> and similar functions are in libc
- paths: changed TCL include and library path
- tests: don't use <code>/bin/bash</code> directly, and use gmake for running test on FreeBSD
=> FreeBSD build

techlibs/ice40/cells_sim.v
The current code requires workarounds for several simulators
For modelsim, the file must be compiled with -mixedansiports and
xsim needs --relax.
=> Avoid mixing module port declaration styles in ice40 cells_sim.v

frontends/verilog/preproc.cc
These patches add support for the ``` `` ``` token-pasting operator in macros, and clean up whitespace handling (which becomes more important when using ``` `` ```).  I verified with:
```
`define ADD(a,b) a+b
`define CONCAT1(a,b) a``b
`define CONCAT2(a) test_``a
`define CONCAT3(a) a``_test
`define FOO foo
`define BAR bar
`define CONCAT4 `FOO```BAR
`define STRING(a) `"a`"
module test;
reg r0  = `CONCAT1(foo, bar);
reg r1  = `CONCAT2(xx);
reg r2  = `CONCAT3(yy);
reg r3  = `CONCAT4;
reg r4  = `ADD(1,2);
reg r5  = `ADD(1, 2);
reg r6  = `ADD(1,2 );
reg r7  = `ADD( 1,2);
reg r8  = `ADD( 1, 2);
reg r9  = `ADD( 1,2 );
reg r10 = `ADD(1 ,2);
reg r11 = `ADD(1 , 2);
reg r12 = `ADD(1 ,2 );
reg r13 = `STRING(hello);
endmodule
```
and compared the output of yosis, iverilog, and Verilog-Perl:
```
yosys …
=> Support SystemVerilog `` extension for macros

passes/cmds/stat.cc
The PR prints the name of the module when displaying the final area count.
Pros:
- Easier for the user to `grep` for area information about a specific module
Cons:
- Arguably more verbose, less "pretty" than what author may desire
Verification:
~~~~
30c30
<    Chip area for this module: 20616.349000
---
>    Chip area for module '$paramod$d1738fc0bb353d517bc2caf8fef2abb20bced034\picorv32': 20616.349000
70c70
<    Chip area for this module: 88.697700
---
>    Chip area for module '\picorv32_axi_adapter': 88.697700
102c102
<    Chip area for this module: 20705.046700
---
>    Chip area for top module '\picorv32_axi': 20705.046700
~~~~
=> Include module name for area summary stats

Makefile, backends/protobuf/.gitignore, backends/protobuf/Makefile.inc, backends/protobuf/protobuf.cc, misc/yosys.proto
This introduces a Google Protocol Buffer backend for Yosys.
The schema is kept similar to the JSON backend, but with a few important changes:
- signal numbers now start from 0, and constant signals are typed to their value
- AIG nodes are typed
Interestingly, these changes cause us to generate fairly large protos - larger than JSON! This is because we end up having a lot of repeated data (ie any bitvector must also specify a type for each member - whether it's a unique signal id, or a constant driver).
To test, compile Yosys with ENABLE_PROTOBUF=1 (you'll need protoc), and run:
yosys -p 'read_verilog ./tests/simple/aes_kexp128.v; write_protobuf -text'
This will spit out a Text Format protobuf to your terminal. For binary proto (ie. the main wire format), run:
yosys -p 'read_verilog …
=> Add Protobuf backend

frontends/ast/genrtlil.cc, kernel/log.cc, kernel/log.h
Provide a standardized warning/error logging which makes it much easier to develop verilog as it allows to step through the messages with IDEs, emacs or vi as they all know the `<filename>:<line>:<msg>` format that is also standardized in compilers such as gcc or clang.
I intend to survey all the places where we have a filename and line-number available in future pull requests, but for now just the base-work and a proof-of-concept place in genrtlil.
o Provide log_file_warning() and log_file_error() that prefix the log
message with `<filename>:<lineno>:` to be easily picked up by IDEs that
need to step through errors.
o Simplify some duplicate logging code in kernel/log.cc
o Use the new log functions in genrtlil.
=> Provide source-location logging.

frontends/ast/ast.cc, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/verilog/const2ast.cc
Mostly statements that span over multiple lines and haven't been
caught with the previous conversion.
=> Convert more log_error() to log_file_error() where possible.

README.md
Single quotes were used instead of backticks leading to incorrect formatting.
=> readme: Fix formatting of a keyword

backends/smt2/Makefile.inc
Use `os.path.realpath` instead to make sure symlinks are followed. This is also required to work for nix package manager.
=> Use `realpath` 

frontends/blif/blifparse.cc
Implements .cname and .conn per http://vtr-verilog-to-routing.readthedocs.io/en/latest/vpr/file_formats.html#conn
=> #565 Add BLIF parsing support for .conn and .cname

examples/basys3/example.xdc, examples/basys3/run_prog.tcl
Added `CONFIG_VOLTAGE` and `CFGBVS` to constraints file
to avoid warning `DRC 23-20`.
Added `open_hw` needed for programming.
=> fix basys3 example

Makefile
This way CC is gcc and CXX and LD is g++ as it is required to proper compile. 
Had to remove -DABC_USE_STDINT_H otherwise getting error that it is unsupported platform
=> Changes for MXE configuration in order to compile

Makefile
Added gcc-static for easier cross compilation, builds static executable.
make config-gcc-static
for aarch64:
make CC="aarch64-linux-gnu-gcc" CXX="aarch64-linux-gnu-g++"
for arm 32bit:
make CC="arm-linux-gnueabihf-gcc" CXX="arm-linux-gnueabihf-g++"
=> Static builds and cross-compilation support

passes/cmds/show.cc
This should be the last quality-of-life PR I need to make on `yosys` for a while, I promise! :)
Recently, msys2 got graphviz support, so now it's easy for a Windows user to use yosys not only to generate `.dot` files, but to also convert them to one's favorite display format!
When using the `system()` `stdlib.h` function, Windows is unable to understand/strip single quotes, as demonstrated in this example program:
```
William@William-THINK MINGW64 ~/src/yosys-experiments/example-011
$ ls
dummy.c   dummy.exe   example.v   manual.c   manual.exe   scripts   show.dot   show.png  "'show.png.new'"
William@William-THINK MINGW64 ~/src/yosys-experiments/example-011
$ cat manual.c
#include <stdlib.h>
int main()
{
system("dot -Tpng 'show.dot' > 'show.png.new' && mv 'show.png.new' 'show.png'"); …
```
=> `show` pass `-format` and `-viewer` improvements on Windows

frontends/ast/ast.cc, frontends/ast/ast.h, frontends/verilog/verilog_frontend.cc
This option disables the memory pointer display.
This is useful when diff'ing different dumps because otherwise the node pointers makes every diff line different when the AST content is the same.
I find this extremely useful when developing verilog frontend enhancements where I need to compare long AST dumps for subtle changes.
For example (before the PR):
```
-- Running command `read_verilog -sv -dump_ast1  tests/simple/always01.v' --
1. Executing Verilog-2005 frontend.
Parsing SystemVerilog input from `tests/simple/always01.v' to AST representation.
Generating RTLIL representation for module `\uut_always01'.
Dumping Verilog AST before simplification:
AST_MODULE <tests/simple/always01.v:1> [0x186a740] str='\uut_always01'
AST_WIRE <tests/simple/always01.v:3> [0x186aa50] str='\clock' input …
```
=> Added -no_dump_ptr flag for AST dump options in 'read_verilog'

Makefile
Missed this one, noticed that it is not actually static while compiling for arm
=> static link flag on main executable

backends/firrtl/firrtl.cc, frontends/verific/verificsva.cc
- add support for modules
- fix shift amounts (strictly unsigned, no padding required)
- don't constrict logical operator operands to result width
- issue 'is invalid' at wire definition, not during actual wiring
=> Add support for modules.

passes/cmds/setundef.cc
Adds default value option as -undef when -expose used. Not having set the value mode set can cause the setundef pass to abort (when trying to replace undef values).
=> Minor revision to -expose in setundef pass

backends/firrtl/firrtl.cc
IN and OUT are quite usual in system headers. Noticed at windows build
=> added prefix to FDirection constants, fixing windows build

techlibs/ecp5/dram.txt
Previously, ROMs were being mapped to distributed RAM, which was less efficient (wasting a slice for the unused write port) than just letting them become LUTs.
=> ecp5: Don't map ROMs to DRAM

passes/equiv/equiv_make.cc
I found that Yosys will create a combinational loop when running equiv_make given my example files. Some functions have been added to check whether a net is in the fanout cone of another net before committing the net substitution. Many thanks.
=> Fix issue #639

frontends/verilog/verilog_lexer.l
Modify verilog_lexer.l just to ignore the {protect, endprotect} markers.
=> Ignore protect endprotect

techlibs/xilinx/synth_xilinx.cc
Then if targeting vpr map all the Xilinx specific LUTs back into generic Yosys LUTs.
This makes LUT8 and LUT7 get converted to `LUT6` + `MUXF8` // `LUT6` + `MUXF7` when using vpr.
=> xilinx: Still map LUT7/LUT8 to Xilinx specific primitives when using `-vpr`

README.md, frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y, kernel/rtlil.cc, kernel/rtlil.h, passes/hierarchy/hierarchy.cc, tests/simple/svinterface1.sv
Hi Clifford,
This time doing the changes mostly in AST before RTLIL generation.
It seems to work correctly for several test cases. Also the normal yosys test suite passes.
It is a bit hard to add test cases in the normal way since iverilog does not support this yet.
=> Support for SystemVerilog interfaces and modports

backends/verilog/verilog_backend.cc
When generating verilog, the offset info of memories is not being used, generating a module that is not equivalent to the originally read one.
=> adding offset info to memories on verilog output

frontends/verilog/verilog_parser.y, tests/errors/syntax_err01.v, tests/errors/syntax_err02.v, tests/errors/syntax_err03.v, tests/errors/syntax_err04.v, tests/errors/syntax_err05.v, tests/errors/syntax_err06.v, tests/errors/syntax_err07.v, tests/errors/syntax_err08.v, tests/errors/syntax_err09.v, tests/errors/syntax_err10.v, tests/errors/syntax_err11.v, tests/errors/syntax_err12.v, tests/errors/syntax_err13.v
Currently, the Verilog/SystemVerilog parser has about 14 cryptic "Syntax error" messages.
This PR renames thosee generic "Syntax error" message from into unique, meaningful info on the error.
Also add 13 compilation examples that triggers each of these messages.
=> More meaningful SystemVerilog/Verilog parser error messages

frontends/ast/simplify.cc
$rose and $fell are, by spec, dependent upon the LSB only.  Yosys treats the multibit parameters of the two as |X instead of X[0].  This change fixes that.
=> Make rose and fell dependent upon LSB only

backends/smt2/smtio.py
The current use of of the smtbmc backend causes an exception on MacOS because the desired resource limits are not allowed. This patch makes them a little more conservative so the process can at least run, but this does mean large inputs may run out of stack on MacOS.
=> Use conservative stack size for SMT2 on MacOS

passes/techmap/dfflibmap.cc
Changed 'missing pin' error into a warning.  The corresponding cell is then ignored in the DFF map pass.
This allows Yosys to continue instead of aborting.
An attempt is made to tell the user whether the problem is caused by an expression in the Liberty FF attributes, or if the referenced pin is actually not defined in the cell.
This fix was successfully tested with 'tsl18fs120' .lib file.
=> DFFLIBMAP: changed 'missing pin' error into a warning.

Makefile
The Makefile assumes static libraries for Linux when building with Verific.
=> Use appropriate static libraries when building with Verific on MacOS

kernel/rtlil.h, passes/equiv/equiv_make.cc
Splits SigSpec into bits before calling check_signal_in_fanout in the equiv_make pass.
=> Splits SigSpec into bits before calling check_signal_in_fanout (solves #675)

techlibs/ice40/Makefile.inc, techlibs/ice40/ice40_opt.cc, techlibs/ice40/ice40_unlut.cc
Currently, `ice40_opt -unlut` would map SB_LUT4 to $lut and convert
them back to logic immediately. This is not desirable if the goal
is to operate on $lut cells. If this is desirable, the same result
as `ice40_opt -unlut` can be achieved by running simplemap and opt
after ice40_unlut.
This is a part of my work on #715.
=> Extract ice40_unlut pass from ice40_opt

techlibs/gowin/Makefile.inc, techlibs/gowin/arith_map.v, techlibs/gowin/cells_sim.v, techlibs/gowin/synth_gowin.cc, techlibs/intel/common/brams_map.v
I have added ALU primitive support, modify the synth_gowin command to handle the new primitive and started SP/SDP memory support as well.
Also, a minor modification on M9K.
=> Changes in GoWin synth commands and ALU primitive support

frontends/ast/simplify.cc
As per Verilog 2005 - 17.11.1.
Fixes #708
=> Make return value of $clog2 signed

passes/opt/opt_lut.cc, tests/opt/opt_lut_port.il, tests/opt/opt_lut_port.ys
=>  opt_lut: leave intact LUTs with cascade feeding module outputs

techlibs/ice40/synth_ice40.cc
I am currently looking at some optimizations to be done on iCE40 that would run on the coarse-grain cells. In this case it is very useful to me to be able to stop synthesis before all arch-dependent transformations, but after all arch-independent optimizations have already been done. I.e. see and affect the state just before techmapping, and restart afterwards.
Feel free to close this PR if this is not something desirable, or tell me to also implement this for other `synth_*` commands.
=> synth_ice40: split `map_gates` off `fine`

techlibs/ice40/cells_sim.v
In an initial statement, blocking assignments are normally used
and e.g. verilator throws a warning if non-blocking ones are used.
Yosys cannot however properly resolve the interdependencies if
blocking assignments are used in the initialization of SB_RAM_40_4K
and thus this has been used.
This patch will change to use non-blocking assignments only for yosys
=> Only use non-blocking assignments of SB_RAM40_4K for yosys

techlibs/ice40/ice40_ffssr.cc
This is useful if you want to place FF manually ... can't merge SR in those
because it might make the manual placement invalid
=> ice40: Honor the "dont_touch" attribute in FFSSR pass

passes/memory/memory_bram.cc
In some cases the memory_bram pass shuffles the order of the bits in a
memory's RD_DATA port. Although the order of the bits in the WR_DATA and
WR_EN ports is changed to match the RD_DATA port, the order of the bits
in the initialization data is not.
This causes reads of initialized memories to return invalid data (until
the initialization data is overwritten).
This commit fixes the bug by shuffling the initdata bits in exactly the
same order as the RD_DATA/WR_DATA/WR_EN bits.
=> memory_bram: Fix initdata bit order after shuffling

passes/equiv/Makefile.inc, passes/equiv/equiv_opt.cc, techlibs/ice40/cells_sim.v, tests/lut/check_map.ys, tests/opt/ice40_carry.v, tests/opt/opt_lut.ys
When writing optimization passes I heavily rely on `equiv` commands to verify correctness. I have a few scripts for that locally, but Yosys scripts are not very flexible, and I feel this is in general a very useful shortcut command to have. This is also quite useful for tests.
=> equiv_opt: new command, for verifying optimization passes

passes/techmap/deminout.cc
Fixes for issues raised in YosysHQ/nextpnr#176
- Consider constant drivers in `deminout` so constant driven signals aren't demoted to inputs
- Treat word-level `$tribuf` the same as `$_TBUF_` in `deminout`, as `synth_ice40` runs `deminout` on the word-level netlist
=> deminout fixes

Makefile
Correct me if I'm wrong, and I don't see that the use of this tool is GNU awk specific. Also on linux systems awk is usually a symbolic link to gawk.
*I'm propose this change as it will allow me to build this on OSX with minimum of dependencies*
=> Using awk rather than gawk

backends/verilog/verilog_backend.cc, passes/cmds/select.cc
This is useful for sanity checks in batch scripts. This functionality cannot be replaced with `select -list` because `-list` does not output anything if `-q` is passed to `yosys`.
=> select: print selection if a -assert-* flag causes an error

passes/memory/memory_dff.cc
Fixes #589 
This was preventing DFFs with an init value of X being merged in memory_dff
=> memory_dff: Fix typo when checking init value

techlibs/anlogic/drams.txt
The dbits of DRAM16X4 is wrong set to 2, which leads to waste of DRAM
bits.
Fix the dbits number in the RAM configuration.
=> anlogic: fix dbits of Anlogic Eagle DRAM16X4

techlibs/anlogic/Makefile.inc
During the addition of DRAM inferring support, the installation of
eagle_bb.v is accidentally removed.
Fix this issue.
=> anlogic: fix Makefile.inc

techlibs/anlogic/synth_anlogic.cc
According to the datasheet of Anlogic Eagle FPGAs, The LUTs natively
in an Anlogic FPGA is LUT4 (in MSLICEs) and "Enhanced LUT5" (in
LSLICEs). An "Enhanced LUT5" can be divided into two LUT4s.
So a LUT5 will cost around 2x resource of a LUT4, and a LUT6 will cost
2x resource of a LUT5.
Change the -lut parameter passed to the abc command to pass this cost
info to the ABC process.
=> Anlogic: let LUT5/6 have more cost than LUT4-

passes/memory/memory_collect.cc
The semantics of an RTLIL constant that has less bits than its declared bit width is zero padding. Therefore, if the output of memory_collect will be used for simulation, truncating 'x from the end of \INIT will produce incorrect simulation results.
For example, this is the `write_verilog` output for a 16-deep memory initialized at two first locations:
```verilog
reg [7:0] mem [15:0];
initial begin
mem[0] = 8'haa;
mem[1] = 8'h55;
mem[2] = 8'b0000000x;
mem[3] = 8'h00;
// [snip]
mem[15] = 8'h00;
end
```
And this is the `write_verilog` output after this patch:
```verilog
initial begin
mem[0] = 8'haa;
mem[1] = 8'h55;
mem[2] = 8'hxx;
// [snip]
mem[15] = 8'hxx;
end
```
The former listing is clearly incorrect, and the bug is caused by, I believe, the fact that RTLIL doesn't appear to have the …
=> memory_collect: do not truncate 'x from \INIT

kernel/yosys.cc
E.g.:
```tcl
puts "argument count: $argc"
puts "argument 0: [lindex $argv 0]"
puts "script name: $argv0"
```
```
tcl test.tcl hello world
```
```
-- Running command `tcl test.tcl hello world' --
argument count: 2
argument 0: hello
script name: test.tcl
```
=> tcl: add support for passing arguments to scripts

manual/CHAPTER_CellLib.tex, manual/CHAPTER_Overview.tex
See inline comments for a few things that I've had to infer from code, and not sure whether my guess is the same as the authoritative definition.
Semi-related, can we get rid of non-free fonts in the Yosys manual? Not only they are non-free but the installation process, as is typical with LaTeX, is prone to obscure failures. I have eventually realized that I had to run the commands from README exactly as stated, with sudo, because it looks like installing to `$HOME` is broken, but that took a while...
=> manual: document $meminit cell and memory_* passes

kernel/rtlil.cc, kernel/rtlil.h, passes/proc/proc_clean.cc
Previously, only completely empty switches were removed.
This is a seemingly simple change with surprisingly far reaching consequences and motivation, so bear with me for a bit.
The immediate effect of this seemingly simple change, using Boneless CPU as a benchmark, is that the LUT count goes up: from 475 to 511 on one specific instantiation. This points to a larger inefficiency in mux tree optimization.
However! The motivation for adding this (and, later, I'd like to add further simplifications) to `proc_clean` is quite complicated, and is mostly because of the behavior of Verilog simulators. Specifically, nMigen would emit all of its logic into one giant RTLIL process, which ends up as a giant `always @*` block after `write_verilog`, plus a few `always @(posedge)` blocks that actually …
=> proc_clean: remove any empty cases, if possible to do safely

techlibs/anlogic/cells_map.v
Add latch cells to Anlogic cells replacement library by copying other
FPGAs' latch code to it.
=> anlogic: add latch cells

passes/opt/opt_lut.cc, tests/opt/opt_lut_elim.il, tests/opt/opt_lut_elim.ys, tests/opt/opt_lut_port.ys
This doesn't fire all that often, but it at least fires on every adder with carry out (even with ABC).
=> opt_lut: eliminate LUTs evaluating to constants or inputs

passes/opt/opt_expr.cc, tests/opt/opt_expr_cmp.v, tests/opt/opt_expr_cmp.ys
See individual commit messages. Only the first and the last commit intend to introduce any functional change; the rest is just refactoring, although I think it would incidentally avoid some aborts the original code warns about.
=> opt_expr: refactor and improve simplification of comparisons

passes/cmds/Makefile.inc, passes/cmds/bugpoint.cc
A typical use of `bugpoint` would involve a script with a pass under test, e.g.:
flowmap -relax -optarea 100
and would be invoked as:
bugpoint -yosys ./yosys -script flowmap.ys -clean -cells
This replaces the current design with the minimal design that still crashes the `flowmap.ys` script.
`bugpoint` can also be used to perform generic design minimization using `select`, e.g. the following script:
select i:* %x t:$_MUX_ %i -assert-max 0
would remove all parts of the design except for an unbroken path from an input to an output port that goes through exactly one `$_MUX_` cell. (The condition is inverted.)
=> bugpoint: new pass

passes/proc/proc_clean.cc
=> proc_clean: fix fully def check to consider compare/signal length

passes/proc/proc_clean.cc
This fixes a one character typo in proc_clean introduced in #793 that completely broke it. I apologize.
=> proc_clean: fix critical typo

backends/firrtl/firrtl.cc, tests/asicworld/run-test.sh, tests/asicworld/xfirrtl, tests/simple/xfirrtl, tests/tools/autotest.mk, tests/tools/autotest.sh
Issue warning messages for missing parameterized modules and attempts to set initial values.
Replace simple "if (cell-type)" with "else if" chain.
Fix FIRRTL shift handling.
Add support for parameterized modules, $shift, $shiftx.
Handle default output file.
Deal with no top module.
Automatically run pmuxtree pass.
Allow EXTRA_FLAGS and SEED parameters to be set in the environment for tests/tools/autotest.mk.
Support FIRRTL regression testing in tests/tools/autotest.sh
Add xfirrtl files to test directories to exclude files from FIRRTL regression tests that are known to fail.
=> Update cells supported for verilog to FIRRTL conversion.

passes/cmds/setundef.cc
This enables synthesis output to tools that require that all parameter values have a particular value, but is more generic than something like https://github.com/YosysHQ/yosys/blame/master/techlibs/anlogic/anlogic_determine_init.cc#L26.  I was considering adding a parameters filter, but I'm not convinced it is required beyond the existing "select" mechanism.
=> Add -params mode to force undef parameters in selected cells.

passes/techmap/abc.cc, techlibs/ecp5/synth_ecp5.cc, techlibs/ice40/synth_ice40.cc
- Better recovered netnames, don't use log_signal as this was adding spaces
- Copy `src` attribute for use with `rename -src`
- Use `abc -dress` by default in the basic part of `synth_ice40` (not when retiming, as this doesn't seem to work)
I'd like to test this a bit more before merging.
=> Improve ABC netname preservation 

passes/opt/wreduce.cc, tests/opt/opt_ff.v, tests/opt/opt_ff.ys
Adds test case that fails without code change.
Fixes #823
=> Fix WREDUCE on FF not fixing ARST_VALUE parameter.

backends/firrtl/firrtl.cc, tests/asicworld/xfirrtl, tests/simple/xfirrtl, tests/tools/autotest.sh
Don't emit subfield assignments: `bits(x, y, z) <= ...` - but instead, add them to the `reverse-wire-map` where they'll be treated at the end of the module.
Enable tests which were disabled due to incorrect treatment of subfields.
Assume the `$firrtl2verilog` variable contains any additional switches to control verilog generation (i.e. `--no-dedup -X mverilog`)
=> Fix FIRRTL to Verilog process instance subfield assignment.

techlibs/ice40/brams_map.v
This was leading to some issues in mapping in symbiflow. I could address with another tech mapping, but I think this is more precise, since is should only take on 4 values.
=> ice40: use 2 bits for READ/WRITE MODE for SB_RAM map

backends/firrtl/firrtl.cc, tests/simple/xfirrtl
This change to fid() (call make_id()) wasn't incorporated in the previous firrtlfixes. Do so now.
Mark dff_init.v as expected to fail since it uses "initial value".
=> Ensure fid() calls make_id() for consistency; tests/simple/dff_init.v fails

techlibs/ecp5/ecp5_ffinit.cc
This is not even a warning in the vendor tools; and all other init-related issues are currently warnings. 
This leaves the conflicting values unprocessed, so that a `check -assert -noinit` can make these errors if needed.
=> ecp5: Demote conflicting FF init values to a warning

backends/smt2/smt2.cc, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/verific/verificsva.cc, frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y
Things like `foo: assert(bar)` should now work as expected.
=> Add support for using SVA labels in yosys-smtbmc console output

techlibs/ice40/Makefile.inc, techlibs/ice40/cells_sim.v, techlibs/ice40/ice40_braminit.cc, techlibs/ice40/synth_ice40.cc
This adds a INIT_FILE attribute to the SB_RAM40_4K blocks that will
initialize content from a hex file. Same behavior is imlemented in the
simulation model and in a new pass for actual synthesis
=> iCE40 BRAM primitives init from file

.gitignore, backends/smt2/Makefile.inc, misc/launcher.c
This is the complement PR to the [one](https://github.com/YosysHQ/SymbiYosys/pull/32) I made for SymbiYosys. Now `yosys-smtbmc` can be used from either a msys2 `bash` prompt or from `cmd.exe` or `powershell.exe` :).
In principle, I can also convert `yosys-config`, but seeing as you already need a `bash` prompt to _compile_ `yosys` natively on Windows (without using the MSVC fork), I don't see much point in making compiling plugins usable from `cmd.exe`/`powershell.exe`.
=> Install launcher executable when running yosys-smtbmc on Windows.

backends/ilang/ilang_backend.cc, frontends/ast/genrtlil.cc
This dramatically improves the way we handle `full_case` attributes, by not eagerly handling them right in the Verilog front-end.
This change reduces the size of PicoRV32 in it's default configuration by 6% on iCE40: 1915 LUTs vs 1802 LUTs. (Feel free to track down where that difference comes from. I'm not spoiling it here. But I'll say this much: It's a *really* stupid QoR / miscompilation bug.)
=> Improve handling of "full_case" attributes

kernel/celltypes.h, kernel/rtlil.cc, passes/sat/Makefile.inc, passes/sat/fmcombine.cc
This can be used to significantly improve solving time in cases where a formal testbench contains two instances of the same module and feeds them almost identical inputs.
=> Add fmcombine pass

README.md
As discussed on Reddit, test execution fails with iverilog version 10.1 (which is the current Ubuntu 18.04 default). With version 10.1, make test fails at svinterface1 with a seg fault, providing no useful information on how to resolve this.
This note should prompt people running into this issue to build a recent iverilog version to resolve the svinterface tests to pass.
=> Add note about test requirements in README

frontends/ast/simplify.cc, tests/simple/generate.v
This addresses an issue where Yosys would fail to resolve items declared within a generate block loop's scope that were used within an `AST_PREFIX` node in that scope.
I have very limited experience with Yosys and HDLs in general, so feedback is greatly appreciated!
=> fix local name resolution in prefix constructs

techlibs/xilinx/cells_xtra.sh, techlibs/xilinx/cells_xtra.v
The order of a couple of RAM primitives also changed. I think that's just because of manual changes to the Verilog & the script not being re-run.
=> xilinx: Add keep attribute where appropriate

passes/techmap/libparse.cc, passes/techmap/libparse.h, tests/liberty/.gitignore, tests/liberty/busdef.lib, tests/liberty/normal.lib, tests/liberty/run-test.sh, tests/liberty/semicolmissing.lib, tests/liberty/small.v
* Updated the liberty parser to accept [A:B] ranges (AST has not been updated).
* Liberty parser now also accepts key : value pair lines that do not end in ';'.
* Added tests.
Prepares for fixing https://github.com/YosysHQ/yosys/issues/825.
Should fix reading of non-standard liberty files: https://github.com/YosysHQ/yosys/issues/894.
=> Liberty parser: Accept ranges [A:B], and ignore missing ';'.

passes/memory/memory_bram.cc
See discussion in #846 
- Will not make transparent logic if read & write clock domains differ
- When both make_outreg and make_transp are in affect, register is put on the address port (and data left unregistered), and transparent bypass logic is not created.
=> memory_bram: Fix multiclock make_transp

passes/proc/proc_mux.cc
I'd like opinions on this `$pmux` to `$shiftx` optimisation inside `proc_mux`
Doing so transforms the following circuit:
```
module top (CLK, SEL, SI, DO);
parameter SELWIDTH = 2;
parameter DATAWIDTH = 1;
input    CLK;
input [DATAWIDTH-1:0] SI;
input [SELWIDTH-1:0] SEL;
output [DATAWIDTH-1:0] DO;
localparam DATADEPTH = 2**SELWIDTH-1; // Note minus 1 so isn't a complete case
reg [DATAWIDTH-1:0] data [DATADEPTH-1:0];
generate
genvar i;
for (i = 0; i < DATADEPTH; i=i+1) begin
always @(posedge CLK)
begin
if (i == 0)
data[i] <= SI[i];
else
data[i] <= data[i-1];
end
end
assign DO = data[SEL];
endgenerate
endmodule
```
from creating this on master @ ccfa2fe:
to creating this:
Are there any side effects to this?
The advantage is that this makes analysis much easier downstream...
=> RFC: Add a pmux-to-shiftx optimisation to proc_mux

passes/memory/memory_bram.cc
The register for the address signals used in the expansion mux wasn't considering the read enable previously.
Thanks @smunaut for finding
=> memory_bram: Consider read enable for address expansion register

passes/proc/proc_mux.cc
=> proc_mux: Fix crash when trying to optimize non-existant mux to shiftx

passes/memory/memory_bram.cc
This was a latent defect revealed by #903 causing things like the picorv32 register file to break, as make_transp wasn't being set on the second read port (but also wasn't being erroneously copied in the wrong place as before, either).
=> memory_bram: Fix multiport make_transp

passes/proc/proc_rmdead.cc, tests/various/muxcover.ys
Reverts YosysHQ/yosys#932; see #935 of breakage.
=> Revert "Recognise default entry in case even if all cases covered (fix for #931)"

passes/proc/proc_mux.cc
Causes issues such as #918.
See discussion in #927.
Consider https://github.com/YosysHQ/yosys/tree/pmux2shiftx to supersede...
=> Revert #895 (mux-to-shiftx optimisation)

README.md, frontends/ast/ast.cc, frontends/ast/ast.h, frontends/verilog/verilog_frontend.cc, frontends/verilog/verilog_frontend.h, frontends/verilog/verilog_parser.y, passes/techmap/techmap.cc, tests/tools/autotest.sh, tests/various/hierarchy.sh
```
-noblackbox
do not automatically add a (* blackbox *) attribute to an
empty module.
-lib
only create empty blackbox modules. This implies -DBLACKBOX.
modules with the (* whitebox *) attribute will be preserved.
(* lib_whitebox *) will be treated like (* whitebox *).
-nowb
delete (* whitebox *) and (* lib_whitebox *) attributes from
all modules.
```
Without `-lib` it automatically deletes `(* lib_whitebox *)` attributes. You can even do for example `(* whitebox, lib_whitebox = 0 *)`.
=> New behavior for read_verilog handling of whiteboxes

passes/opt/Makefile.inc, passes/opt/pmux2shiftx.cc, tests/various/pmux2shiftx.v, tests/various/pmux2shiftx.ys
Consider the following test design (`tests/various/pmux2shiftx.v` in this branch):
```
module pmux2shiftx_test (
input [2:0] S1,
input [5:0] S2,
input [9:0] A, B, C, D, D, E, F,
input [9:0] G, H, I, J, K, L, M, N,
output reg [9:0] X
);
always @* begin
case (S1)
3'd0: X = A;
3'd1: X = B;
3'd2: X = C;
3'd3: X = D;
3'd4: X = E;
3'd5: X = F;
3'd6: X = G;
3'd7: X = H;
endcase
case (S2)
6'd46: X = I;
6'd47: X = J;
6'd48: X = K;
6'd52: X = L;
6'd53: X = M;
6'd54: X = N;
endcase
end
endmodule
```
The command `./yosys -p 'prep; pmux2shiftx; opt; stat' tests/various/pmux2shiftx.v` synthesizes this into a circuit with the following stats:
```
=== pmux2shiftx_test ===
Number of wires:                 22
Number of wire bits:            192
Number of public wires:          17
Number of public wire …
```
=> Add pmux2shiftx command

frontends/ast/simplify.cc, tests/sat/counters-repeat.v, tests/sat/counters-repeat.ys
I changed the `sat/counters` test to use repeat instead of for, and it seems to work. I noticed that the test ran much slower (about ~0.2s vs. ~1.3s), so I imagine I'm missing something important here.
Feedback is greatly appreciated!
=> support repeat loops with constant repeat counts outside of constant functions

techlibs/gowin/synth_gowin.cc
Make nobram to false, to make it same as for other architectures.
Right not it is not possible to make yosys actually use bram due to this.
Also makes testing of parts of code for bram instantiation possible.
=> Make nobram false by default for gowin

techlibs/ice40/cells_sim.v
This is as a result of @whitequark and I abusing some iCE40s for a while. [Useful part of thread starts here](https://twitter.com/whitequark/status/1117916172442316800). Here is a testbench containing the 5th and 6th test from that thread:
```
module tb;
reg e, clk;
wire q;
SB_IO #(
.PIN_TYPE (6'b01_00_00)
//            |  |
//            |  \-------- DDR output
//            \----------- Permanent output enable
) inst_SB_IO (
.CLOCK_ENABLE      (e),
.OUTPUT_CLK        (clk),
.D_OUT_0           (1'b0),
.D_OUT_1           (1'b1),
.PACKAGE_PIN       (q)
);
localparam DELAY = 1000;
initial begin: stimulus
integer i;
{e, clk} = 2'b00;
for (i = 0; i < 5; i = i + 1) begin
#DELAY; {e, clk} = 2'b00;
#DELAY; {e, clk} = 2'b01;
#DELAY; {e, clk} = 2'b11;
#DELAY; {e, clk} = 2'b10;
end
#DELAY;
{e, clk} …
```
=> ice40 cells_sim.v: update clock enable behaviour based on hardware experiments

passes/techmap/attrmap.cc
Currently, `-remove foo` would only remove an attribute `foo = ""`, which doesn't work on an attribute like `src` that may have any value. Extend `-remove` to handle both cases. `-remove foo=""` has the old behavior, and `-remove foo` will remove the attribute with whatever value it may have, which is still compatible with the old behavior.
=> attrmap: extend -remove to allow removing attributes with any value

passes/opt/pmux2shiftx.cc, tests/various/pmux2shiftx.ys
Consider this example:
```
module test (
input [1:0] S,
input [5:0] A, B, C, D,
output reg [5:0] Y
);
always @* begin
Y = A;
case (S)
1: Y = B;
2: Y = C;
3: Y = D;
endcase
end
endmodule
```
With this change, `yosys -p 'prep; pmux2shiftx; opt; stat; show' test.v` will synthesize this to a single `$shiftx` cell, including handling of the default `A` input:
=> Add full_pmux feature to pmux2shiftx

frontends/aiger/aigerparse.cc, kernel/driver.cc, kernel/log.cc, kernel/log.h, kernel/register.cc, passes/cmds/trace.cc, passes/opt/opt_clean.cc, passes/opt/opt_expr.cc, passes/opt/opt_merge.cc, passes/opt/opt_muxtree.cc, passes/techmap/techmap.cc
This adds the new `log_debug()` API, and uses it in a few places to drastically reduce the number of log messages Yosys produces.
Use `yosys -g` or `debug <cmd>` to get the original behavior with many more debug messages.
The `log_suppressed()` API will generate log messages such as `<suppressed ~828 debug messages>`, informing the user that debug messages are available with `yosys -g` or `debug <cmd>`.
=> Add log_debug() framework

frontends/ast/simplify.cc
=> Determine correct signedness and expression width in for-loop unrolling

kernel/driver.cc, kernel/yosys.cc, kernel/yosys.h
filenames are sparated by spaces in the dep file.  if a filename in the
dep file contains spaces they must be escaped, otherwise the tool that
reads the dep file will see multiple wrong filenames.
=> escape spaces with backslash when writing dep file

frontends/ast/simplify.cc
Fixes this test case (per #968):
```
module test(i_value, o_value);
input	wire	[4:0]	i_value;
output	reg	[7:0]	o_value;
integer k;
always @(*)
begin
for(k=0; k<4; k=k+1)
o_value[k] = i_value[k];
o_value[4] = i_value[k];
o_value[5] = i_value[k];
o_value[6] = i_value[k];
o_value[7] = i_value[k];
end
endmodule
```
=> Add final loop variable assignment when unrolling for-loops

backends/firrtl/firrtl.cc, tests/memories/firrtl_938.v, tests/simple/xfirrtl
Add missing memory initialization.
Sanity-check memory parameters.
Add Cell pointer to memory object (for error reporting).
This should resolve #938
=> Fix #938 - Crash occurs in case when use write_firrtl command

tests/svinterfaces/runone.sh
Hi!
The svinterfaces testcases did not fail when yosys exited with a nonzero exit code. Instead, they continued and compared possibly out-of-date outputs.
Regards,
Jakob
=> fail svinterfaces testcases on yosys error exit

passes/opt/opt_clean.cc, passes/opt/opt_expr.cc
=> Improve opt_expr and opt_clean handling of (partially) undriven and/or unused wires

passes/techmap/dffinit.cc, techlibs/xilinx/synth_xilinx.cc
Fix for #982 
@cliffordwolf If this approach is acceptable, perhaps we should do this even when `-noreinit` is not specified?
=> dffinit to do nothing when (* init *) value is 1'bx

passes/techmap/abc.cc
- Fix accidental n² bug when finding original name
- Add handling for `new_` prefix and postfixes other than `inv`
Marking [WIP] because it could do with a bit of testing with things like retiming and other odd modes to make sure there aren't any issues like duplicate names.
Also to consider: should we be copying recovered netnames onto the driving cell too with a post/prefix like `driver_` (instead of using an arbitrary name) - this would result in a nicer critical path report.
=> ABC name recovery fixes

frontends/verilog/verilog_parser.y
As of Bison 2.6, name-prefix is deprecated. This fixes
frontends/verilog/verilog_parser.y:99.1-34: warning: deprecated directive, use ‘%define api.prefix {frontend_verilog_yy}’ [-Wdeprecated]
%name-prefix "frontend_verilog_yy"
For details: https://www.gnu.org/software/bison/manual/html_node/Multiple-Parsers.html
Compile tested only.
Signed-off-by: Ben Widawsky <ben@bwidawsk.net>
=> verilog_parser: Fix Bison warning

frontends/verific/verific.cc, frontends/verific/verific.h, passes/hierarchy/hierarchy.cc, tests/various/chparam.sh
* `verific -import -chparam <param> <value> <top_module(s)>` now imports top modules from Verific using their original (not parameterised) name
* `verific -import <top_module(s)>` now elaborates SV root modules in order to cope with bind statements therein
* `hierarchy -top` using Verific is now improved to not elaborate all modules (only specified module, and root modules)
* Added `hierarchy -chparam` support (only works for Verific so far)
* Also more testing in YosysHQ/yosys-tests#16
TODO:
* `hierarchy -chparam ...` support for non Verific
=> Improve verific -chparam and add hierarchy -chparam

kernel/yosys.cc, kernel/yosys.h
Hey all,
Just was scrolling through `yosys` and this caught my eye. Do you have any thoughts on how to properly incorporate this compiler-specific function? Would really like to land this push, as it leads to a speedup for your `ceil_log2` function. 
Proof:
```
int ceil_log2(int x) {
return (x > 0) * (32 - __builtin_clz(x-1) - (x == 1));
}
int ceil_orig_log2(int x) {
if (x <= 0)
return 0;
for (int i = 0; i < 32; i++)
if (((x-1) >> i) == 0)
return i;
}
```
compiles to:
```
ceil_log2(int):
lea edx, [rdi-1]
mov eax, 32
bsr edx, edx
xor edx, 31
sub eax, edx
xor edx, edx
cmp edi, 1
sete dl
sub eax, edx
xor edx, edx
test edi, edi
setg dl
imul eax, edx
ret
```
and
```
ceil_orig_log2(int):
push    rbp
mov     rbp, rsp
mov     DWORD PTR [rbp-20], edi
cmp     DWORD PTR [rbp-20], 0
jg      .L4
mov …
```
=> Optimize ceil_log2 function

kernel/rtlil.cc
Just caught my eye while reading through this code. Avoid double-lookups in the hash table.
=> Minor optimization to get_attribute_bool

backends/firrtl/firrtl.cc, kernel/rtlil.h, libs/minisat/Vec.h, passes/cmds/bugpoint.cc, passes/techmap/flowmap.cc
The most annoying warning was that the implicit copy assignment was not defined.
=> Fix all warnings that occurred when compiling with gcc9

passes/techmap/zinit.cc
In the help message for `zinit`, the option for setting all uninitialized FFs to zero in the initial state is called `-all`, but the code uses `-singleton`. This just updates the option handling to match the help message.
=> Zinit option '-singleton' -> '-all'

techlibs/ice40/cells_sim.v
=> ice40/cells_sim.v: Add support for TRIM input to SB_HFOSC

Makefile
While building yosys with libyosys+pyosys enabled in an isolated build environment (for distribution packaging), the install step fails at various places. I propose some fixes in this PR:
1. Installation fails at `strip libyosys.so`. This is caused by this copy line:
```
$(INSTALL_SUDO) cp libyosys.so $(DESTDIR)$(LIBDIR)
```
While on a regular system, this folder will exist (and `cp` will copy the file into it), in an isolated environment it might not. This makes libyosys.so end up as a file called 'lib' in $(DESTDIR)/$(PREFIX), and then the 'strip' command fails.
This PR explicitly creates the directory before copying, and also appends slashes to related copy-calls, making already the copy-step fail if the directory does not exist.
2. After fixing the first issue, calling `ldconfig` …
=> Create $(LIBDIR) to fix broken build in isolated environments

frontends/ilang/ilang_parser.y, frontends/verilog/verilog_parser.y
Cleanup.
The %union refers to types such as string or vector as well as e.g. Ast; the generated *.tab.hh did not include the needed includes for that; the code happened to compile because the *.tab.hh were always included after the other headers.
This makes sure that the generated headers contain the necessary includes, so that the declared union refers to known types.
=> Make the generated *.tab.hh include all the headers needed

passes/cmds/cover.cc, passes/techmap/libparse.cc
o In cover.cc, the int-result of mkstemps() was assigned to a string
and silently interpreted as a single-character filename with a funny
value. Fix with the intent: assign the filename.
o in libparse.cc, an int was assigned to a string, but depending on
visible constructors, this is ambiguous. Explicitly cast this to
a char.
=> Fix two instances of integer-assignment to string.

frontends/verilog/verilog_parser.y, tests/simple/localparam_attr.v, tests/simple/param_attr.v
This PR adds to the Verilog frontend support for attributes on the "parameter" and "localparam" statements.  Attributes are just accepted by the parser and their content is ignored. There are also tests added regarding this functionality (under `tests/simple`)
Fixes #1009
=> Support for attributes on parameters and localparams for Verilog frontend

frontends/verilog/Makefile.inc
Hit parser limit with 3M gate design. This commit fix it.
=> Read bigger Verilog files.

techlibs/xilinx/drams.txt
Fixes #1033.
Logic behind `min wrports` is that there is no point inferring a hard ROM when soft LUTs are the ultimate ROM anyway, and leaving them as soft LUTs means it can be optimised by ABC.
=> Add "min bits" and "min wports" to xilinx dram rules

.gitignore
Generated files are just added to .gitignore to prevent them adding by accident (specially cc one)
=> Add files to ignore for python build

passes/opt/opt_rmdff.cc, tests/various/opt_rmdff.v, tests/various/opt_rmdff.ys
Fixes #1034.
In particular, flops with constant enables that are never high (according to enable polarity) will get optimised away to their INIT value (or if one doesn't exist, to nothing at all).
=> opt_rmdff to work on $dffe and $_DFFE_*

kernel/log.cc, passes/opt/opt_clean.cc
Also fixes the log_error issue described in #1023.
Replaces #1025. I think we should only keep zero-width wires when they are module ports. (In those cases removing the port would have unwanted consequences, such as breaking positional arguments. The other option would be to call `Module::fixup_ports()` at the end of `opt_clean`, if we really wanted to remove those ports. I see no reason to keep a zero-width wire that isn't a port, even when it has the `keep` attribute set.)
=>  Keep zero-width wires in opt_clean if and only if they are ports

techlibs/xilinx/synth_xilinx.cc
Since `techmap -map +/techmap.v` can generate arithmetic structures too...
=> Execute techmap and arith_map simultaneously

README.md
This is a drive-by PR to fix an invisible reference to `<size>` due to missing formatting.
=> README.md: Missing formatting for <tag>

passes/cmds/setundef.cc
Currently, setundef -init misses some registers that are also assigned to something:
Running the following Verilog code:
module register #(
parameter DEPTH = 10
) (
input wire clk,
input wire in,
output wire out
);
reg [DEPTH-1:0] regs;
always @(posedge clk) regs <= { regs[DEPTH-2:0], in};
assign out = regs[DEPTH-1];
endmodule
through this script:
read_verilog register.v
prep
setundef -zero -init
The register `regs` should be initialized to zero (attribute init set to 0).
attribute \src "register.v:6"
wire output 3 \out
attribute \init 10'0000000000
attribute \src "register.v:8"
wire width 10 \regs
`out` is initialized to zero.
attribute \init 1'0
attribute \src "register.v:6"
wire output 3 \out
attribute \src "register.v:8"
wire width 10 \regs
This PR tries to fix the issue by waiting to …
=> initialize more registers in setundef -init

techlibs/ecp5/cells_map.v
I'm not sure what to do with the differential ones (or how are they supposed to be used in the first place) so those are stubbed for now. But the list includes every primitive according to Lattice's [FPGA Libraries Reference Guide](http://www.latticesemi.com/~/media/LatticeSemi/Documents/UserManuals/EI/FPGALibrariesReferenceGuide32.pdf?document_id=50687).
=> ECP5: implement most Diamond I/O buffer primitives

frontends/verilog/verilog_parser.y, tests/simple/attrib01_module.v, tests/simple/attrib02_port_decl.v, tests/simple/attrib03_parameter.v, tests/simple/attrib04_net_var.v, tests/simple/attrib05_port_conn.v.DISABLED, tests/simple/attrib06_operator_suffix.v, tests/simple/attrib07_func_call.v.DISABLED, tests/simple/attrib08_mod_inst.v, tests/simple/attrib09_case.v, tests/various/attrib05_port_conn.v, tests/various/attrib05_port_conn.ys, tests/various/attrib07_func_call.v, tests/various/attrib07_func_call.ys
This PR adds support for attributes on port connections to the Verilog frontend. Attributes are allowed but discarded.
=> Added support for parsing attributes on port connections.

misc/py_wrap_generator.py
CentOS7 provides no boost-log, which is why building yosys+pyosys fails there. But as it turns out this include is unused anyways, so removing it solves the issue.
=> Fix pyosys-build on CentOS7

.dockerignore, Dockerfile
This pull request proposes to dockerize Yosys suite. To build the Docker image: `docker build -t yosys .`. To use the image, mount the directory where you have your RTL and library files to `/data` inside the image. There are two options to run yosys:
- Use the interactive shell: `docker run -it -v <data-directory>:/data yosys`. Read files from `/data` directory. For example: `read_verilog /data/design.v`
- Use the yosys commands from a file: `docker run -v <data-directory>:/data yosys /data/synth.ys`, where `synth.ys` should be located in the host data directory as well.
To try without building the image locally, use image name `openroad/yosys` on Docker Hub: https://hub.docker.com/r/openroad/yosys
=> Dockerfile for Yosys

frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y
This seems to fix #1084.
It seems I've broken regular $info/$error/$warning tasks, since the lexer always returns TOK_ELAB_TASK for those, so I made the parser accept it for normal tasks as well (and rename it TOK_MSG_TASKS since it no longer applies to elaboration time tasks only).
=> Fixed broken $error()/$info/$warning() on non-generate blocks (within always/initial blocks)

README.md, frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/verilog/verilog_frontend.cc, frontends/verilog/verilog_parser.y
=> Add "read_verilog -pwires" feature

passes/cmds/blackbox.cc, passes/sat/assertpmux.cc, passes/sat/cutpoint.cc, techlibs/ice40/ice40_unlut.cc
When you run the "help" command in Yosys without an argument, you get a list of commands and a summary of each command. I noticed a few summaries were incorrect since they described other commands. I went through and fixed all the incorrect summaries that appeared to be for other commands.
=> Fixed the help summary line for a few commands

frontends/verilog/verilog_parser.y, tests/various/unpacked_arrays.sv, tests/various/unpacked_arrays.ys
The test needs checks.
Manually I was able to see the output of `stat` to see that there are 2 memories and 16 memory bits as opposed to 9 memory bits in the same test without the changes to `verilog_parser.y` but I did not find a way to check for this.
I would be happy to extend this checks if I could get a pointer of how to do it.
=> Unpacked array declaration using size

kernel/register.cc, passes/sat/sat.cc
This now allows a full pipeline to work, something such as:
yosys -p "synth_ecp5 -json ~/work/fpga/prjtrellis/examples/ecp5_evn/blinky.v"
Otherwise, you will get something along the lines of:
ERROR: Can't open output file `~/work/fpga/prjtrellis/examples/ecp5_evn/blinky.v' for writing: No such file or directory
Signed-off-by: Ben Widawsky <ben@bwidawsk.net>
=> Add a few more filename rewrites

passes/techmap/shregmap.cc, tests/various/shregmap.v, tests/various/shregmap.ys
e.g.
```
module shregmap_test(input i, clk, output [1:0] q);
reg head = 1'b0;
reg [3:0] shift1 = 4'b0000;
reg [3:0] shift2 = 4'b0000;
always @(posedge clk) begin
head <= i;
shift1 <= {shift1[2:0], head};
shift2 <= {shift2[2:0], head};
end
assign q = {shift2[3], shift1[3]};
endmodule
```
Previously, `shregmap` would create one `SHREG` only since the key for `sigbit_chain_next` would be clobbered; now I create a new temporary wire (which isn't updated by `SigMap`) to circumvent this clobbering.... a bit hacky -- is there a better way to do this?
EDIT: The alternative would be to change the data structure (multimap) or a new one (vector) capable of containing duplicates, because I really don't like the fact it could break on a sigmap update...
=> Improve shregmap to handle case where first flop is common to two chains

techlibs/ecp5/cells_map.v, techlibs/ecp5/cells_sim.v
This includes all I/O registers, and a few more regular FFs where it was convenient.
Also, it looks like I've missed the I/O buffers in `cells_sim.v` in #1073.
=> Add more ECP5 Diamond flip-flops.

Makefile, tests/arch/run-test.sh
Should avoid problems like those fixed in #1137 in the future.
=> tests: Check that Icarus can parse arch sim models

Makefile, tests/aiger/run-test.sh, tests/memories/run-test.sh, tests/tools/autotest.sh
Commits 65924fd1, abc40924, and ebe29b66 hard-code the invocation
of yosys-abc, which fails if ABCEXTERNAL was specified during the
build. Allow tests to utilize an optional, externally specified
abc binary.
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
=> tests: use optional ABCEXTERNAL when specified

passes/techmap/Makefile.inc
This is a fixup for the P.R. #1098 merge.
=> Make abc9 pass aware of optional ABCEXTERNAL override

passes/memory/memory_dff.cc, tests/memories/read_two_mux.v, tests/memories/run-test.sh
Fixes a regression from #1130
cc @gsomlo, this was found in https://github.com/gsomlo/yoloRISC
=> memory_dff: Fix checking of feedback mux input when more than one mux

CHANGELOG, kernel/yosys.cc, tests/various/script.ys
Inspired by `_TECHMAP_DO_*`, with the intention for it to be used in testing circuits procedurally generated outside of Yosys so that we don't need to generate two files -- a Verilog and a YS file (and without using less elegant solutions).
=> Add "script -select [selection]" to allow commands to be taken from wires

backends/aiger/xaiger.cc, tests/various/abc9.v, tests/various/abc9.ys
Fixes case where unknown cell is instantiated in design
=>  write_xaiger to treat unknown cell connections as keep-s

misc/py_wrap_generator.py
Throw runtime exception when trying to convert a c++-pointer to a python-object in case the pointer is a nullptr to avoid a segfault.
Fixes #1090
=> Throw runtime exception when trying to convert inexistend C++ object to Python

techlibs/intel/synth_intel.cc
My first PR; since there doesn't seem to be any testing framework and a history of breakage between Quartus and Yosys, I thought it would be best to warn on trying to emit a VQM.
cc @daveshah1 @dh73
=> synth_intel: Warn about untested Quartus backend

CHANGELOG, passes/opt/wreduce.cc, techlibs/common/synth.cc
Propagated through to `wreduce` call.
Also clarify doc for `wreduce -keepdc` to indicate use only for `$mux` cells.
Response to #1165
=> Add "synth -keepdc" option

backends/ilang/ilang_backend.cc, frontends/ilang/ilang_parser.y, kernel/rtlil.h
The parser changes are slightly awkward. Consider the following IL:
process $0
<point 1>
switch \foo
<point 2>
case 1'1
assign \bar \baz
<point 3>
...
case
end
end
Before this commit, attributes are valid in <point 1>, and <point 3>
iff it is immediately followed by a `switch`. (They are essentially
attached to the switch.) But, after this commit, and because switch
cases do not have an ending delimiter, <point 3> becomes ambiguous:
the attribute could attach to either the following `case`, or to
the following `switch`. This isn't expressible in LALR(1) and results
in a reduce/reduce conflict.
To address this, attributes inside processes are now valid anywhere
inside the process: in <point 1> and <point 3> a part of case body,
and in <point 2> as a separate rule. As a consequence, …
=> Allow attributes on individual switch cases in RTLIL

passes/proc/Makefile.inc, passes/proc/proc.cc, passes/proc/proc_arst.cc, passes/proc/proc_init.cc, passes/proc/proc_prune.cc
See commit messages for detailed description and motivation.
Originally I wrote this pass to clean up the output of nMigen (which works very well), but after looking at the `proc_init` change (in the second commit) I think it is just as useful on its own.
=> A new proc_prune pass

passes/cmds/bugpoint.cc, passes/proc/proc_clean.cc
I think it'd make sense to teach `opt_clean` to work on modules with processes, which I may do in the future. I also think it'd make sense to add a `-quiet` option to `opt_clean` (like I did for `proc_clean`) instead of duplicating the entire pass for the `clean` command...
=> Add support for processes in bugpoint

backends/verilog/verilog_backend.cc
Purely a stylistic change, right now the indentation is all weird and the placement is awkward with large case patterns and/or large attributes.
=> write_verilog: fix placement of case attributes

backends/verilog/verilog_backend.cc
Currently, the only ways (determined by grepping for regex \bSa\b) to
end up with RTLIL::Sa in a netlist is by reading a Verilog constant
with ? in it as a part of case, or by running certain FSM passes.
Both of these cases should be round-tripped back to ? in Verilog.
I'm not sure if there was some reason it was written as z. That code
goes back to the very first Yosys commit.
=> write_verilog: write RTLIL::Sa aka - as Verilog ?

frontends/aiger/aigerparse.cc
Fixes a compile error on Windows, tested using `msys2`. No other platforms affected.
=> Fix missing semicolon in Windows-specific code in aigerparse.cc.

backends/smt2/smtio.py
Due to [a bug in the python resource module](https://bugs.python.org/issue36432), any call to SMT currently fails on recent macOS versions because the stack size can't be increased. There might also potentially be other reasons for the syscall to fail, and not getting a larger stack allocated shouldn't be a hard error.
This silently ignores failure from the setrlimit call, and tries to run the solver anyway with whatever stack is available.
I'm assuming that if the solver does run out of memory the error message is explicit enough, but I wasn't able to trigger that message. If it's too cryptic we could consider emitting a warning instead when stack allocation fails.
=> smt: handle failure of setrlimit syscall

README.md
For pkg, the FreeBSD package manager, the pkgconfig package was renamed to pkgconf a while back. I updated the README accordingly.
=> Updated FreeBSD dependencies in README.md

passes/opt/opt_lut.cc
The opt_lut pass, now enabled by default on iCE40, prints thousands of lines of debug messages. I think it predates the suppression of debug messages in e158ea209 so it didn't use that facility. Use it now.
=> Make opt_lut less chatty

passes/techmap/extract_fa.cc
`extract_fa` uses `ConstEval` internally to "simulate" the output of cells. If `ConstEval::eval` fails to simulate a cell, fail more gracefully than a `log_abort`.
Fixes #1099
=> extract_fa to return nothing more gracefully

passes/techmap/abc9.cc, tests/various/abc9.ys
`abc9` can sometimes return a LUT mapping that has a `$_NOT_` gate left behind.
Previously, I would clone the driving flop (if one exists) but flip its mask so that we are guaranteed to never increase the logic depth.
This is sub-optimal as the `$_NOT_` gate can sometimes be absorbed into the driving LUT; doing so also requires that (a) all downstream sinks (i.e. those before the NOT gate) that driven by the same LUT must only be soft logic LUTs, and if so (b) we can then twiddle the mask of those downstream sinks to cope with the driving LUT being inverted.
This PR does (a) and (b).
=> abc9: push inverters driving box inputs (comb outputs) through $lut soft logic

techlibs/ice40/ice40_unlut.cc, techlibs/ice40/synth_ice40.cc
The new mapping introduced in 437fec0d88b4a2ad172edf0d1a861a38845f3b1d
needed matching adaptation when converting and optimizing LUTs during
the relut process
Fixes #1187
(Diagnosis of the issue by @daveshah1 on IRC)
=> ice40: Adapt the relut process passes to the new $lut/SB_LUT4 port map

backends/verilog/verilog_backend.cc
Before this commit, zero width constants were dumped as "" (empty
string). Unfortunately, 1364-2005 5.2.3.3 indicates that an empty
string is equivalent to "\0", and is 8 bits wide, so that's wrong.
After this commit, a replication operation with a count of zero is
used instead, which is explicitly permitted per 1364-2005 5.1.14,
and is defined to have size zero. (Its operand has to have a non-zero
size for it to be legal, though.)
Fixes #948 (again).
=> write_verilog: dump zero width constants correctly

techlibs/intel/synth_intel.cc
Also fix a typo in the help message.
No functional change, but looks a bit nicer.
=> synth_intel: rename for consistency with #1184

techlibs/xilinx/cells_map.v
=> xilinx: Fix missing cell name underscore in cells_map.v

techlibs/intel/synth_intel.cc
Recent (I'm using 18.1 Lite) Quartus versions do not produce any IO pad cells in their netlists, suggesting Quartus can infer them now, or that they're unnecessary. Since Yosys doesn't care, and nextpnr (as a long shot) can infer them too, switch them off by default, while keeping the option around.
=> intel: Make -noiopads the default

frontends/verilog/verilog_lexer.l
Otherwise "medium" Boom configuration (and possibly other FIRRTL-derived Verilog input) fail with `input buffer overflow, can't enlarge buffer because scanner uses REJECT`. 64k shouldn't make a significant difference to Yosys' memory footprint.
=> verilog_lexer: Increase YY_BUF_SIZE to 65536

README.md, frontends/verific/verific.cc
Small code change, big behavior change. This makes non-verific Yosys behave a bit more like verific-yosys.
=> Call "read_verilog" with -defer from "read"

Makefile, backends/aiger/xaiger.cc, frontends/aiger/aigerparse.cc, kernel/yosys.h, misc/launcher.c, passes/opt/opt_lut.cc, passes/opt/rmports.cc, passes/techmap/flowmap.cc, techlibs/anlogic/anlogic_determine_init.cc, techlibs/anlogic/anlogic_eqn.cc, techlibs/gowin/determine_init.cc
- msys2 builds anyway can not be compiled with plugins so made config so compile work by default
- %zu is not supported in msys mingw, mxe and VisualStudio older then 2015 so made define for size_t formatting
- update places where wrong formatting have been used for size_t values
- fixed cast and not defined symbol in launcher.c
TODO: check mxe build after these changes
=> Fix formatting for msys2 mingw build

backends/aiger/xaiger.cc, passes/techmap/abc.cc
bswap32 was defined for each platform but GCC specific was used at the end
including cctype needed due to usage of std::isdigit
=> Visual Studio build fix

passes/proc/proc_prune.cc
Before this commit, proc_prune would ignore partially redundant assignments.
eg.
```
module \top
wire width 2 \s
process $group_0
assign \s 2'00 
assign \s [0] 1'1
end
end
```
would be transformed into:
```
module \top
wire width 2 \s
process $group_0
assign \s 2'00
end
connect \s [0] 1'1
end
```
This is wrong because `\s [0]` is now assigned concurrently twice. 
After this commit, proc_prune promotes the first assignment too:
```
module \top
wire width 2 \s
process $group_0
end
connect \s [0] 1'1
connect \s [1] 1'0
end
```
=> proc_prune: Promote partially redundant assignments.

backends/json/json.cc, frontends/json/jsonparse.cc
Quoting new format description:
> Numeric 32-bit parameter and attribute values are written as decimal values.
Bit verctors of different sizes, or ones containing 'x' or 'z' bits, are written
as string holding the binary representation of the value. Strings are written
as strings, with an appended blank in cases of strings of the form /[01xz]* */.
=> Improved JSON attr/param encoding

backends/aiger/xaiger.cc, frontends/aiger/aigerparse.cc, frontends/aiger/aigerparse.h, passes/techmap/abc9.cc
Unfortunately, I overlooked the fact that while `clean` does operate on selected modules, it also runs `optimize()`/`sort()`/`check()` on the entire design that it gets called on:
https://github.com/YosysHQ/yosys/blob/e8a2d10982cd8f6ba3b0e66fbd922b051073f0cf/passes/opt/opt_clean.cc#L625-L627
Since `abc9` (currently, rightly or wrongly) relies on a O(N) of `clean`-s for (several for each module to be abc9-ed) in order to remove the AIG from which LUTs were generated, this ends up costing quite a bit, particularly on large designs with many modules.
This PR improves this situation by placing each of the to-be-cleaned modules into its own design. ~There's one remaining known TODO (which I will revisit next week) to get rid of one final `clean` call.~ EDIT: Don't think my TODO would have …
=> abc9: speedup by using using "clean" more efficiently

passes/opt/opt_lut.cc
Fixes #1254 
Before, and/or without any `(* keep *)`:
```
Number of cells:                 71
SB_CARRY                       22
SB_DFF                         23
SB_DFFE                         1
SB_LUT4                        25
```
After:
```
Number of cells:                 77
SB_CARRY                       22
SB_DFF                         23
SB_DFFE                         1
SB_LUT4                        31
```
when either of the two `(* keep *)` attributes are present:
```
module top (
output LED
);
// ring oscillator
(* keep *) wire [6:0] buffers_in, buffers_out;
assign buffers_in = {buffers_out[5:0], buffers_out[6]};
(* keep *) SB_LUT4 #(
.LUT_INIT(16'd1)
) buffers [6:0] (
.O(buffers_out),
.I0(buffers_in),
.I1(1'b0),
.I2(1'b0),
.I3(1'b0)
);
// frequency counter
reg [23:0] counter …
```
=> opt_lut to ignore LUT cells, or those that drive bits, with (* keep *)

passes/proc/proc_prune.cc
Before this commit, in a process like:
```
process $proc$bug.v:8$3
assign $foo \bar
switch \sel
case 1'1
assign $foo 1'1
assign $foo 1'1
case
assign $foo 1'0
end
end
```
both of the `assign $foo 1'1` would incorrectly be removed.
Fixes #1243.
=> proc_prune: fix handling of exactly identical assigns

frontends/aiger/aigerparse.cc
I can't seem to reproduce #1271 locally, but patch proposed by @mithro does not seem to be any harm.
Fixes #1271
=> Add __STDC_FORMAT_MACROS before <inttypes.h> as per @mithro

frontends/verific/verific.cc, frontends/verific/verific.h, kernel/celltypes.h
=> Automatically prune init attributes in verific front-end

passes/techmap/extract_fa.cc
Fixes #1284 
@cliffordwolf: Not sure what the value of `leaves.sort()` was to begin with?
=> Since $_ANDNOT_ is not symmetric, do not sort leaves

passes/techmap/extract_fa.cc
Reverts YosysHQ/yosys#1288
Seems to break yosys-tests on internal Jenkins (but can't reproduce locally, indicating order issue?)
=> Revert "Since $_ANDNOT_ is not symmetric, do not sort leaves"

.travis.yml, .travis/setup.sh
A few days ago something with our Travis CI setup (or the repos it depends on) changed:
* gcc-4.8 was refusing to compile iverilog:
```
In file included from /usr/include/string.h:635:0,
from lexor.cc:21:
In function 'void* memset(void*, int, size_t)',
inlined from 'int yylex()' at ./lexor.lex:96:29:
/usr/include/x86_64-linux-gnu/bits/string3.h:86:32: warning: call to '__warn_memset_zero_len' declared with attribute warning: memset used with constant zero length parameter; this could be due to transposed parameters
__warn_memset_zero_len ();
```
* clang-5 was no longer installing
```
The following packages have unmet dependencies:
clang-5.0 : Depends: libjsoncpp0 (>= 0.6.0~rc2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Both from: …
=> Fix Travis CI

kernel/cellaigs.cc, kernel/celledges.cc, kernel/celltypes.h, kernel/consteval.h, kernel/cost.h, kernel/macc.h, kernel/rtlil.cc, kernel/rtlil.h, kernel/satgen.h, kernel/yosys.cc, kernel/yosys.h, passes/opt/muxpack.cc, passes/opt/opt_clean.cc, passes/opt/opt_demorgan.cc, passes/opt/opt_expr.cc, passes/opt/opt_lut.cc, passes/opt/opt_merge.cc, passes/opt/opt_muxtree.cc, passes/opt/opt_reduce.cc, passes/opt/opt_rmdff.cc, passes/opt/pmux2shiftx.cc, passes/opt/share.cc, passes/opt/wreduce.cc
This picks up on the ID() macro introduced a long time ago in 75423169c but was never used.
Usage examples: `ID(A)`, `ID($add)`
86c39d3 updates the `ID()` macro to provide the new API.
14c0289 applies the `ID()` macro to wherever it was easy to do in `passes/opt/*`.
=> New ID() macro and now also use it

passes/techmap/extract_fa.cc
Fixes #1284 (again, again).
See: https://github.com/YosysHQ/yosys/issues/1284#issuecomment-521455881 for an explanation of why this is necessary.
=> extract_fa: Un-inverting AND with an inverted input also inverts input to X{,N}OR

passes/pmgen/.gitignore
new file appeared passes/pmgen/ice40_wrapcarry_pm.h, but we can make this general naming nomenclature
=> Ignore all generated headers for pmgen pass

frontends/ast/ast.cc
Currently, when real values are used as parameters, they are converted to their string value and marked as reals. When the parameterized module is derived, the string's value is used as value for the real.
This PR attempts to fix that by checking for the real values' flag.
=> Handle real values when deriving ast modules

passes/techmap/techmap.cc, tests/techmap/recursive.v, tests/techmap/recursive_map.v, tests/techmap/recursive_runtest.sh
Previously, `techmap -max_iter` is shared between all modules, which is not my expectation of what `-max_iter` should be.
The problem stemming from this is that if there's a hit in one module, based on this line:
https://github.com/YosysHQ/yosys/blob/076af2e6176ecc440be7b7fa984ea5b461bb95de/passes/techmap/techmap.cc#L1168
the next module will be unable to decrement the variable nor break out of the loop.
This means that it will run until a fixed point is reached (and in my niche rule that replaces a module with itself plus something else, run forever).
=> techmap -max_iter to apply to each module individually

passes/opt/opt_expr.cc, tests/opt/opt_expr.ys
Specifically, if MSB of A port is `1'bx`:
```
cell $shiftx \shiftx
parameter signed \Y_WIDTH 1
parameter signed \B_WIDTH 2
parameter signed \A_WIDTH 4
parameter signed \B_SIGNED 0
parameter signed \A_SIGNED 0
connect \Y \y
connect \B \b
connect \A { 1'x \a }
end
```
=>  opt_expr to trim A port of $shiftx/$shift

misc/py_wrap_generator.py
In the Python API for Yosys (pyosys), when I try to access `connections_` from a `Module`, I get the following error in python:
```
TypeError: No to_python (by-value) converter found for C++ type: Yosys::RTLIL::SigSpec
```
I have no previous experience with Boost Python, but it appears from looking at the rest of the C++ wrapper that the C++ code for creating a tuple is missing a call to `get_py_obj` when necessary. I looked at the code in `misc/py_wrap_generator.py` for other containers and modeled my solution after those. In addition to fixing the bug, I also removed a significant amount of dead code in the function.
A possible improvement for this function (beyond my bugfix) is to add logic for the case where the types are in `known_containers`. This case doesn't happen with the …
=> Fixed pyosys commands returning RTLIL::SigSig

passes/sat/sat.cc, tests/sat/initval.v, tests/sat/initval.ys
Attached testcase works if `sat -enable_undef` is specified, even though it shouldn't be necessary as there is no ambiguity.
Also removal of one colon is necessary otherwise signal is collapsed and no init.
=> In sat: 'x' in init attr should be ignored

techlibs/ice40/abc_hx.box, techlibs/ice40/abc_lp.box, techlibs/ice40/abc_u.box, techlibs/ice40/cells_sim.v, techlibs/ice40/ice40_opt.cc, tests/ice40/ice40_opt.ys, tests/ice40/run-test.sh
Sorry for my incompetence! I've just realised that `abc9` ice40 has not been using boxes at all, and discovered these remnants from #1290 and #1260 which addressed #1205 originally.
~I've also had to remove optimising `$__ICE40_CARRY_WRAPPER` (or the deprecated `$__ICE40_FULL_ADDER`) from `ice40_opt` since we can't reason with it the same way -- it can't be guaranteed to implement the sum part of the full adder since the LUT mask could be different, and I0 and I3 could have be non-zero and non-CI respectively.
*EDIT:* Not sure if this is desirable for non-abc9 flows. For `-abc9` it is possible that abc9 may be able to reason about the box and optimise it away entirely (but not demote it back to a soft `$lut` and use that during techmapping). Perhaps it is better to restore its handling in …
=> Fix $__ICE40_CARRY_WRAPPER, restore abc9 functionality

README.md, frontends/aiger/aigerparse.cc, passes/techmap/abc9.cc, tests/simple_abc9/run-test.sh
For example, the `synth_*` passes will often call `clean` after `abc`/`abc9` anyway.
Plus some README.md shuffling.
Also fixed an issue with inout ports when stitching in the circuit from `abc9`.
=> abc9 to not call "clean" at end of run (often called outside)

techlibs/ecp5/cells_sim.v
This enables yosys EQUIV pass to be able to prove equivalence of designs for ECP5 designs
=> Fix TRELLIS_FF simulation model

passes/pmgen/ice40_dsp.cc, tests/ice40/macc.v, tests/ice40/macc.ys
@cliffordwolf what was the reason behind why signed multipliers were rejected in: https://github.com/YosysHQ/yosys/commit/dca65d83a0037539464d303ea8751a3e06a92e03?
Also modified existing testcase to be wider to go over our thresholds for DSP inference.
=> ice40_dsp to allow signed multipliers

tests/simple/run-test.sh, tests/simple_abc9/run-test.sh
`which` is [non-portable](https://twitter.com/whitequark/status/1168670168173559808), requiring an additional package installation on some systems, as I ran into trying to get the NixOS package to run yosys tests; the most common alternative, `type -p` is [POSIX-portable in terms of return value, but not output](https://twitter.com/dev_console/status/1168672291271692288). That doesn't matter particularly here, but I've replaced it with `command -v`, which is [portable in return value and output](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html).
=> Use `command -v` rather than `which`

Makefile
This only gets called on macOS so I missed it in the last PR.
=> Replace `which` with `command -v` in Makefile too

Makefile
Did you think that `$(shell command -v ...)` would actually get run by
the shell? Foolish mortal; GNU Make is obviously far more wise than
thee, as it optimizes it to a direct -- and hence broken (since
`command` is a shell builtin) -- exec. This horrifying contortion
ensures that an actual shell runs the command and fixes the behaviour.
@Shizmob found the source of this misbehaviour; turns out gmake has a
hard-coded, incomplete list of shell builtins:
https://github.com/mirror/make/blob/715c787dc69bac37827a7d6ea6d40a86c55b5583/src/job.c#L2691
This contains `command`, but the whole function is full of horrible
heuristic garbage so who knows. I'm so sorry.
=> Use $(shell :; ...) in Makefile to force shell

README.md, passes/techmap/techmap.cc
Fixes #1145.
This inadvertently also enables the following:
```
module top (input [3:0] A, B, output [3:0] X, Y);
(* keep *) wire [3:0] bar.internal;
assign Y = bar.internal;
foo bar ( A, B, X );
endmodule
module foo (input [3:0] din1, din2, output [3:0] dout);
(* keep *) wire [3:0] internal = din1 & din2;
assign dout = din1 | din2;
endmodule
```
`yosys -p 'read_verilog test.v; prep -top top; flatten;; show'`
=> Add flatten handling of pre-existing wires as created by interfaces

backends/smt2/Makefile.inc, misc/launcher.c, passes/opt/opt_share.cc, tests/ice40/div_mod.ys
This fixes two issues with Yosys when building for MSVC2:
1. The Makefile assumes the compiler is always called `gcc`, which isn't always true.
2. Patch 3d3779b0376b8204ed7637053176a07b7271ac1d added a static map that contains a static class with static members, which might get initialized in an incorrect order.
=> MSVC2 fixes

CHANGELOG, passes/techmap/dff2dffs.cc, tests/techmap/dff2dffs.ys
A lot of FPGA architectures can make use of that one, at the very least ecp5 and xc6s.
=> Add -match-init option to dff2dffs.

frontends/verilog/const2ast.cc, frontends/verilog/verilog_lexer.l
This reverts a change introduced in 34417ce55 by @mmicko that caused #1364. It also adds support for uppercase `S` as signedness indicator.
=> Fix lexing of integer literals

frontends/verilog/const2ast.cc, passes/opt/opt_expr.cc
See https://github.com/m-labs/nmigen/issues/202#issuecomment-530329710 for details.
=> Fix handling of z_digit "?" and fix optimization of cmp with "z"

frontends/ast/ast.cc, frontends/ast/ast.h
=> Fix handling of read_verilog config in AstModule::reprocess_module()

kernel/register.cc
readsome can sometimes return just one char, so it is safe to read one by one, that fixes reading.
changes in gzip_ostream and gzip_streambuf fixes crash writing to gzip file
=> Make read/write gzip files on macos works, fixes #1357

passes/techmap/techmap.cc, tests/techmap/wireinit.ys
Previously, this wire was handled in the code that populated the "do or
do not" techmap cache, resulting in init value removal being performed
only for the first use of a given template.
Fixes the problem identified in #1396.
=> Fix _TECHMAP_REMOVEINIT_ handling.

backends/aiger/aiger.cc, backends/aiger/xaiger.cc, backends/protobuf/protobuf.cc, kernel/register.cc, kernel/register.h
In cases when we need to provide binary output of backend it is important to set that flag, otherwise writing of \n will produce system specific EOL, causing creation of invalid file.
=> Support binary files for backends, fixes #1407

kernel/rtlil.cc
This speeds up processing when number of bits are large but there
is actually nothing to replace. Adresses part of #1382
=> Avoid work in replace() if rules empty.

passes/equiv/equiv_opt.cc
Just like sby does here:
https://github.com/YosysHQ/SymbiYosys/blob/06cc339957a56bf413da911d6c0aa01503590802/sbysrc/sby_core.py#L346-L349
and cleans up small barnacles like this:
https://github.com/YosysHQ/yosys/blob/8c2dd518b908644c9181526e193b8211734e8cef/tests/xilinx/latches.ys#L5-L7
=> equiv_opt to call async2sync when not -multiclock like SymbiYosys

frontends/aiger/aigerparse.cc, kernel/register.cc, kernel/register.h, passes/techmap/abc9.cc
Reading of generated aig files fails when they are in binary format, made change to support frontends with binary input, and use binary stream to open xaig output in ABC9 after generate.
This fixes hang on read in issue #1407
=> Open aig frontend as binary file

frontends/rpc/rpc_frontend.cc
Kept it out of ifdef __APPLE__ since it can help on systems like BSD, and it does not heart mingw or linux builds
=> Define environ, fixes #1424

passes/techmap/techmap.cc, tests/techmap/techmap_replace.ys
... and to substitute the original cell name and alias them to the auto-generated wire.
Useful for creating wires that have a predictable name (not `$techmapNNN...`) that can be recovered by other passes.
Could be used to create `(* hierconn *)` signals, for example, too.
=> RFC: techmap to recognise wires named "_TECHMAP_REPLACE_.<suffix>"

frontends/ast/ast.cc, frontends/ast/ast.h
... by checking the design to see if module already exists before cloning/modifying the ast.
EDIT: This PR isn't driven by any collected performance data, just bourne from an observation for improvement when I was investigating something else.
=> module->derive() to be lazy and not touch ast if already derived

passes/equiv/equiv_opt.cc, tests/ice40/latches.ys, tests/xilinx/latches.ys
Make #1412 more conservative by only calling `async2sync` when new option `equiv_opt -async2sync` is given, since @daveshah1 kindly provided a counter example: https://github.com/YosysHQ/yosys/pull/1412#issuecomment-536680733
This new `-async2sync` option is mutex to `-multiclock`
Also disables equiv checking in ice40/latches.ys since it was broken.
=> async2sync to be called by equiv_opt only when -async2sync given

kernel/log.cc, kernel/log.h, kernel/yosys.h, passes/pmgen/peepopt_dffmux.pmg, tests/various/peepopt.ys
Fixes #1427. 
`equiv_opt synth_ice40` now passes for that testcase.
Issue was that `peepopt_dffmux` was not checking the `\init` value before trimming.
EDIT: Depends on #1431 -- please let that get merged first.
=> Refactor peepopt_dffmux and be sensitive to \init when trimming

passes/sat/sat.cc, tests/sat/initval.ys
See test for testcase.
Found while bug-hunting in #1427
=> sat passes when it should fail if sigmap(wire) has dupes, but differing \init

Makefile, README.md, frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/verilog/verilog_parser.y, tests/svtypes/.gitignore, tests/svtypes/run-test.sh, tests/svtypes/typedef_memory.sv, tests/svtypes/typedef_memory.ys, tests/svtypes/typedef_memory_2.sv, tests/svtypes/typedef_memory_2.ys, tests/svtypes/typedef_package.sv, tests/svtypes/typedef_param.sv, tests/svtypes/typedef_scopes.sv, tests/svtypes/typedef_simple.sv
This work is based on #1389. In order to decouple the GLR discussion from the rest of the original PR, this adds typedef support with a wrong syntax, that doesn't require a GLR parser, so we can merge the rest of the PR and figure out what to do about GLR later.
The following would re-enable the correct syntax, using GLR:
```
--- frontends/verilog/verilog_parser.y
+++ frontends/verilog/verilog_parser.y
@@ -180,7 +180,9 @@ struct specify_rise_fall {
%right UNARY_OPS
%define parse.error verbose
-%define parse.lac full
+//%define parse.lac full
+%glr-parser
+%expect 21
%nonassoc FAKE_THEN
%nonassoc TOK_ELSE
@@ -292,7 +294,7 @@ hierarchical_id:
};
hierarchical_type_id:
-       '(' hierarchical_id ')' { $$ = $2; };
+       hierarchical_id { $$ = $1; };
module:
attr TOK_MODULE TOK_ID {
``` …
=> Typedef support (with wrong syntax)

Makefile, passes/pmgen/Makefile.inc, techlibs/common/Makefile.inc, techlibs/ecp5/Makefile.inc, techlibs/ice40/Makefile.inc, techlibs/xilinx/Makefile.inc
On some architectures, notably on Windows, the official name for the
Python binary from python.org is `python`.  The build system assumes
that python is called `python3`, which breaks under this architecture.
There is already infrastructure in place to determine the name of the
Python binary when building PYOSYS.  Since Python is now always required
to build Yosys, enable this check universally which sets the
`PYTHON_EXECUTABLE` variable.
Then, reuse this variable in other Makefiles as necessary, rather than
hardcoding `python3` everywhere.
=> Makefile: don't assume python is called `python3`

techlibs/ice40/synth_ice40.cc, techlibs/xilinx/synth_xilinx.cc
DSP mapping runs before `memory` so it can sometimes merge an intended read register into DSP. Avoid this by calling `memory_dff` before `xilinx_dsp`/`ice40_dsp`.
With the testcase from #1447:
`synth_xilinx -flatten`
Before this commit:
```
=== testcase ===
Number of wires:               2225
Number of wire bits:           8039
Number of public wires:          16
Number of public wire bits:    1745
Number of memories:               0
Number of memory bits:            0
Number of processes:              0
Number of cells:               2946
BUFG                            1
DSP48E1                        32
FDRE                          552
LUT2                          981
LUT3                          128
MUXCY                         494
RAM128X1D                     256
XORCY …
```
=> Call memory_dff before DSP mapping to reserve registers (fixes #1447)

backends/verilog/verilog_backend.cc
If an init value is emitted for a reg, an (\*init\*) attribute is never
necessary, since it is exactly equivalent. On the other hand, some
tools that consume Verilog (ISE, Vivado, Quartus) complain about
(\*init\*) attributes because their interpretation differs from Yosys.
All (\*init\*) attributes that would not become reg init values anyway
are emitted as before.
=> write_verilog: do not print (*init*) attributes on regs

techlibs/common/cmp2lut.v, tests/arch/anlogic/fsm.ys, tests/arch/ecp5/fsm.ys, tests/arch/efinix/fsm.ys, tests/arch/ice40/fsm.ys, tests/arch/xilinx/fsm.ys
Those are not being mapped by `alumacc` anyway, logic optimization will yield the obvious solution, and converting those `$eq/$ne` cells to other cell types will prevent other coarse-grain optimizations that do not understand the `$lut` circuits.
(This fails some tests atm because right now `fsm` is being prevent from running on some archs because of this, and the fsm arch test is broken if `fsm` actually does something.)
=> Do not map $eq and $ne in cmp2lut, only proper arithmetic cmp

passes/fsm/fsm_detect.cc
The old code contained the following code, which when reached would always set `clr_output = false` because the if-condition was always true.
```
if (port_it.first != "\\A" || port_it.first != "\\Y")
clr_output = false;
```
The new code should do now what the old code was intended to do, I think.
=> Bugfix in fsm_detect

backends/btor/btor.cc
When my Verilog has lots of embedded assertions, sometimes it can be difficult to tell which assertion the bad nodes in btor correspond to.
This PR would add an info string symbol to label bad states in the btor output. Any node in btor can have an associated symbol, and this one is just a convenience to help identify which assertion in the Verilog code is associated with this particular bad node.
If you like this idea, but not the style, I'm happy to make changes. Furthermore, for named assertions, it might be nice to use the name. Where is that information stored? E.g.
```
assertion_name : assert(...);
```
Thanks for all your work on Yosys!
=> Add an info string symbol for bad states in btor backend

techlibs/ice40/cells_sim.v
Corresponds with YosysHQ/nextpnr#345.
Changes include:
- Fixing handling of disconnected ports on `ICESTORM_LC` - as the hardware has defined states for this
- Adding dummy specify blocks to `ICESTORM_LC`, `SB_IO`, `ICESTORM_RAM`. I understand that long-term plans might need data added to these; but these are currently placeholders that are populated by the simulator using an SDF file for nextpnr (which takes into account speed grade, cell config, etc)
- Adding a model for `ICESTORM_RAM`, the post-PnR RAM cell
To complete this PR I still need to fix a few remaining cells.
=> ice40: Support for post-place-and-route timing simulations

passes/cmds/Makefile.inc, passes/cmds/autoname.cc, techlibs/ice40/synth_ice40.cc
For the most part this is useful for getting easier-to-understand timing reports. For example, with `autoname`:
```
Info: Critical path report for clock 'clock_$glb_clk' (posedge -> posedge):
Info: curr total
Info:  0.5  0.5  Source cpu.ldst.mem_valid_reg_SB_DFFESR_Q_DFFLC.O
Info:  1.1  1.7    Net cpu.mem_valid_ldst budget -0.257000 ns (4,2) -> (4,8)
Info:                Sink cpu.ldst.insn_ld_SB_LUT4_I1_LC.I3
Info:  0.3  2.0  Source cpu.ldst.insn_ld_SB_LUT4_I1_LC.O
Info:  0.6  2.6    Net cpu.ldst.insn_ld_SB_LUT4_I1_O budget -0.257000 ns (4,8) -> (3,9)
Info:                Sink cpu.arb_mem_ctrl_SB_LUT4_O_LC.I2
Info:  0.4  2.9  Source cpu.arb_mem_ctrl_SB_LUT4_O_LC.O
Info:  0.6  3.5    Net mem_insn_d budget -0.257000 ns (3,9) -> (2,9)
Info:                Sink …
```
=> Add "autoname" pass and use it in "synth_ice40"

backends/verilog/verilog_backend.cc
Some toolchains (in particular Quartus) are pathologically slow if a large amount of assignments in `initial` blocks are used. In practice, this functionality is required for nMigen to be usable with such toolchains.
=> write_verilog: add -extmem option, to write split memory init files

CHANGELOG, README.md, frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y, passes/proc/proc_dlatch.cc, tests/various/svalways.sh
This handles always_comb, always_latch and always_ff correctly. Sensitivity lists after always_(comb|latch) are now a syntax error as they should be; and an attribute is set on the process according to the type of always.
Checking of the types is done in `proc_dlatch`. Checking for correct use of `always_ff` here feels a bit iffy here; but the sequence inside `proc` means that doing it inside `proc_dff` seems tricky.
My understanding is that latches in always_comb; and vice versa; are only supposed to be a warning according to the standard. This PR implements what 99% of users would expect and throws an error in these cases, happy to change that if strict standards compliance is preferred.
=> sv: Error checking for always_comb, always_latch and always_ff

frontends/verific/verific.cc, frontends/verific/verificsva.cc
Simple test case for both features:
```
module counter (input clk, input reset);
localparam MAX_COUNT = 16'b1000;
reg [15:0] counter;
always @(posedge clk) begin
if(reset || counter == MAX_COUNT)
counter <= 0;
else
counter <= counter + 1'b1;
end
assert property (@(posedge clk) reset |-> always nexttime counter <= MAX_COUNT);
endmodule
```
=> Add Verific/SVA support for "always" and "nexttime" properties

techlibs/coolrunner2/synth_coolrunner2.cc
This was causing a segmentation fault because there is no accompanying
log_push() call so header_count.size() became -1.
Signed-off-by: Martin Pietryka <martin@pietryka.at>
=> coolrunner2: remove spurious log_pop() call, fixes #1463

backends/aiger/xaiger.cc, tests/simple_abc9/abc9.v
* Do not promote output wires, as it is necessary to see when they are driven by inputs
* Do not sigmap `(* keep *)` bits
=> write_xaiger improvements

passes/memory/memory_collect.cc
This would be a prerequisite for any memory mapping decisions (e.g. type of memory) based on attributes
=> memory_collect: Copy attr from RTLIL::Memory to  cell

passes/techmap/abc9.cc, tests/simple_abc9/abc9.v
This correctly handles the case where more than one wire bit is part of an SCC, by checking for this case when rewiring. It also renames the input, rather than the output; to avoid breaking port naming when the output is also a primary output.
Fixes #1487 and fixes #1415; once this is fixed I will be happy making abc9 the default for ECP5 flows - the area reduction is certainly worth it.
=> abc9: Fix breaking of SCCs

techlibs/gowin/cells_map.v, techlibs/gowin/synth_gowin.cc, tests/arch/gowin/adffs.ys, tests/arch/gowin/init.v, tests/arch/gowin/init.ys
In the previous Gowin patch, it was found that DFF init behavior was not supported in hardware and removed. Upon closer inspection it was found that in fact the hardware initializes to the reset value. In the vendor tools, the following code
```verilog
module myDFF (output reg Q = 1, input CLK, D);
always @(posedge CLK)
Q <= D;
endmodule
```
Synthesizes to the following DFFS with the reset tied to ground.
```verilog
DFFS Q_0 (
.Q(Q_c),
.D(D_c),
.CLK(CLK_c),
.SET(GND)
);
```
This pull request adds the same behavior to all Gowin flip-flops that don't use a reset.
In case a reset is used, the wire init parameter is only removed if it is compatible with the reset value.
This PR also adds tests for all DFF types and their init values, and fixed a few typos in previously untested DFF types. …
=> Gowin: add and test DFF init values

passes/techmap/iopadmap.cc, tests/techmap/iopadmap.ys
The previous code for rerouting wires when inserting tristate buffers
was overcomplicated and didn't handle all cases correctly (in
particular, only cell connections were rewired — internal connections
were not).
=> iopadmap: Refactor and fix tristate buffer mapping.

tests/arch/xilinx/macc.sh
Environment:
- macOS Sierra (10.12.6)
- clang (8.1.0)
- iverilog (7f95abc)
Running **macc.sh** script in **tests/arch/xilinx**  results in following error:
```
Running macc.sh..
ERROR: Can't guess frontend for input file `-o' (missing -f option)!
macc_uut.v: No such file or directory
macc_tb.v:77: error: Unknown module type: macc2
macc_tb.v:87: error: Unknown module type: macc2_uut
3 error(s) during elaboration.
*** These modules were missing:
macc2 referenced 1 times.
macc2_uut referenced 1 times.
***
./test_macc: Unable to open input file.
make[1]: *** [run-macc.sh] Error 255
make: *** [test] Error 2
```
Changing the argument order in **macc.sh** fixed the issue.
=> tests: arch: xilinx: Change order of arguments in macc.sh

frontends/verilog/preproc.cc, frontends/verilog/verilog_lexer.l, manual/CHAPTER_Verilog.tex
Is a minimal contribution, but I was surfing the source code of the Verilog frontend and I found a name mismatch between the documentation and the real name of lexer and parser files.
I have not the setup to run `make manual`, but I used '\\_' in the LaTeX source.
=> Fixed some missing "verilog_" in documentation

CHANGELOG, passes/equiv/equiv_opt.cc, techlibs/xilinx/Makefile.inc, techlibs/xilinx/cells_map.v, techlibs/xilinx/cells_sim.v, techlibs/xilinx/cells_xtra.py, techlibs/xilinx/cells_xtra.v, techlibs/xilinx/synth_xilinx.cc, techlibs/xilinx/xc6s_ff_map.v, techlibs/xilinx/xc7_ff_map.v, techlibs/xilinx/xilinx_dffopt.cc, tests/arch/xilinx/adffs.ys, tests/arch/xilinx/fsm.ys, tests/arch/xilinx/macc.ys, tests/arch/xilinx/xilinx_dffopt.ys, tests/arch/xilinx/xilinx_dffopt_blacklist.txt
This adds support for infering more kinds of flip-flops:
- FFs with async set/reset and clock enable
- FFs with sync set/reset
- FFs with sync set/reset and clock enable
Some passes have been moved (and some added) in order for dff2dffs to
work correctly.
This gives us complete coverage of Virtex 6+ and Spartan 6 flip-flop
capabilities (though not latch capabilities).  Older FPGAs also support
having both a set and a reset input, which will be handled at a later
data.
=> xilinx: Improve flip-flop handling.

techlibs/ecp5/cells_map.v, techlibs/ecp5/synth_ecp5.cc
This adds an optional mode to use the "async preload" function of flipflops to implement async features. This is an undocumented mode not used by the vendor tools, but it seems worth including it as an option given async stuff is effectively uncharted waters in any case.
=> ecp5: Add support for mapping PRLD FFs

tests/simple/mem_arst.v
=> mem_arst.v: do not redeclare ANSI port

frontends/ast/simplify.cc, tests/various/bug1531.ys
=> verilog: preserve size of $genval$-s in for loops

backends/aiger/xaiger.cc, techlibs/ecp5/synth_ecp5.cc, techlibs/ice40/synth_ice40.cc, techlibs/xilinx/synth_xilinx.cc
Eliminates 3 `Pass::call()`-s from `write_xaiger`:
* `opt_merge`
* `techmap`
* `aigmap`
=> Optimise write_xaiger

Makefile
The behaviour of `python-config --libs` has changed in Python 3.8.
For example, compare the output of it with Python 3.7 and 3.8 on an ArchLinux system:
$ python3.7-config --libs
-lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm
$ python3.8-config --libs
-lcrypt -lpthread -ldl  -lutil -lm -lm
$
The lack of `-lpython` in the latter case causes the linker to fail when attempting to build Yosys against Python 3.8, with missing symbol errors. It also breaks the boost_python name detection.
Passing the new `--embed` flag to `python-config` adds `-lpython`, just like earlier versions of Python:
$ python3.8-config --embed --libs
-lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm
$
This pull request adds code for automatically detecting support for the `--embed` flag. If it is supported, it is …
=> Fix building against Python 3.8

backends/aiger/xaiger.cc, techlibs/ecp5/synth_ecp5.cc, techlibs/ice40/synth_ice40.cc, techlibs/xilinx/synth_xilinx.cc
Reverts YosysHQ/yosys#1535
It looks we can't aigmap the abc9 whiteboxes since they might contain parameters, in which case Yosys will go back to the AST to generate a paramod...
=> Revert "Optimise write_xaiger"

backends/aiger/xaiger.cc
Reverts YosysHQ/yosys#1588
This is a priority as it causes abc9 flows for ecp5 and ice40 to totally break.
Even the following small example:
```verilog
module led_blink (
input clk,
output ledc
);
reg [6:0] led_counter = 0;
always @( posedge clk ) begin
led_counter <= led_counter + 1;
end
assign ledc = !led_counter[ 6:3 ];
endmodule
```
fails `prep; equiv_opt -map +/ecp5/cells_sim.v synth_ecp5 -abc9` with:
```
Unproven $equiv $auto$equiv_make.cc:251:find_same_wires$3852: \ledc_gold \ledc_gate
Unproven $equiv $auto$equiv_make.cc:280:find_same_wires$3851: \led_counter_gold [6] \led_counter_gate [6]
Unproven $equiv $auto$equiv_make.cc:280:find_same_wires$3849: \led_counter_gold [4] \led_counter_gate [4]
Unproven $equiv $auto$equiv_make.cc:280:find_same_wires$3847: \led_counter_gold [2] …
```
=> Revert "write_xaiger: only instantiate each whitebox cell type once"

backends/aiger/xaiger.cc, tests/arch/ecp5/bug1598.ys, tests/arch/ice40/bug1598.ys, tests/arch/xilinx/bug1598.ys
Retry #1588. Reverted by #1598 due to a bug, which should be fixed here.
Quite disconcerting that it wasn't caught by any of our existing ice40/ecp5 tests... (this particular test case doesn't trigger for xilinx, which is what has been my focus, since its carry boxes are not parameterised).
Incidentally, this PR also fixes a potential for different breakage, since without this the contents of the whitebox would be the default parameters (in the ice40 case, the mask of the carry LUT would be all zeros) and thus there exists a potential that this box could have been swept away.
The testcase in #1598 actually showed boxes being swept away (due to the corrupted port ordering).
=> Retry #1588 -- "write_xaiger: only instantiate each whitebox cell type once"

passes/techmap/iopadmap.cc, tests/arch/xilinx/bug1605.ys
module top(inout io);
wire in;
wire t;
wire o;
IOBUF IOBUF(
.I(in),
.T(t),
.IO(io),
.O(o)
);
endmodule
This simple case create 2 IOBUF cells instead of keeping just one manually instantiated.
Thanks @mwkmwkmwk for suggesting what to check.
=> iopad mapping should take care of existing io buffers

passes/techmap/abc.cc, techlibs/achronix/synth_achronix.cc, techlibs/anlogic/synth_anlogic.cc, techlibs/coolrunner2/synth_coolrunner2.cc, techlibs/easic/synth_easic.cc, techlibs/ecp5/synth_ecp5.cc, techlibs/efinix/synth_efinix.cc, techlibs/gowin/synth_gowin.cc, techlibs/greenpak4/synth_greenpak4.cc, techlibs/ice40/synth_ice40.cc, techlibs/intel/synth_intel.cc, techlibs/sf2/synth_sf2.cc, techlibs/xilinx/synth_xilinx.cc
Partially reverts https://github.com/YosysHQ/yosys/pull/917 since `abc9` does not support retiming.
`synth_* -retime` option now calls `abc -dff -D 1` to preserve old behaviour.
=> "abc -dff" to no longer retime by default

techlibs/ice40/ice40_opt.cc
Right now executing synth_ice40 on https://github.com/YosysHQ/yosys-tests/blob/master/regression/issue_00160/top.v fails since there is attribute named SB_CARRY. even if carry part is optimized out from carry wrapper
=> Valid to have attribute starting with SB_CARRY.

passes/techmap/abc.cc
Previously, multiple -g options passed to abc would all affect the enabled gates, but with the latest changes only the last option would be honored. Since the behavior might now be different, throw an error if multiple -g options are given to ensure it's at least not a silent surprise.
=> error if multiple -g options are given for abc

kernel/rtlil.cc, kernel/rtlil.h, kernel/yosys.cc, passes/cmds/scratchpad.cc, passes/techmap/abc9.cc, techlibs/xilinx/synth_xilinx.cc, tests/techmap/abc9.ys
~DEPENDENCY: #1622~
Example usage:
`scratchpad -copy abc9.script.flow3 abc9.script` before `synth_xilinx -abc9`
* Added an `RTLIL::constpad` global for storing constant things that can be read from and copied into a design's scratchpad (initialised by `Pass::on_register()`) -- readable but not writable by the `scratchpad` command
* Added the following constpad entries for now:
```
abc9.script.default # (as before)
abc9.script.default.area # (as abc9.script.default, but with the "-a" option to &if)
abc9.script.default.fast # (as before)
abc9.script.flow
abc9.script.flow2
abc9.script.flow3
```
* `abc9.if.C` to control `&if -C`
* `abc9.if.R` to control `&if -R`
* `abc9.debug` as alias to `abc9.nocleanup` and `abc9.showtmp`
* `abc9.verify` to add `verify [-s]` to end of script
=> abc9: add some scripts/options into "scratchpad"

backends/edif/edif.cc, techlibs/xilinx/synth_xilinx.cc, tests/arch/xilinx/add_sub.ys, tests/arch/xilinx/counter.ys, tests/arch/xilinx/fsm.ys
In Yosys+Vivado flow preserving DONT_TOUCH in EDIF is essential to make design work on real hardware.
Also used CARRY4 for abc1 pass for adder, otherwise design is not possible to place if there are dont_touch attributes set on wires for XORCY/MUXCY
=> Export wire properties in EDIF

kernel/driver.cc
Use `ru_maxrss` for peak memory utilisation, rather than two current memory values on exit.
`scratchpad -set print_stats.include_children 1` to include runtime and peak memory usage of child processes.
=> print_stats footer to return peak memory, option for including children

techlibs/ice40/ice40_ffinit.cc
This duplicates for Ice40 a change already made for ECP5: https://github.com/YosysHQ/yosys/pull/850/commits/777864d02ea3382c822a764e928e06b6142da6ec
Following conversation about LiteDRAM here: https://github.com/enjoy-digital/litedram/issues/96
=> ice40: Demote conflicting FF init values to a warning

backends/edif/edif.cc
Connecting a const 'z to a net should be equivalent to not connecting it
at all, so let's just ignore such connections on output.
Reported by heijligen on IRC.
=> edif: Just ignore connections to 'z

kernel/driver.cc
The flag `--version` is commonly accepted by command line tools.
The code for the version flags added here matches the pattern used for the help flag aliases, for consistency.
Fixes #1612
=> Add --version and -version as aliases for -V

passes/cmds/show.cc
On Arch linux `fuser` seems to try to read  file descriptors of other users, giving permission errors:
```
$ fuser -s *
Cannot stat file /proc/951/fd/0: Permission denied
Cannot stat file /proc/951/fd/1: Permission denied
Cannot stat file /proc/951/fd/2: Permission denied
Cannot stat file /proc/951/fd/3: Permission denied
Cannot stat file /proc/951/fd/4: Permission denied
Cannot stat file /proc/951/fd/5: Permission denied
Cannot stat file /proc/951/fd/6: Permission denied
Cannot stat file /proc/951/fd/7: Permission denied
Cannot stat file /proc/951/fd/8: Permission denied
Cannot stat file /proc/951/fd/9: Permission denied
Cannot stat file /proc/951/fd/10: Permission denied
Cannot stat file /proc/951/fd/11: Permission denied
Cannot stat file /proc/951/fd/12: Permission denied
Cannot stat …
```
=> Redirect fuser stderr to /dev/null

passes/sat/sat.cc, tests/sat/initval.ys
The attached testcase is synthetic (should never have an `init` on a wire) but can occur when other passes (e.g. #1566) set certain bit(s) to be so (which may not be a whole wire).
=> sat: suppress 'Warning: ignoring initial value on non-register: ...' when init[i] = 1'bx

frontends/aiger/aigerparse.cc, kernel/rtlil.h, passes/pmgen/ice40_wrapcarry.cc, techlibs/ecp5/cells_map.v, techlibs/ice40/cells_map.v, techlibs/ice40/ice40_opt.cc, techlibs/xilinx/lut_map.v, tests/arch/ice40/bug1597.ys, tests/arch/ice40/ice40_opt.ys
Originally, `abc9` required that the inputs be ordered fastest first, and so I changed the `techmap`-ing rules for supported architectures to do this, including twiddling the LUT masks to cope.
I've just realised that there's no need to do that, as I can just reverse the ordering coming out of `abc9`... and this cleans up the `techmap` rules as well as makes debugging easier.
Fixes #1597 
Supersedes/fixes #1628
=> Unpermute LUT ordering for ice40/ecp5/xilinx

tests/arch/efinix/mux.ys
There seams to be non-deterministic behavior. Output blif that yosys generates contains always same number of elements:
Extracted 49 gates and 69 wires to a netlist network with 20 inputs and 1 outputs.
But order of those is not deterministic, so abc produce different number of $lut  cells, when we just run mux16 then it is 11, when we run others before we have 12.
Strange is that with clang and gcc on Linux and msvc on Windows we have same problem (12 luts), but on clang 10 on macOS (11 luts) it works fine even others are executed before.
This is fix for #1556
We also have same issue appearing on xilinx pull request for same mux test.
=> Fix for non-deterministic test

backends/edif/edif.cc
Make sure we preserve "keep" nets in EDIF back-end. Requires testing @mmicko.
=> Preserve wires with keep attribute in EDIF back-end

passes/opt/opt_reduce.cc
This avoids effectively n^2 performance scaling on designs where there is a lot of opt_reduce, Chisel output seems particularly liable to this.
=> opt_reduce: Call check() per run rather than per optimised cell

frontends/verific/verific.cc
Fixes YosysHQ/SymbiYosys#69.
Previously:
```
$ ./yosys -Qp "verific -sv bug69.sv; verific -import -all; dump i:in*"
-- Running command `verific -sv bug69.sv; verific -import -all; dump i:in*' --
1. Executing VERIFIC (loading SystemVerilog and VHDL designs using Verific).
Built with Verific Dec19_SW_Release, released at Tue Dec 31 23:22:23 2019.
VERIFIC-COMMENT [VERI-1482] Analyzing Verilog file 'bug69.sv'
2. Executing VERIFIC (loading SystemVerilog and VHDL designs using Verific).
Built with Verific Dec19_SW_Release, released at Tue Dec 31 23:22:23 2019.
Running hier_tree::ElaborateAll().
VERIFIC-INFO [VERI-1018] bug69.sv:6: compiling module 'mcve'
Importing module mcve.
Importing module \$unit_bug69_sv.
attribute \src "bug69.sv:6"
wire width 2 input 1 \in
```
Now:
```
$ ./yosys -Qp …
```
=> verific: unflatten struct ports

techlibs/xilinx/lutrams.txt
This fixes inefficient LUT RAM usage for memories with one write
and two read ports (commonly used as register files).
=> xilinx: use RAM32M/RAM64M for memories with two read ports

passes/pmgen/xilinx_dsp.cc
This is intended to get some kind of DSP usage - simple combinational multiplies only - working with open source flows, without the complexity of dealing with cascades, etc, to start with. It is a bit of a hack so happy for this not to go upstream if you prefer.
=> synth_xilinx: add -dsp-multonly

frontends/ast/ast.h, frontends/ast/simplify.cc, tests/various/sformatf.ys
This refactors the formatting code used by $display and $write into a function that is then also be used to implement the ~$sprintf~ $sformatf system function; which I want to use in the CrossLink-NX support as Radiant tends to use C-style parameters in Verilog strings rather than Verilog numeric parameters... (and it would be best to stay compatible).
edit: just after submitting the PR I realised the standard-compliant name is $sformatf, not $sprintf (which is some kind of non-standard feature), derp.
=> ast: Add support for $sformatf system function

techlibs/anlogic/synth_anlogic.cc, techlibs/coolrunner2/synth_coolrunner2.cc, techlibs/ecp5/synth_ecp5.cc, techlibs/efinix/synth_efinix.cc, techlibs/gowin/synth_gowin.cc, techlibs/greenpak4/synth_greenpak4.cc, techlibs/ice40/synth_ice40.cc, techlibs/sf2/synth_sf2.cc
Necessary post-#1650-with-[fix](4c1d3a126d3978aeacbab623532c0ec9400b8959) at least on `tests/arch/anlogic/mux.ys`, which transforms:
into
which leads to the "optimal" solution of 5xLUT6...
To be honest, I think only a `clean` was strictly necessary but I think there may be value in doing `opt -fast` as done in `synth_xilinx`.
Even though it wasn't necessary for other arches to get back to passing status, I've done the same change for them...
=> synth_*: call 'opt -fast' after 'techmap'

backends/verilog/verilog_backend.cc
The Verilog backend already dumps attributes on RTLIL::Memory objects but not on `$mem` cells.
=> write_verilog: dump $mem cell attributes

techlibs/gowin/synth_gowin.cc
Answering @eddiehung reviews request, I'm fixing one of the comments: 
https://github.com/YosysHQ/yosys/commit/f9272fc56d7179f04a9f776bf056eedfc33dd358#r37144384
the other one: https://github.com/YosysHQ/yosys/commit/f9272fc56d7179f04a9f776bf056eedfc33dd358#r37144371
Makes perfect sense to remove `run("techmap -map +/techmap.v");` since is irrelevant, but `fine` synthesis seems to be replaced for `map_ffram` and `map_gates` in current head, so these lines does not exists in master anymore.
=> Removing cells_sim from GoWin bram techmap

misc/py_wrap_generator.py
Currently, the pyosys wrapper generator disregards any information on inheritance. As most of the RTLIL classes (Module, Cell, Wire, ...) derive their attribute capabilites from AttrObject, their accessors are lost during wrapper generation.
This patch adds a basic notion of inheritance to the wrapper generation process. Now one can do:
```
[thasti@pc]$ cat test.v 
module test();
(* my_attr = 1 *) wire attrwire;
endmodule
[thasti@pc]$ cat yo.py 
from pyosys import libyosys as ys
design = ys.Design()
ys.run_pass("read_verilog test.v", design)
mod = design.module(ys.IdString("\\test"))
print("Module Source Attribute: %s " % mod.get_src_attribute())
wire = mod.wire(ys.IdString(ys.IdString("\\attrwire")))
print("All Wire Attributes: %s" % wire.attributes)
[thasti@pc]$ python yo.py 
-- Running …
```
=> Make RTLIL attributes accessible via pyosys

frontends/verilog/verilog_parser.y, tests/various/bug1614.ys
Fixes a minor bug in the verilog frontend that caused #1614. The previous grammar accepted syntax that both iverilog and verilator flagged as invalid. Testcase added as in the reported issue. Please review, I'm not sure whether my fix missed some part of the verilog spec and broke something else.
Testcase as in #1614 now parses successfully, syntax also accepted by iverilog and verilator.
```
[thasti@pc]$ cat delay.v
module testcase;
wire [3:0] #1 a = 4'b0000;
endmodule
[thasti@pc]$ yosys delay.v
Parsing Verilog input from `/tmp/delay.v' to AST representation.
Time spent: 100% Parsing Verilog input from `/tmp/delay.v' to AST representation.
Generating RTLIL representation for module `\testcase'.
Successfully finished Verilog frontend.
[thasti@pc]$ iverilog /tmp/delay.v 
[no output] …
```
=> Fix crash on wire declaration with delay

backends/json/json.cc
This increases compatibility with certain older parsers in some cases that worked before commit 15fae357 but do not work with the current compat-int mode
The specific case that I encountered involved flip-flop cells with `INIT` attributes set to 0 (these attributes are created by the `dffinit` pass). For some reason that I didn't fully investigate (because it does not seem to cause any breakage), yosys seems to think that these attributes are 0 bits wide (e.g. `write_verilog` will output `.INIT({0{1'b0}})`). The code prior to commit 15fae357 would have output a 0 into the resulting JSON file, but the code that is currently in master will output an empty string (even with `-compat-int`).
By making `-compat-int` write attributes with <= 32 bits (rather than == 32 bits) as JSON numbers, the …
=> json: Change compat mode to directly emit ints <= 32 bits

passes/techmap/iopadmap.cc, tests/techmap/iopadmap.ys
=> iopadmap: move \init attributes from outpad output to its input

tests/rpc/frontend.py, tests/rpc/run-test.sh, tests/rpc/unix.ys
The unix socket test of the rpc frontend relies on the command `python3 frontend.py unix-socket frontend.sock` creating the named socket within 0.1 seconds. However, the speed of the test environment isn't really something we want to test here. Waiting longer is also undesirable as it artificially increases the execution time of the test. Moreover, when the script does not execute fast enough, the test leaves behind a running python process and an open socket. (If the test is run a second time it then succeeds by using the instance from the previous run...)
To remedy this problem, this PR puts the python script in charge for the unix-socket test case. Yosys is launched by the python script after the socket is established. In case of any exception both the socket and the yosys process are …
=> make rpc frontend unix socket test less fragile

README.md, frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/verilog/verilog_parser.y, tests/svtypes/enum_simple.sv, tests/svtypes/enum_simple.ys, tests/svtypes/typedef_package.sv, tests/svtypes/typedef_scopes.sv
I rebased PeterCrozier's enum work onto current master
I tried to keep only the enum-related changes, and minimize the diff. (The original commit also had a lot of work done to get typedefs working, but yosys has diverged quite a bit since the 2018-03-09 commit, with a new typedef implementation https://github.com/YosysHQ/yosys/pull/1389.) I did not include the import related changes either.
I added support for enum typedefs at the toplevel scope and in generate if blocks, and some simple tests. It works so far for my purposes, but any comments are welcome. The enums are currently not strongly typed.
Resolves #248
Original commit:
"Initial implementation of enum, typedef, import.  Still a WIP."
https://github.com/PeterCrozier/yosys/commit/881833aa738e7404987646ea8076284e911fce3f
=> Enum support

techlibs/xilinx/cells_xtra.py, techlibs/xilinx/cells_xtra.v
While using a Yosys-Vivado flow I've noticed an issue with how `IOB` in `IOBUFDSE3` was handled, this PR aims to fix this issue.
=> xilinx: mark IOBUFDSE3 IOB pin as external

techlibs/coolrunner2/Makefile.inc, techlibs/coolrunner2/coolrunner2_fixup.cc, techlibs/coolrunner2/coolrunner2_sop.cc, techlibs/coolrunner2/synth_coolrunner2.cc
The new pass will contain all of the logic for inserting "passthrough"
product term and XOR cells as appropriate for the architecture. For
example, this commit fixes connecting an input pin directly to another
output pin with no logic in between.
=> coolrunner2: Separate and improve buffer cell insertion pass

passes/techmap/extract_counter.cc, techlibs/coolrunner2/Makefile.inc, techlibs/coolrunner2/cells_counter_map.v, techlibs/coolrunner2/synth_coolrunner2.cc
The current implementation tends to implement counters in a very inefficient way using a very large number of pterms. Using the `extract_counter` pass, it is possible to detect most common ways of describing a counter in HDL and map them to a manually-optimized implementation that uses significantly fewer resources (max 2 pterms per bit)
=> Improve CoolRunner-II optimization by using extract_counter pass

frontends/ast/simplify.cc
Fixes #1663 by mostly reverting #1569 and resizing the initial expression directly.
@cliffordwolf is there a more elegant way of doing this?
=> verilog: instead of modifying localparam size, extend init constant expr

frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/verilog/verilog_frontend.cc, frontends/verilog/verilog_frontend.h, frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y, kernel/rtlil.cc, tests/arch/ice40/ice40_wrapcarry.ys, tests/various/mem2reg.ys
I am not sure if other frontends (verific, ghdl, others ?) use the `linenum` member.  If so, then it needs to be decided whether to keep both `linenum` and `location` and synchronize their updates, to keep only `location` and require those frontends to change to using `location`, or some other strategy.
Maybe the best strategy is to keep the `use_internal_line_num()`, `set_line_num()`, and `get_line_num()` interface, add a `set_precise_location()` and `get_precise_location()` interface, and update all existing references to `linenum` to use `get_line_num()` or `get_precise_location()` as appropriate.
@eddiehung Thoughts?
=> Closes #1717. Add more precise Verilog source location information to AST and RTLIL nodes.

techlibs/common/synth.cc, techlibs/ice40/synth_ice40.cc
This is more of a discussion point than a pull request.
The PR itself is simple: use the `flowmap` pass from #775 instead of `techmap -map +/gate2lut.v` for better synthesis quality when using `synth{,_ice40} -noabc`.
But should we just remove `-noabc`, given that only iCE40 even exposes an option for it?
Or should we add `-noabc` option that uses `flowmap` to all flows, so that Yosys does not require ABC for FPGA synthesis?
What about CMOS synthesis, which currently *does* require ABC?
=> Use flowmap instead of gate2lut in noabc modes

tests/rpc/frontend.py
There was still another race condition in the RPC frontend test: if the yosys process executes `connect_rpc` before the python process gets to `sock.listen()` the connection would fail and the test would hang.
This executes `sock.listen()` before launching the yosys process. It also adds a 30 second timeout to the socket so that the test will eventually fail rather than hang.
=> More rpc test fixes

techlibs/ecp5/brams_map.v
This caused yosys to fail when running with implicit nets turned off, even if no bram was used...
=> ecp5: Add missing parameter to \$__ECP5_PDPW16KD

passes/techmap/deminout.cc, tests/various/deminout_unused.ys
Previously, `deminout` was converting `inout` ports with unused bits to outputs with those bits driving 'x', which doesn't seem like a sound transformation to me as those unused bits should be high-z.
example case:
```verilog
module top(input clk, inout [7:0] x);
reg [3:0] ctr;
always @(posedge clk) ctr <= ctr + 1'b1;
assign x[7:4] = ctr;
endmodule
````
```
yosys -p "synth_ecp5; dump" tri.v
```
=> deminout: Don't demote inouts with unused bits

kernel/register.cc, kernel/register.h, passes/techmap/abc9.cc
Found that abc9 had significantly regressed when dealing with large "noflatten" designs while trying to build a large place and route benchmark; this turns out to be due to excessive Design::check calls after every step. To compensate the removed whole-design checks I've added a single Module::check after each module is processed.
This trivial example demonstrates the problem well:
```verilog
module xorx #(parameter [31:0] b = 0) (input [31:0] a, output [31:0] y);
assign y = a ^ b;
endmodule
module top(input [31:0] a, output [31:0] y);
localparam N = 2000;
wire [31:0] s[0:N];
generate
genvar i;
for (i = 0; i < N; i = i + 1'b1) begin
xorx #(.b(i)) xor_i(.a(s[i]), .y(s[i+1]));
end
endgenerate
assign s[0] = a;
assign y = s[N];
endmodule
```
`synth_xilinx` (old ABC) takes 3m30s; `synth_xilinx …
=> Add ScriptPass::run_nocheck and use for abc9

Makefile
Fixes #1675 by pulling in upstream fix.
Specific ABC testcase provided in #1675 now passes with `yosys-abc`, and the result also passes ABC's own combinational equivalence check `cec`.
=> Bump ABCREV to receive fix for #1675

backends/aiger/xaiger.cc, passes/techmap/abc.cc, passes/techmap/abc9_ops.cc
Currently, `(* keep *)`-ed wires are transformed into primary inputs and primary outputs.
That appears to be overly onerous (and is not what `abc` does) so only transform them into primary outputs.
=> abc9: improve (* keep *) handling

Makefile, frontends/rpc/Makefile.inc, kernel/log.cc, kernel/yosys.cc
This fixes the following errors:
1. TOTAL_MEMORY no longer supports '128\*1024\*1024'.
2. Set ENABLE_ZLIB = 0 for emcc.
3. Disable rpc frontend because it uses unimplemented posix api.
4. Remove call to popen.
5. Allow YosysJS to call 'cccall'.
=> Fix compilation for emcc

Makefile
While working on the [yosys-git](https://aur.archlinux.org/packages/yosys-git/) AUR package, I noticed a few hickups in the make system that cause some trouble for packaging. Apart from fixes for build failures, the only observable change this PR should have is that `libyosys.so` is no longer installed to `BINDIR`, and the copy installed to `PYTHON_DESTDIR` is a symlink pointing to `LIBDIR` instead. Also, a 30% reduction in package size.
=> Makefile improvements for packaging scripts

Makefile
The output of `rev-parse --short` may be abbreviated differently from ABCREV (e.g. `ed90ce20` vs `ed90ce2`), so simply comparing the strings to check whether the correct revision is checked out will always fail. Passing both HEAD and ABCREV through `rev-parse` and then comparing the full hashes fixes that.
Packaging scripts might want to avoid sources being downloaded during build, which is ensured by `ABCPULL=0`. However, unless `ABCREV=default` is used (which is also not ideal) the correct ABC commit needs to be checked out before building. The newly added `echo-abc-rev` target can be used by packaging scripts to do just that, such that a subsequent build with `ABCPULL=0` succeeds.
This is a followup to #1666, which was reverted because of multiple issues. The commit in this PR includes …
=> Improve ABC repository management in Makefile

backends/firrtl/firrtl.cc, kernel/driver.cc, kernel/log.cc, kernel/log.h, passes/cmds/logger.cc, tests/various/logger_error.ys, tests/various/logger_nowarning.ys, tests/various/logger_warn.ys, tests/various/logger_warning.ys
Since std::regex does not work (it compiles) on gcc 4.8, there were few possible ways to go
- boost::regex - it is 1:1 with std::regex but there is a big issue, in case boost is compiled on later gcc and linked with gcc 4.8 then linking will fail, also requires additional library to be linked
- boost::xpressive - compatible but slightly different syntax for some parts, header only, so no additional library to link
=> Regex support for GCC 4.8

frontends/verilog/verilog_parser.y, tests/various/src.ys
See #1717 and #1718. This PR sets the `AstSrcLocType` member `location` for more AST nodes generated in the parser.
=> Set AST node source location in more parser rules.

frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y, tests/various/bug1745.ys, tests/various/constcomment.ys
The code to handle comments between size and value in constants by arbitrarily concatenating two TOK_CONSTVAL which was introduced in ee8ad72fd950e1ee204e5c97155a50b8b1445dec has three problems:
* It accepts invalid code; e.g. the expression `12'h4 /*foo*/'b0` is accepted as the hexadecimal constant `12'h4b0` despite being syntactically incorrect
* It generates misleading diagnostics; e.g. the expression `a == 1'b0? 1'b1 : 1'b0`
yields the diagnostic "Digit larger than 1 used in in base-2 constant" (issue #1745)
* It is incomplete - It does not accept any spaces between the comment and the `'`, and no comments between the base and the digits even though spaces are allowed there.
This PR fixes all three problems by making the three parts of a based constant (size, base, digits) into three …
=> refixed parsing of constant with comment between size and value

techlibs/ice40/cells_sim.v
According to the official simulation model, and also cross-checked
on real hardware, the data output of the SPRAM when chipselect is
low is kept stable. It doesn't go undefined.
=> ice40: Fix SPRAM model to keep data stable if chipselect is low

backends/smt2/smt2.cc, backends/smt2/smtbmc.py, backends/smt2/smtio.py, examples/smtbmc/Makefile, examples/smtbmc/demo9.v
* Modifies smt2 backend to recognize `$anyconst` etc. assigned to a wire with the `maximize` or `minimize` attribute and emit a `; yosys-smt2-maximize` or `; yosys-smt2-minimize` directive as appropriate.
* Modifies `backends/smt2/smtbmc.py` and `smtio.py` to recognize those directives and emit a `(maximize ...)` or `(minimize ...)` command at the end of `smt_forall_assert()`, as described in the paper [νZ - An Optimizing SMT Solver](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/nbjorner-nuz.pdf) by Nikolaj Bjørner et al.
* Adds an example `examples/smtbmc/demo9.v` to show how it can be used.
AFAIK this is only supported by z3, but cvc4 might be able to do it, too.
Multiple objectives appear to be supported, but I have added an assertion to limit to only one …
=> Add support for optimizing exists-forall problems.

COPYING, README.md, kernel/yosys.cc
The title is not legally mandated, but it's convenient for human consumption, and is included in the template text of this license, as recommended by [OSI](https://opensource.org/licenses/isc-license), [SPDX](https://spdx.org/licenses/ISC.html#licenseText), [choosealicense.com](https://choosealicense.com/licenses/isc/), and others.
***Note**: This PR is part of my personal project to improve the consistency and visibility of the ISC license in open source projects. See https://github.com/github/choosealicense.com/issues/377 for more details.*"
=> License: bump year and add title

kernel/rtlil.h, passes/cmds/select.cc
Also adds a `contains()` member function to `ObjRange` in `kernel/rtlil.h`.
I think a benchmark comparison with and without this PR must be done before merging.  My concern is that in the original code, `it` has the `RTLIL::IdString` local, next to the `RTLIL::Module *` in memory.  In the new code that uses the `ObjRange` accessor functions, the name that is passed to many functions no longer local.  Instead, it's an indirect jump away, at e.g. `wire->name`.
=> Clean up code style and pseudo-private member usage in `passes/cmds/select.cc`

frontends/ast/simplify.cc, frontends/verilog/verilog_parser.y
This commit add precise locations for `assume`, `assert`, etc. in verilog parser rules. And it also fills `location` member in new assert nodes created during simplification.
A better approach may be implementing the new location interfaces mentioned in #1728 and do initialization in `AstNode` constructor.
=> Add precise locations for asserts

frontends/verilog/Makefile.inc
This solves issue when verilog_parser.y is changes, since implicitly it depends of verilog_parser.tab.cc and verilog_parser.tab.h
=> Add dependency to verilog_lexer.cc

passes/fsm/fsm_extract.cc, tests/various/bug1781.ys
=> fsm_extract: Initialize celltypes with full design.

techlibs/ice40/cells_sim.v
This fixes error like
ERROR: Module 'SB_SPRAM256KA' contains specify cell '$specify$2054' where DST '$dummywireforinterface\CLK' is not a module input.
=> ice40: Fix typos in SPRAM ABC9 timing specs

techlibs/ice40/synth_ice40.cc, tests/various/ice40_mince_abc9.ys
Otherwise, they are not mapped to `SB_DFF` before ABC, which causes a 'no loops' failure in `abc9` (and would also mean that required times etc were wrong).
cc @smunaut
=> ice40: Map unmapped 'mince' DFFs to gate level

Makefile, passes/cmds/add.cc, passes/cmds/select.cc, tests/select/no_warn_assert.ys, tests/select/no_warn_prefixed_arg_memb.ys, tests/select/no_warn_prefixed_empty_select_arg.ys, tests/select/run-test.sh, tests/select/warn_empty_select_arg.ys
See discussion in #1756 and #1762.
The changes to `add.cc` are pretty straightforward.  The changes to `select.cc` definitely require review and should probably be discussed.
First, is this implemented correctly?  I don't have a lot of experience with this part of the code base.
Second, are there bad performance implications?  I don't imagine there will be much impact, but maybe I'm wrong.
Third, is this the desired behavior?  Should `select` arguments that do not match anything generate an error instead of a warning?
=> Closes #1762. Adds warnings for `select` arguments not matching any object and for `add` command when no modules selected

backends/smt2/smtio.py
This assumes the only desired output from the solver will be "sat", "unsat", or "unknown".
=> Fix solver output parsing for exists-forall optimization 

frontends/ast/simplify.cc
Before this commit, every initial assignment to a memory generated
two wires and four assigns in a process. For unknown reasons (I did
not investigate), large amounts of assigns cause quadratic slowdown
later in the AST frontend, in processAst/removeSignalFromCaseTree.
As a consequence, common and reasonable Verilog code, such as:
reg [`WIDTH:0] mem [0:`DEPTH];
integer i; initial for (i = 0; i <= `DEPTH; i++) mem[i] = 0;
took extremely long time to be processed; around 80 s for a 8-wide,
8192-deep memory.
After this commit, initial assignments where address and/or data are
constant (after `generate`) do not incur the cost of intermediate
wires; expressions like `mem[i+1]=i^(i<<1)` are considered constant.
This results in speedups of orders of magnitude for common memory
sizes; it now …
=> ast: avoid intermediate wires/assigns when lowering to AST_MEMINIT

frontends/verilog/preproc.cc, frontends/verilog/preproc.h, frontends/verilog/verilog_frontend.cc, frontends/verilog/verilog_frontend.h, kernel/rtlil.cc, kernel/rtlil.h, passes/cmds/design.cc, tests/various/sv_defines.ys, tests/various/sv_defines_dup.ys, tests/various/sv_defines_mismatch.ys, tests/various/sv_defines_too_few.ys
This patch should support things like
`define foo(a, b = 3, c)   a+b+c
`foo(1, ,2)
which will evaluate to 1+3+2. It also spots mistakes like
`foo(1)
(the 3rd argument doesn't have a default value, so a call site is
required to set it).
Most of the patch is a simple parser for the format in preproc.cc, but
I've also taken the opportunity to wrap up the "name -> definition"
map in a type, rather than use multiple std::map's.
Since this type needs to be visible to code that touches defines, I've
pulled it (and the frontend_verilog_preproc declaration) out into a
new file at frontends/verilog/preproc.h and included that where
necessary.
Finally, the patch adds a few tests in tests/various to check that we
are parsing everything correctly.
=> Add support for SystemVerilog-style `define to Verilog frontend

passes/cmds/design.cc
Mostly straightforward.
The interesting parts are things like (orig. line 233):
```
if (copy_to_design->modules_.count(prefix))
delete copy_to_design->modules_.at(prefix);
```
changing to:
```
if (copy_to_design->module(prefix) != nullptr)
copy_to_design->remove(copy_to_design->module(prefix));
```
The `if` condition is a standard change.  But the mechanics change from `delete`ing it to `remove()`ing it.  `remove()` does `delete` it, too, but it also erases the entry in `modules_` (which should have been done before, no?) and notifies any monitors.
Similarly, the lines changed to e.g:
```
RTLIL::Module *t = fmod->clone();
t->name = trg_name;
t->design = copy_to_design;
t->attributes.erase("\\top");
copy_to_design->add(t);
```
now use the proper `add()` method rather than brute forcing it …
=> Clean up pseudo-private member usage in `passes/cmds/design.cc`.

passes/opt/opt_merge.cc, tests/opt/opt_merge_init.ys, tests/opt/opt_merge_keep.ys
Previously, a `std::map` was used to keep the cells seen so far, using a custom comparator function which first looks at a cell's type, as well as some other factors like the existence of a keep attribute, before using a custom hash (cached so only run once per cell) to quickly check if same.
Transformed the `std::map` container into a ~`std::unordered_map`~ `dict` that maps directly from hash-string to cell, with a match triggering a more complex equality comparison (as before) to check that they really are identical before merging. Optimised many things inside the comparator and hash function along the way. 
*****
Now I've built this mostly preserving the existing (and potentially expensive) hashing function, however, we need not keep it so complex, since we are resistant to collisions …
=> opt_merge: speedup

passes/opt/opt_expr.cc, tests/opt/opt_expr_alu.ys
In particular:
* `$alu` cells (implementing `$add` or `$sub` functionality only) where an input is empty or all zero -- this duplicates the same functionality as for `$add` and `$sub`
* `$sub` cells with least-significant bits equal to `1'b1` -- e.g. the expression `{a,1'b1}-1'b1` can be safely optimised to `{a,1'b0}`.
=> opt_expr: improve performance on $alu and $sub

passes/opt/opt_expr.cc, tests/arch/anlogic/fsm.ys, tests/arch/efinix/fsm.ys, tests/opt/opt_expr_xor.ys
Interestingly, it seems that `opt_expr` will only optimise word-level `$and`/`$or` cells if they are one-bit wide:
https://github.com/YosysHQ/yosys/blob/f828cb5132b5d1a2c2d4d26ffaac6d492c7cc69e/passes/opt/opt_expr.cc#L443
https://github.com/YosysHQ/yosys/blob/f828cb5132b5d1a2c2d4d26ffaac6d492c7cc69e/passes/opt/opt_expr.cc#L449
Thus something like: `assign y = a & 2'b11` would not get optimised until simplemap breaks it down to gate-level/1-bit wide `$_AND_` cells.
In the case of `$xor`/`$xnor`/`$_XOR_`/`$_XNOR_` it seems that no optimisation was done at all, so this PR fixes that (but still only operates on 1-bit word cells).
=> opt_expr: optimise $xor/$xnor/$_XOR_/$_XNOR_ -s with constant inputs

kernel/modtools.h, passes/memory/memory_share.cc, passes/opt/opt_expr.cc, passes/opt/share.cc
Profiling showed that `CellTypes` was being created for each module in the design when inside `share`  and `memory_share`; rewrite to avoid doing that because constructing one can be expensive...
=> kernel: share a single CellTypes within a pass

libs/ezsat/ezsat.cc
The only user of this API right now is the puzzle3d benchmark and
it sees a slight reduction in CNF size from this, but the performance
difference is within the noise of measurement on my system.
=> Using LFSR counter for ezSAT::manyhot()

frontends/ast/ast.cc, frontends/ast/ast.h, frontends/rpc/rpc_frontend.cc, kernel/modtools.h, kernel/rtlil.cc, kernel/rtlil.h, kernel/sigtools.h, passes/cmds/trace.cc, passes/memory/memory_share.cc, passes/opt/opt_clean.cc, passes/opt/opt_expr.cc, passes/opt/opt_reduce.cc, passes/opt/pmux2shiftx.cc, passes/opt/share.cc, passes/opt/wreduce.cc, passes/proc/proc_prune.cc, passes/sat/clk2fflogic.cc, passes/techmap/extract_reduce.cc, passes/techmap/flowmap.cc, passes/techmap/techmap.cc
Especially `SigSpec` and `SigBit`.
Also speedup wire deletion by directly modifying `Module`'s private members.
Retry of #1827...
=> kernel: speedup by using more pass-by-const-ref

passes/techmap/deminout.cc
Before this patch,
```
module top(inout io);
assign io = 1'bx;
endmodule
```
would have the `io` pin demoted to input (same happens for `1'bz`,
but not for `1'b0` or `1'b1`), resulting in check failures later on.
Part of fix for #1841.
=> deminout: prevent any constant assignment from demoting to input

frontends/verilog/const2ast.cc
The following PR aims to close #1808 . Given that this is a front-end specific change, and even if the change may look simple, please feel free to comment if doesn't looks good enough or should be applied at a different level.
=> Adding error message for when size (width) of number literal is zero

frontends/ast/simplify.cc
Warnings like these:
```
techlibs/xilinx/cells_sim.v:0: Warning: Range [64:63] select out of bounds on signal `\mem_a': Setting 1 MSB bits to undef.
techlibs/xilinx/cells_sim.v:0: Warning: Range [64:63] select out of bounds on signal `\mem_b': Setting 1 MSB bits to undef.
techlibs/xilinx/cells_sim.v:0: Warning: Range [64:63] select out of bounds on signal `\mem_c': Setting 1 MSB bits to undef.
techlibs/xilinx/cells_sim.v:0: Warning: Range [64:63] select out of bounds on signal `\mem_d': Setting 1 MSB bits to undef.
```
as spotted by @Xiretza in https://github.com/YosysHQ/yosys/pull/1848#commitcomment-38195329
=> ast: cap dynamic range select to size of signal, suppresses warnings

passes/cmds/design.cc
There is currently no way to push the current design onto the design stack without also clearing the current design.  This PR adds the `-duplicate` option to the `design` command, which allows exactly that functionality.
=> Add `-push-copy` option to the `design` command.

Makefile
Since for pyosys libyosys is mandatory, this makes it more user friendly.
This closes issue  #1813
=> Enable ENABLE_LIBYOSYS when ENABLE_PYOSYS is set (closes #1813)

passes/cmds/splitnets.cc
This is similar to some other utility passes.
This is very useful for the cxxrtl backend (which calls splitnets internally) because that backend works just fine on modules with processes. In particular a situation where some modules have processes (and should be skipped) and some modules do not (and will be processed) is normal for that backend, and calling splitnets in that situation is beneficial.
=> splitnets: skip modules with processes

kernel/rtlil.cc, kernel/rtlil.h, passes/cmds/check.cc, passes/cmds/setundef.cc, passes/opt/opt_merge.cc
A few passes included the same list of FF cell types.  Make it a global
const instead.
The zinit pass also seems to include a list like that, but given that
it seems to be completely broken at the time (see #1568 discussion),
I'm going to pretend I didn't see that.
=> [NFCI] Deduplicate builtin FF cell types list

passes/techmap/zinit.cc, tests/techmap/zinit.ys
* Fixes `zinit` to handle coarse and fine-grained async flops
* Disables support for `$dffsr` and `$_DFFSR_[NP][NP][NP]_`
* `(* init *)` attributes only erased when consumed by `zinit`
=> zinit: fixes for $_DFF_[NP][NP][01]_and $adff cells with init = 1'b1

frontends/ast/simplify.cc
(the previous behavior was to just ignore the 2nd/subsequent declarations)
=> duplicated enum item names should result in an error

frontends/ast/simplify.cc, frontends/verilog/verilog_parser.y, tests/svtypes/typedef_package.sv
This commit adds support for using previously declared typedefs, enum values, and localparams/parameters within the same package. It also adds syntax support for parameters in systemverilog packages.
(parameters in systemverilog packages can't actually be overridden, so
allowing parameters in addition to localparams doesn't actually add any
new functionality, but it's useful to be able to use the parameter
keyword also within packages, especially for existing code)
=> support using previously declared types/localparams/parameters in package

backends/cxxrtl/cxxrtl.cc, backends/verilog/verilog_backend.cc
This PR makes it possible to use several cxxrtl-generated files in one application, as well as compiling cxxrtl-generated code as a separate compilation unit.
=> write_cxxrtl: enable separate compilation

backends/cxxrtl/cxxrtl.cc
E.g. port `q` in `submod x(.p(p), .q());`.
Fixes #1920.
=> write_cxxrtl: ignore disconnected module ports

passes/techmap/dffinit.cc, tests/techmap/dffinit.ys
=> dffinit: Avoid setting init parameter to zero-length value.

passes/opt/opt_expr.cc, tests/opt/opt_expr_alu.ys
Detect the places in the $alu where the carry bit is constant (due to
const A[i] == B[i] ^ BI) and split it into smaller $alu at these points.
Also, make the existing const-carry detection for low bits more generic
(now handles cases where both BI and CI are constant, but not equal to
one another).
Fixes #1912.
=> opt_expr: Add more $alu optimizations.

backends/cxxrtl/cxxrtl.cc
EN is 1'bx for unclocked ports
Fixes #1931
=> cxxrtl: Fix handling of unclocked memory read ports

Makefile, techlibs/intel/Makefile.inc, techlibs/intel_alm/Makefile.inc, techlibs/intel_alm/common/alm_map.v, techlibs/intel_alm/common/alm_sim.v, techlibs/intel_alm/common/arith_alm_map.v, techlibs/intel_alm/common/bram_m10k.txt, techlibs/intel_alm/common/bram_m10k_map.v, techlibs/intel_alm/common/bram_m20k.txt, techlibs/intel_alm/common/bram_m20k_map.v, techlibs/intel_alm/common/dff_map.v, techlibs/intel_alm/common/dff_sim.v, techlibs/intel_alm/common/lutram_mlab.txt, techlibs/intel_alm/common/lutram_mlab_map.v, techlibs/intel_alm/common/megafunction_bb.v, techlibs/intel_alm/common/quartus_rename.v, techlibs/intel_alm/cyclone10gx/quartus_rename.v, techlibs/intel_alm/cyclonev/quartus_rename.v, techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/add_sub.ys, tests/arch/intel_alm/adffs.ys, tests/arch/intel_alm/counter.ys, tests/arch/intel_alm/dffs.ys, tests/arch/intel_alm/fsm.ys, tests/arch/intel_alm/logic.ys, tests/arch/intel_alm/mux.ys, tests/arch/intel_alm/run-test.sh, tests/arch/intel_alm/shifter.ys, tests/arch/intel_alm/tribuf.ys
`synth_intel` has long been neglected, and I think it should be divided into two back-end sub-scripts to better represent architectural differences between LUT4+FF ("Logic Element") based FPGAs, such as the Cyclone IV and Cyclone 10LP; and LUT6+4xFF ("Adapatable Logic Module") based FPGAs, such as the Stratix II, Cyclone V and Cyclone 10GX. For now, this covers the ALM family; specifically the Cyclone V. 
The vendor LUT primitives (`{stratixii,cyclonev,cyclone10gx}_lcell_comb`) for the ALM architectures have been replaced with Yosys-internal `MISTRAL_ALMk` primitives; this allows Intel passes to operate on a single primitive family instead of multiple, deferring vendor primitive mapping until the end.
The equivalency tests have been ported from Efinix, barring `memory.ys` (I don't …
=> synth_intel_alm: replacement flow for ALM-based Intel FPGAs.

techlibs/intel_alm/common/quartus_rename.v, techlibs/intel_alm/synth_intel_alm.cc
This is enough for Quartus to accept `synth_intel_alm -vqm` output, and compile attosoc to run on real hardware.
The lack of initialisable BRAM is annoying, but for attosoc it's small enough that implementing in flops isn't a big deal.
I would *love* to add tests for this, but testing with `synth_intel_alm -quartus` would be blocked on #1498, which doesn't seem to be going anywhere.
=> synth_intel_alm: VQM support

README.md, frontends/ast/simplify.cc
Before this commit, enum values were serialized as attributes of form
\enum_<width>_<value>
where \<value> was a decimal signed integer.
This has multiple drawbacks:
* Enums with large values would be hard to process for downstream tooling that cannot easily parse arbitrary precision decimals. (In fact Yosys also did not correctly process enums with large values, and would overflow `int` in that case, which is UB.)
* Enum value attributes were not confined to their own namespace, making it harder for downstream tooling to enumerate all such attributes, as opposed to looking up any specific value.
* Enum values could not include `x` or `z`, which are explicitly permitted in the SystemVerilog standard.
After this commit, enum values are serialized as attributes of form
\enum_value_<value> …
=> ast/simplify: improve enum handling

techlibs/common/gen_fine_ffs.py, techlibs/common/simcells.v, techlibs/common/simlib.v
This brings the documented behavior for these cells in line with
$_DFFSR_* and $_DLATCHSR_*, which is that R has priority over S.
The models were already reflecting that behavior.
Also get rid of sim-synth mismatch in the models while we're at it.
=> Fix the truth table for $_SR_* cells.

backends/smt2/smtbmc.py, kernel/log.h, passes/cmds/design.cc, passes/sat/Makefile.inc, passes/sat/qbfsat.cc
This PR adds a new command, `qbfsat`, to solve combinational exists-forall problems.  These problems are useful for a number of different applications, including syntax-guided synthesis (SyGuS), circuit [debugging](https://www.epfl.ch/labs/lap/wp-content/uploads/2018/05/BeckerNov15_FudgeFactorSyntaxGuidedSynthesisForAccurateRtlErrorLocalizationAndCorrection_HVC15.pdf), [GLIFT optimization](https://www.epfl.ch/labs/lap/wp-content/uploads/2018/05/BeckerJun17_ArbitraryPrecisionAndComplexityTradeoffsForGateLevelInformationFlowTracking_DAC17.pdf), and [solver-aided design optimization](https://infoscience.epfl.ch/record/257026).
Exactly one module is expected to be selected, just like the `sat` command.
Existentially-quantified variables can be created with the `$anyconst` cell.  Regular …
=> Add `qbfsat` command to integrate exists-forall solving and specialization

kernel/rtlil.cc
Not removing connections can lead to the equivalent of:
`assign 1'bx = 1'bx;`
(since wires have been deleted) which fires an assertion in `Module::check()`
=> kernel: Module::makeblackbox() to clear connections too

libs/sha1/sha1.h, libs/subcircuit/subcircuit.cc
In particular inside class declarations, a static const
assignment is technically not a definition, while constexpr is.
Signed-off-by: Henner Zeller <h.zeller@acm.org>
=> Use static constexpr instead of static const where possible.

Makefile
The make targets echo-yosys-ver, echo-git-ver and echo-abc-rev can be used to programmatically extract contents of make variables for external scripts. Unfortunately, when a Makefile.conf exists, its contents would also be echoed, making the output almost unusable. This patch selectively disables this functionality for these special targets.
=> Suppress output of Makefile.conf when printing source versions

kernel/hashlib.h
This avoids an unnecessary copy of the `std::pair<K, T>` in the `entry_t` constructor when the inserted key/value pair is an rvalue and also always avoids an unnecessary `std::move()` into the `entries` member variable by instead constructing the `entry_t` in place with `emplace_back()`.
Inserting an rvalue into a `dict` is actually not super uncommon throughout the code base:
```
user@host:~/github/yosys$ find . -type f | xargs grep -n "\.insert(.*std::make_pair" | grep -v "^Binary file"
./techlibs/ice40/ice40_opt.cc:128:							new_attr.insert(std::make_pair(a.first, a.second));
./passes/hierarchy/submod.cc:187:						auto jt = new_wire->attributes.insert(std::make_pair(ID::init, Const(State::Sx, GetSize(sig)))).first;
./passes/pmgen/ice40_wrapcarry.cc:147: …
```
=> kernel: Add `dict` support for rvalue references and C++11 move semantics.

kernel/rtlil.cc, passes/cmds/design.cc
To prevent insertion during iteration; in line with `Design::add()`, `Module::{add,remove}()`, etc.
https://github.com/YosysHQ/yosys/pull/1862#discussion_r406340722
=> kernel: Design::remove(RTLIL::Module *) to check refcount_modules_

kernel/register.cc
When using the REPL, there is no convenient way to specify a design.  One can call `read_verilog`, `read_blif`, etc., but the Verilog or BLIF, etc. must exist in some file.
This PR enables recognition of "-" as a filename for `Frontend` passes, and when that is given, it reads from stdin just like it would read from a script file with a heredoc.  This means one can do something like the following:
```
yosys> read_verilog -dump_ast1 -
module top(input a, output reg q);
always @*
if (1'b1)
q = !a;
endmodule
EOT
1. Executing Verilog-2005 frontend: <stdin>
Parsing Verilog input from `<stdin>' to AST representation.
Generating RTLIL representation for module `\top'.
Dumping AST before simplification:
AST_MODULE <<stdin>:1.1-5.10> [0x1da4420] str='\top'
AST_WIRE <<stdin>:1.18-1.19> [0x1da4c30] …
```
=> Frontend: allow reading file input from stdin, like a REPL heredoc mode

passes/cmds/rename.cc
Unfortunately this might have performance implications.  Instead of iterating through `wires_` or `cells_` once directly, creating one renamed copy, and swapping members, we now iterate through once to create `selected_wires()` or `selected_cells()`, then potentially iterate through everything again, where we then rename each element in place.
=> Clean up pseudo-private member usage in `passes/cmds/rename.cc`.

passes/techmap/abc.cc
This also eliminates many explicit `RTLIL::SigSpec` constructions, which IMO are just clutter.  I think the changed code is now much more readable.
=> Clean up pseudo-private member usage and simplify `passes/techmap/abc.cc`

frontends/verilog/verilog_parser.y
See #1855.
The example to `read_verilog -dump_ast1`:
```
module top(input a, output reg q);
always @*
if (1'b1)
q = !a;
endmodule
```
now gives:
```
AST_MODULE <<stdin>:1.1-5.10> [0x218ae70] str='\top'
AST_WIRE <<stdin>:1.18-1.19> [0x218b680] str='\a' input port=1
AST_WIRE <<stdin>:1.32-1.33> [0x218b7c0] str='\q' output reg port=2
AST_ALWAYS <<stdin>:2.2-4.11> [0x218b900]
AST_BLOCK <<stdin>:2.11-4.11> [0x218ba40]
AST_CASE <<stdin>:3.3-4.11> [0x2186ce0]
AST_REDUCE_BOOL <<stdin>:0.0-0.0> [0x218c320]
AST_CONSTANT <<stdin>:3.7-3.11> [0x2164c60] bits='1'(1) range=[0:0] int=1
AST_COND <<stdin>:3.7-3.11> [0x218c080]
AST_CONSTANT <<stdin>:0.0-0.0> [0x218bf30] bits='1'(1) range=[0:0] int=1
AST_BLOCK <<stdin>:4.4-4.11> [0x2189e10]
AST_ASSIGN_EQ <<stdin>:4.4-4.10> [0x218cc30]
AST_IDENTIFIER …
```
=> Verilog frontend: add location information to parsed constants

kernel/rtlil.cc, kernel/rtlil.h
Cxxrtl is going to use a few string attributes, so I decided to factor these functions out. I also think that `has_attribute(ID::X)` reads nicer than `attributes.count(ID::X)`.
=> rtlil: add AttrObject::{get,set}_string_attribute, AttrObject::has_attribute

passes/sat/qbfsat.cc
Some libcs, validly, have stdout as a macro which means it can't be used as an identifier elsewhere.
Fixes #1953
=> qbfsat: Fix illegal use of 'stdout' identifier

frontends/verilog/verilog_parser.y
See #1855.
Before this PR:
```
yosys> read_verilog -dump_ast1 <<EOT
module foo(input clk);
always @(posedge clk) begin:foo
reg bar;
bar <= ~bar;
end
endmodule
EOT
1. Executing Verilog-2005 frontend: <stdin>
Parsing Verilog input from `<stdin>' to AST representation.
Generating RTLIL representation for module `\foo'.
Dumping AST before simplification:
AST_MODULE <<stdin>:1.1-7.10> [0x598402ff9670] str='\foo'
AST_WIRE <<stdin>:1.18-1.21> [0x598402ff2d00] str='\clk' input port=1
AST_ALWAYS <<stdin>:3.1-6.4> [0x598402ff2e40]
AST_POSEDGE <<stdin>:0.0-0.0> [0x598402ff6cf0]
AST_IDENTIFIER <<stdin>:3.18-3.21> [0x598402ff6bb0] str='\clk'
AST_BLOCK <<stdin>:3.22-6.4> [0x598402ff6e30]
AST_BLOCK <<stdin>:0.0-0.0> [0x598402ff3850] str='\foo'
AST_WIRE <<stdin>:4.9-4.12> [0x598402ff7560] str='\bar' reg …
```
=> Verilog frontend: add source location in more parser rules

backends/cxxrtl/cxxrtl.cc
=> cxxrtl: correctly handle `sync always` rules

backends/cxxrtl/cxxrtl.cc, backends/cxxrtl/cxxrtl.h
This PR makes it possible to replace certain modules in CXXRTL-generated code with C++ black boxes, with either fixed or parameterized port widths. The implementation of a black box may reside in a separate translation unit (even if the port widths are parameterized), and each instance of a black box can have different behavior, selected via synthesis-time parameters and/or runtime environment. This should be enough for even the most complex applications.
See the individual commits and the pass help text for details.
=> cxxrtl: add support for simple and templated C++ black boxes

backends/cxxrtl/cxxrtl.cc, backends/cxxrtl/cxxrtl.h
Both parameters and attributes are necessary because the parameters have to be the same between every instantiation of the cell, but attributes may well vary. For example, for an UART PHY, the type of the PHY (tty, pty, socket) would be a parameter, but configuration of the implementation specified by the type (socket address) would be an attribute.
=> cxxrtl: provide attributes to black box factories, too

backends/firrtl/firrtl.cc, frontends/ast/ast.cc, frontends/rpc/rpc_frontend.cc
The `$paramod` name mangling is not invertible (the `\` character, which separates the module name from the parameters, is valid in the module name itself), which does not stop people from trying to invert it.
This commit makes it easy to invert the name mangling by storing the original name explicitly in the `\hdlname` attribute, and fixes the firrtl backend to use the newly introduced attribute.
**Unresolved question:** is `\hdlname` the appropriate attribute here? Currently it's only used in the `unique` pass, and I think the intent is the same, but I'd rather double check.
=> ast, rpc: record original name of $paramod\* as \hdlname attribute

backends/cxxrtl/cxxrtl.cc, backends/cxxrtl/cxxrtl.h
This PR improves performance of the CXXRTL simulations by approximately 2.6× uniformly across different pass pipelines on a single representative design (Minerva SRAM SoC with black box UART). Moreover, if the design is fully flattened, it is able to achieve 1 delta cycle per clock edge by optimally scheduling all of the logic in the design, including the black box.
The following is a totally non-scientific estimate of the speedup provided by this PR. It was collected on an idle Dell XPS13 9360 laptop with Intel Core i7-7500U CPU, Linux 4.19.0-8, and clang++ 7.0.1-8 by running the Minerva SRAM SoC for 1 million cycles. Each evaluation step invokes the `poll()` syscall (and very few of them also `write()`), which are excluded from the measurements (i.e. only user time is counted). …
=> cxxrtl: Gas gas gas! I'm gonna step on the gas! Tonight I'll fly!

passes/sat/sim.cc, tests/various/sim_const.ys
From https://www.reddit.com/r/yosys/comments/g57t8d/using_sim_to_get_initial_state_for_smtlib2_and/
=> sim: Fix handling of constant-connected cell inputs at startup

kernel/hashlib.h
This is similar to the recent changes to `dict`.
This always avoids a `std::move` by `emplace_back()`ing `entry_t`s in-place, and avoids making a copy when `insert()` is given an rvalue reference by `std::forward<>()`ing and `std::move()`ing it into the `udata` member of `entry_t`.
=> kernel: Add `pool` support for rvalue references and C++11 move semantics.

passes/pmgen/ice40_dsp.cc, passes/pmgen/ice40_dsp.pmg, passes/pmgen/xilinx_dsp.pmg, passes/pmgen/xilinx_dsp_CREG.pmg, passes/pmgen/xilinx_dsp_cascade.pmg, passes/pmgen/xilinx_srl.cc, passes/pmgen/xilinx_srl.pmg, techlibs/ecp5/ecp5_ffinit.cc, techlibs/ecp5/ecp5_gsr.cc
Courtesy of functionality enabled in #1945. Means that default parameter values are held in one place only: `<arch>/cells_sim.v`.
=> Cleanup use of hard-coded default parameters in light of #1945

passes/cmds/select.cc, tests/select/blackboxes.ys
Without which `select c:*` will select specify cells inside blackboxes, or anything inside a whitebox.
=> select: do not select inside black-/white- boxes unless '=' prefix used

kernel/rtlil.cc, passes/pmgen/xilinx_dsp_cascade.pmg, techlibs/ecp5/ecp5_gsr.cc, techlibs/xilinx/xilinx_dffopt.cc, tests/arch/ice40/ice40_dsp.ys, tests/arch/xilinx/xilinx_dffopt.ys, tests/arch/xilinx/xilinx_dsp.ys
As it did before #1945.
Would not expect this to be reachable for the end-user, but makes debugging a little easier for developers who may have fat fingers.
=> kernel: Cell::getParam() to throw exception again if not found

techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/quartus_ice.ys
After knowing about this bug for [ten months](https://pastebin.com/iFbMHsiL) this morning I finally spent time (>12 hours of `bugpoint`) trying to diagnose what the hell was going on. It turns out that Quartus also appears to suffer something like #1676, and when presented with a raw identifier that contains `[]` parses uses of it as a slice access.
I also took the opportunity to add a few comments around here too about VQM and the various workarounds used for it.
=> intel_alm: work around a Quartus ICE

passes/sat/qbfsat.cc
This PR allows, for `$anyconst` "hole" specialization purposes, multiple cells to share the same source location as long as only one `$anyconst` or `$anyseq` has that location.
This may seem stupid: Exactly one cell should have any particular source location.  But if we do some transformations to the design in order to add the `$anyconst`, there is no natural source location, so they might get tagged with the location of another related cell.
=> qbfsat: Make hole name recovery from source locations more robust.

backends/cxxrtl/cxxrtl.cc
I did not realize that an attribute named `pass.attr` needs escaping in Verilog (mostly because Yosys gladly accepts it). Because of that the Yosys convention is `pass_attr`, and this PR updates CXX to use that convention.
=> cxxrtl: fix attribute syntax, minor fixes

backends/cxxrtl/cxxrtl.cc
Otherwise, a 3-bit memory value was being output as 0xu.
=> cxxrtl: Round up constant width

CHANGELOG, Makefile, manual/CHAPTER_Auxprogs.tex
Enabling modifications.
Currently, the only modification is YosysHQ/abc#1 which is a proposed fix for Yosys' `abc9 -dff` operating on multi clock designs.
=> abc: use YosysHQ/abc instead of upstream berkeley-abc/abc

.editorconfig
abc has lots of trailing spaces and a different convention for indents.
=> Fix .editorconfig to not break abc

frontends/verific/verific.cc, frontends/verific/verific.h
Supersedes #1986 
Test at YosysHQ/yosys-tests#90
=> verific: recover wiretype/enum attr as part of import_attributes()

Makefile, README.md, techlibs/ecp5/Makefile.inc, techlibs/gowin/Makefile.inc
All this time I thought Yosys can't be built out of tree, but it turns out it can be, it's just really cleverly hidden. (As far as I can find, even though support for this was added in 2015, but no Yosys-related resource explained how to actually use it at any point. I had to reverse-engineer it from the Makefiles.)
=> Explain how to do out-of-tree builds in README

Makefile, frontends/rpc/Makefile.inc, kernel/driver.cc, kernel/register.cc, kernel/yosys.cc, kernel/yosys.h, libs/ezsat/ezminisat.cc, libs/minisat/00_PATCH_wasm.patch, libs/minisat/00_UPDATE.sh, libs/minisat/System.cc, passes/cmds/Makefile.inc, passes/cmds/cover.cc, passes/cmds/show.cc, passes/sat/Makefile.inc, passes/techmap/Makefile.inc, passes/techmap/abc.cc, passes/techmap/abc9_exe.cc
See PR #1483 for a previous attempt (for some reason I can't reopen that PR).
<hr>
This PR includes the following significant changes:
* Patching ezsat and minisat to disable resource limiting code on WASM/WASI, since the POSIX functions they use are unavailable.
* Adding a new definition, `YOSYS_DISABLE_SPAWN`, present if platform does not support spawning subprocesses (i.e. Emscripten or WASI). This definition hides the definition of `run_command()`.
* Adding a new Makefile flag, `DISABLE_SPAWN`, present in the same condition. This flag disables all passes that require spawning subprocesses for their function. It replaces ad-hoc checks of `$(CONFIG)`.
<hr>
This PR cannot be merged yet. Unresolved issues:
<hr>
In practice, WASI Yosys works quite well. I can synthesize medium sized iCE40 …
=> Add WASI platform support

kernel/log.cc, kernel/log.h
The workflow of debugging fatal pass errors in Yosys is flawed in three ways:
1. Running Yosys under a debugger is sufficient for the debugger to catch some fatal errors (segfaults, aborts, STL exceptions) but not others (`log_error()`, `log_cmd_error()`). This is neither obvious nor easy to remember.
2. To catch Yosys-specific fatal errors, it is necessary to set a breakpoint at `logv_error_with_prefix()`, or at least, `logv_error()`. This is neither obvious nor easy to remember, and GDB's autocomplete takes many seconds to suggest function names due to the large amount of symbols in Yosys.
3. If a breakpoint is not set and Yosys encounters with such a fatal error, the process terminates. When debugging a crash that takes a long time to reproduce (or a nondeterministic crash) this can …
=> kernel: Trap in `log_error()` when a debugger is attached

frontends/ast/genrtlil.cc
This PR adds the complete source location, including `first_line`, `first_column`, `last_line`, and `last_column`, in all the places in `genrtlil.cc` where source location attributes are currently set.
=> frontend: Include complete source location instead of just `location.first_line` in `frontends/ast/genrtlil.cc`.

techlibs/ecp5/synth_ecp5.cc, techlibs/ice40/synth_ice40.cc, techlibs/xilinx/synth_xilinx.cc
```
scratchpad -set synth_ice40.abc9.W 250
scratchpad -set synth_ecp5.abc9.W 200
scratchpad -set synth_xilinx.abc9.W 300
```
=> synth_ice40/ecp5/xilinx: allow abc9.W to be overridden via scratchpad

Makefile
This PR works around #2011 and updates ABC to a more recent commit with WASI support.
=> Fix WASI builds with abc enabled

frontends/verilog/verilog_parser.y, tests/various/gen_if_null.v, tests/various/gen_if_null.ys
This addresses #2021. This wraps the then block of gen-ifs in an implicit block, similar to the strategy employed for procedural if statements. I am not sure if my strategy for "asserting" which branch is taken via the port bindings is reasonable. I am eager to receive any feedback you may have!
=> verilog: allow null gen-if then block

backends/cxxrtl/cxxrtl.cc, backends/firrtl/firrtl.cc, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, kernel/yosys.h
Add a few comments and an unreachable `break` in cxxrtl to silence implicit fallthrough warnings. For some reason, the g++9 configuration on travis doesn't allow comments to [silence the warnings](https://travis-ci.org/github/YosysHQ/yosys/jobs/682632651#L661), even though this [should be enabled](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html) by `-Wextra`. Not that this is too big of a deal, but specifying the warning option explicitly might just fix it.
=> Avoid switch fall-through warnings

Makefile
`$(LIBDIR)` is only created at install, so at best contains an older version of libyosys; and yosys is not linked against older versions of itself, so there is no reason to add it to linker flags. If no previous install with `ENABLE_LIBYOSYS := 1` was done, the directory doesn't exist at all and leads to a warning at build:
```
ld: warning: directory not found for option '-L/usr/local/lib/yosys'
```
=> Remove yosys libdir from LDFLAGS (and fix a typo)

passes/opt/opt_clean.cc, tests/opt/opt_clean_init.ys
* Remove `(* init *)` on public signals regardless of `-purge` option -- since we're not removing signals, we're just removing redundant information
* Remove `(* init *)` when consistent with the sigmap (constant) result, see testcase
* `clean` was not behaving identically to `opt_clean` as per documentation, since it didn't invoke this `init` removal
=> opt_clean: remove (* init *) regardless of -purge, remove (* init *) when consistent with sigmap, clean to behave identically

frontends/verific/verific.cc
Test case:
```
module test (
input  logic clock,        
input  logic reset,
input  logic [0:0] A,
input  logic [1:0] B,
input  logic [2:0] C,
input  logic [15:0] din,
output logic [15:0] dout
);
logic [15:0] mem [0:1][0:3][0:5];
always @(posedge clock) begin
if (reset) begin
for (int I = 0; I < 2; I++)
for (int K = 0; K < 4; K++)
mem[I][K] <= '{default:0};
end else begin
dout <= mem[A][B][C];
mem[A][B][C] <= din;
end
end
endmodule
```
=> Add support for non-power-of-two mem chunks in verific importer

Makefile, frontends/verilog/verilog_parser.y, tests/verilog/.gitignore, tests/verilog/bug2042-sv.ys, tests/verilog/bug2042.ys, tests/verilog/run-test.sh
Fixes #2042.
~Supporting this is left as a future enhancement.~
=> verilog: error if no direction given for task arguments, default to input in SV mode

passes/opt/opt_expr.cc, tests/fsm/generate.py, tests/opt/bug1758.ys, tests/opt/opt_expr_alu.ys, tests/opt/opt_expr_and.ys, tests/opt/opt_expr_consumex.ys, tests/opt/opt_expr_or.ys, tests/opt/opt_expr_xnor.ys, tests/opt/opt_expr_xor.ys
Before this, `opt_expr -keepdc` wasn't always behaving correctly, and there were missed opportunities surrounding single-bit coarse cells `$and/$or/$xor/$xnor`.
Fixes #1758.
~The one remaining issue with `opt_expr` is that it won't optimise multi-bit coarse grained cells directly:~
```
read_verilog <<EOT
module top(input [1:0] i, output [1:0] o);
assign o = 2'b00 & i;
endmodule
EOT
opt_expr
```
~will show a 2-bit `$and` cell remaining. Instead, Yosys seems to rely on bit-blasting into fine-grained cells (`$_AND_`) and optimising there. I'll file this as a separate issue.~
EDIT: I'm wrong. I needed `opt_expr -fine`.
=> opt_expr: improve single-bit $and/$or/$xor/$xnor cells; gate cells too

backends/smt2/smtbmc.py
It looks like `retstatus` was changed in 2ed2e9c3e but these lines were not updated.
=> smtbmc: Fix return status handling.

kernel/log.h
PR #2000 was only implemented for Windows and Linux.  This enables the Unix code under MacOS where the signal type is different.
=> Extend YS_DEBUGTRAP to MacOS.

kernel/log.cc, kernel/log.h, passes/cmds/logger.cc
This refactors the `logger_expect_*` data structures to use the (`std::string`) regex pattern as the key to a `dict`, and to put the compiled `YS_REGEX_TYPE` into the value type `LogExpectedItem`.  This eliminates the need for the code added in #2055 and better expresses the intent: There should only be one entry per regex.
=> log: Use `dict` instead of `std::vector<std::pair>` for `log_expect_{error, warning, log}` to better express the intent that each element is unique.

frontends/verilog/verilog_parser.y, tests/verilog/task_attr.ys
Attributes go after the function identifier for function calls, but before the task identifier for task enable statements.
This fixes it, but introduces 13 shift-reduce conflicts. Can someone smarter than I help me figure out where the conflict is please?
EDIT: Actually, it goes further and breaks a task related test...
Potentially blocking #2044 which also has 13 shift-reduce conflicts when I try and add support for attributes for `simple_behavioural_stmt`.
=> verilog: support attributes before (not after) task identifier (but 13 s/r conflicts)

backends/cxxrtl/cxxrtl.cc
This isn't actually necessary anymore after scheduling was improved, and `clean -purge` disrupts the mapping between wires in the input RTLIL netlist and the output CXXRTL code.
=> cxxrtl: get rid of -O5 aka `opt_clean -purge` optimization level

passes/sat/qbfsat.cc
Overview:
----
It turns out that Z3's SMT optimization implementation (see #1746 ) sadly really does not support optimizing quantified variables, even though it appears to work for simple examples.
This PR adds an alternative: An iterated bisection method.  This method adds a thresholding comparator to the module and `$assume`s that the wire to be optimized is either less-than-or-equal-to (if minimizing) or greater-than-or-equal-to (if maximizing) some constant value.  `yosys-smtbmc` is called multiple times, each time solving an instance of the problem with a different constant threshold value.
Algorithm summary:
----
First, we solve an instance of the problem with no constraint on the value of the wire to be optimized.  If we cannot find a solution, the problem is UNSAT.  Otherwise, we …
=> qbfsat: Add an iterative bisection optimization method and make it the default.

frontends/verilog/verilog_parser.y, tests/verilog/bug2037.ys
Fixes #2037. 
To support the null statement I had to remove the `gen_stmt_or_null` rule as modifying it to allow attributes created a shift/reduce conflict.
=> verilog: allow attributes on behavioural statements (including null statement)

kernel/rtlil.h
These operators work by fetching the string from the global string
table and then comparing with the std::string that was passed in as
rhs.
Using str() means that we create a std::string (strlen; malloc;
memcpy), compare for equality (another memcmp if they have the same
length) and then finally free the string.
Using c_str() means that we pass the const char* straight to
std::string's equality operator. This ends up as a call to
std::string::compare (the const char* flavour), which is essentially
strcmp.
=> Use c_str(), not str() for IdString/std::string == and != operators

kernel/rtlil.h
There was a handwritten copy constructor, which I'm not sure was
actually legal C++ (it unconditionally read from the 'data' member of
a union, which wouldn't have been written if wire was true). It was
also a bit less efficient than the constructor you get from the
compiler by default (which is allowed to just copy the memory).
This gives a marginal (~0.25%) decrease in code size when compiled
with GCC 9.3.
=> Use default copy constructor for RTLIL::SigBit

kernel/rtlil.h
The existing code does a search to figure out whether id is in the
dict (with the call to count()), and then looks it up again to get the
result (with the call to at()). This version calls find() instead,
avoiding the double lookup.
Code size increases slightly (6kb). I think this is because the
contents of find() are getting inlined, and then inlined into lots of
the callsites for cell() and wire().
Looking at the compiled code before this patch, you just get
a (non-inlined) call to count() followed by a call to at(). After the
patch, the contents of find() have been inlined (so you see do_hash,
then do_lookup). The result for each function is about 30 bytes / 40%
bigger, which presumably also enlarges call-sites that inline it.
=> Minor optimisation in Module::wire() and Module::cell()

backends/firrtl/firrtl.cc
The current firrtl backend emits blackboxes as standard modules
with an empty body, but this causes the firrtl compiler to
optimize out entire circuits due to the absence of any drivers.
Yosys already tags blackboxes with a (*blackbox*) attribute, so this
commit just propagates this change to firrtl's syntax for blackboxes.
=> Add extmodule support to firrtl backend

Makefile
9dedac50 introduced this harmless but disconcerting warning, which was emitted when abc/ did not yet exist and was about to be cloned:
```
$ make abc/abc-fd2c9b1
[Makefile.conf] CONFIG := gcc
[  0%] Building abc/abc-fd2c9b1
/bin/sh: line 0: cd: abc: No such file or directory
Pulling ABC from https://github.com/YosysHQ/abc:
+ test -d abc
+ git clone https://github.com/YosysHQ/abc abc
Cloning into 'abc'...
[...]
```
=> Suppress warning during initial clone of ABC repo

passes/cmds/Makefile.inc, passes/cmds/printattrs.cc, tests/various/printattr.ys
AFAIK in general there is no way to know if an attribute is a string attribute, a bool attribute, or bit string attribute.  So the attribute value is printed first as `decode_string()` and then as `as_string()`, so all kinds of attribute values will be visible.
=> Add `printattrs` command to print attributes of currently selected objects.

frontends/ilang/ilang_lexer.l
Commit ca70a104 did not use a correct check.
Extracted from #2066.
=> ilang_lexer: fix check for out of range literal

backends/smt2/smtio.py, passes/sat/qbfsat.cc
Overview:
----
This PR adds support for using Yices in exists-forall mode to `yosys-smtbmc` and `qbfsat`.  This requires some tweaks like ensuring the logic specification is only `BV` and appears before any uses of operators or types from that logic.
This PR also makes Yices the default solver, replacing Z3.  This is because I have [found](https://github.com/boqwxp/yosys-examples/tree/master/example1) that Yices is *much* faster than Z3.  In this example, Yices found a solution to a bisection iteration problem in ~6m on my machine (~3m when linking Yices with `libtcmalloc`), using no more than 400MB of memory.  Z3, on the other hand, took approximately the same amount of time to gobble up 8GB of memory and fail.  While this is only one data point, it agrees with my experience that Yices …
=> qbfsat: Add `-solver` option and allow choice of Z3 or Yices, making Yices the default.

backends/smt2/smtio.py, passes/sat/qbfsat.cc
Overview:
----
This PR adds support for using [CVC4](https://github.com/CVC4/CVC4) as a solver for `qbfsat`.
I have not been able to get acceptable performance from CVC4; even Z3 seems to be faster.  It does seem to have very low memory usage, but I'm not sure how meaningful that is if I can never get a solution for even fairly small problems.  [The example](https://github.com/boqwxp/yosys-examples/blob/master/example1/example.smt2) that Yices solves in less than 6 minutes still was not solved by CVC4 after 200 minutes on my machine.
But it is possible to use it, it takes very little additional effort, and there are lots of knobs to fiddle with, so maybe it would work better for someone else who knows just how to tune those knobs.
Depends:
----
=> qbfsat: Add support for CVC4.

kernel/rtlil.h, manual/CHAPTER_Overview.tex
This is an existing invariant (most backends can't cope with these) but one that was not checked or documented.
=> Restrict RTLIL::IdString to not contain whitespace or control chars

CHANGELOG, backends/btor/btor.cc, backends/btor/test_cells.sh, backends/firrtl/firrtl.cc, backends/smt2/smt2.cc, backends/smv/smv.cc, backends/smv/test_cells.sh, backends/verilog/verilog_backend.cc, kernel/calc.cc, kernel/celledges.cc, kernel/celltypes.h, kernel/rtlil.cc, kernel/rtlil.h, kernel/satgen.h, manual/CHAPTER_CellLib.tex, manual/PRESENTATION_Prog.tex, passes/cmds/stat.cc, passes/memory/memory_share.cc, passes/opt/opt_expr.cc, passes/opt/opt_share.cc, passes/opt/share.cc, passes/opt/wreduce.cc, passes/tests/test_cell.cc, techlibs/common/simlib.v, techlibs/common/techmap.v, tests/simple/constmuldivmod.v
Many languages have both modulo and remainder operations. They perform the same basic task (remainder of an integer division), but the sign of the output changes:
- The result of a remainder operation has the sign of the numerator (dividend)
- The result of a modulo operation has the sign of the denominator (divisor)
The `$mod` cell, being targeted at the Verilog `%` operator, used remainder semantics, making it hard to add a cell for actual modulo operations. `$mod` was renamed to `$rem`, and a new `$mod2` cell that performs denominator-signed modulo was added.
Fixes #1523.
=> Fix modulo/remainder semantics

backends/smt2/smtbmc.py, backends/smt2/smtio.py, passes/sat/qbfsat.cc
Overview:
----
This PR adds support to `yosys-smtbmc` and `qbfsat` for setting solver timeouts.
This is mostly straightforward, ~but `yices-smt2` currently has [a bug](https://github.com/SRI-CSL/yices2/issues/210) that renders the proper command line argument mechanism for specifying a timeout ineffective.~
~The draft PR includes an additional commit to what is intended to merge that works around this issue by using the `timeout` program.  Obviously this is not portable and this workaround commit will be removed once the Yices issue is fixed.  Until then, the commit exists to help test Yosys and `yosys-smtbmc` behavior and the PR will remain as a draft.~
**Update**: Yices has been fixed and the workaround commit has been removed.  This PR is now ready for review.
Depends:
----
=> smtbmc and qbfsat: Add timeout option to set solver timeouts for Z3, Yices, and CVC4.

passes/cmds/blackbox.cc
~Currently, `blackbox` only sets the RTLIL blackbox attribute. Re-jig it so that the AST attribute is also set, such that derived modules created by `Module::derive()` also inherit this blackbox attribute.~
=> blackbox: use Module::makeblackbox() method

backends/ilang/ilang_backend.cc, backends/json/json.cc, frontends/ast/genrtlil.cc, frontends/ilang/ilang_parser.y, frontends/json/jsonparse.cc, kernel/rtlil.cc, kernel/rtlil.h
As per suggestion made in https://github.com/YosysHQ/yosys/pull/1987, now:
`RTLIL::Wire` now holds an is_signed field.
`signed` is exported via JSON backend, and read in via JSON frontend
Also exported via dump_rtlil command, and read back via ilang_parser
I am sure I missed a few other places, and would love to add a test somewhere. Please feel free to advise!
=> Preserve 'signed'-ness of a verilog wire through RTLIL

backends/btor/btor.cc
This adds the `-n` option to disable adding symbols for names starting with `$` to the btor model, so they don't end up in VCDs generated with btorsim.
=> btor backend: add option to not include internal names

manual/PRESENTATION_Prog/Makefile
This is basically the same issue as in `tests/various/plugin.sh`, which uses yosys-config to compile a plugin. `yosys-config --cxxflags` points to `$PREFIX/share/` (`/usr/local/share` by default), which might not exist yet or might be out of date. Building directly from the headers in `share/` avoids this.
=> Use in-tree include directory in manual build

backends/btor/btor.cc
Since the btor backend only used for sby where this is the more useful behavior.
Rename the option to include internal names -x (for 'extra names').
=> btor backend: make not printing internal names default

backends/smt2/smtio.py
Invoking sby in macOS Catalina fails because of bizarre stack limits in Catalina.
See related issue here: https://github.com/YosysHQ/yosys/issues/692
Invoking sby in Catalina fails with:
```
SBY 13:58:00 [adder3_formal] engine_0: Traceback (most recent call last):
SBY 13:58:00 [adder3_formal] engine_0: File "/usr/local/bin/yosys-smtbmc", line 22, in <module>
SBY 13:58:00 [adder3_formal] engine_0: from smtio import SmtIo, SmtOpts, MkVcd
SBY 13:58:00 [adder3_formal] engine_0: File "/usr/local/Cellar/yosys/0.9_2/bin/../share/yosys/python3/smtio.py", line 46, in <module>
SBY 13:58:00 [adder3_formal] engine_0: resource.setrlimit(resource.RLIMIT_STACK, (smtio_stacksize, current_rlimit_stack[1]))
SBY 13:58:00 [adder3_formal] engine_0: ValueError: current limit exceeds maximum limit
SBY 13:58:00 …
```
=> MacOS has even stricter stack limits in catalina.

backends/cxxrtl/cxxrtl.cc, backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_capi.cc, backends/cxxrtl/cxxrtl_capi.h
See individual commits for details.
This PR has two main opportunities for improvement, to be addressed in future PRs:
1. Memories cannot be updated in a race-free way either through the C++ debug information or the C API.
2. Localized and elided public signals do not appear in the debug information and cannot be introspected.
This PR significantly benefits from (but does not depend on) #2107.
=> cxxrtl: add debug information to the C++ API, and add introspection via a new C API

passes/fsm/fsm_extract.cc
log_signal can result in a string with spaces (when bit selection is
involved), which breaks the rule of IdString not containing whitespace.
Instead, remove the sigspec from the name entirely — given that the
resulting wire will have no users, it will be removed later anyway,
so its name doesn't really matter.
Fixes #2118
=> fsm_extract: avoid calling log_signal to determine wire name

frontends/ast/simplify.cc, frontends/verilog/verilog_parser.y, tests/svtypes/struct_array.sv
Allow packed arrays of the form
bit [5:0] [63:0] a;         // 6 elements each 64 bits in size
in packed struct/union.
=> Support packed arrays in struct/union.

kernel/rtlil.cc, kernel/rtlil.h, passes/techmap/Makefile.inc, passes/techmap/flatten.cc, passes/techmap/techmap.cc
Although the two passes started out very similar, they diverged over time and now have little in common. Moreover, `techmap` is extremely complex while `flatten` does not have to be, and this complexity interferes with improving `flatten`.
This is a fairly large PR, and it is best reviewed commit by commit: it starts by copying the techmap code wholesale and then simplifying it to make it easier to convince yourself that the changes are indeed correct. It can also be helpful to append `?w=1` to the URL to omit whitespace changes from the output.
The only actual improvement to `flatten` in this PR is using topological order, but it sets the stage for adding support for `hdlname` and processes (without `proc`).
=> Split `flatten` from `techmap` and simplify it

passes/hierarchy/hierarchy.cc
This code originally comes from commit 458a940. When an interface is
used via a modport, code in genrtlil.cc sets '\\interface_type' and
'\\interface_modport' properties on the wire.
In hierarchy.cc, we pick up the modport name and add it to a dict
called modports_used_in_submodule (that maps connection source to
modport name).
Before this patch, the modport name is retrieved as a strpool and then
iterated over in an arbitrary order, discarding all entries but the
last. In practice, the pool will always have 0 or 1 entries because
the string used to construct it is a valid identifier, so doesn't
contain any pipe symbols.
This patch changes the code to retrieve the modport name as just a
string. This will have the same effect in practice, but may be a bit
less confusing!
The code also gets …
=> Simplify a modport check in hierarchy.cc

kernel/register.h, passes/cmds/select.cc
With GCC 9.3, at least, compiling select.cc spits out a warning about
an implausible bound being passed to strncmp.
While tidying up the warning (and looking at the generated code), I
realised that we're creating several std::string objects and generally
repeating computations. This version should have the same behaviour,
but be rather more efficient.
Since I was visiting the file anyway, I also changed functions that
pass a std::string or standard library container by value to pass by
reference. The resulting code is ~6.4kb smaller when compiled with GCC
9.3 and standard settings.
=> Silence warning in select.cc and pass some more args by ref

Makefile, backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc, backends/cxxrtl/cxxrtl_capi.h, backends/cxxrtl/cxxrtl_vcd.h
This PR improves the quality of debug information with little overhead by observing that hierarchical designs often have highly redundant signals, generic designs often have signals tied to constants, and the cost of including these redundancies is minimal. It also fixes a few minor issues.
=> cxxrtl: improve design visibility

README.md, backends/cxxrtl/cxxrtl_backend.cc, kernel/rtlil.cc, kernel/rtlil.h, manual/CHAPTER_Overview.tex, passes/techmap/flatten.cc
This PR depends on #2120.
This PR adjusts `flatten` to track the exact original name in the `hdlname` attribute, and describes the semantics of that attribute in the manual.
This addition lays the groundwork for robust end-to-end tracking of public names, from frontend to bitstream. I would like to see a future where tooling can find out where every bit of every register ended up without ever having to guess, even though registers could have a name that contains dots, have been removed, duplicated, renamed to avoid conflicts, or split.
=> flatten: preserve original object names

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc
Before this commit, Verilog expressions like `x && 1` would result in references to `logic_and_us` in generated CXXRTL code, which would not compile. After this commit, since cells like that actually behave the same regardless of signedness attributes, the signedness is ignored, which also reduces the template instantiation pressure.
=> cxxrtl: ignore cell input signedness when it is irrelevant

backends/cxxrtl/cxxrtl_backend.cc, backends/cxxrtl/cxxrtl_vcd.h
(Something about the first binary search and the first correct binary search...)
=> cxxrtl: fix two buggy split_by functions

kernel/rtlil.cc, kernel/rtlil.h, passes/techmap/flatten.cc
There is no reason not to do this (the code that accepts processes is actually as long as the code that would print the error message rejecting them), it makes the pass nicer to use, and it allows some interesting experiments with other passes like CXXRTL (turns out `-noproc -flatten` has 15% lower compile time, which I was only able to measure after doing this change).
=> flatten: accept processes

frontends/verific/verific.cc, passes/opt/opt.cc, passes/sat/sat.cc, techlibs/common/prep.cc, tests/opt/opt_rmdff.v, tests/opt/opt_rmdff.ys
This PR also fixes `tests/opt/opt_rmdff` that previously only passed because `prep` was also running `opt_rmdff`. (Plus some drive-by modernizations in `sat.cc`.)
=> Do not optimize away FFs in "prep" and Verific front-end

backends/cxxrtl/cxxrtl_backend.cc
The new `-Og` optimization level guarantees 100% debug visibility with a relatively small (~2× on Minerva) slowdown and no extra delta cycles.
=> cxxrtl: introduce -Og optimization level

techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/dffs.ys, tests/arch/intel_alm/fsm.ys
While working on M10K direct instantiation, I discovered an embarrassing bug where the `dff2dffe` pass was doing nothing because it's pattern matching against `$_DFF_*` before `techmap` executes; the fix is simply to be less specific.
This one-line patch reduces the area of VexRiscV by about 15%.
cc @mwkmwkmwk
=> intel_alm: fix DFFE matching

backends/cxxrtl/cxxrtl_backend.cc
Without unbuffering output wires of, at least, toplevel modules, it is not possible to have most designs that rely on IO via toplevel ports (as opposed to using exclusively blackboxes) converge within one delta cycle. That seriously impairs the performance of CXXRTL.
=> cxxrtl: unbuffer output wires of toplevel module

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc, backends/cxxrtl/cxxrtl_capi.cc, backends/cxxrtl/cxxrtl_capi.h, backends/cxxrtl/cxxrtl_vcd.h
This avoids losing design visibility when using the `splitnets` pass.
Depends on #2142 to be useful.
=> cxxrtl: handle multipart signals

backends/cxxrtl/cxxrtl.h
This was a correctness issue, but one of the consequences is that it resulted in jumps in generated machine code where there should have been none. As a side effect of fixing the bug, Minerva SoC became 10% faster.
=> cxxrtl: fix rzext()

kernel/log.h
Upgrading to WASI SDK 11.0 caused the WASM build to fail because WASM does not have signals.
=> kernel: guard include of signal.h more precisely

backends/cxxrtl/cxxrtl.h
This fixes #2157
I think this covers all the cases now. It works by finding the most significant chunk after the shift, calculating the number of bits in that chunk, then masking the rest. In the edge case where a small shift lands right on a chunk boundary, it will mask off the whole chunk above - I think that's reasonable so it didn't seem worth adding a special case.
This won't guarantee masking all chunks above the new "valid" region (ie: if a small shift moves the value out of chunk[1] and completely into chunk[0], this won't mask chunk[1]). I wasn't sure whether that was required as the result will get sliced down immediately anyway?
=> cxxrtl: fix sshr sign-extension.

techlibs/ice40/cells_sim.v
Sylvain "tnt" Munaut suggested I create this PR to solve a few warnings from Verilator in an ice40 simulation file when I asked about them. -Thanks!
=> Fix Verilator sim warnings: 1 BLKSEQ and 3 WIDTH

frontends/verilog/preproc.cc, frontends/verilog/verilog_parser.y, kernel/yosys.h, passes/techmap/extract_counter.cc
These patches will make yosys build on MSVC 15 2017:
- The TRANSPARENT patch is similar to the one in the [mingw_fix branch](https://github.com/YosysHQ/yosys/tree/mingw_fix)
- The `__builtin_unreachable` patch can probably be generalized to a header to a `#define YOSYS_UNREACHABLE`, but since this is the only usage of `__builtin_unreachable`, I just did the change there.
=> Get yosys building on Visual Studio

passes/cmds/splitnets.cc
This allows reliably coalescing the split wires later.
=> splitnets: propagate (*hdlname*) and disambiguate via start_offset

backends/cxxrtl/cxxrtl_backend.cc
This breaks NDEBUG builds.
Fixes #2166.
=> cxxrtl: don't compute vital values in log_assert()

passes/cmds/splitnets.cc
This PR consists of two commits.  The first replaces code like:
```
if (wire->attributes.count(ID::src))
new_wire->attributes[ID::src] = wire->attributes.at(ID::src);
```
with:
```
auto it = wire->attributes.find(ID::src);
if (it != wire->attributes.end())
new_wire->attributes.emplace(ID::src, it->second);
```
The second replaces `for` loops over the pseudo-private members `wires_` and `cells_` with loops over `wires()` and `cells()`.
Depends:
----
=> splitnets: Cleanup and efficiency improvements

passes/sat/cutpoint.cc
=> cutpoint: Improve efficiency by iterating over module ports instead of module wires

.gitattributes
This actually does confuse real people looking at language statistics in this repo...
=> Fix GitHub misidentifying *.v files as Coq

kernel/log.h
Previously this was tagged only with `YS_ATTRIBUTE(noreturn)`, but not `YS_NORETURN`, so it got lost in #2173, resulting in warnings in `frontends/ast/simplify.cc`:
```
frontends/ast/simplify.cc:267:1: warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
}
^
frontends/ast/simplify.cc:379:1: warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
}
^
```
=> Add missing [[noreturn]] to log_file_error()

kernel/rtlil.h
This PR adds a `select()` method for selecting whole modules, in addition to the existing `select()` method for selecting module members.
=> rtlil: Add `Design::select()` for selecting whole modules

kernel/hashlib.h, kernel/rtlil.h
Currently, with `dict` iterators like you'd get from e.g. `module->cells().begin()`, you can increment them: `module->cells().begin()++` but you can't offset from them: `module->cells().begin() + 5`.  This PR changes that.
Specifically, this PR adds `operator+=()` to `dict<>::iterator` and `dict<>::const_iterator` and adds `operator+()` and `operator+=()` to `ObjIterator`. 
This PR is used in PR #2172 in which it helps to reduce memory usage by obviating the need for a `dict<int, Cell *>` mapping node numbers to cells with: `RTLIL::Cell *cell = *(module->cells().begin() += i);`  Note that one can use `operator+=()` on any temporary object to improve efficiency vs. `operator+()`, which makes a copy of the iterator object.
=> hashlib, rtlil: Add `operator+()` and `operator+=()` to `dict` iterators

misc/py_wrap_generator.py
7191dd16 dropped the `YS_OVERRIDE` macro, but it was still being generated by the python bindings generator, resulting in errors like these when compiled with `ENABLE_PYOSYS=1`:
```
kernel/python_wrappers.cc:350:21: error: expected ‘;’ at end of member declaration
350 |   virtual void help() YS_OVERRIDE;
|                     ^
|                      ;
kernel/python_wrappers.cc:350:23: error: ‘YS_OVERRIDE’ does not name a type
350 |   virtual void help() YS_OVERRIDE;
|                       ^~~~~~~~~~~
```
=> pyosys: Use C++11 override keyword for bindings

libs/minisat/00_PATCH_wasm.patch, libs/minisat/System.cc
Including signal.h used to be allowed in WASI by mistake, but it's an error since SDK 11.
=> minisat: add missing include guard for WASI

kernel/rtlil.h, passes/sat/qbfsat.cc
This PR fixes multiple bugs in the `qbfsat` optimization procedure and hole specialization.
The first commit, b3040c31e2d3d9dd9b12173a75cebccda9f74e42 , updates the specialization code to use a bit-precise mapping for hole/$anyconst values and use a much more robust solution file format.  This fixes a bug preventing solutions being used to specialize other modules, e.g. one part of a miter vs. the entire miter.  Solution files now have to ways to identify each bit of the solution: the source location of the corresponding $anyconst cell, and the name of the wire for the appropriate SigBit.  Wire name matches are preferred, but we fall back to matching source locations (in a robust way).
The second commit, fe48e6a0bc8f658055625b873fc35979d6a1d758 , fixes three bugs in the optimization …
=> qbfsat: Multiple bugfixes

kernel/log.h, kernel/rtlil.h, passes/sat/qbfsat.cc
This PR makes two changes:
1. In `kernel/log.h`, in the definition for `PerformanceTimer::query()`, include the rusage for both `RUSAGE_SELF` and `RUSAGE_CHILDREN` rather than just `RUSAGE_SELF`.  This fixes a bug that causes the execution time spent on passes that launch subprocesses (`abc` and `qbfsat` at least) to be misreported upon Yosys exit.
2. In `passes/sat/qbfsat.cc`, add a `solver_time` field to the `QbfSolutionType` object, and print the solver time in each call to `call_qbf_solver()`.
This is not split into two commits/PRs because the first change is sort of necessary for the second.  At least, it would be necessary to call `getrusage()` with `RUSAGE_CHILDREN`, and this is IMO the most elegant way to do that--it kills two birds with one stone.
Depends
----
(Not a strict …
=> log and qbfsat: Also include child process usage in `PerformanceTimer::query()` and report the time for each call to the QBF-SAT solver

backends/ilang/ilang_backend.cc, frontends/aiger/aigerparse.cc, frontends/ast/simplify.cc, frontends/verific/verific.cc, kernel/log.h, kernel/macc.h, kernel/modtools.h, kernel/yosys.h, passes/opt/opt_expr.cc, passes/pmgen/pmgen.py, passes/techmap/abc9_ops.cc, passes/techmap/dfflibmap.cc, passes/tests/test_abcloop.cc
This avoids warnings in NDEBUG builds emitted when a variable is only used in log_assert, but is always defined.
I've done this to avoid a warning introduced by commit 3c4e974, and fixed up the other places where this problem came up before.
=> Use (and ignore) the expression provided to log_assert in NDEBUG builds

passes/tests/test_cell.cc
This was made an explicit error in e97e33d, "kernel: require \B_SIGNED=0 on $shl, $sshl, $shr, $sshr.".
=> test_cell: don't generate directional shifts with \B_SIGNED=1

passes/sat/expose.cc
After change https://github.com/YosysHQ/yosys/commit/696660351f657a42ec5d4785d8ab547e0b568c94 expose pass was broken due to assertion caused by reference counter (code was adding new wires while looping trough them, which is not allowed). 
This change, adds new all new wires after loop have been finished.
=> expose pass fix

passes/techmap/techmap.cc
This was introduced in 76c4ee4ea5cb6a3dc214f66237af22a1bedda010.
Fixes #2204.
=> techmap: don't drop attributes on replaced cells

frontends/verific/verific.cc
Verific updated with new API version number (yyyyMM format), now we check for latest version to be used.
This resolves issue #2144
=> Update verific API version check

passes/tests/test_cell.cc
Fixes test case for test_cell -f with ilang file.
Without this change there is assertion in get_reference  of IdString ( log_assert(p[0] == '$' || p[0] == '\\'); )
=> Use ID macro to fix assertion

passes/sat/qbfsat.cc
This PR adds `-O` flags to the `qbfsat` command.  `-O0` leaves the problem untouched (default behavior).  `-O1` and `-O2` trigger the execution of the following scripts on a copy of the selected module before `call_qbf_solver()` is called, where `write_smt2` is called and the solver is invoked.
`-O1`:
```
abc -g AND,NAND,OR,NOR,XOR,XNOR,MUX,NMUX -script +print_stats;strash;print_stats;drwsat;print_stats;fraig;print_stats;refactor,-N,10,-lz;print_stats;&get,-n;&dch,-pem;&nf;&put
techmap
opt
```
`-O2`:
```
abc -g AND,NAND,OR,NOR,XOR,XNOR,MUX,NMUX -script +print_stats;strash;print_stats;drwsat;print_stats;dch,-S,1000000,-C,100000,-p;print_stats;fraig;print_stats;refactor,-N,15,-lz;print_stats;dc2,-pbl;print_stats;drwsat;print_stats;&get,-n;&dch,-pem;&nf;&put 
techmap
opt
```
Anecdotally, I …
=> qbfsat: Add `-O[012]` options to control pre-solving simplification with ABC

frontends/verilog/verilog_parser.y, tests/various/signed.ys
This PR fixes some issues in `signed` and macro calls grammar
=> Signed and macro grammar update

manual/CHAPTER_CellLib.tex
If anyone has some idea on how to insert linebreaks into `\lstinline` and thus fit the MUX4/8/16 cells into the main table, please let me know.  Also, if anyone has some idea how to insert a `$` character inside `\lstlisting`, please let me know as well.
I hate tex.
=> Add a few more gate types to the manual.

CODEOWNERS, passes/sat/qbfsat.cc, passes/sat/qbfsat.h
This PR refactors `QbfSolveOptions` and `QbfSolutionType` and various accessory functions to a new `qbfsat.h` header, improves organization, and does general clean up.
Depends:
----
=> qbfsat: Cleanup and refactoring

passes/techmap/abc9.cc, techlibs/intel_alm/Makefile.inc, techlibs/intel_alm/common/abc9_map.v, techlibs/intel_alm/common/abc9_model.v, techlibs/intel_alm/common/abc9_unmap.v, techlibs/intel_alm/common/dff_sim.v, techlibs/intel_alm/common/mem_sim.v, techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/fsm.ys
This plugs in #1926 for `synth_intel_alm`. The benefits are [modest](https://gist.github.com/ZirconiumX/a9b2c4bc7f5be27962415d698e5495cf) but might be worth it to somebody.
Some small mapping files are used to distinguish between flops with asynchronous clear (which should be `(* abc9_box *)`) and those without (which can be passed to ABC9 as `(* abc9_flop *)`).
This lead to some cleanup; flops and LUTRAM are a bit better specified, and I also reorganised the help to put more useful options near the top.
cc @mwkmwkmwk @eddiehung
=> intel_alm: ABC9 sequential optimisations

techlibs/intel_alm/common/dff_map.v, techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/fsm.ys
Bonus: adds support for mapping flops with async reset + enable, as well as flops with sync reset (and maybe enable), though that's not properly utilized yet (pending `opt_dff` changes).
CC: @Ravenslofty (github doesn't allow me to add you as a reviewer properly).
=> synth_intel_alm: Use dfflegalize.

techlibs/intel_alm/Makefile.inc, techlibs/intel_alm/common/dsp_map.v, techlibs/intel_alm/common/dsp_sim.v, techlibs/intel_alm/common/megafunction_bb.v, techlibs/intel_alm/common/quartus_rename.v, techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/mul.ys
This adds basic support for the multiply-accumulate slices within the Cyclone V, using `mul2dsp.v` to map them. They're rather unusual in that a slice can be three 9x9 multipliers, two 18x18 multipliers or a 27x27 multiplier.  Ideally this would have a Yosys pass to attempt to pack adders and flops into the cell, but this works fine as a minimum viable product.
cc @mwkmwkmwk
=> intel_alm: DSP inference

passes/techmap/dfflegalize.cc
This ensures that, when both sync and async FFs are available and abc9
is involved, the sync FFs will be used, and will thus remain available
for sequential synthesis.
=> dfflegalize: Prefer mapping dff to sdff before adff

Makefile
I got tired of waiting for Yosys rebuilds, and of patching the Makefile to invoke `ccache`. This adds a simple option to use it in the Makefile. NFCI.
=> Add option to use ccache when building

tests/arch/intel_alm/add_sub.ys, tests/arch/intel_alm/adffs.ys, tests/arch/intel_alm/counter.ys, tests/arch/intel_alm/dffs.ys, tests/arch/intel_alm/fsm.ys, tests/arch/intel_alm/logic.ys, tests/arch/intel_alm/lutram.ys, tests/arch/intel_alm/mux.ys, tests/arch/intel_alm/quartus_ice.ys, tests/arch/intel_alm/shifter.ys, tests/arch/intel_alm/tribuf.ys
While much of the Cyclone 10 GX cells were covered by the Cyclone V tests, I figured I should duplicate the tests for C10GX just to be on the safe side.
=> intel_alm: add Cyclone 10 GX tests

techlibs/gowin/cells_sim.v, techlibs/gowin/synth_gowin.cc, tests/arch/gowin/init.ys
With the recent addition of timing data for Apicula, that can now be added to `specify` blocks and used for ABC9 synthesis and Eddie's static timing analysis.
There are a few things to note:
- Memory arrival times and I/O buffer delays haven't been reverse-engineered yet, so they're set to zero.
- The timings here are for GW1N (Littlebee) speed grade 4, making them very conservative. I could add GW2A (Arora) timings if desired, but I only know of a single GW2A devboard.
- The formatting looks a little weird in areas because I'm using Yosys-standard tabs while the surrounding code is two-space indented.
- ~~I've reduced the maximum LUT size from 8 to 6, because inter-CLU timings are presently unknown, and I'd rather not feed ABC9 fudged data.~~
Here are some numbers from the VexRiscV core …
=> Gowin ABC9 support

techlibs/efinix/cells_map.v, techlibs/efinix/synth_efinix.cc
This adds a bunch of new FF type mappings to Efinix as well:
- FFs with clock enable and async set/reset
- FFs with clock enable and sync set/reset, reset over enable
- FFs with clock enable and sync set/reset, enable over reset
- initialized FFs (all FFs are assumed to be initialized to 0)
Note that the new mappings aren't actually used by the flow yet — they will be enabled by the upcoming `opt_dff` patch.
I based all of this functionality on the EFX_FF simulation model — would be good to verify all of it is actually supported by the hardware.
=> efinix: Use dfflegalize.

passes/techmap/dfflegalize.cc, tests/techmap/dfflegalize_dlatch_const.ys
Those can be created by `opt_dff` when optimizing `$adff` with const
clock, or with D == Q.  Make dfflegalize do the opposite transform
when such dlatches would be otherwise unimplementable.
=> dfflegalize: Add special support for const-D latches.

passes/sat/clk2fflogic.cc, tests/techmap/dfflegalize_adff.ys, tests/techmap/dfflegalize_adff_init.ys, tests/techmap/dfflegalize_adlatch.ys, tests/techmap/dfflegalize_adlatch_init.ys, tests/techmap/dfflegalize_dffsr_init.ys, tests/techmap/dfflegalize_sr.ys, tests/techmap/dfflegalize_sr_init.ys
This fixes some dfflegalize equivalence checks, and breaks others — and
I strongly suspect the others are due to bad support for multiple
async inputs in `proc` (in particular, lack of proper support for
dlatchsr and sketchy circuits on dffsr control inputs).
=> clk2fflogic: Consistently treat async control signals as having negative hold time

passes/techmap/clkbufmap.cc, tests/techmap/clkbufmap.ys
- allow inserting only the input pad cell
- do not insert the usual buffer if the input pad already acts as a
buffer
=> clkbufmap: improve input pad handling.

techlibs/sf2/cells_map.v, techlibs/sf2/synth_sf2.cc
Note: I added support for FFs with clock enable while I'm at it, as well as latches — it seems to be correct based on the sim models, but please let me know if there's some issue that means we shouldn't actually be using it.
Also: is there support for initalized FFs on sf2? The current flow doesn't support them, and there is no matching parameter on the FF cell, but the code contains a commented out call to `sf2_ffinit` — or is that just a copypaste leftover that should be nuked?
=> sf2: Use dfflegalize.

backends/cxxrtl/cxxrtl_backend.cc
This bug was hidden if a header was generated.
=> cxxrtl: add missing extern "C"

passes/techmap/dfflegalize.cc
Skipping non-selected wires is unsound in an obvious way.
=> dfflegalize: Gather init values from all wires.

techlibs/xilinx/synth_xilinx.cc, tests/arch/xilinx/nosrl.ys
Of standard yosys cells, xilinx_srl only works on $_DFF_?_ and
$_DFFE_?P_, which get upgraded to $_SDFFE_?P?P_ by dfflegalize at the
point where xilinx_srl is called for non-abc9.  Fix this by running
ff_map.v first, resulting in FDRE cells, which are handled correctly.
=> xilinx: Fix srl regression.

techlibs/intel_alm/Makefile.inc, techlibs/intel_alm/common/bram_m10k.txt, techlibs/intel_alm/common/bram_m10k_map.v, techlibs/intel_alm/common/megafunction_bb.v, techlibs/intel_alm/common/mem_sim.v, techlibs/intel_alm/common/quartus_rename.v, techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/blockram.ys
So, the M10K PR broke the Quartus backend in two ways, one trivial, one substantially less so.
- the `port_[ab]_last_address` parameters to `cyclonev_ram_block` use `CFG_DBITS` instead of `CFG_ABITS`; this means Quartus can fail to infer the RAM size and then gives up. This by itself is just a single character fix and a regression test to avoid breaking it again.
- all the RAM cells have the same logical RAM name, which worked fine in my own testing until I ran it with a different codebase and it broke horribly because Quartus does *not* like RAMs of different geometries having the same logical RAM name.
The problem is that Yosys does not have a way to assign a unique identifier to a cell parameter - even just the cell name would work, I believe. I've been wondering if it would be better …
=> Revert "intel_alm: direct M10K instantiation"

techlibs/anlogic/cells_map.v, techlibs/anlogic/cells_sim.v, techlibs/anlogic/synth_anlogic.cc, tests/arch/anlogic/latches.ys
Notes:
1. This fixes the sim library to something sane (with proper clock gating and latch model). Hopefully this actually matches the hardware.  If not, the corresponding functionality needs to be disabled, because there's just no hope for it.
2. This adds support for mapping DFFs with both async reset and enable, with sync reset (and maybe enable), and proper latch support.  The new DFF types are not actually emitted yet — this will be done in the future `opt_dff` pass.
=> anlogic: Use dfflegalize.

backends/verilog/verilog_backend.cc, kernel/yosys.cc
This PR depends on and includes #2272. It only affects translation of RTLIL processes (for which there is limited support).
Due to the event-driven nature of Verilog, processes like
reg x;
always @*
x <= 1;
may never execute. This can be fixed in SystemVerilog code by using `always_comb` instead of `always @*`, but in Verilog-2001 the options are limited. This PR implements the following workaround:
reg init = 0;
reg x;
always @* begin
if (init) begin end
x <= 1;
end
=> verilog_backend: in non-SV mode, add a trigger for `always @*`

techlibs/sf2/synth_sf2.cc
This restores pre #2229 behavior.
=> sf2: Emit CLKINT even if -clkbuf not passed

backends/smt2/smt2.cc, backends/smt2/smtio.py, passes/sat/qbfsat.cc, passes/sat/qbfsat.h
`qbfsat` and `write_smt2` take `-solver-option` arguments that get emitted as `; yosys-smt2-solver-option` info statements.  In `smtio.py`, those info statements are translated into `(set-option ...)` commands.
Depends:
----
=> qbfsat, smt2, smtio: Add `-solver-option` to allow specifying SMT-LIBv2 `(set-option ...)` commands

techlibs/xilinx/arith_map.v, techlibs/xilinx/cells_sim.v, techlibs/xilinx/synth_xilinx.cc
The symbiflow-arch-defs tool chain no longer needs the EXPLICIT_CARRY within yosys itself.
=> Remove EXPLICIT_CARRY logic.

techlibs/intel_alm/common/alm_sim.v, techlibs/intel_alm/common/dff_sim.v, techlibs/intel_alm/common/dsp_sim.v, techlibs/intel_alm/common/mem_sim.v, tests/arch/intel_alm/mux.ys
These timings come from the Quartus DMF dumps, so they should more accurately reflect the timings of actual hardware, compared to the timings scavenged from the Quartus Timing Analyzer which may include other factors like fanout.
=> intel_alm: add additional ABC9 timings

passes/memory/memory_dff.cc, passes/opt/pmux2shiftx.cc, passes/opt/wreduce.cc, passes/proc/proc_dlatch.cc, passes/sat/async2sync.cc, passes/techmap/abc.cc, passes/techmap/dffinit.cc, passes/techmap/dfflegalize.cc, passes/techmap/shregmap.cc, passes/techmap/techmap.cc, passes/techmap/zinit.cc, tests/techmap/zinit.ys
This depends on #2277 and uses it to remove some redundant code in our existing passes.
Marking as draft because it shouldn't be merged before #2277.
=> Refactor multiple passes to use FfInitVals.

techlibs/intel_alm/synth_intel_alm.cc, tests/arch/intel_alm/mux.ys
This turns the weird Cyclone V MUX8 mapping into the "two MUX4s into a MUX2" mapping you'd expect.
=> intel_alm: increase abc9 -W

passes/equiv/equiv_induct.cc, tests/various/equiv_opt_undef.ys
Before this fix, equiv_induct only assumed that one of the following is
true:
- defined value of A is equal to defined value of B
- A is undefined
This lets through valuations where A is defined, B is undefined, and
the defined (meaningless) value of B happens to match the defined value
of A.  Instead, tighten this up to OR of the following:
- defined value of A is equal to defined value of B, and B is not
undefined
- A is undefined
=> equiv_induct: Fix up assumption for $equiv cells in -undef mode.

passes/opt/opt_expr.cc, tests/opt/bug2311.ys
=> opt_expr: Fix handling of $_XNOR_ cells with A = B.

passes/pmgen/xilinx_dsp.cc, passes/pmgen/xilinx_dsp.pmg, passes/pmgen/xilinx_dsp48a.pmg, passes/pmgen/xilinx_dsp_CREG.pmg, passes/pmgen/xilinx_dsp_cascade.pmg, techlibs/xilinx/synth_xilinx.cc, tests/arch/xilinx/fsm.ys
The main part is converting xilinx_dsp to recognize the new FF types
created in opt_dff instead of trying to recognize the patterns on its
own.
The fsm call has been moved upwards because the passes cannot deal with
$dffe/$sdff*, and other optimizations don't help it much anyway.
Depends on #2291
=> synth_xilinx: Use opt_dff.

passes/opt/opt.cc, passes/opt/opt_expr.cc, techlibs/greenpak4/synth_greenpak4.cc, techlibs/xilinx/synth_xilinx.cc, tests/arch/xilinx/latches.ys
Adds -noclkinv option just in case the old behavior was actually useful
to someone.
=> opt_expr: Remove -clkinv option, make it the default.

techlibs/intel_alm/common/megafunction_bb.v
This adds the `altera_pll` and `altddio_*` megafunctions to the blackbox list. This should probably be automated somehow, but that's for later.
=> intel_alm: add more megafunctions. NFC.

backends/cxxrtl/cxxrtl.h
This PR fixes the alu function in cxxrtl.h to return correct CarryOut when Bits % 32 != 0 && Invert == False, by updating carry after the last chunk is masked.
(CarryOut is currently only used by ucmp(), which always sets Invert = True, so this bug has not been triggered)
=> cxxrtl.h: Fix incorrect CarryOut in alu when Bits % 32 != 0 && Invert == False

techlibs/intel_alm/common/dsp_sim.v
This escaped code review and broke things unintentionally.
=> intel_alm: fix typo in MISTRAL_MUL27X27 cell name

frontends/ast/ast.h, frontends/ast/simplify.cc, tests/simple/generate.v
- expand_genblock defers prefixing of items within named sub-blocks
- Allow partially-qualified references to local scopes
- Handle shadowing within generate blocks
- Resolve generate scope references within tasks and functions
- Apply generate scoping to genvars
- Resolves #2214, resolves #1456
I'm very excited to finally have these issues resolved. I've done my best to adhere to the surrounding style and structure. Any feedback is greatly appreciated!
=> Fix generate scoping issues

backends/btor/btor.cc, backends/btor/test_cells.sh, backends/verilog/verilog_backend.cc, kernel/calc.cc, kernel/rtlil.cc, kernel/satgen.cc, passes/tests/test_cell.cc, techlibs/common/simlib.v, techlibs/common/techmap.v
This reflects the behaviour of `$shr`/`$shl`, which sign-extend their A operands to the size of their output, then do a logical shift (shift in 0-bits).
Fixes #2196, replaces #2217.
=> Respect \A_SIGNED for $shift

frontends/ast/simplify.cc, tests/svtypes/struct_array.sv
Support bit slicing of array elements in structs or unions e.g.
s.a[i][p:q]
Array indexing when the array stride is a power of two is now done with a shift rather than a multiply.
=> Support 2D bit arrays in structures. Optimise array indexing.

passes/techmap/techmap.cc, tests/techmap/bug2321.ys
=> techmap.CONSTMAP: Handle outputs before inputs.

passes/opt/opt_clean.cc
- wires with keep attribute now force a module to be kept
- presence of $memwr and $meminit cells no longer forces a module to be
kept
=> opt_clean: Fix module keep rules.

techlibs/common/techmap.v, tests/arch/intel_alm/mux.ys, tests/techmap/shiftx2mux.ys
Our techmap rules for $shift and $shiftx cells contained a special path
that aimed to decompose the shift LSB-first instead of MSB-first in
select cases that come up in pmux lowering.  This path was needlessly
overcomplicated and contained bugs.
Instead of doing that, just switch over the main path to iterate
LSB-first (except for the specially-handled MSB for signed shifts
and overflow handling).  This also makes the code consistent with
shl/shr/sshl/sshr cells, which are already decomposed LSB-first.
Fixes #2346.
=> techmap/shift_shiftx: Remove the "shiftx2mux" special path.

passes/proc/proc.cc
Running `proc -nomux` will with this change omit the `proc_mux` pass.
This PR was prompted by nmigen/nmigen#479
=> Add -nomux switch to proc

techlibs/intel_alm/common/dsp_map.v, techlibs/intel_alm/common/dsp_sim.v, techlibs/intel_alm/common/megafunction_bb.v, techlibs/intel_alm/common/quartus_rename.v, techlibs/intel_alm/synth_intel_alm.cc, tests/arch/common/mul.v, tests/arch/intel_alm/mul.ys
Quartus assumes unsigned multiplication by default, breaking signed multiplies, so add an input signedness parameter to the MISTRAL_MUL* cells to propagate to Quartus' <family>_mac cells.
Also added some multiplier tests to avoid #2342 again.
=> intel_alm: Add multiply signedness to cells

passes/techmap/dfflegalize.cc
When an adffe is being legalized, and is not natively supported,
prioritize unmapping to adff over converting to dffsre if dffsre is not
natively supported itself.
Fixes #2361.
=> dfflegalize: Fix decision tree for adffe.

passes/techmap/flatten.cc, passes/techmap/techmap.cc, tests/techmap/bug2183.ys
For connection `assign a = b;`, `sigmap(a)` returns `b`. This is
exactly the opposite of the desired canonicalization for driven bits.
Consider the following code:
module foo(inout a, b);
assign a = b;
endmodule
module bar(output c);
foo f(c, 1'b0);
endmodule
Before this commit, the inout ports would be swapped after flattening
(and cause a crash while attempting to drive a constant value).
This issue was introduced in 9f772eb9.
Fixes #2183.
=> flatten, techmap: don't canonicalize tpl driven bits via sigmap

Makefile
This avoids an issue where deleting or moving headers breaks the next incremental build until the outdated `*.d` files are deleted.
=> Add -MP to CXXFLAGS

techlibs/intel_alm/synth_intel_alm.cc
Before, M-bit x N-bit (with M large and N small) would be built out of MISTRAL_MUL9X9 cells, which obviously gets inefficient for large M. By loosening one of the bounds at a time, synth_intel_alm can better map these kinds of multiplies. (e.g. a 20x4 multiply was mapped out of 4 9x9 multipliers, using 1 1/3rd DSP blocks, and is now mapped out of 2 18x18 multipliers, using only 1 DSP block).
=> intel_alm: better map wide but shallow multiplies

frontends/ast/simplify.cc, tests/various/const_arg_loop.v
This fixes the issue I inadvertently introduced in #2299. Thanks to @mmicko for spotting and reporting this!
=> Fix constant args used with function ports split across declarations

frontends/ast/simplify.cc, tests/simple/generate.v
In certain contexts, using the name of the module as a scope prefix is needed to refer to a data declaration which has been shadowed in the local scope. These "name hierarchy" roots are described in Section 12.5 of IEEE 1364-2005.
I'm not sure that this is a great method of getting these wires to properly resolve. I also considered attempting to resolve the autowires as part of `genRTLIL`, but I'm not familiar with that code. Any feedback you may have is greatly appreciated!
=> Module name scope support

frontends/ast/simplify.cc
Yosys doesn't support libraries, so this provides the same behavior as %m, as some other tools have opted to do.
=> Simple support for %l format specifier

frontends/ast/simplify.cc, tests/various/const_func_block_var.v
Note that this change and the addition of sub-block declaration support in #2300 do not properly handle shadowing. Rather that complicate this PR, I will introduce some form of stack for `backup_scope` within `eval_const_function` in a later PR.
=> Allow localparams in constant functions

frontends/verilog/verilog_parser.y, tests/svtypes/multirange_array.sv
This PR fixes multirange arrays size in cases when dimension is specified as size (not as a range)
=> Rewrite multirange arrays sizes [n] as [n-1:0]

techlibs/xilinx/cells_sim.v, techlibs/xilinx/xc7_dsp_map.v, tests/arch/xilinx/dsp_abc9.ys, tests/arch/xilinx/dsp_scc.ys
Since it is a big fat block with little gains expected. Can still be enabled using a macro (in the attached testcase, DSP48E1 is ~8000 AIG nodes, ~18000 wires, 263 inputs and 154 outputs).
And make sure it works when it is enabled by fixing combinatorial loops cause problems in ABC9. Passes `techlibs/xilinx/test_dsp_models.h`.
Should fix #2190.
=>  xilinx: do not make DSP48E1 a whitebox for ABC9 by default

Makefile
The .pyh files were generated without the CXXFLAGS. This meant that code
marked by the WITH_PYTHON flag was excluded. This is fixed by adding the
flag in the rule for .pyh files.
=> Use CXXFLAGS to enable pyosys specific code before generating wrappers

Makefile
The path where python expects it's libraries seems to change from
operating system to operating system, but can be querried from the site
package.
=> Fixed python installation path

passes/hierarchy/hierarchy.cc
This solves problem on hierarchy pass where string parameters are properly handled by Verific but validation for "our" parameters does not support strings and fails here. In Verific case this dict (top_parameters) is not used anyway, so with this additional if statement we are just doing conversion if this is going to be used at all.
=> Validate parameters only when they are used

backends/verilog/verilog_backend.cc, tests/verilog/const_arst.ys, tests/verilog/const_sr.ys
While `posedge 1'b0` in a sensitivity list is technically standard-compliant verilog, it is not supported by many verilog frontends (including our own: `read_verilog` errors and `verific -sv` delivers wrong results...) To avoid these issues,  this makes `write_verilog` assign the constant value to a wire and use the wire in the sensitivity list.
=> write_verilog: emit intermediate wire for constant values in sensitivity list

tests/arch/anlogic/run-test.sh, tests/arch/ecp5/run-test.sh, tests/arch/efinix/run-test.sh, tests/arch/gowin/run-test.sh, tests/arch/ice40/run-test.sh, tests/arch/intel_alm/run-test.sh, tests/arch/xilinx/run-test.sh, tests/gen-tests-makefile.sh, tests/memories/run-test.sh, tests/opt/.gitignore, tests/opt/run-test.sh, tests/opt_share/run-test.sh, tests/sat/.gitignore, tests/sat/run-test.sh, tests/simple/run-test.sh, tests/svtypes/run-test.sh, tests/techmap/mem_simple_4x1_runtest.sh, tests/techmap/recursive_runtest.sh, tests/techmap/run-test.sh, tests/various/run-test.sh, tests/verilog/run-test.sh
- Factor out creating a Makefile from the `*.ys`/`*.v`/`*.sh` in the working directory to reduce redundancy in `run-test.sh` files
- Convert several tests to use Makefiles supporting `-j` for concurrency
Here are some crude timing benchmarks. First, on my i7-3520M (quad core) laptop:
.               | `make -j4 test` (before) | `make -j4 test` (after) | `make -j1`
--------------- | ------------------------ | ----------------------- | ----------
Wall time       | 899 s                    | 544 s                   | 1070 s
usr+sys time    | 1253 s                   | 1515 s                  | 1069 s
= concurrency   | 1.39                     | 2.78                    | 1.00
Resulting in a concurrency boost of **+100%** and a runtime change of **-39%**. I'm pretty sure the increase in total …
=> Clean up and parallelize testsuite

frontends/verilog/verilog_parser.y
=> Ignore empty parameters in Verilog module instantiations

passes/opt/opt_clean.cc, tests/opt/opt_clean_mem.ys
Previously, `$memwr` and `$meminit` cells were always preserved (along
with the memory itself).  With this change, they are instead part of the
main cell mark-and-sweep pass: a memory (and its `$meminit` and `$memwr`
cells) is only preserved iff any associated `$memrd` cell needs to be
preserved.
=> opt_clean: Better memory handling.

backends/smt2/smtbmc.py
yosys-smtbmc's Verilog testbenches do not escape any identifier names. When identifiers contain special characters, the emitted code is invalid. This PR tries to fix that.
=> smtbmc: escape identifiers in verilog testbench

techlibs/xilinx/cells_sim.v
xilinx/cells_sim.v has an issue where a couple signals (A_MULT, B_MULT) are used before they are declared.  
This causes issues trying to parse the file with certain tools (Cadence Conformal in my case).
=> xilinx/cells_sim.v: Move signal declaration to before first use

passes/memory/memory_dff.cc, tests/arch/ecp5/bug2409.ys
When the register being merged into the EN signal happens to be a $sdff,
the current code creates a new $mux for every bit, even if they happen
to be identical (as is usually the case), preventing proper grouping
further down the flow.  Fix this by adding a simple cache.
Fixes #2409.
=> memory_dff: Fix needlessly duplicating enable bits.

passes/sat/sim.cc
Fixes #2401.
The Verilog standard is very vague on which parts of the header are mandatory in a VCD file:
> The VCD file starts with header information giving the date, the version number of the simulator used for the simulation, and the timescale used. Next, the file contains definitions of the scope and type of variables being dumped, followed by the actual value changes at each simulation time increment. Only the variables that change value during a time increment are listed.
Similar present tense statements are used to describe mandatory as well as clearly optional elements. Either way, some VCD viewers require a timescale to be present to function correctly.
This adds an option to the `sim` pass to insert a timescale. It also always inserts yosys version and current local date and …
=> sim -vcd: add date, version, and option for timescale

tests/arch/xilinx/attributes_test.ys
This test pretty much passes by accident — the `prep` command runs
memory_collect without memory_dff first, which prevents merging read
register into the memory, and thus blocks block RAM inference for a
reason completely unrelated to the attribute.
The attribute setting didn't actually work because it was set on the
containing module instead of the actual memory.
=> xilinx: Fix attributes_test.ys

passes/techmap/abc.cc
This patch adds support for defining the ABC location at runtime instead of at compile time. This is helpful in build systems like bazel which do not have stable locations for binaries or directories during the compilation phase.
This change should be backwards compatible with the existing behavior.
=> Adds support for defining abc location at runtime

backends/cxxrtl/cxxrtl_backend.cc
=> cxxrtl: don't assert on wires with multiple drivers

backends/cxxrtl/cxxrtl_backend.cc
=> cxxrtl: don't assert on non-constant $meminit inputs

backends/cxxrtl/cxxrtl_backend.cc
In most cases, a CXXRTL simulation would use a top module, either because this module serves as an entry point to the CXXRTL C API, or because the outputs of a top module are unbuffered, improving performance. Taking this into account, the CXXRTL backend now runs `hierarchy -auto-top` if there is no top module. For the few cases where this behavior is unwanted, it now accepts a `-nohierarchy` option.
Fixes #2373.
=> cxxrtl: run `hierarchy -auto-top` if no top module is present

Makefile
Under certain circumstances¹, the CXXFLAGS assigned by the main `Makefile` can leak down to `abc/Makefile`.  This causes them to be passed along to `abc/depends.sh` when depending C++ code (such as `abc/src/sat/glucose/AbcGlucose.cpp`).  With `gcc` this seems work cause no problems, but when the compiler is `clang` this causes an issue because `clang` is unhappy with getting both `-MM` (which is from `abc/depends.sh`) and `-MD` (which is from `Makefile`) at the same time, and outputs preprocessed C code instead of dependency rules.
By unexporting CXXFLAGS, the leak is plugged and the build completes normally with `clang`.
¹ This happens when the environment variable CXXFLAGS is set to something in the environment where the top level `make` command is run.  The fact that CXXFLAGS was set …
=> Prevent CXXFLAGS from leaking to abc Makefile

kernel/yosys.cc, kernel/yosys.h, passes/techmap/abc.cc, passes/techmap/abc9_exe.cc
To be able to use and check pyosys builds without installing yosys itself (for CI) we need to override determined data share location and location from ABC, since those are calculated from python location and not from yosys itslef.
Even when installed as is, ABC executable was not able to be determined correctly. 
This is replacement for #2430
=> Expose abc and data paths as globals for pyosys 

backends/blif/blif.cc
For reasons that are unclear to me, this was being used to store every
result of `cstr` before returning them. The vector was never accessed otherwise,
resulting in a huge unnecessary memory sink when emitting to BLIF.
On local tests, this saves an extraordinary amount of memory (and subsequently time) during BLIF emission:
an 87MB BLIF output previously required 1GB of resident memory, and now requires virtually none.
=> backends/blif: Remove unused vector of strings

backends/firrtl/firrtl.cc
Previous blackbox components were just emitted with their interface ports, but their generic parameters were never emitted and it was therefore impossible to customize them.
This commit adds support for blackbox generic parameters, though support is only provided for INTEGER and STRING parameters. Other types of parameters would result in undefined behavior here.
This PR allows one to start from synthesized verilog circuits that contain blackbox definitions and convert them to firrtl. A small example is provided below:
Input synthesized verilog:
```verilog
module test (
out_0,
out_1,
in_0,
in_1);
output 	out_0;
output  out_1;
input 	in_0;
input 	in_1;
wire gnd;
wire vcc;
assign gnd = 1'b0;
assign vcc = 1'b1;
wire FIRST_combout;
wire SECOND_combout;
fourteennm_lcell_comb FIRST ( …
```
=> Add firrtl backend support for generic parameters in blackbox components

passes/cmds/check.cc
This is helpful for e.g. nMigen and CXXRTL, both of which support processes natively without requiring them to be expanded immediately after the frontend runs.
=> check: add support for processes

passes/sat/sim.cc
I've added a call to `rewrite_filename` on a local copy of the argument value passed with `-vcd` to the `sim` pass. I kept having an issue with my build scripts where it wouldn't generate the vcd file, but worked fine if I did it by hand. Turns out it was quotes on the filename string, which `rewrite_filename` tidies up, among other things.
=> Add rewrite_filename for sim -vcd argument.

Makefile
[`sccache`](https://github.com/mozilla/sccache) is a `ccache`-like tool that supports distributed compilation and more languages. While it can be used as a `ccache`-replacement, I've found a few edge cases where symlinking `sccache` to `ccache` can choke. This includes on Windows where the symlink just plain doesn't work, and incompatibility with mixed C/C++ projects on all systems (`yosys` is unaffected by the latter).
Considering edge cases, along with using a completely separate cache and its extra distributed compilation capabilities, I think it's reasonable to add an `ENABLE_SCCACHE` option disabled by default. Like `ENABLE_EDITLINE` and `ENABLE_READLINE`, this option is mutually-exclusive with `ENABLE_CCACHE`; the former takes priority.
Two caveats:
* I can't speak for `ccache`, but …
=> Makefile: Add disabled-by-default ENABLE_SCCACHE config option.

tests/various/dynamic_part_select.ys, tests/various/dynamic_part_select/forloop_select.v, tests/various/dynamic_part_select/forloop_select_gate.v, tests/various/dynamic_part_select/latch_002.v, tests/various/dynamic_part_select/latch_002_gate.v, tests/various/dynamic_part_select/latch_002_gate_good.v, tests/various/dynamic_part_select/latch_1990.v, tests/various/dynamic_part_select/latch_1990_gate.v, tests/various/dynamic_part_select/multiple_blocking.v, tests/various/dynamic_part_select/multiple_blocking_gate.v, tests/various/dynamic_part_select/nonblocking.v, tests/various/dynamic_part_select/nonblocking_gate.v, tests/various/dynamic_part_select/original.v, tests/various/dynamic_part_select/original_gate.v, tests/various/dynamic_part_select/reset_test.v, tests/various/dynamic_part_select/reset_test_gate.v, tests/various/dynamic_part_select/reversed.v, tests/various/dynamic_part_select/reversed_gate.v
Enhancing tests as per  #2112 request. This PR is mainly #2079 with test for latch detection mechanism.
This test is already enabled and passing
```
make -j$(nproc) test | tee log && grep -e "dynamic" log && grep -e "make test" log 
```
`Running dynamic_part_select.ys..
Passed "make test".
`
=> Adding latch tests for shift&mask AST dynamic part-select enhancements

backends/verilog/verilog_backend.cc
Yosys currently emits assigns with a concatenated expression on the LHS in form like:
assign {a,b} = {c,d,e};
this change generate instead (note that size is taken into consideration):
assign a = {c, d};
assign b = e;
This fixes issue #1286
=> Generate only simple assignments in verilog backend

frontends/rtlil/rtlil_lexer.l
No one knows where they came from and they never did anything useful.
=> rtlil: remove dotted identifiers

frontends/verilog/preproc.cc, frontends/verilog/verilog_frontend.cc
This patch fixes a bug where the verilog macro SYNTHESIS is always defined when using read_verilog even when the -formal option is used.
The bug occured as the define_map_t constructor in frontends/verilog/preproc.cc set one of the two macros, dependent on the formal_mode global variable. In VerilogFrontend::execute() in frontends/verilog/verilog_frontend.cc the object defines_map is created before the options to read_verilog have been parsed. This means that formal_mode has not been set correctly yet, so SYNTHESIS is always defined.
This is fixed by defining the verilog macros in execute(), after the read_verilog options have been parsed, instead of in the define_map_t constructor.
=> Fix SYNTHESIS always being defined in Verilog frontend

Makefile, passes/sat/freduce.cc
I co-maintain yosys in the Fedora distribution, and the following two patches help get the latest upstream to build correctly in that environment:
- an additional `#include` is needed to build `passes/sat/freduce.cc` with the upcoming `gcc-11` toolchain
- we need to pass `-DABCEXTERNAL` into `kernel/yosys.cc` to have the latter actually do something productive in that situation
Thanks for considering!
=> Fixes for building Fedora distro RPMs of yosys

frontends/ast/ast.cc
Fixes  #2451 where otherwise equal submodules were showing different types.
=> Return correct modname when found in cache.

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc, backends/cxxrtl/cxxrtl_capi.cc, backends/cxxrtl/cxxrtl_capi.h
Although it is always possible to destroy and recreate the design to simulate a power-on reset, this has two drawbacks:
* Black boxes are also destroyed and recreated, which causes them to reacquire their resources, which might be costly and/or erase important state.
* Pointers into the design are invalidated and have to be acquired again, which is costly and might be very inconvenient if they are captured elsewhere (especially through the C API).
=> cxxrtl: provide a way to perform unobtrusive power-on reset

backends/cxxrtl/cxxrtl_backend.cc
E.g. in:
module test;
wire clk = 0;
reg data;
always @(posedge clk)
data <= 0;
endmodule
=> cxxrtl: fix crashes caused by a floating or constant clock input

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc
RTL contract violations and C++ contract violations are different: the former depend on the netlist and will never violate memory safety whereas the latter may. When loading a CXXRTL simulation into another process, RTL contract violations should generally not crash it, while C++ contract violations should.
=> cxxrtl: use CXXRTL_ASSERT for RTL contract violations instead of assert

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc
Before this commit, a cell's input was always assigned like:
p_cell.p_input = (value...);
If `p_input` is buffered (e.g. if the design is built at -O0), this is not correct. (In practice, this breaks clocking.) Unfortunately, the incorrect design was compiled without diagnostics because `wire<>` was move-assignable and also implicitly constructible from `value<>`.
After this commit, cell inputs are no longer incorrectly assumed to always be unbuffered, and wires are not assignable from values.
=> cxxrtl: don't overwrite buffered inputs

techlibs/xilinx/cells_xtra.py, techlibs/xilinx/cells_xtra.v
These are necessary primitives for proper DDR support on Virtex 2 and
Spartan 3.
=> xilinx: Add FDDRCPE and FDDRRSE blackbox cells.

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_backend.cc, backends/cxxrtl/cxxrtl_capi.cc, backends/cxxrtl/cxxrtl_capi.h, backends/cxxrtl/cxxrtl_vcd.h, kernel/rtlil.h
This PR significantly improves almost every aspect of CXXRTL's performance. Most importantly, it eliminates the tradeoff between debug information coverage (which directly translates to available VCD traces and so on), runtime throughput, and compilation latency.
That's right: CXXRTL no longer has the `-Og` (optimize for debug coverage) option because it is now able to provide **100% debug coverage for every net in the source HDL at all times regardless of optimization settings**.
That's not all though. This PR also improves compilation latency, runtime throughput at 100% coverage, VCD writing performance, and VCD file size. On the benchmark I'm using (1M cycles of Minerva with UART blackbox), this changeset makes CXXRTL set up for full coverage **compile ~30% faster, run ~40% faster …
=> CXXRTL: implement zero-cost full coverage debug information through the magic✨ of outlining🪄🎀🧹

frontends/ast/genrtlil.cc, passes/hierarchy/hierarchy.cc, passes/techmap/flatten.cc, tests/various/port_sign_extend.v, tests/various/port_sign_extend.ys
- Signed cell outputs are sign extended when bound to larger wires
- Signed connections are sign extended when bound to larger cell inputs
- Sign extension is performed in hierarchy and flatten phases
- genrtlil indirects signed constants through signed wires
- Other phases producing RTLIL may need to be updated to preserve signedness information
- Resolves #1418
- Resolves #2265
This change may need further revisions, but I am eager for feedback!
=> Sign extend port connections where necessary

backends/cxxrtl/cxxrtl_backend.cc, kernel/yosys.h
See the commit messages for details. On Minerva SoC SRAM, this improves runtime by **20-25%** across the board, and compile time by **30-50%** only on clang (gcc is not affected). There are also other correctness and usability improvements; in particular the new netlist layout code is specifically written to take the greatest advantage of outlining.
=> cxxrtl: completely rewrite netlist layout code

passes/opt/opt_lut.cc
RTLIL::Module::remove(Cell* cell) calls `delete cell`.
Any subsequent accesses of `cell` then causes undefined behavior.
=> Fix use-after-free in LUT opt pass

frontends/ast/simplify.cc, tests/various/const_arg_loop.v
The changes in #2476 ensured that function inputs like `input x;` retained their single-bit size when instantiated with a constant argument and turned into a localparam. That change did not handle the possibility for an input to be redeclared later on with an explicit width, such as `integer x;`.
=> Fix constants bound to redeclared function args

kernel/yosys.h
As suggested by @whitequark in #2505, this is a minor fix for allowing Yosys to be built on MINGW64.
=> kernel/yosys.h: undef CONST on WIN32

Makefile, kernel/yosys.h
Close #2505
Close #2507
This PR is based on #2507.
CONFIG option `msys2` is renamed to `msys2-32`, for consistency. Furthermore, `PREFIX := $(MINGW_PREFIX)` is added to both `msys2-32` and `msys2-64`.
=> Update MSYS2 build system

Makefile
When merging and squashing the suggestion in #2514, I overlooked that `GHDL_DIR` was changed to `GHDL_PREFIX`, so I should have changed that below.
=> makefile: fix GHDL vars, replace GHDL_DIR with GHDL_PREFIX

passes/opt/opt_share.cc, tests/opt/opt_share_bug2538.ys
These need to be the same length as actual Y, not visible part of Y.
Fixes #2538.
=> opt_share: Fix X and CO signal width for shifted $alu in opt_share.

tests/various/.gitignore
This artifact is automatically generated by the builtin clang on macOS when -g is used.
=> Add plugin.so.dSYM to .gitignore

passes/techmap/abc.cc
The goto statement seems to be missing.
Specifying "-g all" for abc produces an error: `ERROR: Command syntax error: Unsupported gate type: all`
**If this is not a bug then just close this PR**.
=> Fixed missing goto statement in passes/techmap/abc.cc

frontends/verilog/preproc.cc, tests/simple/macro_arg_spaces.sv
=> verilog: allow spaces in macro arguments

backends/cxxrtl/cxxrtl_backend.cc
Currently in cxxrtl due to an earlier change that fixed issues with constant signals driving clock inputs of clocked cells, when cells are clocked by a `SigSpec` that doesn't pass `is_wire()` most of them will be ignored. 
This causes an issue because slices of another signal (i.e. a single `SigBit`) don't return `true` for `is_wire()`. While it's arguable that there should be some `is_wire()` like function defined that passes for slices (at least for single bits), that's another issue.
In order to fix #2542, I implemented a subset of `is_wire()` internally to the cxxrtl backend, so that it can handle cells with clocks that are not directly backed by a wire. This doesn't fully convert all uses of `is_wire()` for clocks. Some of the code can map them onto their unique driving signal at the …
=> CXXRTL: Fix sliced bits as clock inputs

backends/cxxrtl/cxxrtl.h, backends/cxxrtl/cxxrtl_vcd.h
This breaks build on MSVC but not GCC/Clang.
=> cxxrtl: do not use `->template` for non-dependent names

techlibs/xilinx/cells_sim.v, techlibs/xilinx/xilinx_dffopt.cc, tests/arch/xilinx/mux.ys, tests/arch/xilinx/xilinx_dffopt.ys
The presence of `IS_*_INVERTED` on `FD*` cells follows Vivado, which apparently has been decided by a dice roll.  Just assume false if the
parameter doesn't exist.
Fixes #2559.
=> xilinx_dffopt: Don't crash on missing IS_*_INVERTED.

passes/cmds/scc.cc, passes/techmap/abc9.cc
Part of the fix for #2530: enhance SCC to detect logic loops through combinational specify rules.
=> scc: Add -specify option to find loops in boxes

frontends/verilog/preproc.cc, tests/simple/macro_arg_surrounding_spaces.v
Fixes a regression in #2550. Thanks @Xiretza for catching this!
=> verilog: strip leading and trailing spaces in macro args

passes/techmap/flatten.cc
This error does not always indicate any mismatch in directionality or any problem with the cell at all. For example, in this case, which was extracted from a large codebase where a developer had mistakenly left the second `assign` after some modifications:
```verilog
module m1(...);
output wire x;
assign x = 1'b0;
endmodule
module m2(...);
wire y;
assign y = 1'b0; // this was left here by mistake
m1 c(y);
endmodule
```
The new message is still not a perfect solution (which would be to detect multiple drivers properly, something I wanted to see in Yosys for years now) but it is at least not flat out wrong.
=> flatten: clarify confusing error message

frontends/ast/ast.cc
The first child of AST_CASE is the case expression, it's subsequent
childrean that are AST_COND* and can be used to discriminate the type of
the case.
=> ast: fix dump_vlog display of casex/casez

tests/simple/const_branch_finish.v, tests/simple/generate.v
In my understanding, unconditional_block in generate is not allowed.
Instead of it, `if (1) begin` can be used to introduce a new name scope.
=> Fix begin/end in generate

frontends/verilog/verilog_parser.y, tests/verilog/block_labels.ys
This PR adds a check for begin/end labels mismatches in genblocks - this is similar to what is currently done for behavrioral_stmt blocks
=> verilog_parser: add label check to gen_block

frontends/ast/genrtlil.cc, tests/various/port_sign_extend.v, tests/various/port_sign_extend.ys
This fixes binding signed memory reads, signed unary expressions, and signed complex SigSpecs to ports. This also sets `is_signed` for wires generated from signed params when -pwires is used. Though not necessary for any of the current usages, `is_signed` is now appropriately set when the `extendWidth` helper is used.
Fixes #2575
=> genrtlil: fix signed port connection codegen failures

frontends/verilog/verilog_parser.y, tests/verilog/atom_type_signedness.ys
This PR adds missing ``is_signed`` attribute in ``type_atom``.
Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>
=> verilog_parser: fix missing is_signed attribute in type_atom

frontends/verilog/verilog_parser.y, tests/simple/genblk_port_shadow.v, tests/verilog/genblk_port_decl.ys
This is a somewhat obscure edge case I encountered while working on test cases for earlier changes. Declarations in generate blocks should not be checked against the list of ports. This change also adds a check forbidding declarations within generate blocks being tagged as inputs or outputs.
=> verlog: allow shadowing module ports within generate blocks

frontends/ast/ast.h, frontends/ast/simplify.cc, tests/simple/const_fold_func.v, tests/simple/const_func_shadow.v
Elaboration now attempts constant evaluation of any function call with only constant arguments, regardless of the context or contents of the function. This removes the concept of "recommended constant evaluation" which previously applied to functions with `for` loops or which were (sometimes erroneously) identified as recursive. Any function call in a constant context (e.g., `localparam`) or which contains a constant-only procedural construct (`while` or `repeat`) in its body will fail as before if constant evaluation does not succeed.
Fixes #2562
=> verilog: refactored constant function evaluation

frontends/verific/verificsva.cc
This PR handles default disable clauses for live/fair properties that caused those properties to fail.
Consider this example of a storage device that becomes `1'b1` forever, fulfilling the property semantics:
``` systemverilog
var logic tmp;
always_ff @(posedge clk) begin
if (!rstn) tmp <= 1'b0;
else       tmp <= 1'b1;
end
assign a = tmp;
ap0: assert property (@(posedge clk) disable iff (!rstn)
s_eventually nexttime a);
```
Without this PR, `SBY` in `live` mode fails to prove the property. By looking into the model, the RTL semantics are wrong due missing `clocking.disable_sig`.
```
SBY 16:36:56 [liveness_test] engine_0: Status returned by engine: FAIL
```
Since proving liveness in Yosys, without aiger or super prove is not possible, I am not adding any kind of test to this PR but will …
=> Accept disable case for SVA liveness properties.

frontends/verilog/preproc.cc, tests/verilog/macro_unapplied.ys, tests/verilog/macro_unapplied_newline.ys
This would previously complain about an undefined internal macro if the unapplied macro had not already been used. If it had, it would incorrectly use the arguments from the previous invocation.
@rswarbrick
=> verilog: error on macro invocations with missing argument lists

frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, tests/various/fib_tern.v, tests/various/fib_tern.ys
This adds a mechanism for marking certain portions of elaboration as occurring within unevaluated ternary branches. To enable elaboration of the overall ternary, this also adds width detection for these unelaborated function calls.
While this implementation is meant to be low-impact for prior inputs, I do think the introduction of `unevaluated_tern_branch` is not necessarily ideal. I'm eager for any feedback or alternative suggestions.
This fixes #247 (the original example uses a ternary in this way).
=> verilog: support recursive functions using ternary expressions

passes/sat/assertpmux.cc, tests/sat/bug2595.ys
=> assertpmux: Fix crash on unused $pmux output.

frontends/json/jsonparse.cc
When scc breaks logic loops with `$__ABC9_SCC_BREAKER` module it adds the following entry to resulting json:
```"$__ABC9_SCC_BREAKER": {
"attributes": {
"blackbox": "00000000000000000000000000000001",
"cells_not_processed": "00000000000000000000000000000001",
"dynports": "00000000000000000000000000000001",
"src": "/(...)/share/yosys/abc9_model.v:9.1-11.10"
},  
"cells": {}, 
"netnames": {
"I": {
"attributes": {
"src": "/(...)/share/yosys/abc9_model.v:9.47-9.48"
},  
"bits": [
2,  
3   
],  
"hide_name": 0,
"offset": -1, 
"upto": 1
}, 
```
reading the json back to yosys results in:
```
ERROR: Unexpected character in JSON file: '-'
```
in the `"offset": -1,` line
This PR fixes that
=> frontend: json: parse negative values

kernel/rtlil.h
Useful for PYOSYS because Python can't easily check wire against NULL.
=> Adds is_wire to SigBit and SigChunk

frontends/ast/ast.h, frontends/ast/simplify.cc, tests/various/const_arg_loop.sv, tests/various/const_arg_loop.ys, tests/various/const_func.sv, tests/various/const_func.ys, tests/verilog/func_arg_mismatch_1.ys, tests/verilog/func_arg_mismatch_2.ys, tests/verilog/func_arg_mismatch_3.ys, tests/verilog/func_arg_mismatch_4.ys
- Simplify synthetic localparams for normal calls to update their width
- This step was inadvertently removed alongside `added_mod_children`
- Support redeclaration of constant function arguments
- `eval_const_function` never correctly handled this, but the issue
was not exposed in the existing tests until the recent change to
always attempt constant function evaluation when all-const args
are used
- Check asserts in const_arg_loop and const_func tests
- Add coverage for width mismatch error cases
Fixes #2592
=> verilog: fix sizing of constant args for tasks/functions

kernel/log.cc
When an expected logger error pattern is unmatched, the logger raises another (hidden) error. Because of the previous ordering of actions, `logv_error_with_prefix()` would inadvertently invoke `yosys_atexit()` twice, causing a double-free.
This is related to, but should not necessarily close, #2606.
=> Fix double-free on unmatched logger error pattern

frontends/verilog/verilog_parser.y, tests/verilog/delay_mintypmax.ys, tests/verilog/delay_risefall.ys
- Per LRM A.2.2.3
- Not for synthesis, just for Verilog acceptance by front-end
Resolves YosysHQ/yosys#2565
=> Extend "delay" expressions to handle pair and triplet, i.e. rise, fall and turn-off

frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y
Basically:
- priority converts to (* full_case *)
- unique0 converts to (* parallel_case *)
- unique converts to (* parallel_case, full_case *)
Fixes #2596.
=> Fix handling of unique/unique0/priority cases in the frontend.

frontends/aiger/aigerparse.cc
Calling log10() on zero causes a non-sensical value to be calculated. On some
compile options, I've observed yosys crashing with an illegal
instruction (SIGILL).
To make it safe, fix the calculation to do a range check; wrap it a
decimal_digits() function, and use it where the previous ceil(log10(n)) call
was used. As a side, it also improves readability.
Signed-off-by: Henner Zeller <h.zeller@acm.org>
=> Fix digit-formatting calculation for small numbers.

frontends/ast/simplify.cc, tests/various/countbits.sv, tests/various/countbits.ys
I have implemented those functions so I can write
`assert ($onehot0(foo[2:0]));`
instead of
`assert (foo[0] + foo[1] + foo[2] <= 1);`
`$countbits(foo, 'z)` doesn't really work and `$countbits(foo, 'x)` counts both `'x` and `'z`. I guess this is because `'1&'z` results in `'x` and not `'z`. I hope this is okay.
I think that some test cases would be good, but before I take a look at that, I wanted to check if you are interested to merge this and if my code is acceptable or if I messed something up. I'm not sure about `children.size()`. It was written as `GetSize(children)` at other places I think. Is there a preference?
=> Add $countbits, $countones, $isunknown, $onehot and $onehot0 functions

frontends/verilog/verilog_lexer.l, frontends/verilog/verilog_parser.y, tests/verilog/int_types.sv, tests/verilog/int_types.ys, tests/verilog/param_int_types.sv, tests/verilog/param_int_types.ys
- Standard data declarations can now use any integer type
- Parameters and localparams can now use any integer type
- Function returns types can now use any integer type
- Fix `parameter logic`, `localparam reg`, etc. to be 1 bit (previously 32 bits)
- Added longint type (64 bits)
- Unified parser source for integer type widths
=> sv: extended support for integer types

Brewfile
If enable python-api, do need boost-python3.
=> Add boost-python3

frontends/verilog/verilog_frontend.cc
Right now, `read_verilog` either defines SYNTHESIS or FORMAL, but there is no way to not define both SYNTHESIS and FORMAL.
With the existence of CXXRTL, Yosys can also be used for pure simulation, in which case both SYNTHESIS and FORMAL defines are sometimes undesirable.
=> Add -nosynthesis flag for read_verilog command

tests/simple_abc9/.gitignore, tests/simple_abc9/run-test.sh
New test cases on one branch may be automatically copied from simple/ to simple_abc9/, causing failures when switching to another branch. This updates the simple_abc9 script to set aside extraneous tests in a non-destructive way.
=> Set aside extraneous tests in simple_abc9 test suite

frontends/verilog/preproc.cc, tests/simple/ifdef_1.v, tests/simple/ifdef_2.v, tests/verilog/include_self.v, tests/verilog/include_self.ys, tests/verilog/unmatched_else.ys, tests/verilog/unmatched_elsif.ys, tests/verilog/unmatched_endif.ys
- track depth so we know whether to consider higher-level elsifs
- error on unmatched endif/elsif/else
@rswarbrick
=> verilog: fix handling of nested ifdef directives

frontends/verilog/verilog_parser.y, tests/verilog/port_int_types.sv, tests/verilog/port_int_types.ys
Declaring the ports as standard module items already worked as expected. This adds a missing usage of `checkRange()` so that headers such as `module m(output integer x);` now work correctly.
=> verilog: fix sizing of ports with int types in module headers

backends/cxxrtl/cxxrtl_backend.cc
This crash (assertion failure) was unintentionally introduced in 65083e9520e3f39bef3e89a56ecc08f60c1286e6.
=> cxxrtl: don't crash on empty designs

backends/cxxrtl/cxxrtl_backend.cc
Otherwise, this combination (with #2634)
```
Debug wire types:
\terminal.cpu.i_tv80_core.RegAddrA: OUTLINE
\terminal.cpu.i_tv80_core.i_reg.AddrA: ALIAS = \terminal.cpu.i_tv80_core.RegAddrA
```
resulted in `\terminal.cpu.i_tv80_core.i_reg.AddrA` being referenced but not defined.
=> cxxrtl: follow aliases to outlines when emitting $memrd.ADDR

kernel/rtlil.cc
I'm increasingly finding `log_assert` to be unhelpful, especially when users are presented with them due to bugs. I just hit this one and thought it would be significantly more helpful to describe the error condition without having to spend time looking at the surrounding context to work out the problem.
=> Replace assert in addModule with more useful error message

passes/proc/proc_clean.cc
=> proc_clean: Fix empty case removal conditions.

frontends/ast/ast.cc, frontends/ast/simplify.cc, tests/verilog/unbased_unsized.sv, tests/verilog/unbased_unsized.ys
- Fix explicit size cast of unbased unsized literals
- Fix unbased unsized literal bound directly to port
- Output `is_unsized` flag in `dumpAst`
Related to #2622
=> sv: fix some edge cases for unbased unsized literals

frontends/ast/genrtlil.cc, tests/verilog/absurd_width.ys, tests/verilog/absurd_width_const.ys
Designs with unreasonably wide expressions would previously get stuck allocating memory forever.
Fixes #2290
=> verilog: impose limit on maximum expression width

frontends/ast/ast.cc, frontends/verilog/verilog_parser.y, tests/verilog/localparam_no_default_1.ys, tests/verilog/localparam_no_default_2.ys, tests/verilog/param_no_default.sv, tests/verilog/param_no_default.ys, tests/verilog/param_no_default_not_svmode.ys, tests/verilog/param_no_default_unbound_1.ys, tests/verilog/param_no_default_unbound_2.ys, tests/verilog/param_no_default_unbound_3.ys, tests/verilog/param_no_default_unbound_4.ys, tests/verilog/param_no_default_unbound_5.ys
- Modules with a parameter without a default value will be automatically deferred until the hierarchy pass
- Allows for parameters without defaults as module items, rather than just int the `parameter_port_list`, despite being forbidden in the LRM
- Check for parameters without defaults that haven't been overriden
- Add location info to parameter/localparam declarations
=> sv: support for parameters without default values

passes/proc/proc_dff.cc, tests/proc/bug2619.ys
=> proc_dff: Fix emitted FF when a register is not assigned in async reset branch

backends/rtlil/rtlil_backend.cc, frontends/ast/ast.cc, frontends/ast/ast.h, frontends/ast/genrtlil.cc, frontends/ast/simplify.cc, frontends/rtlil/rtlil_lexer.l, frontends/rtlil/rtlil_parser.y, kernel/rtlil.cc, kernel/rtlil.h, manual/CHAPTER_Overview.tex, manual/CHAPTER_Verilog.tex, passes/cmds/bugpoint.cc, passes/cmds/check.cc, passes/cmds/show.cc, passes/memory/memory.cc, passes/memory/memory_dff.cc, passes/memory/memory_nordff.cc, passes/proc/Makefile.inc, passes/proc/proc.cc, passes/proc/proc_arst.cc, passes/proc/proc_clean.cc, passes/proc/proc_dlatch.cc, passes/proc/proc_init.cc, passes/proc/proc_memwr.cc, techlibs/common/prep.cc, tests/opt/opt_clean_mem.ys, tests/tools/autotest.sh
As discussed on the 2021-02-15 meeting, this is the proper fix for #2473 and related issues — no more `memory_dff` converting async ports to sync ports, instead the memory writes are first emitted by the frontend as part of processes, and then converted to `$memwr` cells by `proc_memwr`, which has enough information to know the proper clock (or lack thereof).
This patch also adds more granular priority tracking in the frontend — the priority masks store information on which write ports need to have priority over which other ones, and which ones are unordered.  Currently this information is lost in `proc_memwr` (and converted to an arbitrary total order), but it will be properly hooked up and used in the upcoming memory inference changes.
TODO:
- the `tests/bram` test is now *broken* — it …
=> Add memory writes to processes.

frontends/ast/ast.cc, tests/verilog/global_parameter.ys
It was previously possible to override global parameters on a per-instance basis. This could be dangerous when using positional parameter bindings, hiding oversupplied parameters.
I'm not certain that this is forbidden by the LRM. Some tools allow it, others don't. I believe the current behavior is accidental. Let's use this PR to discuss which behavior we prefer.
=> verilog: disallow overriding global parameters

frontends/ast/ast.cc, frontends/ast/simplify.cc, tests/verilog/parameters_across_files.ys
This defers the simplification of globals so that globals in one file may depend on globals in other files. Adds a simplify() call downstream because globals are appended at the end.
Fixes #2571
=> sv: allow globals in one file to depend on globals in another

kernel/rtlil.cc, tests/opt/bug2623.ys
Among other problems, this also fixes equality comparisons between
SigSpec by enforcing a canonical form.
Also fix another minor issue with possible non-canonical SigSpec.
Fixes #2623.
=> rtlil: Disallow 0-width chunks in SigSpec.

passes/proc/proc_arst.cc, tests/proc/bug2656.ys
The already-existing special case for conditionals on clock has been
remade as follows:
- now triggered for the last remaining edge trigger after all others
have been converted to async reset, not just when there is only one
sync rule in the first place
- does not require all contained assignments to be constant, as opposed
to a reset conditional — merely const-folds the condition
In addition, the code has been refactored a bit; as a bonus, the
priority order of async resets found is now preserved in resulting sync
rule ordering (though this is not yet respected by proc_dff).
Fixes #2656.
=> proc_arst: Add special-casing of clock signal in conditionals.

backends/json/json.cc, frontends/json/jsonparse.cc
Previously, memories were silently discarded by the JSON backend, making
round-tripping modules with them crash.
Since there are already some users using JSON to implement custom
external passes that use memories (and infer width/size from memory
ports), let's fix this by just making JSON backend and frontend support
memories as first-class objects.
Processes are still not supported, and will now cause a hard error.
Fixes #1908.
=> json: Add support for memories.

kernel/rtlil.h
This assert caught the regression caused by #2646, so it deserves a promotion into a human-readable error.
=> Replace assert in get_reference with more useful error message

frontends/ast/simplify.cc, tests/simple/verilog_primitives.v
From IEEE1364-2005 section 7.3, buf and not gates:
> These two logic gates shall have one input and one or more outputs. The last terminal in the terminal list shall connect to the input of the logic gate, and the other terminals shall connect to the outputs of the logic gate.
yosys does not follow this and instead interprets the first argument as the output, the second as the input and ignores the rest.
There exists a test in `tests/asicworld/code_verilog_tutorial_n_out_primitive.v` that should probably catch this; not sure what's up with that.
=> verilog: fix buf/not primitives with multiple outputs

frontends/verilog/verilog_frontend.cc, tests/verilog/typedef_across_files.ys, tests/verilog/typedef_legacy_conflict.ys
This breaks the ability to use a global typename as a standard identifier in a subsequent input file. This is otherwise backwards compatible, including for sources which previously included conflicting typedefs in each input file.
I'm not sure why this logic is in `add_package_types`, but I figure I'd just fix it in place rather than making a larger change.
Fixes #2440
=> sv: carry over global typedefs from previous files

manual/command-reference-manual.tex, passes/cmds/bugpoint.cc
This has been updated to the more general `-runner` option proposed below. *nix systems appear to have the `timeout` command available in general. I confirmed that with the recent zero-width chunk fix reverted, the following script
```
read_rtlil <<EOF
module \top
wire output 1 \a
wire width 0 $dummy
cell \abc \abc
connect \a \a
connect \b $dummy
end
wire width 1 \foo
wire width 2 \bar
end
EOF
bugpoint -yosys "./yosys" -command opt_clean -runner "timeout 5"
```
correctly runs and produces
```
autoidx 5
module \top
wire width 0 $delete_wire$2
wire $delete_wire$4
cell \abc \abc
connect \a $delete_wire$4
connect \b $delete_wire$2
end
end
```
Fixes #2629
=> bugpoint: add runner option

techlibs/achronix/synth_achronix.cc, techlibs/anlogic/synth_anlogic.cc, techlibs/coolrunner2/synth_coolrunner2.cc, techlibs/easic/synth_easic.cc, techlibs/ecp5/synth_ecp5.cc, techlibs/efinix/synth_efinix.cc, techlibs/gowin/synth_gowin.cc, techlibs/greenpak4/synth_greenpak4.cc, techlibs/ice40/synth_ice40.cc, techlibs/intel/synth_intel.cc, techlibs/intel_alm/synth_intel_alm.cc, techlibs/machxo2/synth_machxo2.cc, techlibs/nexus/synth_nexus.cc, techlibs/sf2/synth_sf2.cc, techlibs/xilinx/synth_xilinx.cc, tests/arch/ecp5/mux.ys
This prevents issues like processes in whiteboxes triggering an error in the JSON backend. Fixes #2667
=> Blackbox all whiteboxes after synthesis

frontends/ast/ast.cc, tests/arch/xilinx/abc9_dff.ys
Calling log_signal is problematic for several reasons:
- with recent changes, empty string is serialized as { }, which violates
the "no spaces in IdString" rule
- the type (plain / real / signed / string) is dropped, wrongly conflating
functionally different values and potentially introducing a subtle
elaboration bug
Instead, use a custom simple serialization scheme.
=> ast: Use better parameter serialization for paramod names.

Makefile, techlibs/quicklogic/Makefile.inc, techlibs/quicklogic/cells_sim.v, techlibs/quicklogic/lut_sim.v, techlibs/quicklogic/pp3_cells_map.v, techlibs/quicklogic/pp3_cells_sim.v, techlibs/quicklogic/pp3_ffs_map.v, techlibs/quicklogic/pp3_latches_map.v, techlibs/quicklogic/pp3_lut_map.v, techlibs/quicklogic/synth_quicklogic.cc, tests/arch/quicklogic/add_sub.ys, tests/arch/quicklogic/adffs.ys, tests/arch/quicklogic/counter.ys, tests/arch/quicklogic/dffs.ys, tests/arch/quicklogic/fsm.ys, tests/arch/quicklogic/latches.ys, tests/arch/quicklogic/logic.ys, tests/arch/quicklogic/mux.ys, tests/arch/quicklogic/run-test.sh, tests/arch/quicklogic/tribuf.ys
This is essentially #1816 but slimmed down to the bare essentials of PolarPro 3 support - no BRAM, no ABC9, no multiplier inference, and with Yosys-standard tests.
=> quicklogic: PolarPro 3 support

kernel/modtools.h
`cell_inputs` and `cell_outputs` retain cell pointers as their keys across invocations of `setup()`, which may however be invalidated in the meantime (as happens in e.g. [`passes/opt/share.cc:1432`](https://github.com/YosysHQ/yosys/blob/e178d0367a315213560514f827072595adfd4b4a/passes/opt/share.cc#L1432)). A later rehash of the dicts (caused e.g. by inserting in `ModWalker::add_wire()`) will cause them to be dereferenced.
I have to admit I don't fully understand the internals of the share pass, is it supposed to share across modules? The test suite didn't complain locally, so if this fix actually breaks it, it should probably be tested for explicitly.
Note: I found this issue by running the test suite under ASan, is it worth adding that as a CI pass?
=> modtools: fix use-after-free of cell pointers in ModWalker

frontends/verilog/verilog_parser.y, tests/svtypes/typedef_scopes.sv
yosys only searches the current type scope for definitions of struct and union member type, and hits an assertion failure if the typedef is in a parent scope instead. While I'm not 100% certain, I'm pretty sure this behaviour is wrong.
Tests may be failing because of newly-uncovered UB fixed in #2688, so that should be merged first.
=> verilog: check entire user type stack for type definition

backends/rtlil/rtlil_backend.cc
=> rtlil: Fix process memwr roundtrip.

passes/cmds/bugpoint.cc
Bugpoint's current documentation does specify that the result of a run is stored as the current design,
however it's easy to skim over what that means in practice. 
Add a documentation comment to explain specifically that an after bugpoint `write_xyz` pass is required to save
the reduced design.
=> Clarify bugpoint documentation regarding output

kernel/rtlil.cc, kernel/rtlil.h
This allows future changes to have const access to a `Design` and still meaningfully inspect portions of the hierarchy. I simply duplicated the non-const definitions of these three functions. Some prefer to define either the const or non-const accessor in terms of the other using `const_cast`. I have no preference either way.
=> rtlil: add const accessors for modules, wires, and cells

.github/workflows/test.yml
- Only install needed dependencies rather than using Brewfile
- Remove brew update (recent enough formulae already baked in)
- Saves ~16 minutes in macOS CI
=> gha: trim macOS dependencies

passes/techmap/abc9_ops.cc, tests/various/abc9.ys
`abc9` will uniquify parameterised whiteboxes (i.e. create a unique module with parameter values constant-propagated) but not blackboxes. This is an oversight resolved here.
Whiteboxes would be typically preferred so that `abc9` can optimise the box away or short it if necessary. It won't do that for a blackbox, however, it will still sweep that box away if it has a dangling/redundant output (making this not a completely bulletproof equivalent to `(* keep *)` which hides it from `abc9` entirely -- but also means it will not be considered for timing-aware mapping).
CC: @Ravenslofty
=> abc9: uniquify blackboxes like whiteboxes

techlibs/sf2/cells_sim.v
When searching through the techlibs to reuse implementations I stumbled upon this file and got a bit confused by modules called `ADD` when they are in fact AND gates. Looking at the referenced pdf confirms that the modules should be called AND2, etc.
I grep'ed through the repo and luckily nothing else is referencing or using the wrong names, so the PR should be pretty much safe. (famous last words)
Kind regards,
Riesi
=> sf2: fix name of AND modules

techlibs/ice40/cells_sim.v, tests/arch/run-test.sh
Lattice Reference Document containing (some of) the default assignments:
http://www.latticesemi.com/~/media/LatticeSemi/Documents/TechnicalBriefs/SBTICETechnologyLibrary201608.pdf
closes #2390
=> Add input default assignments to iCE40 cell library

techlibs/xilinx/synth_xilinx.cc
Yosys ignores the name of the BLIF file passed in with the `synth_xilinx` command.
For example, 
```bash
yosys -p "synth_xilinx -top toplevel -blif counter.blif" counter.v
```
Yosys ignores the given BLIF name (`counter.blif`), and instead prints the BLIF output to the command line.
This fix now causes `counter.blif` to be written to.
=> Fix use of blif name in synth_xilinx command

Makefile, frontends/blif/blifparse.cc, passes/cmds/connect.cc, tests/blif/bug2729.ys, tests/blif/run-test.sh
=> blif: Use library cells' start_offset and upto for wideports.

techlibs/ecp5/cells_bb.v
While investigating extending ECP5 DSP support in nextpnr I found these parameters from the MULT18X18D and ALU54B were missing from the techlib. They are all documented in Lattice TN1267 1.1 and are all accepted by Diamond for synthesis. They were mostly removed from the original techlib PR in b65932edc4a00860cafc04f962f2a08dd782b075, except `OPCODEOP1_1_CLK` which seems to have been missing from the start.
I've tested a few designs in Diamond which set these parameters and all the ones I checked appear to have some effect on the bitstream, though often interact with parameters elsewhere in the DSP (e.g. `MULT_BYPASS` on MULT18X18D errors unless the connected ALU54B has the AMUX bits in its opcode set to 0b10) so might have been missed in initial fuzzing.
Even without full nextpnr …
=> Add missing parameters for MULT18X18D and ALU54B to ECP5 techlib.

frontends/ast/ast.cc, frontends/ast/ast.h
The current_module global is needed so that genRTLIL has somewhere to
put cells and wires that it generates as it makes sense of expressions
that it sees. However, that doesn't actually need to be an AstModule:
the Module base class is enough.
This patch should cause no functional change, but the point is that
it's now possible to call genRTLIL with a module that isn't an
AstModule as "current_module". This will be needed for 'bind' support.
(Note: This patch is part of the larger queue at #2752. The idea is to split things out to avoid having a giant PR to review all at once)
=> Change the type of current_module to Module

backends/btor/btor.cc, backends/smt2/smt2.cc, backends/verilog/verilog_backend.cc, kernel/rtlil.cc, kernel/rtlil.h, passes/cmds/delete.cc, passes/sat/sim.cc, passes/techmap/abc9_ops.cc, passes/techmap/flatten.cc, passes/techmap/techmap.cc
There will soon be more (versioned) memory cells, so handle passes that
only care if a cell is memory-related by a simple helper call instead of
a hardcoded list.
=> kernel/rtlil: Extract some helpers for checking memory cell types.
