YosysHQ/yosys

backends/verilog/verilog_backend.cc

This adds support for $mem cells to the verilog backend, but I do have some open questions:
1. The $mem cell parameter "\\WR_EN" seems to have width number of bits for every writer and all of the bits for each port appear to be the same, at least for my simple trials. For example here is the parameter for 2 write ports : *connect \WR_EN { 8'11111111 \wr_en \wr_en \wr_en \wr_en \wr_en \wr_en \wr_en \wr_en }*. Will these enable bits ever be different? 
I've added some code to check if they are different and fail if they are, but I'm not sure if this is necessary.
2. The "RD_TRANSPARENT" parameter appears to be unused. Is it ever used and what does it indicate?
Suggestion : Does it make sense to add an init member to RTLIL::Memory?

Added support for $mem cells in the verilog backend.

---

backends/verilog/verilog_backend.cc

This takes care of the segfault and "make test" now passes.

Fixed bug in $mem cell verilog code generation.

---

backends/json/json.cc
manual/command-reference-manual.tex

"speciefied" -> "specified"
"unkown" -> "unknown"

user-facing spelling fixes

---

Makefile
kernel/yosys.cc

Use it as the last resort in the share/ directory location search.

Embed DATDIR make variable value into yosys binary.

---

README
manual/manual.tex

Add instructions for building manual on Ubuntu.
Also fix a few minor spelling errors.

Add instructions for building manual on Ubuntu

---

passes/cmds/select.cc

For resource limited designs such as FPGA it can be useful to specify limit of specific resources available on board. So user can check if he should change RTL as early as mapping done.

Added 'assert-limit' option for 'select' command

---

techlibs/greenpak4/cells_sim.v

greenpak4: add GP_COUNT{8,14}_ADV cells

---

README.md

My main reason for this is that I want to link to some sections from the wiki.
There are some other minor changes I want to make, so don't merge this yet. Right now I just want to know if there is any reason *not* to have a proper markdown readme. So please tell me what you think.

Markdownify README

---

README.md

I was planning to add more commits to the previous pull request and did not expect it to be merged as fast (e.g. it broke rendering of things enclosed in ``<angle brackets>``), so here is another pull request that takes it one step further.

Markdownify README (№2)

---

.gitignore
CodingReadme
Makefile
tests/unit/Makefile
tests/unit/kernel/logTest.cc
tests/unit/kernel/rtlilTest.cc

In this Pull Request we concentrate to add the basic structure for unit tests. We tried to make it without insert a lot of extra code in the main Makefile. Finally, we tried to make the processes of adding new unit test easy.

Unit test structure

---

manual/clean.sh

BSD sed does not support -r parameter.
This is a quick and dirty solution. Better suggestions welcome.

Use gsed vs sed on Darwin.

---

passes/opt/opt_expr.cc

Add check for whether the high bit in the constant expression is greater
than the width of the variable, and optimizes that to a constant 1 or
0.

Fix issue #306, "Bug in opt -full"

---

backends/firrtl/firrtl.cc
backends/firrtl/test.sh
backends/firrtl/test.v

Chisel -> Firrtl -> Verilog -> Firrtl -> Verilog is successful for a
simple rocket-chip design.

More progress on Firrtl backend.

---

Makefile
backends/edif/edif.cc

*to force renames on wide ports
*to choose array delimiters
*to choose up or downwards indices

add options for edif flavors

---

techlibs/coolrunner2/Makefile.inc
techlibs/coolrunner2/cells_latch.v
techlibs/coolrunner2/cells_sim.v
techlibs/coolrunner2/coolrunner2_sop.cpp
techlibs/coolrunner2/synth_coolrunner2.cpp
techlibs/coolrunner2/xc2_dff.lib

The PAR functionality isn't done yet, but I wanted to create this initial PR to see if I did it right.

Initial Coolrunner-II support

---

passes/techmap/extract_counter.cc
techlibs/greenpak4/cells_blackbox.v
techlibs/greenpak4/cells_map.v

This PR implements some (but not all) of the features requested by #388. I'm submitting it now because several important bug fixes leading to incorrect synthesis are included; the remaining features will follow later.

Various improvements and bug fixes to extract_counter

---

frontends/verilog/preproc.cc

It's a bit clumsy, but illustrates the problem.

Adding support for string macros and macros with arguments after include

---

frontends/verilog/preproc.cc

According to `frontend/verilog/preproc.cc`, during include-file processing, if the following conditions [hold](https://github.com/cliffordwolf/yosys/blob/660473a485019ab07f0af19d3c84aff11be41d1c/frontends/verilog/preproc.cc#L369-L378):
* A valid file as specified by the `include` directive was not found.
* The include file was given with a relative path.
* The currently-open file was given to yosys with a path.
`yosys` should attempt to find the include file relative to the directory of the currently-open file, and then attempt to find the include file from paths given on the command line.
Currently, yosys does not consider Windows-style paths in determining whether the currently-open file was given to yosys with a path. Additionally, the check for a relative path for an include file …

Accommodate Windows-style paths during include-file processing.

---

.travis.yml
.travis/build-and-test.sh
.travis/common.sh
.travis/deploy-after-success.sh
.travis/setup.sh

This fixes a number of issues;
* Fixes #442 - Make travis build pass
* Fixes #441 - Fix git version information on travis build
* Fixes #440 - Make travis cache the iverilog build

Reworking the Travis CI for Yosys.

---

passes/hierarchy/hierarchy.cc

This also makes it easier to add new file extensions support.
Signed-off-by: Sergi Granell <xerpi.g.12@gmail.com>

passes/hierarchy: Reduce code duplication in expand_module

---

tests/tools/autotest.sh

Prepared a pull request for #559  after all...

Fixed typo (sikp -> skip)

---

backends/protobuf/Makefile.inc

Leftover from when I had the proto in share/.

Fix protobuf build

---

frontends/ast/genrtlil.cc
frontends/ast/simplify.cc
frontends/verilog/verilog_frontend.cc

where we have a source-level location available.

Use log_file_warning(), log_file_error() functions

---

frontends/verilog/verilog_parser.y

This PR improves the specify/endspecify handling and solves the issues in issue #604 
After making this change, I made sure `make test` is still passing.
Feel free to squash all 3 commits.

More specify/endspecify fixes

---

frontends/ast/genrtlil.cc

Just print a warning with file and line number.

Fix for issue 594.

---

.github/issue_template.md

Fix misspelling in issue_template.md

---

kernel/celltypes.h

Fix IdString M in setup_stdcells()

---

Makefile
tests/svinterfaces/run-test.sh
tests/svinterfaces/runone.sh
tests/svinterfaces/svinterface1.sv
tests/svinterfaces/svinterface1_ref.v
tests/svinterfaces/svinterface1_tb.v

Just a simple test so there is something at least which checks and fails if wrong.

Basic test for checking correct synthesis of SystemVerilog interfaces

---

techlibs/ecp5/Makefile.inc
techlibs/ecp5/cells_sim.v
techlibs/ecp5/latches_map.v
techlibs/ecp5/synth_ecp5.cc

Add support for inferred latches :nauseated_face: and fix the IO sim model when T is not connected

Small ECP5 improvements

---

passes/techmap/dfflibmap.cc
passes/techmap/libparse.cc

Liberty file: error when it contains pin references to non-existing pins

---

backends/smt2/smtio.py

This should fix #692 and cleanup #691.
Please test @hotwolf @arjenroodselaar @mmicko.

improve rlimit handling in smtio.py

---

techlibs/ecp5/cells_bb.v
techlibs/ecp5/cells_sim.v

Signed-off-by: David Shah <dave@ds0.me>

ecp5: Adding some blackbox cells

---

.travis.yml
.travis/setup.sh

I can't easily debug this (it's 2018 and I'm still not allowed to run OSX on non-Apple hardware), so I'll just try changing some random things until it works ¯\\\_(ツ)\_/¯.

Fix Travis on OSX

---

passes/techmap/abc.cc

This likely doesn't work for all cases, nor am I sure if it is the correct approach, just trying to work out what is possible.

Proof-of-concept: preserve naming through ABC using dress

---

frontends/verilog/verilog_parser.y

Instead of having a single attr_list object, we create a new one at the beginning of each option list.
If there is an existing one, then we put it on top of a stack and at the end of the opt list, we check the
stack, pop one if there is one.

verilog_parser: Properly handle recursion when processing attributes

---

CHANGELOG

I haven't realized before that it exists...

Update CHANGELOG to mention my improvements

---

passes/opt/opt_lut.cc

A few fixes for opt_lut that would sometimes result in missing optimization opportunities.

opt_lut: elimination fixes

---

passes/opt/Makefile.inc
passes/techmap/Makefile.inc
passes/techmap/flowmap.cc

PR provided for early review. I plan to add some low hanging fruit here so we can merge a version that's more than just depth-optimal.

flowmap: new techmap pass

---

passes/cmds/rename.cc

Extend the rename pass to optionally rename cells based on the wires they drive.
This pass is especially useful to give names to flipflop cells.
Here is the renaming scheme I've decided to implement:
| Cell is: | Replace name with | Example |
|-----------|---------------------------|-------------|
| Driving a whole wire | `wirename$celltype` | `counter$dff` |
| Driving chunk of a wire | `wirename[slice]$celltype` | `rgb_out[7:0]$add` |
| Driving chunks of multiple wires | `wire1$wire2$wire3$celltype` | `divde_by_2$divide_by_4$divide_by_8$dff` |
The renaming aborts if one or more of the wires the cell is driving has a private name.

Rename cells based on the wires they drive.

---

passes/techmap/flowmap.cc
passes/tests/flowmap/flow.v
passes/tests/flowmap/flowp.v

FlowMap should use a DFS, not just any search, to construct a max-volume cut. A few other cleanups went in as well.

 flowmap: construct a max-volume max-flow min-cut, not just any one

---

passes/techmap/flowmap.cc
passes/tests/flowmap/pack1.v
passes/tests/flowmap/pack1p.v
passes/tests/flowmap/pack2.v
passes/tests/flowmap/pack2p.v
passes/tests/flowmap/pack3.v
passes/tests/flowmap/pack3p.v

This is not very useful on its own, but it enables further work on repacking, and carries important cleanups. (Although, there is minor benefit in using `opt_lut` after `-optarea 0`.)

flowmap: implement depth relaxation

---

passes/fsm/fsm_opt.cc

Thanks to @sxpert for reporting this one

fsm_opt: Fix runtime error for FSMs without a reset state

---

backends/verilog/verilog_backend.cc

This commit fixes two related issues:
* For asynchronous ports, clock is no longer added to domain list.
(This would lead to absurd constructs like `always @(posedge 0)`.
* The logic to distinguish synchronous and asynchronous ports is
changed to correctly use or avoid clock in all cases.
Before this commit, the following RTLIL snippet (after memory_collect)
cell $memrd $2
parameter \MEMID "\\mem"
parameter \ABITS 2
parameter \WIDTH 4
parameter \CLK_ENABLE 0
parameter \CLK_POLARITY 1
parameter \TRANSPARENT 1
connect \CLK 1'0
connect \EN 1'1
connect \ADDR \mem_r_addr
connect \DATA \mem_r_data
end
would lead to invalid Verilog:
reg [1:0] _0_;
always @(posedge 1'h0) begin
_0_ <= mem_r_addr;
end
assign mem_r_data = mem[_0_];
Note that there are two potential pitfalls remaining after this …

write_verilog: correctly emit asynchronous transparent ports

---

tests/tools/autotest.sh

This reverts commit 281f2aadcab01465f83a3f3a697eec42503e9f8b.

Revert "Add -B option to autotest.sh to append to backend_opts"

---

passes/opt/opt_rmdff.cc

Fix opt_rmdff handling of $_DFFSR_???_ and $_DLATCHSR_???_, fixes #816

---

kernel/driver.cc

Rename "yosys -D" to "yosys -U", add "yosys -D" with expected behavior

---

passes/opt/wreduce.cc

Fix multiple issues in wreduce FF handling, fixes #835

---

.travis.yml

Disable macOS builds in Travis

---

frontends/ast/simplify.cc

Fix $readmem[hb] for mem2reg memories, fixes #785

---

README.md
frontends/ast/ast.h
frontends/ast/simplify.cc
passes/hierarchy/hierarchy.cc

Only run derive on blackbox modules when ports have dynamic size

---

frontends/ast/genrtlil.cc

Fix error for wire decl in always block, fixes 763

---

frontends/verific/README
frontends/verific/verific.cc

Tests at YosysHQ/yosys-tests#14

Add -chparam option to verific command

---

frontends/verilog/verilog_lexer.l
frontends/verilog/verilog_parser.y

Fix handling of cases that look like sva labels, fixes #862

---

backends/verilog/verilog_backend.cc
kernel/log.cc
kernel/register.cc
kernel/rtlil.cc
kernel/rtlil.h

Improve determinism of IdString DB for similar scripts

---

frontends/ast/simplify.cc
techlibs/ice40/cells_sim.v

This fixes the issues raised in #867 and slightly improves some related pain points.

Various mem2reg-related improvements in handling of memories

---

passes/opt/opt_expr.cc

Improve handling of and-with-1 and or-with-0 in opt_expr, fixes #327

---

backends/smt2/smtbmc.py
kernel/hashlib.h
passes/sat/Makefile.inc
passes/sat/mutate.cc

This also fixes a small bug in yosys-smtbmc (bacca5753775bfabed955a9772a5d86d85007c58) and adds an utility function to hashlib (76c9c350e7d0dfc11b609d98bdcd1ea0d845cb06).

Add "mutate" pass

---

techlibs/xilinx/synth_xilinx.cc

Add Xilinx negedge FFs to synth_xilinx dffinit call, fixes #873

---

frontends/ast/simplify.cc

Fix mem2reg handling of memories with upto data ports

---

frontends/verilog/Makefile.inc

Build Verilog parser with -DYYMAXDEPTH=100000

---

passes/proc/proc_rmdead.cc
tests/various/muxcover.ys

Recognise default entry in case even if all cases covered (fix for #931)

---

techlibs/intel/cyclonev/cells_sim.v

Fixing issues in CycloneV cell sim

---

techlibs/xilinx/cells_sim.v
techlibs/xilinx/cells_xtra.sh
techlibs/xilinx/cells_xtra.v

- Adds some parameters to IBUF, OBUF primitive
- Add more general clock primitives, the BUFGCTRL and BUFHCE primitives
- Add LUT6_2 primitive

Add additional cells sim models for core 7-series primitives.

---

passes/proc/proc_mux.cc
passes/proc/proc_rmdead.cc

Improve proc full_case detection and handling

---

backends/verilog/verilog_backend.cc

Add support for zero-width signals to Verilog back-end

---

kernel/cellaigs.cc
kernel/celltypes.h

Fixes #955 and the underlying issue in #954

Fixes for OAI4 cell implementation

---

passes/opt/opt_clean.cc
passes/opt/opt_expr.cc
techlibs/ecp5/synth_ecp5.cc

Drive dangling wires with init attr with their init value

---

frontends/ast/genrtlil.cc
frontends/ast/simplify.cc
tests/simple/mem2reg.v

Fix width detection of memory access with bit slice

---

.clang-format
techlibs/intel/synth_intel.cc

Add clang format, and use on intel_synth (v2)

---

passes/opt/opt_muxtree.cc

Fix handling of glob_abort_cnt in opt_muxtree

---

passes/cmds/bugpoint.cc

bugpoint: check for -script option

---

kernel/rtlil.cc
kernel/rtlil.h
passes/opt/opt_clean.cc

Also adds rewrite_spec2() API and improves the way we remove wires.

Another rounds of opt_clean improvements

---

passes/opt/wreduce.cc
techlibs/common/prep.cc

Add "wreduce -keepdc"

---

libs/subcircuit/subcircuit.cc

You don't need to compute this each time; instead, just perform a lookup table search.

Optimize numberOfPermutations

---

backends/blif/blif.cc

Fix handling of offset and upto module ports in write_blif

---

Makefile

Cleaned my OS X Makefile and put needed if(Darwin..) #1029 fix is also included in this.
This PR fixes also  -DWITH_PYTHON mentioned in #1027

OS X related Makefile fixes.

---

frontends/ast/ast.cc
frontends/ast/ast.h
frontends/ast/genrtlil.cc
frontends/verilog/const2ast.cc
frontends/verilog/verilog_lexer.l

Includes work from @sumit0190 and @AaronKel

Added support for unsized constants, fixes #1022

---

Makefile

Precondition on work for issue #613
To get afl-gcc available:
=================
git clone https://github.com/mirrorer/afl/
cd afl
make
sudo make install

afl-fuzzer compile config

---

Makefile

Fix for ability to use settings from conf when building pyosys, fixes issue produced by #1030

Moved pyosys block in Makefile

---

passes/pmgen/peepopt_shiftmul.pmg
tests/simple/peepopt.v

 Do not use shiftmul peepopt pattern when mul result is truncated

---

Makefile

Aded one more load of .conf to support change of prefix

---

misc/py_wrap_generator.py

Remove yosys_banner() from python wrapper init

---

passes/opt/opt_clean.cc

Suppress driver-driver conflict warning for unknown cell types

---

passes/sat/sim.cc

Error out if no top module given before 'sim'

---

passes/opt/opt_rmdff.cc

Fix typo in opt_rmdff causing register to be incorrectly removed

---

frontends/verilog/verilog_parser.y
tests/simple/run-test.sh
tests/tools/autotest.sh
tests/various/implicit_ports.sv
tests/various/implicit_ports.ys

This code was split out and adapted from #560.

SystemVerilog support for implicit named port connections

---

passes/techmap/muxcover.cc

Add optional cost arguments to `muxcover`: `-mux4[=cost]`, `-mux8[=cost]`, `-mux16[=cost]`

Allow muxcover costs to be changed

---

backends/aiger/aiger.cc
backends/ilang/ilang_backend.cc
backends/json/json.cc
backends/protobuf/protobuf.cc
kernel/yosys.cc

Untested on non-Linux platforms...
Signed-off-by: Ben Widawsky <ben@bwidawsk.net>

Support ~ in filename parsing

---

README.md
frontends/verilog/verilog_parser.y
passes/hierarchy/hierarchy.cc
tests/simple/defvalue.sv
tests/tools/autotest.sh

Fixes https://github.com/YosysHQ/SymbiYosys/issues/51
Also adds support for default values for input ports (cc @ZipCPU ).

Improve handling of initial/default values

---

CHANGELOG
frontends/verilog/const2ast.cc
kernel/rtlil.cc
tests/various/signext.ys

Sign extend unsized 'bx and 'bz values

---

frontends/verilog/verilog_parser.y
tests/simple/generate.v

Make genvar a signed type

---

techlibs/ecp5/arith_map.v

ecp5: Improve mapping of $alu when BI is used

---

passes/techmap/muxcover.cc
tests/various/muxcover.ys

Add support for partial matches to muxcover

---

techlibs/xilinx/cells_sim.v
techlibs/xilinx/cells_xtra.sh
techlibs/xilinx/cells_xtra.v
techlibs/xilinx/drams.txt
techlibs/xilinx/drams_map.v

Adapted from RAM64X1D template

Add RAM32X1D support

---

passes/memory/memory_dff.cc
tests/memories/issue00710.v
tests/memories/run-test.sh

memory_dff: walk through more than one mux for computing read enable

---

passes/techmap/muxcover.cc
tests/various/muxcover.ys

Fix handling of partial covers in muxcover

---

CHANGELOG
passes/opt/pmux2shiftx.cc
tests/various/pmux2shiftx.v
tests/various/pmux2shiftx.ys

Add "pmux2shiftx -norange"

---

frontends/verilog/verilog_parser.y
tests/various/specify.v
tests/various/specify.ys

Improve specify dummy parser

---

techlibs/xilinx/cells_map.v

Testing using updated https://github.com/YosysHQ/yosys-tests/pull/44

Cleanup synth_xilinx SRL inference, make more consistent

---

backends/ilang/ilang_backend.cc
backends/verilog/verilog_backend.cc
frontends/ast/genrtlil.cc
frontends/ilang/ilang_parser.y
kernel/rtlil.h
passes/proc/proc_mux.cc

This is a follow-up PR to #1162 that depends on it and adds inessential (but handy) additional support for attributes on case rules.

More support for case rule attributes

---

backends/aiger/xaiger.cc

Courtesy of @whitequark: https://github.com/YosysHQ/yosys/commit/38d8806bd74b9bb448c7488ec571e197fe2f96d6#r34238578

Rename __builtin_bswap32 -> bswap32

---

CHANGELOG
passes/opt/wreduce.cc
techlibs/common/synth.cc

Revert "Add "synth -keepdc" option"

---

passes/techmap/techmap.cc

Increment _TECHMAP_BITS_CONNMAP_ by one since counting from zero

---

techlibs/ice40/synth_ice40.cc

As far as I know this switch either does nothing or makes the design faster. People like @smunaut have been using it extensively and it appears robust.

synth_ice40: switch -relut to be always on

---

passes/memory/memory_bram.cc

Error out if enable > dbits in memory_bram file

---

passes/techmap/extract_fa.cc

Fix for regression introduced in https://github.com/YosysHQ/yosys/commit/9b91d815b55343630c3c2d4a5a7d2a593c344f07

Fix check logic in extract_fa

---

passes/techmap/abc.cc
techlibs/ice40/abc_hx.box
techlibs/ice40/abc_lp.box
techlibs/ice40/abc_u.box
techlibs/ice40/arith_map.v
techlibs/ice40/cells_map.v
techlibs/ice40/cells_sim.v
techlibs/ice40/ice40_opt.cc
techlibs/ice40/synth_ice40.cc

Otherwise ABC warns about internal fanouts and may not preserve carry chains correctly

abc9/ice40: encapsulate SB_CARRY+SB_LUT4 into one box

---

techlibs/common/cmp2lut.v
tests/lut/check_map_lut6.ys
tests/lut/map_cmp.v
tests/lut/run-test.sh

cmp2lut transformation to support >32 bit LUT masks

---

examples/intel/MAX10/run_max10
techlibs/intel/synth_intel.cc

I figured it'd be best to get these into the code base, as they're non-functional changes that are easy to review.

Assorted synth_intel cleanups from @bwidawsk

---

techlibs/ice40/cells_sim.v
techlibs/ice40/tests/test_dsp_model.sh
techlibs/ice40/tests/test_dsp_model.v

Credit to @daveshah1 for doing the hard stuff.
Fixes #1211

ice40: Fix SB_MAC16 sim model for signed modes

---

kernel/rtlil.h
kernel/yosys.h

this makes it possible to use std algorithms on them

made ObjectIterator comply with Iterator Interface

---

CHANGELOG
backends/blif/blif.cc
backends/btor/btor.cc
backends/simplec/simplec.cc
backends/smt2/smt2.cc
backends/smv/smv.cc
backends/verilog/verilog_backend.cc
kernel/cellaigs.cc
kernel/celltypes.h
kernel/consteval.h
kernel/cost.h
kernel/rtlil.cc
kernel/rtlil.h
kernel/satgen.h
manual/CHAPTER_CellLib.tex
passes/cmds/stat.cc
passes/techmap/abc.cc
passes/techmap/extract_fa.cc
techlibs/common/simcells.v

This improves quality and stability of mockup cmos synthesis with `abc -g cmos; stat -tech cmos`.

Add $_NMUX_, add "abc -g cmos", add proper cmos cell costs

---

CHANGELOG
kernel/register.cc
tests/various/.gitignore
tests/various/write_gzip.ys

gzip compression is automatically enabled when an output file has the extension ".gz".
cc @mithro

Add support for writing gzip-compressed files

---

frontends/ast/simplify.cc

Fix handling of functions/tasks without top-level begin-end block

---

techlibs/anlogic/arith_map.v

Fix calculation of CO and highest bit.

anlogic : Fix alu mapping

---

passes/techmap/abc.cc

And also add `abc -g all`. Fixes #1273.

Disable NMUX, AOI3, OAI3, AOI4, OAI4 in ABC default gate lib

---

.travis/build-and-test.sh

Let's try out if this is sufficient

Propagate parameters for Travis build

---

backends/aiger/xaiger.cc
frontends/aiger/aigerparse.cc
frontends/verific/verific.cc
kernel/log.h
passes/opt/opt_expr.cc
passes/techmap/abc9.cc

This is an alternative to #1255. With this NDEBUG compiles without warnings for me.

Fix various NDEBUG compiler warnings

---

README.md
backends/aiger/xaiger.cc
passes/techmap/abc9.cc
techlibs/ecp5/cells_sim.v
techlibs/ice40/cells_sim.v
techlibs/xilinx/cells_sim.v

Refactor abc9 to use port attributes, not module attributes

---

passes/pmgen/Makefile.inc

Fix test_pmgen deps

---

CHANGELOG
passes/pmgen/README.md
passes/pmgen/pmgen.py
passes/pmgen/test_pmgen.cc
passes/pmgen/test_pmgen.pmg

I think this can now do everything we have discussed. @eddiehung

Add pmgen slices and choices

---

techlibs/xilinx/cells_sim.v

xilinx: Add SRLC16E primitive.

---

frontends/ast/simplify.cc

Fixes https://github.com/YosysHQ/SymbiYosys/issues/59
No idea when this broke.. Unfortunately we can't really add a test case for this to yosys afaict because there's not built-in lifeness checker in yosys and we are trying to keep the dependencies for `make test` at an absolute minimum. But we probably should run all SymbiYosys examples in yosys tests I think. @eddiehung @SergeyDegtyar

Properly construct $live and $fair cells from "if (...) assume/assert (s_eventually ...)"

---

frontends/ast/simplify.cc

Fix handling of range selects on loop variables

---

passes/techmap/techmap.cc

Add techmap_autopurge attribute

---

passes/techmap/abc9.cc
passes/techmap/techmap.cc
tests/techmap/autopurge.ys

(* techmap_autopurge *) fixes when ports aren't consistently-sized

---

tests/ice40/adffs.v
tests/ice40/adffs.ys

The same changes as in https://github.com/YosysHQ/yosys/pull/1352/commits/c597c2f2ae10111b2dc28e9738ea336d8ad22b31, but for ICE40 architecture.

ICE40 tests. adffs test update (equiv_opt -multiclock).

---

CHANGELOG
techlibs/xilinx/cells_sim.v
techlibs/xilinx/cells_xtra.py
techlibs/xilinx/xc6s_cells_xtra.v
techlibs/xilinx/xc6s_ff_map.v
techlibs/xilinx/xc6v_cells_xtra.v
techlibs/xilinx/xc7_cells_xtra.v
techlibs/xilinx/xc7_ff_map.v
techlibs/xilinx/xcu_cells_xtra.v
tests/xilinx/latches.v
tests/xilinx/latches.ys

synth_xilinx: Support latches, remove used-up FF init values.

---

misc/py_wrap_generator.py

Generate Python wrappers for inline constructors

---

passes/techmap/aigmap.cc
tests/techmap/aigmap.ys

```
log("    -select\n");
log("        Overwrite replaced cells in the current selection with new $_AND_,\n");
log("        $_NOT_, and $_NAND_, cells\n")
```
Following along the same lines as `scc -select`

Add -select option to aigmap

---

passes/pmgen/xilinx_dsp.cc
passes/pmgen/xilinx_dsp.pmg
passes/pmgen/xilinx_dsp_CREG.pmg
passes/pmgen/xilinx_dsp_cascade.pmg
techlibs/xilinx/synth_xilinx.cc

Add notes and comments for xilinx_dsp, and fix a few barnacles.

Add notes and comments for xilinx_dsp

---

passes/techmap/flowmap.cc

flowmap: fix a few crashes

---

passes/opt/wreduce.cc

wreduce: Don't trim zeros or sext when not matching ARST_VALUE

---

frontends/verific/verific.cc
frontends/verific/verific.h

This should fix the build issues in qa-ysfvclass and the issues we have been seeing with black box modules.

Some fixes in our Verific integration

---

passes/memory/memory.cc
passes/opt/Makefile.inc
passes/opt/opt_mem.cc

With the most basic optimization: Remove a memory that has neither write port nor init data.

Add "opt_mem" pass

---

passes/opt/opt_share.cc
tests/opt/bug1525.ys

opt_share: Fix handling of fine cells.

---

techlibs/xilinx/cells_map.v
techlibs/xilinx/synth_xilinx.cc

xilinx: Add tristate buffer mapping.

---

manual/manual.tex

Fix nit in manual's Abstract section.

manual: Fix text in Abstract section

---

techlibs/xilinx/xilinx_dffopt.cc

See rationale at https://github.com/YosysHQ/yosys/pull/1557#discussion_r359196549

xilinx_dffopt: Keep order of LUT inputs.

---

passes/sat/sim.cc

Fix sim for assignments with lhs<rhs size

---

passes/techmap/abc9.cc

Interpret "abc9 -lut" as lut string only if [0-9:]

---

backends/aiger/xaiger.cc

Previously part of #1558, which ended up being reverted

write_xaiger: only instantiate each whitebox cell type once

---

techlibs/anlogic/cells_map.v
tests/arch/anlogic/counter.ys
tests/arch/ecp5/counter.ys
tests/arch/ecp5/macc.ys
tests/arch/ecp5/mul.ys
tests/arch/efinix/counter.ys
tests/arch/gowin/counter.ys
tests/arch/ice40/counter.ys
tests/arch/ice40/mul.ys
tests/arch/ice40/rom.v

* `equiv_opt` missing `-assert`
* `equiv_opt` missing `-multiclock` when asynchronous flops were involved
* Added a missing `reg`
* `synth_anlogic` not mapping async flops correctly

Fix a few issues in tests/arch/*

---

kernel/rtlil.cc

Always create $shl, $shr, $sshl, $sshr cells with unsigned B inputs

---

passes/cmds/autoname.cc
tests/various/autoname.ys

Fixes second bullet point of https://github.com/YosysHQ/yosys/issues/1630#issuecomment-574140963

autoname: do not rename ports

---

passes/fsm/fsm_detect.cc

fsm_detect: Add a cache to avoid excessive CPU usage for big mux networks.

---

misc/py_wrap_generator.py

PR with suggested fix from #1080

handle anonymous unions to fix #1080

---

frontends/verific/verific.cc
passes/opt/opt_reduce.cc

New try. Infinite loop should be now fixed.

Reduce vector fix

---

backends/json/json.cc

Before, the rules for encoding parameters in JSON were as follows:
- if the parameter is not a string:
- if it is exactly 32 bits long and there are no z or x bits, emit it
as an int
- otherwise, emit it as a string made of 0/1/x/z characters
- if the parameter is a string:
- if it contains only 0/1/x/z characters, append a space at the end
to distinguish it from a non-string
- otherwise, emit it directly
However, this caused a problem in the json11 parser used in nextpnr:
yosys emits unsigned ints, and nextpnr parses them as signed, using
the value of INT_MIN for values that overflow the signed int range.
This caused destruction of LUT5 initialization values.  Since both
nextpnr and yosys parser can also accept 32-bit parameters in the
same encoding as other widths, let's just remove …

json: remove the 32-bit parameter special case

---

passes/sat/clk2fflogic.cc
tests/sat/clk2fflogic.ys

clk2fflogic: work for bit-level $_DFF_* and $_DFFSR_*

---

backends/edif/edif.cc

edif: more resilience to mismatched port connection sizes.

---

manual/CHAPTER_Overview.tex

From https://github.com/YosysHQ/yosys/issues/1693#issuecomment-583835368.

manual: explain RTLIL::Wire::{upto,offset}

---

passes/cmds/show.cc

Makes yosys wait for the viewer command to finish before continuing.

show: Add -nobg argument.

---

passes/techmap/abc9_ops.cc

Remove the #ifndef NDEBUG guard in passes/techmap/abc9_ops.cc

Closes #1714. Fix make failure when NDEBUG=1.

---

frontends/ast/genrtlil.cc
tests/various/bug1710.ys

The relevant bit from #1651 that I'm confident enough to make the merge call on...

ast: fixes #1710; do not generate RTLIL for unreachable ternary branch

---

techlibs/coolrunner2/coolrunner2_fixup.cc
techlibs/coolrunner2/coolrunner2_sop.cc
techlibs/coolrunner2/synth_coolrunner2.cc

This should fix:
* https://github.com/azonenberg/openfpga/issues/131
* https://github.com/azonenberg/openfpga/issues/133
* https://github.com/azonenberg/openfpga/issues/134
* https://github.com/azonenberg/openfpga/issues/135

coolrunner2 buffer cell insertion fixes

---

passes/techmap/iopadmap.cc
tests/techmap/iopadmap.ys

iopadmap: Look harder for already-present buffers.

---

techlibs/ice40/cells_sim.v
tests/arch/run-test.sh

ice40: fix specify for -device {lp,u}

---

passes/cmds/add.cc

Review of #1751 showed outdated style and pseudo-private member usage in `passes/cmds/add.cc`.  This PR (hopefully) cleans this file up to current standards.

Clean up `passes/cmds/add.cc` code style.

---

passes/cmds/add.cc

See #1749 .  I accidentally closed the PR with a premature force push.
@nakengelhardt is this more like what you had in mind?

Extend `add` command to allow adding $assert cells.

---

frontends/ast/ast.cc
frontends/verilog/verilog_frontend.cc
frontends/verilog/verilog_frontend.h
frontends/verilog/verilog_lexer.l
frontends/verilog/verilog_parser.y
tests/svtypes/enum_simple.sv
tests/svtypes/typedef_memory.sv
tests/svtypes/typedef_memory_2.sv
tests/svtypes/typedef_package.sv
tests/svtypes/typedef_param.sv
tests/svtypes/typedef_scopes.sv
tests/svtypes/typedef_simple.sv

This is just #1725, I needed the feature and it was broken on his fork, so I fixed it.

Support standard typedef grammar (Fixed)

---

passes/techmap/techmap.cc
tests/techmap/techmap_replace.ys

techmap: Fix cell names with _TECHMAP_REPLACE_.*

---

README.md
frontends/verilog/verilog_frontend.cc
frontends/verilog/verilog_frontend.h
frontends/verilog/verilog_lexer.l
frontends/verilog/verilog_parser.y
tests/svtypes/typedef_scopes.sv

Addresses @davesha1 comments about edge cases.

Support module/package/interface/block scope for typedef names.

---

frontends/verilog/verilog_parser.y

verilog: Add location info for generate constructs

---

backends/btor/btor.cc

Simple demo input:
```
module test (input CP, CN, CX, input A, B, output reg XP, XN, YP, YN);
always @* begin
assume (A || B);
assume (!A || !B);
assert (A != B);
cover (A);
cover (B);
end
always @(posedge CP)
XP <= A;
always @(negedge CN)
XN <= B;
always @(posedge CX)
YP <= A;
always @(negedge CX)
YN <= B;
endmodule
```
Demo commands:
```
yosys -p 'read_verilog -sv test.v; prep; dump; write_btor -i x'; cat x
yosys -p 'read_verilog -sv test.v; prep; dump; write_btor -c -i x'; cat x
yosys -p 'read_verilog -sv test.v; synth; dump; write_btor -i x'; cat x
yosys -p 'read_verilog -sv test.v; synth; dump; write_btor -c -i x'; cat x
```

Add info-file and cover features to write_btor

---

backends/btor/btor.cc

- Add symbols to more entities
- Use src location instead of internal cell names for props only
- Add src location as btor comments to most lines

Improve write_btor symbol handling

---

passes/techmap/iopadmap.cc
tests/techmap/iopadmap.ys

iopadmap: Fix z assignment to inout port

---

frontends/ilang/ilang_lexer.l
frontends/ilang/ilang_parser.y

Addresses #1838, and fixes UB that was previously invoked when lexing an overly large integer value.

Improve handling of integer literals in RTLIL frontend

---

kernel/rtlil.cc
kernel/rtlil.h
kernel/yosys.cc
tests/various/.gitignore
tests/various/plugin.cc
tests/various/plugin.sh

kernel: include "kernel/constids.inc"

---

frontends/verilog/verilog_parser.y

Fixes #1906 
I can't see this doing anything useful other than causing errors, but maybe I'm missing something. cc @boqwxp

verilog: Fix write to deleted object

---

passes/opt/opt_expr.cc
tests/opt/opt_expr.ys

opt_expr: Optimize multiplications with low 0 bits in operands.

---

frontends/ast/genrtlil.cc
tests/various/bug1876.ys

Fix bug introduced in 5bba9c3, as reported in #1876.

Fix handling of ternary with constant condition

---

passes/cmds/setundef.cc

setundef: Improve error messages.

---

passes/memory/memory_bram.cc

memory_bram: Fix ignorance of valid, matched rules

---

frontends/ast/ast.cc
frontends/ast/simplify.cc
tests/various/global_scope.ys

ast: Fix handling of identifiers in the global scope

---

frontends/ast/simplify.cc

With this patch code such as `.init($sformatf("%08x", INIT))` can be used to generate hex strings from any constant expression.

Extend support for format strings in Verilog front-end

---

passes/techmap/abc9_ops.cc
tests/various/abc9.ys

 abc9_ops: -prep_lut to be more robust

---

backends/edif/edif.cc

This replicated the XST behavior of simply ignoring nets with conflicting KEEP attributes, as described in https://github.com/YosysHQ/yosys/issues/1733#issuecomment-595923804.
I've investigated options for writing BUF cells for those nets directly in the EDIF file, but because of the way EDIF works and the way the current back-end is written this turns out to be not feasible without a major rewrite of the EDIF back-end.
An alternative would be a different pass that adds the buffers before even calling the EDIF back-end.

Ignore conflicting keep attributes, unless asked not to

---

techlibs/intel_alm/common/alm_sim.v
techlibs/intel_alm/common/dff_map.v
techlibs/intel_alm/common/dff_sim.v

intel_alm: Documentation improvements

---

passes/cmds/bugpoint.cc

bugpoint: Don't remove modules while iterating over them.

---

misc/yosys-config.in
tests/various/plugin.sh

tests: fix various/plugin.sh when PREFIX != /usr/local/share

---

backends/cxxrtl/cxxrtl.h

Strategically inserting the pending memory write in memory::update to keep the
queue sorted allows us to skip the queue sort in memory::commit.
The Minerva SRAM SoC runs ~7% faster as a result.
Tested over 100 runs, the average execution time of the test provided by #1979 decreases from 0.79s to 0.74s.

cxxrtl: keep the memory write queue sorted on insertion.

---

passes/sat/qbfsat.cc

This PR adds the `-assume-negative-polarity` option.  This option, when combined with `-assume-outputs`, means that we should assume the conjunction of the *negation* of each one-bit module output.
This is especially useful when working with miters created by `miter -equiv`, which generate `trigger` signals that should always be low.

qbfsat: Add `-assume-negative-polarity` option.

---

frontends/ast/ast.cc

Clear current_scope when done with RTLIL generation

---

Makefile

Should resolve issue described at https://github.com/YosysHQ/yosys/commit/ae409d4d81f3a15aba58d5144e68b565cf70b79a#commitcomment-38972956
CC: @Xiretza @boqwxp

Makefile: git fetch $(ABCURL) explicitly for local ABC checkout

---

backends/cxxrtl/cxxrtl.cc

Looks like I wasn't awake when submitting #2072...

Minor fixes for CXXRTL

---

backends/firrtl/firrtl.cc

This PR adds support for writing techmapped designs to FIRRTL.

firrtl: Accept techmapped cell types in FIRRTL backend.

---

tests/arch/ice40/mux.ys

Fix current failing yosys tests, fixes #2100

allow range for mux test

---

backends/aiger/xaiger.cc
passes/techmap/abc9_ops.cc
tests/arch/ecp5/latches_abc9.ys

abc9: fixes around handling combinatorial loops

---

kernel/rtlil.h
misc/py_wrap_generator.py

Q&D patch for:
- Support of access of idict type members
- Hotfix (no line breaks) in order to have all methods parsed (see also #2036)
Hereby requesting review.
Question: are there any test suites for the Python API planned?

Pyosys API: idict type handling

---

backends/cxxrtl/cxxrtl.h

cxxrtl: fix implementation of $sshr cell

---

passes/techmap/flatten.cc

This PR adjusts `flatten` to handle some edge cases related to dotted names that can lead to crashes (#2106). It also makes it easier to extend, such as by adding support for preserving hierarchy in the `hdlname` attribute (PR #2107, which this PR is split out of), allowing arbitrarily many wires connected through `hierconn` to wires in submodules (to use `hierconn` for probe insertion), and adding support for flattening of modules with processes.

flatten: make hygienic

---

backends/cxxrtl/cxxrtl_vcd_capi.cc

cxxrtl: add missing namespace

---

frontends/ast/ast.h
frontends/ast/simplify.cc

Add latch detection for use_case_method in part-select write

---

frontends/verific/verific.cc

Prevent crash noticed in issue #1579

verific - detect missing memory to prevent crash.

---

backends/cxxrtl/cxxrtl_backend.cc

On Minerva, this improves runtime by around 10-15%, mostly by ensuring that the logic driving FFs is packed into edge conditionals.

cxxrtl: elide $pmux cells

---

backends/cxxrtl/cxxrtl.h

This can result in massive reduction in runtime, up to 50% depending on workload. Currently people are using `-mllvm -inline-threshold=` as a workaround (with clang++), but this solution is more portable.

cxxrtl: always inline internal cells and slice/concat operations

---

backends/cxxrtl/cxxrtl.h

Simple chunk-wise multiplication. Given typical bitsizes, using a more advanced algorithm seemed like overkill. Reduces to a single multiply for Bits <= 32.
---
Regarding overflow:
The maximal value in a `wide_result` element is `0x1'ffff'fffe`.
The maximal result of multiplication is `0xffff'fffe'0000'0001`.
Therefore their sum will never overflow.

cxxrtl: Implement chunk-wise multiplication

---

backends/cxxrtl/cxxrtl.h

For several reasons:
* They're more convenient than accessing .data.
* They accommodate variably-sized types like `size_t` transparently.
* They statically ensure that no out of range conversions happen.
For now these are only provided for unsigned integers, but eventually they should be provided for signed integers too. (Annoyingly this affects conversions to/from `char` at the moment.)
Fixes #2127.

cxxrtl: add .get() and .set() accessors on value<> and wire<>

---

frontends/verilog/verilog_parser.y

this PR adds support for optional labels in module and package definitions

Add support for optional labels

---

passes/sat/sim.cc

Gives proper error and fixes issue #2194

sim - error when memrd and memwr detected

---

frontends/ast/simplify.cc
tests/various/const_func.v
tests/various/const_func.ys

This resolves #2123. I'm not completely sure this is the right fix, but it seems to work without breaking anything.

Allow constant function calls in for loops and generate if and case

---

passes/sat/qbfsat.cc

This PR fixes a bug with name-based solution specialization that arises because currently, the `$anyconst` cell Y port is `log_signal()`ed, rather than a wire connected to that `$anyconst` cell Y port.  Here the `SigBit` map created by `get_hole_loc_idx_sigbit_map()` instead maps to the corresponding `SigBit`s of the connected wire (where possible).

qbfsat: Fix name-based hole specialization

---

frontends/verilog/verilog_parser.y
tests/various/integer_range_bad_syntax.ys
tests/various/integer_real_bad_syntax.ys
tests/various/logic_param_simple.ys

This PR adds support for `logic` type

Add logic type support to parameters

---

frontends/ast/simplify.cc

Add AST_EDGE support to AstNode::detect_latch()

---

passes/proc/proc_dlatch.cc

proc_dlatch: Remove init values for combinatorial processes.

---

techlibs/intel/Makefile.inc
techlibs/intel/common/ff_map.v
techlibs/intel/cyclone10lp/cells_map.v
techlibs/intel/cycloneiv/cells_map.v
techlibs/intel/cycloneive/cells_map.v
techlibs/intel/cyclonev/cells_map.v
techlibs/intel/max10/cells_map.v
techlibs/intel/synth_intel.cc

Note: the ff mappings seemed very shady to me, and I'm not at all convinced they actually match hardware capabilities, but I'm reasonably sure this code is not worse than before...

intel: Use dfflegalize.

---

techlibs/achronix/synth_achronix.cc

This target should support more FFs, but they're not in the sim library yet.  Oh well.

achronix: Use dfflegalize.

---

frontends/verilog/verilog_parser.y
tests/various/integer_range_bad_syntax.ys
tests/various/integer_real_bad_syntax.ys
tests/various/logic_param_simple.ys
tests/various/signed.ys

This PR restores #2203 and #2244 and resolves parser conflicts introduced by them

Restore #2203 and #2244 and fix parser conflicts

---

backends/smt2/smtbmc.py
backends/smt2/smtio.py

See https://github.com/YosysHQ/SymbiYosys/pull/102. cc @boqwxp

Only allow "sat" and "unsat" smt solver responses in yosys-smtbmc

---

kernel/satgen.cc
kernel/satgen.h
tests/arch/xilinx/pmgen_xilinx_srl.ys
tests/sat/dff.ys

satgen: Add support for dffe, sdff, sdffe, sdffce cells.

---

passes/sat/clk2fflogic.cc
tests/opt/opt_rmdff.ys
tests/techmap/dfflegalize_adff.ys
tests/techmap/dfflegalize_adff_init.ys
tests/techmap/dfflegalize_adlatch.ys
tests/techmap/dfflegalize_adlatch_init.ys
tests/techmap/dfflegalize_dff.ys
tests/techmap/dfflegalize_dff_init.ys
tests/techmap/dfflegalize_dffsr.ys
tests/techmap/dfflegalize_dffsr_init.ys
tests/techmap/dfflegalize_dlatch.ys
tests/techmap/dfflegalize_dlatch_const.ys
tests/techmap/dfflegalize_dlatch_init.ys
tests/techmap/dfflegalize_dlatchsr.ys
tests/techmap/dfflegalize_dlatchsr_init.ys
tests/techmap/dfflegalize_inv.ys
tests/techmap/dfflegalize_mince.ys
tests/techmap/dfflegalize_minsrst.ys
tests/techmap/dfflegalize_sr.ys
tests/techmap/dfflegalize_sr_init.ys

Depends on #2277, #2286, #2287 .

clk2fflogic: Support all FF types.

---

frontends/ast/simplify.cc
tests/various/const_arg_loop.v
tests/various/const_arg_loop.ys

Resolves #2296. Any feedback is greatly appreciated!

Avoid generating wires for function args which are constant

---

kernel/ffinit.h

This fixes handling of messy cases involving repeatedly setting and
removing the same init bit.

ffinit: Fortify the code a bit.

---

passes/opt/Makefile.inc
passes/opt/opt_dff.cc
tests/opt/opt_dff_arst.ys
tests/opt/opt_dff_clk.ys
tests/opt/opt_dff_const.ys
tests/opt/opt_dff_en.ys
tests/opt/opt_dff_mux.ys
tests/opt/opt_dff_qd.ys
tests/opt/opt_dff_sr.ys
tests/opt/opt_dff_srst.ys
tests/opt/opt_rmdff.ys
tests/opt/opt_rmdff_sat.ys

Depends on #2277, #2286, #2287, #2288.

Add opt_dff pass.

---

passes/techmap/Makefile.inc
passes/techmap/dffunmap.cc
tests/techmap/dffunmap.ys

To be used with backends that cannot deal with fancy FF types (like blif or smt).
Depends on #2184, #2298.

Add dffunmap pass.

---

frontends/ast/simplify.cc
tests/various/const_func.v

Please let me know if this needs any changes!

Allow reals as constant function parameters

---

frontends/ast/simplify.cc
tests/various/const_func_block_var.v
tests/various/const_func_block_var.ys

Allow blocks with declarations within constant functions

---

frontends/ast/simplify.cc
tests/simple/const_branch_finish.v

Propagate const_fold through generate blocks and branches

---

passes/techmap/techmap.cc
techlibs/common/abc9_map.v
techlibs/efinix/cells_map.v

techmap: Add support for [] wildcards in techmap_celltype.

---

passes/pmgen/peepopt_muldiv.pmg
tests/opt/bug2318.ys

peepopt.muldiv: Add a signedness check.

---

passes/pmgen/peepopt_shiftmul.pmg
tests/techmap/bug2332.ys

peeopt.shiftmul: Add a signedness check.

---

passes/opt/opt_share.cc
tests/opt/opt_share_bug2334.ys
tests/opt/opt_share_bug2335.ys
tests/opt/opt_share_bug2336.ys

Fixes #2334.
Fixes #2335.
Fixes #2336.

opt_share: Refactor, fix some bugs.

---

frontends/verific/verific.cc

Yosys part of recent improvements added to SEDA specific Verific library.

Add formal apps and template generators

---

frontends/verific/verific.cc

Current code fails to import VHDL design when one of ports is of type boolean.

Fix import of VHDL enums

---

frontends/ast/simplify.cc
tests/svtypes/multirange_subarray_access.ys

This PR fixes a test condition so Yosys can properly detect unsupported subarray access

Fix unsupported subarray access detection

---

tests/aiger/run-test.sh

switch argument order to work with macOS getopt

---

frontends/verific/verific.cc

Since Verific can accept parameters that can be string, and IdString can not contain spaces it is needed to be altered.
Note that content for parameters in not formed with "(" + nl->Name() + ")" expression but is given in brackets from Verific itself, so to preserve at least module name it is required to do some std::string "gymnastics".

Use sha1 for parameter list in case if they contain spaces

---

frontends/ast/ast.cc
frontends/ast/ast.h
frontends/ast/simplify.cc
tests/sat/sizebits.sv

This PR adds the $high(), $low(), $left(), $right() functions.
A future commit will add $increment(), $dimensions, $unpacked_dimensions()

Added $high(), $low(), $left(), $right()

---

tests/arch/nexus/run-test.sh

Update nexus arch tests to new harness

---

kernel/driver.cc

Found myself chasing my tail a bit trying to figure out how to run scripts. Figured I'd update the `-h` output and the manual so people after me chase their tails less! 🙂

Tcl script documentation fixes

---

techlibs/gowin/synth_gowin.cc

At the moment I'm working on a Nextpnr target for Gowin, but Apicula does not yet support some of the primitives supported by the yosys backend.
This PR adds a `-noalu` option that prevents ALUs from being used, and also adds a `-json` option that will set all the right parameters for use with Apicula, similar to the `-vout` option for the vendor toolchain.
Semi-random question: any idea why there is a `-nodffe` option? Enable is basically free and even Apicula already supports it, but maybe it's more timing related?

add -noalu and -json option for apicula

---

manual/CHAPTER_Overview.tex
manual/CHAPTER_TextRtlil.tex
manual/manual.tex

Issue #2445. Here's the excerpt: (updated) [rtlil.pdf](https://github.com/YosysHQ/yosys/files/5599027/rtlil.pdf)

Adds appendix on RTLIL text format

---

techlibs/nexus/arith_map.v

Thanks to @mwkmwkmwk for pointing this out to me

nexus: More efficient CO mapping

---

kernel/timinginfo.h

timinginfo: Error instead of segfault on const signals.

---

backends/cxxrtl/cxxrtl_backend.cc

cxxrtl: don't crash generating debug information for unused wires

---

passes/cmds/plugin.cc

plugin: enhance no-plugin error

---

techlibs/common/simlib.v

Just some stuff that initially confused me.

Fix some trivial typos.

---

backends/spice/spice.cc

I'm experimenting with doing mixed signal simulations with NgSpice and Yosys, similar to https://www.isotel.eu/mixedsim/intro/concept.html
Instead of a custom synth script, I'm basically trying to use the output of `synth` directly. Either way you end up having to define all the subcircuit models.
Rather than CMOS transistors, my models use the XSPICE event-driven digital models, which should be much faster than a full analog CMOS simulation. However, Yosys currently inserts DC sources to connect nets together, which is incompatible with digital signals.
So this PR introduces a `-buf` option that allows you to specify a subcircuit implementation instead of the DC source. From there you can just use the digital `d_buffer` cell to implement it. The default still uses the DC source, which …

Add buffer option to spice backend

---

frontends/ast/simplify.cc
frontends/verilog/verilog_parser.y
tests/svtypes/typedef_struct_port.sv
tests/svtypes/typedef_struct_port.ys

This PR adds support for using user defined types in module's IO list

Add support for user types in IOs

---

frontends/verilog/verilog_parser.y
tests/verilog/wire_and_var.sv
tests/verilog/wire_and_var.ys

Fixes issue introduced in #2312

sv: fix support wire and var data type modifiers

---

passes/techmap/abc.cc

This change adds support for passing multiple liberty files to abc. This is very useful when working on larger designs with multiple sources of intellectual property, such as memories and pad libraries.
The syntax for abc does not change, except for supporting additional flags: `abc -D 10000 -liberty lib1.lib -liberty lib2.lib` which translates into multiple `read_lib` commands in the resultant abc script.

adding support for passing multiple liberty files to abc

---

techlibs/nexus/cells_sim.v

A forgotten patch from a few months ago....

nexus: Add MULTADDSUB9X9WIDE sim model

---

techlibs/common/adff2dff.v
tests/techmap/adff2dff.ys
tests/techmap/dff2ff.ys
tests/techmap/pmux2mux.ys

Fix syntax error in adff2dff.v

---

frontends/ast/genrtlil.cc
tests/verilog/conflict_assert.ys
tests/verilog/conflict_cell_memory.ys
tests/verilog/conflict_interface_port.ys
tests/verilog/conflict_memory_wire.ys
tests/verilog/conflict_pwire.ys
tests/verilog/conflict_wire_memory.ys

genrtlil: improve name conflict error messaging

---

backends/cxxrtl/cxxrtl_backend.cc

cxxrtl: add pass debug flag to show assigned wire types

---

passes/techmap/abc9_ops.cc

I wasn't sure how to succintly express the error condition here, so instead I settled for a paragraph comment above the assert in the hopes whoever hits the error condition sees it.

Replace assert in abc9_ops with more useful error message

---

tests/bram/generate.py

These have no defined semantics, making the tests non-deterministic.

tests/bram: Do not generate write address collisions.

---

passes/memory/memory_dff.cc

This job is now performed by `opt_dff`, which runs before this pass.

memory_dff: Remove code looking for $mux cells.

---

passes/sat/sim.cc

sim: Avoid a crash on empty cell connection.

---

frontends/ast/ast.cc

This fixes a mistake I made while working on #2626.

Fix param without default log line

---

backends/aiger/xaiger.cc

I wasn't sure how best to hint a fix, so I settled for a mention of #2530.

Replace assert in xaiger with more useful error message

---

passes/opt/opt_clean.cc
tests/opt/opt_clean_init.ys

opt_clean: Remove init attribute bits together with removed DFFs.

---

frontends/ast/simplify.cc
tests/simple/module_scope.v

verilog: support module scope identifiers in parametric modules

---

kernel/rtlil.cc
kernel/rtlil.h
passes/cmds/blackbox.cc
tests/various/blackbox_wb.ys

First part of the fix for #2667

blackbox: Include whiteboxed modules

---

frontends/verilog/verilog_frontend.cc

This was actually a ticking UB bomb: after running the parser, the type maps contain pointers to children of the current AST, which is recursively deleted after the pass has executed. This leaves the pointers in `user_type_stack` dangling, which just happened to never be a problem due to another bug that causes typedefs from higher-level type maps to never be considered.
Rebuilding the type stack from the design's globals ensures the `AstNode` pointers are valid.

verilog: rebuild user_type_stack from globals before parsing file

---

kernel/log.h

Fixes #2606
I tested it with GCC 4.8.5, GCC 7.3.1 and Clang 3.4.2 on CentOS 7. All three produce a binary with a working ``logger -expect`` command. I tested each with these yosys commands:
```
logger -expect error "syntax error, unexpected TOK_CONSTVAL" 1
read_verilog <<EOT
module inverter(input a, output y);
assign y = (a == 1'b0? 1'b1 : 1'b0);
endmodule // inverter
EOT
```
Yosys terminates with exit code 0. And then again with a non-matching string for the ``logger`` command: Yosys terminates with exit code 1.

Fix check for bad std::regex

---

frontends/verilog/verilog_parser.y
tests/verilog/func_typename_ret.sv
tests/verilog/func_typename_ret.ys

sv: allow typenames as function return types

---

frontends/ast/ast.cc

Per the March 15 meeting, we may be able to address a few existing issues with the elaboration of port connections by making the module information available during `simplify()`. This is a tiny stepping stone in that direction which provides access to the design at the call site of the module `simplify()` entrypoint. While I'd be happy to defer changes like this until the overall implementation is finished, I'd hoping to reduce noise in that final change set as much as possible.

ast: make design available to process_module()

---

.github/workflows/test.yml

This combines the Linux and macOS jobs into one using matrix builds and a couple of conditional steps.

gha: combine jobs using matrix

---

frontends/verilog/preproc.cc

preproc: Fix up conditional handling.

---

frontends/verilog/verilog_lexer.l

The exact wording and structure likely needs tweaking.
Fixes #1410

verilog: revise hot comment warnings

---

passes/cmds/connect.cc

Should be useful for writing tests.

connect: Add -assert option, fix non-working sigmap.

---

frontends/ast/ast.cc

No functional change: just get rid of the explicit iterator and
replace (*it)-> with child->. It's even the same number of characters,
but is hopefully a little easier to read.
(Note: This patch is part of the larger queue at #2752. The idea is to split things out to avoid having a giant PR to review all at once)

Use range-based for loop in AST::process

---

kernel/mem.cc
kernel/mem.h

Pushing these ahead of bigger model changes.

kernel/mem: Minor improvements.

---

passes/opt/opt_mem.cc
tests/opt/bug2765.ys

opt_mem: Remove write ports with const-0 EN.

---

Makefile
kernel/ff.h
kernel/ffinit.h
kernel/ffmerge.cc
kernel/ffmerge.h
passes/memory/memory_dff.cc
tests/opt/bug1854.ys

Add new helper class for merging FFs into cells, use for memory_dff.

---

.github/workflows/test.yml

github actions: Test on several gcc and clang versions on Linux.

---

backends/firrtl/firrtl.cc

I am not exactly sure this code actually works, but I can vouch that it was completely broken before, and the current output at least looks semi-reasonable...

backend/firrtl: Convert to use Mem helpers.

---

passes/opt/opt_mem_feedback.cc
tests/opt/bug2766.ys
tests/opt/opt_mem_feedback.ys

opt_mem_feedback: Rewrite feedback path finding logic.

---

backends/btor/btor.cc
backends/firrtl/firrtl.cc
backends/smt2/smt2.cc
kernel/mem.cc
kernel/mem.h
passes/memory/memory_bram.cc

This is initial stage of wide port support.  They are in no way usable yet.

kernel/mem: Add model for wide ports.

---

kernel/mem.cc

When extracting read register from a transparent port that has an
enable, reset, or initial value, the usual trick of putting a register
on the address instead of data doesn't work.  In this case, create soft
transparency logic instead.
When transparency masks land, this will also be used to handle ports
that are transparent to only a subset of write ports.

mem/extract_rdff: Add alternate transparency handling.

---

passes/memory/memory_share.cc

This is mostly meant for wide port recognition, but may also happen to
merge some ports with compatible initial/reset values (eg. 0 vs x).

memory_share: Add read port merging.

---

passes/memory/memory_map.cc
tests/opt/memory_map_offset.ys

memory_map: Improve start_offset handling.

---

frontends/ast/ast.cc
frontends/ast/simplify.cc
frontends/verilog/verilog_parser.y
tests/verilog/package_task_func.sv
tests/verilog/package_task_func.ys

sv: support tasks and functions within packages

---

passes/opt/opt_muxtree.cc
tests/opt/bug2824.ys

opt_muxtree: Update port_off and port_idx even for constant bits

---

frontends/verilog/verilog_frontend.cc
frontends/verilog/verilog_frontend.h
frontends/verilog/verilog_lexer.l
frontends/verilog/verilog_parser.y

That was added in ecc22f7fedfa639482dbc55a05709da85116a60f

verilog: Squash a memory leak.

---

frontends/ast/genrtlil.cc
frontends/ast/simplify.cc
frontends/verilog/verilog_parser.y

I managed to find a few leaks in verilog/ast when running the testsuite under ASan, there's at least one more related to SV struct/enum typedefs that I wasn't able to track down.

Plug a few memory leaks

---

frontends/verilog/verilog_parser.y
tests/simple/matching_end_labels.sv
tests/verilog/block_end_label_only.ys
tests/verilog/block_end_label_wrong.ys
tests/verilog/gen_block_end_label_only.ys
tests/verilog/gen_block_end_label_wrong.ys
tests/verilog/module_end_label.ys

- disallow [gen]blocks with an end label but not begin label
- check validity of module end label
- fix memory leak of package name and end label
- fix memory leak of module end label

sv: fix up end label checking

---

frontends/ast/genrtlil.cc
frontends/rtlil/rtlil_parser.y
kernel/rtlil.cc
kernel/rtlil.h
kernel/yosys.h
passes/cmds/bugpoint.cc
passes/cmds/delete.cc
passes/proc/proc_clean.cc

- add a backlink to module from Process
- make constructor and destructor protected, expose Module functions
to add and remove processes

rtlil: Make Process handling more uniform with Cell and Wire.

---

backends/cxxrtl/cxxrtl.h

cxxrtl: add debug_item::{get,set}

---

CHANGELOG
backends/verilog/verilog_backend.cc
frontends/ast/ast.cc
frontends/ast/ast.h
frontends/ast/genrtlil.cc
frontends/ast/simplify.cc
kernel/celltypes.h
kernel/mem.cc
kernel/mem.h
kernel/rtlil.cc
manual/CHAPTER_CellLib.tex
passes/opt/opt_clean.cc
passes/opt/wreduce.cc
passes/sat/sim.cc
techlibs/common/simlib.v
tests/opt/opt_clean_mem.ys

Fixes #2447.
Depends on #2863.

Add support for memory initialization with mask.

---

passes/opt/opt_lut.cc
techlibs/ice40/synth_ice40.cc
tests/arch/ice40/bug2061.ys

opt_lut: Allow more than one -dlogic per cell type.

---

frontends/ast/genrtlil.cc
tests/simple/loop_prefix_case.v

genrtlil: add width detection for AST_PREFIX nodes

---

passes/memory/memory_bram.cc

This will make more sense when the new transparency masks land.
Fixes #2902.

memory_bram: Some refactoring

---

backends/verilog/verilog_backend.cc

This mode will be used whenever read port cannot be handled in the
"extract address register" way, ie. whenever it has enable, reset,
init functionality or (in the future) mixed transparency mask.

backend/verilog: Add alternate mode for transparent read port output.

---

passes/opt/opt_merge.cc
tests/opt/bug2920.ys
tests/opt/opt_merge_init.ys

opt_merge: Use FfInitVals.

---

passes/memory/memory.cc
passes/opt/Makefile.inc
passes/opt/opt_mem_priority.cc
tests/opt/opt_mem_priority.ys

Still tests needed for that one.

Add new opt_mem_priority pass.

---

passes/memory/memory_dff.cc
tests/memories/trans_sdp.v
tests/memories/trans_sp.v
tests/opt/memory_dff_trans.ys

Depends on #2904 and #2807 .  Still needs tests.

memory_dff: Recognize soft transparency logic.

---

passes/memory/memory.cc
passes/opt/Makefile.inc
passes/opt/opt_mem_widen.cc
tests/memories/wide_all.v

If all of us are wide, then none of us are!
Depends on #2930 and, transitively, a whole lot of others.

Add opt_mem_widen pass.

---

frontends/verilog/verilog_parser.y
tests/verilog/for_decl_no_init.ys
tests/verilog/for_decl_no_sv.ys
tests/verilog/for_decl_shadow.sv
tests/verilog/for_decl_shadow.ys

In line with other tools, this adds an extra wrapping block around such for loops to appropriately scope the variable.

sv: support declaration in procedural for initialization

---

backends/smt2/smtbmc.py

yosys-smtbmc: Fix reused loop variable.

---

CHANGELOG

Various updated for CHANGELOG since 0.9 release.
Will split per update type, but splitting into multiple  commits for easier change tracking.

Updates for CHANGELOG

---

frontends/verific/verific.cc

This fixes gclk SVA properties.

Fix verific gclk handling for async-load FFs

---

passes/techmap/flatten.cc

flatten: Keep sigmap around between flatten_cell invocations.

---

kernel/driver.cc
kernel/yosys.cc
kernel/yosys.h
tests/arch/xilinx/tribuf.sh
tests/bram/run-single.sh
tests/memories/run-test.sh
tests/techmap/mem_simple_4x1_runtest.sh
tests/techmap/recursive_runtest.sh
tests/various/async.sh

This might break some stuff, but it's clearly the behavior users would be more likely to expect.

Use "read" command to parse HDL files from Yosys command-line

---

passes/cmds/bugpoint.cc

bugpoint: avoid infinite loop between -connections and -wires

---

passes/memory/memory_share.cc
tests/opt/bug3117.ys

memory_share: Fix SAT-based sharing for wide ports.

---

manual/PRESENTATION_Prog/Makefile

manual: Fix a custom pass example.

---

passes/pmgen/ice40_dsp.pmg

Ice40 dsp unextend bug

---

passes/techmap/iopadmap.cc

Signed-off-by: YRabbit <rabbit@yrabbit.cyou>

Correct a typo in the manual

---

techlibs/nexus/arith_map.v

nexus: Fix arith_map CO signal.

---

CHANGELOG
frontends/ast/ast.h
frontends/ast/simplify.cc
tests/verilog/func_upto.sv
tests/verilog/func_upto.ys

verilog: fix const func eval with upto variables

---

CHANGELOG
frontends/ast/simplify.cc
tests/verilog/dynamic_range_lhs.sh
tests/verilog/dynamic_range_lhs.v

Fixes #3085 @ZachGu
Fixes #3051 @tcal-x

verilog: fix dynamic dynamic range asgn elab

---

CHANGELOG
frontends/verilog/verilog_lexer.l
frontends/verilog/verilog_parser.y
tests/verilog/delay_time_scale.ys

verilog: support for time scale delay values

---

Makefile

Signed-off-by: Claire Xenia Wolf <claire@clairexen.net>

Bump ABC version

---

techlibs/gowin/cells_sim.v

Signed-off-by: YRabbit <rabbit@yrabbit.cyou>

gowin: Add support for true differential output

---

techlibs/gowin/cells_sim.v

Signed-off-by: YRabbit <rabbit@yrabbit.cyou>

gowin: add support for Double Data Rate primitives

---

passes/techmap/abc9_ops.cc

Fixes #3244; as we now derive any box with timing as it could have port widths, generate blocks, etc that depend on parameters.

abc9_ops: Also derive blackboxes with timing info

---

passes/cmds/show.cc

show: Fix width labels.

---

CHANGELOG
frontends/ast/simplify.cc
tests/verilog/always_comb_nolatch_5.ys
tests/verilog/always_comb_nolatch_6.ys

This supersedes #3153. @kamilrakoczy @tgorochowik

sv: fix always_comb auto nosync for nested and function blocks

---

passes/techmap/tribuf.cc

Using this simplifies formal verification of designs containing tristate busses. https://gist.github.com/jix/6ccf5b58f10ce77cf40d9f13ed15db86 is an example of using it via sby.

tribuf: `-formal` option: convert all to logic and detect conflicts

---

passes/opt/opt_ffinv.cc

This avoids using out-of-data index information.

opt_ffinv: Use ModIndex instead of ModWalker.

---

passes/techmap/abc9_ops.cc

These later become accidentally used for techmap replacements for blackboxes that we don't actually want.

abc9_ops: Don't leave unused derived modules lying around

---

passes/techmap/iopadmap.cc

iopadmap: Fix z assignment removal.

---

manual/command-reference-manual.tex
passes/hierarchy/hierarchy.cc

like -simcheck, but allow smtlib2_module modules.
Requested in https://github.com/YosysHQ/sby/pull/170#issuecomment-1160477086

add hierarchy -smtcheck

---

passes/opt/opt_reduce.cc

opt_reduce: Fix use-after-free.

---

backends/smt2/smt2.cc

smt2: Fix $shift/$shiftx with negative shift ammounts

---

frontends/verific/verific.cc

Import memory cell related attributes in verific frontend.

Import memory attributes

---

passes/sat/miter.cc

Needed for eqy "amend" feature

Add miter -cross option

---

passes/sat/sim.cc

The previous approach only initialized past_d and past_ad while for FST cosim we also need to initialize the other past values like past_clk, etc. Also to properly initialize them, we need to run a combinational update step in case any of the wires feeding into the FF are private or otherwise not part of the FST.

sim: Run a comb-only update step to set past values during FST cosim

---

kernel/driver.cc
kernel/yosys.cc

This adds -C command line option enabling TCL interactive shell mode.

Add TCL interactive shell mode

---

frontends/ast/simplify.cc
tests/svtypes/struct_array.sv

@jix Would you like to have a look at this while it's still fresh in memory? :wink: 
I added your tests for multidimensional arrays from #3551

Support for packed multidimensional arrays within packed structs

---

kernel/register.cc

Better way of communicating error to user as in issue #3603

Display error instead of assertion when pass exists

---

Makefile
backends/btor/btor.cc
backends/firrtl/firrtl.cc
backends/smt2/smt2.cc
backends/smv/smv.cc
backends/verilog/verilog_backend.cc
kernel/calc.cc
kernel/celltypes.h
kernel/rtlil.cc
kernel/rtlil.h
kernel/satgen.cc
passes/cmds/Makefile.inc
passes/cmds/xprop.cc
passes/opt/opt_expr.cc
passes/sat/formalff.cc
passes/sat/miter.cc
passes/sat/sim.cc
passes/techmap/Makefile.inc
passes/techmap/bwmuxmap.cc
passes/techmap/simplemap.cc
passes/techmap/simplemap.h
techlibs/common/simlib.v
techlibs/common/techmap.v
tests/opt/opt_expr_xnor.ys
tests/opt/opt_expr_xor.ys
tests/xprop/.gitignore
tests/xprop/generate.py
tests/xprop/run-test.sh
tests/xprop/test.py

Current WIP of the new xprop pass and preparatory changes.
The xprop pass itself needs more celltypes and more tests, but the current version can handle nerv after pmuxtree and dffunmap.

New xprop pass

---

frontends/liberty/liberty.cc

print filename in liberty log_header

---

frontends/ast/simplify.cc
tests/svinterfaces/resolve_types.sv
tests/svinterfaces/resolve_types.ys
tests/svinterfaces/run-test.sh

Resolve package types in interfaces

---

techlibs/ecp5/cells_sim.v

Since the split-slice move about a year ago, `TRELLIS_SLICE` has not been supported by nextpnr so leaving it in was simply a source of confusion.
Remove it; and as a replacement add a simulation model for the `TRELLIS_COMB` that takes it place.

ecp5: Remove TRELLIS_SLICE and add TRELLIS_COMB model

---

passes/sat/Makefile.inc
passes/sat/synthprop.cc

Initial implementation for "synthprop" pass

Synthesizable properties

---

frontends/ast/genrtlil.cc

I believe this was intended behavior of this code.

Fix missing brackets around ``else`` in genrtlil

---

docs/source/CHAPTER_Memorymap.rst

Move additional notes up to the top and give it its own section.  Also reformat some paragraphs, and turn some bullet points into paragraphs. 
Split supported patterns section into some kind of grouping. Currently:
- SDP
- single-port RAM
- reset patterns
- asymmetric
- TDP

Reflow memory map doc sections

---

backends/verilog/verilog_backend.cc

Speedup of `write_verilog`

---

frontends/ast/simplify.cc
frontends/verilog/verilog_parser.y
tests/svtypes/typedef_scopes.sv
tests/svtypes/typedef_struct.sv

Corrected handling of nested typedefs of struct/union

---

README.md
backends/blif/blif.cc
backends/firrtl/firrtl.cc
backends/jny/jny.cc
kernel/cellaigs.cc
passes/techmap/extract_counter.cc
tests/various/help.ys

These are very minor things I stumbled on.

Various cleanup

---

kernel/cellaigs.cc

Add the case of $lt, $le, $gt, $ge to the code generating AIGs.

cellaigs: Generate models for integer comparison cells

---

passes/cmds/xprop.cc

* Fixes a non-deterministic polarity error for $eqx/$nex cells
* Fixes a deterministic polarity error for $_NOR_ and $_ORNOT_ cells
* Generates hdlnames when xprop is run after flatten

xprop: Fix polarity errors and generate hdlnames

---

passes/sat/sim.cc

Ping @jix since they expressed interest in this support.
Ping @kivikakk, @mwkmwkmwk should they want to double check the triggering semantics.

sim: Add print support

---

Makefile

To fix incompatibility introduced by https://github.com/YosysHQ/yosys/pull/3926.

Update ABC for WASI support

---

.gitignore

Ignore emacs auto-save files.

---

passes/sat/sim.cc

Take e.g.
```
module top();
a a_();
endmodule
module a();
b b_();
endmodule
module b();
always @(*)
assert(0);
endmodule
```
as input to sim (`read_verilog -sv sample.sv; hierarchy -top top; proc; sim -assert`).
You will now get
```
4. Executing SIM pass (simulate the circuit).
Simulating cycle 0.
Simulating cycle 1.
Failed assertion $assert$sample.sv:10$5 at
sample.sv:10.13-11.12
in instance b_ of module b at
sample.sv:6.5-6.9
in instance a_ of module a at
sample.sv:2.4-2.8
ERROR: Assertion top.a_.b_.$assert$sample.sv:10$5 (sample.sv:10.13-11.12) failed.
```

sim: Print hierarchy for failed assertions

---

Makefile
backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
tests/cxxrtl/.gitignore
tests/cxxrtl/run-test.sh
tests/cxxrtl/test_value.cc
tests/cxxrtl/test_value_fuzz.cc

cxxrtl: Add simple tests for cxxrtl::value from cxxrtl runtime

---

backends/cxxrtl/runtime/cxxrtl/cxxrtl.h
backends/cxxrtl/runtime/cxxrtl/cxxrtl_time.h

Avoid overflow during conversion for any representable raw value.

cxxrtl: improve robustness of `cxxrtl::time`

---

passes/opt/opt_lut.cc
techlibs/ice40/synth_ice40.cc

opt_lut: Replace `-dlogic` with `-tech ice40`

---

passes/sat/sim.cc

While trying to add more tests to get better coverage for the code I added for #4128 (which had quite a few bugs not uncovered by our current tests) I noticed that `sim`'s sampling behavior of enable and arguments for `$print` with a trigger does not match how we treat edge triggered FFs. In particular that makes it impossible to use `sim` to test that `clk2fflogic` doesn't change the semantics of a design that should be supported by `clk2fflogic`.
I think it could also lead to quite confusing behavior when for Verilog inputs, inside an edge triggered process there is an assignment to a register next to a print of the same expression that is assigned to the register. ~~I haven't yet tried to reproduce that exact scenario (I've focused on the more complex `clk2fflogic` testcases) but I …

sim: Bring $print trigger/sampling semantics in line with FFs

---

kernel/rtlil.cc

SigSpec/SigChunk::extract(): assert offset/length are not out of range

---

tests/various/clk2fflogic_effects.sh

tests/various/clk2fflogic_effects.sh: fix on macOS

---

passes/techmap/dfflibmap.cc

Replace OS matching functions with yosys kernel function.
Addresses feedback in https://github.com/YosysHQ/yosys/pull/4219#discussion_r1495765618 @povik

dfflibmap: use patmatch() from kernel/yosys.cc

---

guidelines/CodingStyle

Original link is a manual redirect

docs: Update linux kernel coding style link

---

frontends/ast/genrtlil.cc
kernel/driver.cc
passes/pmgen/ice40_dsp.cc
techlibs/anlogic/synth_anlogic.cc
techlibs/ecp5/synth_ecp5.cc
techlibs/efinix/synth_efinix.cc
techlibs/fabulous/synth_fabulous.cc
techlibs/gowin/synth_gowin.cc
techlibs/ice40/synth_ice40.cc
techlibs/lattice/synth_lattice.cc
techlibs/nexus/synth_nexus.cc

Fixing a few typos and help output in synth commands.

Typo fixing

---

passes/techmap/cellmatch.cc

This PR explains internal logic of the cellmatch pass. Corrections from https://github.com/widlarizer/yosys/commit/24bf8a5c1eb2171ee77917cb1c8fcd4ffc9f5b3f have been addressed

cellmatch: add comments

---

Makefile
docs/source/conf.py

Docs: Set release to YOSYS_VER

---

frontends/verilog/verilog_frontend.cc

read_verilog: Add missing defaults for flags

---

Makefile

Should be solution for issues like https://github.com/YosysHQ/yosys/issues/4383 and solve other cases not handled by https://github.com/YosysHQ/yosys/pull/4384

Modify abc directory content check

---

Makefile

without defining marco in qtcreator.config, some code will be regarded as a comment by qt creator

export define marco to qtcreator.config

---

frontends/liberty/liberty.cc

This makes two changes to allow reading in IO liberty files, for e.g. verification or simulation purposes where the Verilog simulation models are too non-synthesisable for Yosys to be able to handle them:
- support for the `three_state` attribute which specifies a condition on which an output is tristated, converted into a `$tribuf`
- `inout`s with a missing function aren't skipped, as the library we are using uses them for power pins

liberty: Support for IO liberty files for verification

---

Makefile
kernel/yosys.cc

Adding some basic build support for the Haiku operating system.
Correcting some missing requirements for non-posix API calls.

haiku: Basic fixes to build under Haiku

---

tests/proc/proc_rom.ys

Modifies tests to somewhat cover change in #4508

proc_rom: test src attribute on memories

---

passes/sat/sim.cc

Ranges for wires and registers are not same as in design, it was previously left to GtkWave to interpret data.
Each name is expanded by " [start_offset:end_offset]" in cases where width of signal is not 1. Also we do this when there is "[" used inside name of wire to prevent GtkWave to interpret data wrong way.

Set ranges on exported wires in VCD and FST

---

frontends/liberty/liberty.cc
passes/cmds/stat.cc
passes/techmap/dfflibmap.cc
passes/techmap/libparse.cc
passes/techmap/libparse.h
tests/liberty/.gitignore
tests/liberty/XNOR2X1.lib.filtered.ok
tests/liberty/XNOR2X1.lib.verilogsim.ok
tests/liberty/busdef.lib.filtered.ok
tests/liberty/busdef.lib.verilogsim.ok
tests/liberty/issue3498_bad.lib.filtered.ok
tests/liberty/issue3498_bad.lib.verilogsim.ok
tests/liberty/normal.lib.filtered.ok
tests/liberty/normal.lib.verilogsim.ok
tests/liberty/normal.verilogsim.ok
tests/liberty/processdefs.lib.filtered.ok
tests/liberty/run-test.sh
tests/liberty/semicolextra.lib.filtered.ok
tests/liberty/semicolextra.lib.verilogsim.ok
tests/liberty/semicolmissing.lib.filtered.ok
tests/liberty/semicolmissing.lib.verilogsim.ok

Liberty parsing cleanup

---

.gitmodules

cxxopts: https submodule

---

techlibs/xilinx/synth_xilinx.cc

For interface consistency with other family synth commands

synth_xilinx: add -json

---

backends/aiger2/aiger.cc

A minor fix (to fix usage of Index out of the aiger backend)

aiger2: Fix open-coded constants

---

kernel/yosys.cc
setup.py

see https://github.com/YosysHQ/yosys/pull/4672#issuecomment-2420128412

yosys: fix pyosys initialization segfault

---

passes/cmds/stat.cc

stat: Drop unused field

---

passes/techmap/libparse.cc

filterlib: preserve value quotes

---

passes/techmap/clockgate.cc

clockgate: reduce build warnings

---

frontends/ast/dpicall.cc

Fix the compiler warning
variable length arrays in C++ are a Clang extension [-Wvla-cxx-extension]

ast/dpicall: Stop using variable length array

---

CONTRIBUTING.md
docs/source/yosys_internals/extending_yosys/contributing.rst

There is no existing guide for making contributions
Add the file

Initial version of CONTRIBUTING.md

---

passes/opt/share.cc

share: re-add SAT solver cell count to log message

---

libs/ezsat/ezsat.cc

tiny log fixups for things that tripped me up when trying to read ezsat.cc

ezsat: fix incorrect logging references to function names

---

passes/cmds/abstract.cc

- `-Wmaybe-uninitialized` on line 43 and 44.
- Line 50 uses spaces instead of tabs.

Fixes for abstract.cc

---

.github/workflows/codeql.yml
.github/workflows/extra-builds.yml
.github/workflows/prepare-docs.yml
.github/workflows/source-vendor.yml
.github/workflows/test-build.yml
.github/workflows/test-compile.yml
.github/workflows/test-verific.yml
.github/workflows/update-flake-lock.yml
.github/workflows/version.yml
.github/workflows/wheels.yml

> A static analysis tool for Github Actions
https://github.com/woodruffw/zizmor
Suggested by @Ravenslofty, but apparently I forgot to make a PR >.>
Mostly means adding `persist-credentials: false` to checkouts and replacing `{{ env.VARNAME }}` with shell substitution.
Install and run `zizmor .` in local clone of repo to get reported issues.

CI: Fixes from zizmor

---

passes/memory/memory_libmap.cc

Alternative to #5015 without potential performance regression

memory_libmap: fix MapWorker memory allocation

---

passes/cmds/Makefile.inc
passes/cmds/timeest.cc

This is a rebased version of PR #4422.

timeest: Add command for critical path estimation (rebased)

---

techlibs/gatemate/cells_sim.v

Use of non-blocking assignments in non-clocked processes.
Changed to blocking assignments.
Simulate and test with expected behavior.

Change to blocking assignments in non-clocked process.

---

techlibs/greenpak4/cells_sim_digital.v

Use of non-blocking assignments in non-clocked always processes.
Change to blocking assignments.
SImulate and checked expected behavior.

Change to use blocking assignments in non-clocked processes.

---

kernel/rtlil.h
passes/opt/opt_expr.cc

Cleanup one or two instances of trailing whitespace that had been annoying me as my editor automatically trims them and it was making my diffs noisier.

Whitespace Cleanup

---

frontends/ast/simplify.cc

Fixes leak introduced in #5095

simplify: fix single_bit_vector memory leak

---

passes/memory/memlib.md

Minor typo fixes for enhanced legibility.

Fix typos in memlib.md

---

passes/opt/opt_muxtree.cc

I did some refactoring and added a bunch of clarifying comments with no intended functional impact to allow transparency for soundness and make future rewrites easier
cc @rocallahan

opt_muxtree: refactor

---

backends/aiger2/aiger.cc

While working on adding inout / undirected connection support to bufnorm and trying to make sure those survive `abc_new` I ran into sporadic bugs where unrelated wires would end up getting connected. Eventually I was able to track it down to inconsistent numbering of aiger output ports between the actual logic in the aiger file and the generated port mapping file.
The changed code looked like an easy to make bug and making this change fixed it. I don't really understand the reasoning behind the way the aiger2 backend allocates ports, so I'm not sure this change is generally correct, but the observed inconsistencies disappeared.
I'm …

write_xaiger2: Fix output port mapping when opaque boxes are present

---

.gitignore

Test artifacts and Homebrew locks often end up in git changes, which is annoying.
Ignore relevant files.

Small gitignore fixes
